-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group Representation.identifier
import P4SpecTec.Refine.Representation.Delay
import P4SpecTec.Refine.Representation.Source
import P4SpecTec.Refine.Representation.SourceAlias
import P4SpecTec.Refine.Representation.SourceAtomic
import P4SpecTec.Refine.Representation.SourceRecord
import P4SpecTec.Refine.Representation.SourceCodec
import P4SpecTec.Refine.Representation.SourceTuple
import P4SpecTec.Refine.Representation.SourceExtern
import P4SpecTec.Refine.Representation.SourceVariant
import P4SpecTec.Tactic.Audit
import P4SpecTec.Tactic.CarrierInduction
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality

/-! # NanoP4Spec.Refinement.Representation.identifier

Generated: refinement theorems, group Representation.identifier.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

/-- The complete independent source grammar of the quoted variant. -/
def identifier.source (v : Lang.Il.value) : Prop :=
  Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain
    (Q.varT "identifier" []) v

private theorem identifier.sourceFields (v : Lang.Il.value) (hv : identifier.source v) :
    ∃ tree : Domain.Mixfix.t Lang.Il.value, v.it = .CaseV tree ∧
      Domain.Mixfix.eq_mixop tree (.Seq [(.Atom (Prelude.Value.atom (.Tag "ID"))), (.Arg ())]) =
        true ∧
      ∃ text : Lang.Il.value, Domain.Mixfix.args tree = [text] ∧
        (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t
          .TextT).it) text := by
  have normalize : ∀ actual : Lang.Il.typ,
      Representation.Source.Substitutes [] ((Q.t .TextT)).it actual.it →
      ∀ v, Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain
        actual.it v → (Representation.Source.Valid NanoP4Spec.spec
          Representation.Source.externDomain (Q.t .TextT).it) v := (by
  intro actual substitution v valid
  simpa only [substitution.textResult] using valid)
  obtain ⟨constructor, member, fields, instantiated, tree, shape, matching, valid⟩ :=
    hv.variantPayload (Q.i "identifier") [] []
      [Q.tc (.Seq [.Atom (Q.a (.Tag "ID")), .Arg (Q.t .TextT)]) "identifier" []]
      v (by rfl)
  simp only [List.mem_cons, List.not_mem_nil, or_false] at member
  subst constructor
  dsimp [Representation.Source.instantiatedFields, Q.tc, Q.nt, Q.t, Lang.Il.typcase.nottyp,
    P4SpecTec.Util.Source.mkPhrase, Domain.Mixfix.args] at instantiated
  repeat' first
    | simp only [Domain.Mixfix.args] at instantiated
    | dsimp only [List.flatMap, List.append, List.map, List.flatten] at instantiated
  rcases instantiated with ⟨_, instantiated⟩
  cases instantiated with
  | cons first rest =>
    cases rest
    generalize hargs : Domain.Mixfix.args tree = args at valid
    cases valid with
    | cons type text types values head tail =>
      cases tail
      have head := normalize _ first text head
      exact ⟨tree, shape, Representation.Source.mixopTrans tree _ _ matching rfl, text, hargs,
        head⟩


/-- Admission is inherited from the independently specified field contract. -/
def identifier.admitted : NanoP4Spec.identifier → Prop
  | ._ID x => (fun _ : ByteText => True) x


/-- The full source codec fixes the actual named encoder and decoder dictionaries. -/
theorem identifier.codec :
    @Representation.Codec NanoP4Spec.identifier ⟨NanoP4Spec.identifier.toValue⟩
      ⟨NanoP4Spec.identifier.ofValue⟩
      identifier.source identifier.admitted := by
  letI : ToValue NanoP4Spec.identifier := ⟨NanoP4Spec.identifier.toValue⟩
  letI : OfValue NanoP4Spec.identifier := ⟨NanoP4Spec.identifier.ofValue⟩
  letI : ToValue (ByteText) := ⟨@ToValue.toValue ByteText P4SpecTec.Prelude.instToValueByteText⟩
  letI : OfValue (ByteText) := ⟨@OfValue.ofValue ByteText P4SpecTec.Prelude.instOfValueByteText⟩
  have childCodec : @Representation.Codec (ByteText) ⟨@ToValue.toValue ByteText
    P4SpecTec.Prelude.instToValueByteText⟩ ⟨@OfValue.ofValue ByteText
    P4SpecTec.Prelude.instOfValueByteText⟩ (Representation.Source.Valid NanoP4Spec.spec
    Representation.Source.externDomain (Q.t .TextT).it) (fun _ : ByteText => True) :=
    @Representation.Source.textCodec NanoP4Spec.spec Representation.Source.externDomain
  refine { encodingValid := ?_, decoder := { sound := ?_, sufficient := ?_ } }
  · intro x hx
    cases x with
    | _ID text =>
      change (fun _ : ByteText => True) text at hx
      apply Representation.Source.ConstructorDomain.valid
        (Q.i "identifier") [] []
        [Q.tc (.Seq [.Atom (Q.a (.Tag "ID")), .Arg (Q.t .TextT)]) "identifier" []]
        (Q.tc (.Seq [.Atom (Q.a (.Tag "ID")), .Arg (Q.t .TextT)]) "identifier" [])
        [(Q.t .TextT)] _ (by rfl) (by simp)
        (by
          refine ⟨rfl, ?_⟩
          dsimp [Q.tc, Q.nt, Q.t, Lang.Il.typcase.nottyp,
            P4SpecTec.Util.Source.mkPhrase, Domain.Mixfix.args]
          repeat' first
            | simp only [Domain.Mixfix.args]
            | dsimp only [List.flatMap, List.append, List.map, List.flatten]
          change List.Forall₂ (fun a b : Lang.Il.typ =>
            Representation.Source.Substitutes [] a.it b.it) [(Q.t .TextT)] [(Q.t .TextT)]
          exact .cons (Representation.Source.Substitutes.text) .nil)
      refine ⟨(.Seq [(.Atom (Prelude.Value.atom (.Tag "ID"))), (.Arg ((@ToValue.toValue ByteText
        P4SpecTec.Prelude.instToValueByteText) text))]),
        rfl, rfl, ?_⟩
      repeat' first
        | simp only [Domain.Mixfix.args]
        | dsimp only [List.flatMap, List.append, List.map, List.flatten]
      exact .cons ((Q.t .TextT)) ((@ToValue.toValue ByteText
        P4SpecTec.Prelude.instToValueByteText) text) [] [] (childCodec.encodingValid text hx)
        .nil
  · intro fuel v x hv hd
    obtain ⟨tree, shape, matching, text, fields, valid⟩ := identifier.sourceFields v hv
    have args : Prelude.Value.caseArgs tree
        (.Seq [(.Atom (Prelude.Value.atom (.Tag "ID"))), (.Arg ())]) = some [text] := by
      change Domain.Mixfix.eq_mixop tree
        (.Seq [(.Atom (Prelude.Value.atom (.Tag "ID"))), (.Arg ())]) = true at matching
      simp only [Prelude.Value.caseArgs, matching, ite_true, fields]
    cases fuel with
    | zero => cases hd
    | succ fuel =>
      simp only [OfValue.ofValue, NanoP4Spec.identifier.ofValue, shape, args] at hd
      cases decoded : (@OfValue.ofValue ByteText P4SpecTec.Prelude.instOfValueByteText) fuel
        text with
      | none =>
        change ((@OfValue.ofValue ByteText P4SpecTec.Prelude.instOfValueByteText) fuel
          text).bind (fun r => some (NanoP4Spec.identifier._ID r)) = some x at hd
        rw [decoded] at hd
        cases hd
      | some result =>
        change ((@OfValue.ofValue ByteText P4SpecTec.Prelude.instOfValueByteText) fuel
          text).bind (fun r => some (NanoP4Spec.identifier._ID r)) = some x at hd
        rw [decoded] at hd
        change some (NanoP4Spec.identifier._ID result) = some x at hd
        cases Option.some.inj hd
        have related := childCodec.decoder.sound fuel text result valid decoded
        constructor
        · exact related.1
        ·
          change Rel v (NanoP4Spec.identifier.toValue (._ID result))
          apply Representation.Source.caseRelation (rendered :=
            (.Seq [(.Atom (Prelude.Value.atom (.Tag "ID"))), (.Arg ((@ToValue.toValue ByteText
              P4SpecTec.Prelude.instToValueByteText) result))]))
            shape rfl
          · exact Representation.Source.mixopTrans tree _ _ matching rfl
          · rw [fields]
            repeat' first
              | simp only [Domain.Mixfix.args]
              | dsimp only [List.flatMap, List.append, List.map, List.flatten]
            dsimp only [canons]
            exact congrArg (fun c => [c]) related.2
  · intro v hv
    obtain ⟨tree, shape, matching, text, fields, valid⟩ := identifier.sourceFields v hv
    obtain ⟨result, bound, stable⟩ := childCodec.decoder.sufficient text valid
    change ∀ fuel, bound ≤ fuel → (@OfValue.ofValue ByteText
      P4SpecTec.Prelude.instOfValueByteText) fuel text =
      some result at stable
    refine ⟨ ._ID result, bound + 1, ?_⟩
    intro fuel large
    cases fuel with
    | zero => omega
    | succ fuel =>
      have args : Prelude.Value.caseArgs tree
          (.Seq [(.Atom (Prelude.Value.atom (.Tag "ID"))), (.Arg ())]) = some [text] := by
        change Domain.Mixfix.eq_mixop tree
          (.Seq [(.Atom (Prelude.Value.atom (.Tag "ID"))), (.Arg ())]) = true at matching
        simp only [Prelude.Value.caseArgs, matching, ite_true, fields]
      simp only [OfValue.ofValue, NanoP4Spec.identifier.ofValue, shape, args]
      change ((@OfValue.ofValue ByteText P4SpecTec.Prelude.instOfValueByteText) fuel text).bind
        (fun r => some (NanoP4Spec.identifier._ID r)) = _
      rw [stable fuel (by omega)]
      rfl


/-- Every carrier value is admitted under the stated child totals. -/
theorem identifier.admittedAll : ∀ x : NanoP4Spec.identifier, (NanoP4Spec.identifier.admitted) x
  := by
  intro x
  cases x with
  | _ID a =>
    exact ((show ∀ x : (ByteText), (fun _ : ByteText => True) x from (fun _ => True.intro))) a

#audit_axioms NanoP4Spec.identifier.sourceFields
#audit_axioms NanoP4Spec.identifier.codec
#audit_axioms NanoP4Spec.identifier.admittedAll

end NanoP4Spec
