-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group Representation.matchKindDeclaration
import P4SpecTec.Refine.Representation.Delay
import P4SpecTec.Refine.Representation.Source
import P4SpecTec.Refine.Representation.SourceAlias
import P4SpecTec.Refine.Representation.SourceAtomic
import P4SpecTec.Refine.Representation.SourceRecord
import P4SpecTec.Refine.Representation.SourceCodec
import P4SpecTec.Refine.Representation.SourceTuple
import P4SpecTec.Refine.Representation.SourceExtern
import P4SpecTec.Refine.Representation.SourceVariant
import P4SpecTec.Tactic.Audit
import P4SpecTec.Tactic.CarrierInduction
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality
import NanoP4Spec.Refinement.Representation.nameList

/-! # NanoP4Spec.Refinement.Representation.matchKindDeclaration

Generated: refinement theorems, group Representation.matchKindDeclaration.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

/-- The complete independent source grammar of the quoted variant. -/
def matchKindDeclaration.source (v : Lang.Il.value) : Prop :=
  Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain
    (Q.varT "matchKindDeclaration" []) v

private theorem matchKindDeclaration.sourceFields (v : Lang.Il.value) (hv :
  matchKindDeclaration.source v) :
    ∃ tree : Domain.Mixfix.t Lang.Il.value, v.it = .CaseV tree ∧
      Domain.Mixfix.eq_mixop tree (.Seq [(.Atom (Prelude.Value.atom (.Keyword "MATCH_KIND"))),
        (.Brack (Prelude.Value.atom .LBrace) (.Arg ()) (Prelude.Value.atom .RBrace))]) = true ∧
      ∃ text : Lang.Il.value, Domain.Mixfix.args tree = [text] ∧
        (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t
          (Q.varT "nameList" [])).it) text := by
  have normalize : ∀ actual : Lang.Il.typ,
      Representation.Source.Substitutes [] ((Q.t (Q.varT "nameList" []))).it actual.it →
      ∀ v, Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain
        actual.it v → (Representation.Source.Valid NanoP4Spec.spec
          Representation.Source.externDomain (Q.t (Q.varT "nameList" [])).it) v := (by
  intro actual substitution v valid
  rw [substitution.emptyNamedResult (Q.i "nameList")] at valid
  exact valid)
  obtain ⟨constructor, member, fields, instantiated, tree, shape, matching, valid⟩ :=
    hv.variantPayload (Q.i "matchKindDeclaration") [] []
      [Q.tc (.Seq [.Atom (Q.a (.Keyword "MATCH_KIND")), .Brack (Q.a .LBrace) (.Arg (Q.t (Q.varT
        "nameList" []))) (Q.a .RBrace)]) "matchKindDeclaration" []]
      v (by rfl)
  simp only [List.mem_cons, List.not_mem_nil, or_false] at member
  subst constructor
  dsimp [Representation.Source.instantiatedFields, Q.tc, Q.nt, Q.t, Lang.Il.typcase.nottyp,
    P4SpecTec.Util.Source.mkPhrase, Domain.Mixfix.args] at instantiated
  repeat' first
    | simp only [Domain.Mixfix.args] at instantiated
    | dsimp only [List.flatMap, List.append, List.map, List.flatten] at instantiated
  rcases instantiated with ⟨_, instantiated⟩
  cases instantiated with
  | cons first rest =>
    cases rest
    generalize hargs : Domain.Mixfix.args tree = args at valid
    cases valid with
    | cons type text types values head tail =>
      cases tail
      have head := normalize _ first text head
      exact ⟨tree, shape, Representation.Source.mixopTrans tree _ _ matching rfl, text, hargs,
        head⟩

#audit_axioms NanoP4Spec.matchKindDeclaration.sourceFields


/-- Admission is inherited from the independently specified field contract. -/
def matchKindDeclaration.admitted : NanoP4Spec.matchKindDeclaration → Prop
  | .MATCH_KIND_lbrace_rbrace x => (NanoP4Spec.nameList.admitted) x


/-- The full source codec fixes the actual named encoder and decoder dictionaries. -/
theorem matchKindDeclaration.codec :
    @Representation.Codec NanoP4Spec.matchKindDeclaration
      ⟨NanoP4Spec.matchKindDeclaration.toValue⟩ ⟨NanoP4Spec.matchKindDeclaration.ofValue⟩
      matchKindDeclaration.source matchKindDeclaration.admitted := by
  letI : ToValue NanoP4Spec.matchKindDeclaration := ⟨NanoP4Spec.matchKindDeclaration.toValue⟩
  letI : OfValue NanoP4Spec.matchKindDeclaration := ⟨NanoP4Spec.matchKindDeclaration.ofValue⟩
  letI : ToValue (NanoP4Spec.nameList) := ⟨NanoP4Spec.nameList.toValue⟩
  letI : OfValue (NanoP4Spec.nameList) := ⟨NanoP4Spec.nameList.ofValue⟩
  have childCodec : @Representation.Codec (NanoP4Spec.nameList) ⟨NanoP4Spec.nameList.toValue⟩
    ⟨NanoP4Spec.nameList.ofValue⟩ (Representation.Source.Valid NanoP4Spec.spec
    Representation.Source.externDomain (Q.t (Q.varT "nameList" [])).it)
    (NanoP4Spec.nameList.admitted) := NanoP4Spec.nameList.codec
  refine { encodingValid := ?_, decoder := { sound := ?_, sufficient := ?_ } }
  · intro x hx
    cases x with
    | MATCH_KIND_lbrace_rbrace text =>
      change (NanoP4Spec.nameList.admitted) text at hx
      apply Representation.Source.ConstructorDomain.valid
        (Q.i "matchKindDeclaration") [] []
        [Q.tc (.Seq [.Atom (Q.a (.Keyword "MATCH_KIND")), .Brack (Q.a .LBrace) (.Arg (Q.t
          (Q.varT "nameList" []))) (Q.a .RBrace)]) "matchKindDeclaration" []]
        (Q.tc (.Seq [.Atom (Q.a (.Keyword "MATCH_KIND")), .Brack (Q.a .LBrace) (.Arg (Q.t
          (Q.varT "nameList" []))) (Q.a .RBrace)]) "matchKindDeclaration" [])
        [(Q.t (Q.varT "nameList" []))] _ (by rfl) (by simp)
        (by
          refine ⟨rfl, ?_⟩
          dsimp [Q.tc, Q.nt, Q.t, Lang.Il.typcase.nottyp,
            P4SpecTec.Util.Source.mkPhrase, Domain.Mixfix.args]
          repeat' first
            | simp only [Domain.Mixfix.args]
            | dsimp only [List.flatMap, List.append, List.map, List.flatten]
          change List.Forall₂ (fun a b : Lang.Il.typ =>
            Representation.Source.Substitutes [] a.it b.it) [(Q.t (Q.varT "nameList" []))] [(Q.t
              (Q.varT "nameList" []))]
          exact .cons (Representation.Source.Substitutes.named (Q.i "nameList") [] [] rfl
            (.nil)) .nil)
      refine ⟨(.Seq [(.Atom (Prelude.Value.atom (.Keyword "MATCH_KIND"))), (.Brack
        (Prelude.Value.atom .LBrace) (.Arg ((NanoP4Spec.nameList.toValue) text))
        (Prelude.Value.atom .RBrace))]),
        rfl, rfl, ?_⟩
      repeat' first
        | simp only [Domain.Mixfix.args]
        | dsimp only [List.flatMap, List.append, List.map, List.flatten]
      exact .cons ((Q.t (Q.varT "nameList" []))) ((NanoP4Spec.nameList.toValue) text) [] []
        (childCodec.encodingValid text hx) .nil
  · intro fuel v x hv hd
    obtain ⟨tree, shape, matching, text, fields, valid⟩ := matchKindDeclaration.sourceFields v
      hv
    have args : Prelude.Value.caseArgs tree
        (.Seq [(.Atom (Prelude.Value.atom (.Keyword "MATCH_KIND"))), (.Brack (Prelude.Value.atom
          .LBrace) (.Arg ()) (Prelude.Value.atom .RBrace))]) = some [text] := by
      change Domain.Mixfix.eq_mixop tree
        (.Seq [(.Atom (Prelude.Value.atom (.Keyword "MATCH_KIND"))), (.Brack (Prelude.Value.atom
          .LBrace) (.Arg ()) (Prelude.Value.atom .RBrace))]) = true at matching
      simp only [Prelude.Value.caseArgs, matching, ite_true, fields]
    cases fuel with
    | zero => cases hd
    | succ fuel =>
      simp only [OfValue.ofValue, NanoP4Spec.matchKindDeclaration.ofValue, shape, args] at hd
      cases decoded : (NanoP4Spec.nameList.ofValue) fuel text with
      | none =>
        change ((NanoP4Spec.nameList.ofValue) fuel text).bind (fun r => some
          (NanoP4Spec.matchKindDeclaration.MATCH_KIND_lbrace_rbrace r)) = some x at hd
        rw [decoded] at hd
        cases hd
      | some result =>
        change ((NanoP4Spec.nameList.ofValue) fuel text).bind (fun r => some
          (NanoP4Spec.matchKindDeclaration.MATCH_KIND_lbrace_rbrace r)) = some x at hd
        rw [decoded] at hd
        change some (NanoP4Spec.matchKindDeclaration.MATCH_KIND_lbrace_rbrace result) = some x
          at hd
        cases Option.some.inj hd
        have related := childCodec.decoder.sound fuel text result valid decoded
        constructor
        · exact related.1
        ·
          change Rel v (NanoP4Spec.matchKindDeclaration.toValue (.MATCH_KIND_lbrace_rbrace
            result))
          apply Representation.Source.caseRelation (rendered :=
            (.Seq [(.Atom (Prelude.Value.atom (.Keyword "MATCH_KIND"))), (.Brack
              (Prelude.Value.atom .LBrace) (.Arg ((NanoP4Spec.nameList.toValue) result))
              (Prelude.Value.atom .RBrace))]))
            shape rfl
          · exact Representation.Source.mixopTrans tree _ _ matching rfl
          · rw [fields]
            repeat' first
              | simp only [Domain.Mixfix.args]
              | dsimp only [List.flatMap, List.append, List.map, List.flatten]
            dsimp only [canons]
            exact congrArg (fun c => [c]) related.2
  · intro v hv
    obtain ⟨tree, shape, matching, text, fields, valid⟩ := matchKindDeclaration.sourceFields v
      hv
    obtain ⟨result, bound, stable⟩ := childCodec.decoder.sufficient text valid
    change ∀ fuel, bound ≤ fuel → (NanoP4Spec.nameList.ofValue) fuel text =
      some result at stable
    refine ⟨ .MATCH_KIND_lbrace_rbrace result, bound + 1, ?_⟩
    intro fuel large
    cases fuel with
    | zero => omega
    | succ fuel =>
      have args : Prelude.Value.caseArgs tree
          (.Seq [(.Atom (Prelude.Value.atom (.Keyword "MATCH_KIND"))), (.Brack
            (Prelude.Value.atom .LBrace) (.Arg ()) (Prelude.Value.atom .RBrace))]) = some [text]
            := by
        change Domain.Mixfix.eq_mixop tree
          (.Seq [(.Atom (Prelude.Value.atom (.Keyword "MATCH_KIND"))), (.Brack
            (Prelude.Value.atom .LBrace) (.Arg ()) (Prelude.Value.atom .RBrace))]) = true
            at matching
        simp only [Prelude.Value.caseArgs, matching, ite_true, fields]
      simp only [OfValue.ofValue, NanoP4Spec.matchKindDeclaration.ofValue, shape, args]
      change ((NanoP4Spec.nameList.ofValue) fuel text).bind (fun r => some
        (NanoP4Spec.matchKindDeclaration.MATCH_KIND_lbrace_rbrace r)) = _
      rw [stable fuel (by omega)]
      rfl

#audit_axioms NanoP4Spec.matchKindDeclaration.codec


/-- Every carrier value is admitted under the stated child totals. -/
theorem matchKindDeclaration.admittedAll : ∀ x : NanoP4Spec.matchKindDeclaration,
  (NanoP4Spec.matchKindDeclaration.admitted) x := by
  intro x
  cases x with
  | MATCH_KIND_lbrace_rbrace a =>
    exact ((show ∀ x : (NanoP4Spec.nameList), (NanoP4Spec.nameList.admitted) x from
      NanoP4Spec.nameList.admittedAll)) a

#audit_axioms NanoP4Spec.matchKindDeclaration.admittedAll

end NanoP4Spec
