-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group Representation.objectValue
import P4SpecTec.Refine.Representation.Delay
import P4SpecTec.Refine.Representation.Source
import P4SpecTec.Refine.Representation.SourceAlias
import P4SpecTec.Refine.Representation.SourceAtomic
import P4SpecTec.Refine.Representation.SourceRecord
import P4SpecTec.Refine.Representation.SourceCodec
import P4SpecTec.Refine.Representation.SourceTuple
import P4SpecTec.Refine.Representation.SourceExtern
import P4SpecTec.Refine.Representation.SourceVariant
import P4SpecTec.Tactic.Audit
import P4SpecTec.Tactic.CarrierInduction
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality
import NanoP4Spec.Refinement.Representation.typeId
import NanoP4Spec.Refinement.Representation.nameIR
import NanoP4Spec.Refinement.Representation.tableProperties
import NanoP4Spec.Refinement.Representation.objectState

/-! # NanoP4Spec.Refinement.Representation.objectValue

Generated: refinement theorems, group Representation.objectValue.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

private def objectValue.sourceCases : List Lang.Il.typcase := [Q.tc (.Seq [.Atom (Q.a (.Keyword
  "PACKET")), .Arg (Q.t (Q.varT "typeId" [])), .Arg (Q.t (Q.varT "objectState" []))])
  "packetValue" [], Q.tc (.Seq [.Atom (Q.a (.Keyword "TABLE")), .Arg (Q.t (Q.varT "nameIR" [])),
  .Arg (Q.t (Q.varT "tableProperties" []))]) "tableValue" []]

/-- The complete independent grammar of the actual quoted variant. -/
def objectValue.source (v : Lang.Il.value) : Prop :=
  Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.varT
    "objectValue" []) v

/-- Every constructor inherits exactly its positional fields' admission. -/
def objectValue.admitted : NanoP4Spec.objectValue → Prop
  | .PACKET x0 x1 => (fun _ => True) x0 ∧ (fun _ : ExternValue => True) x1 ∧ True
  | .TABLE x0 x1 => (fun _ => True) x0 ∧ (NanoP4Spec.tableProperties.admitted) x1 ∧ True

/-- The exact positional field codec on its independent source grammar. -/
private theorem objectValue.fieldCodec0_0 : @Representation.Codec (NanoP4Spec.typeId)
  ⟨NanoP4Spec.typeId.toValue⟩ ⟨NanoP4Spec.typeId.ofValue⟩ (Representation.Source.Valid
  NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT "typeId" [])).it) (fun _ =>
  True) :=
  NanoP4Spec.typeId.codec

/-- Empty substitution preserves the complete independent field domain. -/
private theorem objectValue.fieldSubstitution0_0 : ∀ actual,
    Representation.Source.Substitutes [] (Q.t (Q.varT "typeId" [])).it actual → ∀ v,
    Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain actual v →
      (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t
      (Q.varT "typeId" [])).it) v :=
  (by
    intro actual substitution v valid
    rw [substitution.emptyNamedResult (Q.i "typeId")] at valid
    exact valid)

/-- The exact positional field codec on its independent source grammar. -/
private theorem objectValue.fieldCodec0_1 : @Representation.Codec (NanoP4Spec.objectState)
  ⟨@ToValue.toValue ExternValue P4SpecTec.Prelude.instToValueExternValue⟩ ⟨@OfValue.ofValue
  ExternValue P4SpecTec.Prelude.instOfValueExternValue⟩ (Representation.Source.Valid
  NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT "objectState" [])).it) (fun _
  : ExternValue => True) :=
  @Representation.Source.externalCodec NanoP4Spec.spec (Q.i "objectState") (by rfl)

/-- Empty substitution preserves the complete independent field domain. -/
private theorem objectValue.fieldSubstitution0_1 : ∀ actual,
    Representation.Source.Substitutes [] (Q.t (Q.varT "objectState" [])).it actual → ∀ v,
    Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain actual v →
      (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t
      (Q.varT "objectState" [])).it) v :=
  (by
    intro actual substitution v valid
    rw [substitution.emptyNamedResult (Q.i "objectState")] at valid
    exact valid)

/-- The exact positional field codec on its independent source grammar. -/
private theorem objectValue.fieldCodec1_0 : @Representation.Codec (NanoP4Spec.nameIR)
  ⟨NanoP4Spec.nameIR.toValue⟩ ⟨NanoP4Spec.nameIR.ofValue⟩ (Representation.Source.Valid
  NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT "nameIR" [])).it) (fun _ =>
  True) :=
  NanoP4Spec.nameIR.codec

/-- Empty substitution preserves the complete independent field domain. -/
private theorem objectValue.fieldSubstitution1_0 : ∀ actual,
    Representation.Source.Substitutes [] (Q.t (Q.varT "nameIR" [])).it actual → ∀ v,
    Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain actual v →
      (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t
      (Q.varT "nameIR" [])).it) v :=
  (by
    intro actual substitution v valid
    rw [substitution.emptyNamedResult (Q.i "nameIR")] at valid
    exact valid)

/-- The exact positional field codec on its independent source grammar. -/
private theorem objectValue.fieldCodec1_1 : @Representation.Codec (NanoP4Spec.tableProperties)
  ⟨NanoP4Spec.tableProperties.toValue⟩ ⟨NanoP4Spec.tableProperties.ofValue⟩
  (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT
  "tableProperties" [])).it) (NanoP4Spec.tableProperties.admitted) :=
  NanoP4Spec.tableProperties.codec

/-- Empty substitution preserves the complete independent field domain. -/
private theorem objectValue.fieldSubstitution1_1 : ∀ actual,
    Representation.Source.Substitutes [] (Q.t (Q.varT "tableProperties" [])).it actual → ∀ v,
    Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain actual v →
      (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t
      (Q.varT "tableProperties" [])).it) v :=
  (by
    intro actual substitution v valid
    rw [substitution.emptyNamedResult (Q.i "tableProperties")] at valid
    exact valid)

private theorem objectValue.sourceCasesValid (v : Lang.Il.value) (hv : objectValue.source v) :
    ∃ c ∈ objectValue.sourceCases, Representation.Source.ConstructorDomain NanoP4Spec.spec
      Representation.Source.externDomain c (Domain.Mixfix.args c.nottyp.it) v := by
  obtain ⟨c, member, fields, sub, tree, shape, matching, valid⟩ :=
    hv.variantPayload (Q.i "objectValue") [] [] objectValue.sourceCases v (by rfl)
  refine ⟨c, member, tree, shape, matching, ?_⟩
  apply valid.domains
  simp only [objectValue.sourceCases, List.mem_cons, List.not_mem_nil, or_false] at member
  rcases member with rfl | rfl
  ·
    dsimp [Representation.Source.instantiatedFields, Q.tc, Q.nt, Q.t,
      Lang.Il.typcase.nottyp, P4SpecTec.Util.Source.mkPhrase] at sub
    repeat' first
      | simp only [Domain.Mixfix.args] at sub
      | dsimp only [List.flatMap, List.append, List.map, List.flatten] at sub
    obtain ⟨_, sub⟩ := sub
    cases sub with
    | cons sub0 tail =>
      cases tail with
      | cons sub1 tail =>
        cases tail
        dsimp [Q.tc, Q.nt, Q.t, Lang.Il.typcase.nottyp, P4SpecTec.Util.Source.mkPhrase]
        repeat' first
          | simp only [Domain.Mixfix.args]
          | dsimp only [List.flatMap, List.append, List.map, List.flatten]
        exact .cons (objectValue.fieldSubstitution0_0 _ sub0) (.cons
          (objectValue.fieldSubstitution0_1 _ sub1) (.nil))
  ·
    dsimp [Representation.Source.instantiatedFields, Q.tc, Q.nt, Q.t,
      Lang.Il.typcase.nottyp, P4SpecTec.Util.Source.mkPhrase] at sub
    repeat' first
      | simp only [Domain.Mixfix.args] at sub
      | dsimp only [List.flatMap, List.append, List.map, List.flatten] at sub
    obtain ⟨_, sub⟩ := sub
    cases sub with
    | cons sub0 tail =>
      cases tail with
      | cons sub1 tail =>
        cases tail
        dsimp [Q.tc, Q.nt, Q.t, Lang.Il.typcase.nottyp, P4SpecTec.Util.Source.mkPhrase]
        repeat' first
          | simp only [Domain.Mixfix.args]
          | dsimp only [List.flatMap, List.append, List.map, List.flatten]
        exact .cons (objectValue.fieldSubstitution1_0 _ sub0) (.cons
          (objectValue.fieldSubstitution1_1 _ sub1) (.nil))

private theorem objectValue.decode0 (fuel : Nat) (v : Lang.Il.value) (tree : Domain.Mixfix.t
  Lang.Il.value) (v0 : Lang.Il.value) (v1 : Lang.Il.value)
    (shape : v.it = .CaseV tree) (matching : Domain.Mixfix.eq_mixop tree (((.Seq [(.Atom
      (Prelude.Value.atom (.Keyword "PACKET"))), (.Arg ()), (.Arg ())])) : Domain.Mixfix.mixop)
      = true)
    (fields : Domain.Mixfix.args tree = [v0, v1]) :
    NanoP4Spec.objectValue.ofValue (fuel + 1) v = ((NanoP4Spec.typeId.ofValue) fuel v0).bind
      (fun x0 => ((@OfValue.ofValue ExternValue P4SpecTec.Prelude.instOfValueExternValue) fuel
      v1).bind (fun x1 => some (NanoP4Spec.objectValue.PACKET x0 x1))) := by
  have selected : Prelude.Value.caseArgs tree ((.Seq [(.Atom (Prelude.Value.atom (.Keyword
    "PACKET"))), (.Arg ()), (.Arg ())])) = some [v0, v1] := by
    simp only [Prelude.Value.caseArgs, matching, ite_true, fields]
  have other1 : Prelude.Value.caseArgs tree ((.Seq [(.Atom (Prelude.Value.atom (.Keyword
    "TABLE"))), (.Arg ()), (.Arg ())])) = none :=
    Representation.Source.caseArgsDisjoint tree ((.Seq [(.Atom (Prelude.Value.atom (.Keyword
      "PACKET"))), (.Arg ()), (.Arg ())])) ((.Seq [(.Atom (Prelude.Value.atom (.Keyword
      "TABLE"))), (.Arg ()), (.Arg ())])) matching (by decide)
  simp only [NanoP4Spec.objectValue.ofValue, shape, selected, other1]
  change ((((NanoP4Spec.typeId.ofValue) fuel v0).bind (fun x0 => ((@OfValue.ofValue ExternValue
    P4SpecTec.Prelude.instOfValueExternValue) fuel v1).bind (fun x1 => some
    (NanoP4Spec.objectValue.PACKET x0 x1)))) <|> none) = ((NanoP4Spec.typeId.ofValue) fuel
    v0).bind (fun x0 => ((@OfValue.ofValue ExternValue P4SpecTec.Prelude.instOfValueExternValue)
    fuel v1).bind (fun x1 => some (NanoP4Spec.objectValue.PACKET x0 x1)))
  cases ((NanoP4Spec.typeId.ofValue) fuel v0) <;> cases ((@OfValue.ofValue ExternValue
    P4SpecTec.Prelude.instOfValueExternValue) fuel v1) <;> rfl

private theorem objectValue.decode1 (fuel : Nat) (v : Lang.Il.value) (tree : Domain.Mixfix.t
  Lang.Il.value) (v0 : Lang.Il.value) (v1 : Lang.Il.value)
    (shape : v.it = .CaseV tree) (matching : Domain.Mixfix.eq_mixop tree (((.Seq [(.Atom
      (Prelude.Value.atom (.Keyword "TABLE"))), (.Arg ()), (.Arg ())])) : Domain.Mixfix.mixop) =
      true)
    (fields : Domain.Mixfix.args tree = [v0, v1]) :
    NanoP4Spec.objectValue.ofValue (fuel + 1) v = ((NanoP4Spec.nameIR.ofValue) fuel v0).bind
      (fun x0 => ((NanoP4Spec.tableProperties.ofValue) fuel v1).bind (fun x1 => some
      (NanoP4Spec.objectValue.TABLE x0 x1))) := by
  have selected : Prelude.Value.caseArgs tree ((.Seq [(.Atom (Prelude.Value.atom (.Keyword
    "TABLE"))), (.Arg ()), (.Arg ())])) = some [v0, v1] := by
    simp only [Prelude.Value.caseArgs, matching, ite_true, fields]
  have other0 : Prelude.Value.caseArgs tree ((.Seq [(.Atom (Prelude.Value.atom (.Keyword
    "PACKET"))), (.Arg ()), (.Arg ())])) = none :=
    Representation.Source.caseArgsDisjoint tree ((.Seq [(.Atom (Prelude.Value.atom (.Keyword
      "TABLE"))), (.Arg ()), (.Arg ())])) ((.Seq [(.Atom (Prelude.Value.atom (.Keyword
      "PACKET"))), (.Arg ()), (.Arg ())])) matching (by decide)
  simp only [NanoP4Spec.objectValue.ofValue, shape, selected, other0]
  change (none <|> (((NanoP4Spec.nameIR.ofValue) fuel v0).bind (fun x0 =>
    ((NanoP4Spec.tableProperties.ofValue) fuel v1).bind (fun x1 => some
    (NanoP4Spec.objectValue.TABLE x0 x1))))) = ((NanoP4Spec.nameIR.ofValue) fuel v0).bind (fun
    x0 => ((NanoP4Spec.tableProperties.ofValue) fuel v1).bind (fun x1 => some
    (NanoP4Spec.objectValue.TABLE x0 x1)))
  cases ((NanoP4Spec.nameIR.ofValue) fuel v0) <;> cases ((NanoP4Spec.tableProperties.ofValue)
    fuel v1) <;> rfl

/-- The full codec fixes the actual named encoder and decoder dictionaries. -/
theorem objectValue.codec : @Refine.Representation.Codec NanoP4Spec.objectValue
  ⟨NanoP4Spec.objectValue.toValue⟩ ⟨NanoP4Spec.objectValue.ofValue⟩
  NanoP4Spec.objectValue.source NanoP4Spec.objectValue.admitted := by
  letI : ToValue NanoP4Spec.objectValue := ⟨NanoP4Spec.objectValue.toValue⟩
  letI : OfValue NanoP4Spec.objectValue := ⟨NanoP4Spec.objectValue.ofValue⟩
  refine { encodingValid := ?_, decoder := { sound := ?_, sufficient := ?_ } }
  · intro x hx
    cases x with
    | PACKET x0 x1 =>
      dsimp only [NanoP4Spec.objectValue.admitted] at hx
      obtain ⟨admitted0, admitted1, _⟩ := hx
      apply Representation.Source.ConstructorDomain.valid (Q.i "objectValue") [] []
        objectValue.sourceCases (Q.tc (.Seq [.Atom (Q.a (.Keyword "PACKET")), .Arg (Q.t (Q.varT
        "typeId" [])), .Arg (Q.t (Q.varT "objectState" []))]) "packetValue" []) [Q.t (Q.varT
        "typeId" []), Q.t (Q.varT "objectState" [])] _ (by rfl)
        (by simp [objectValue.sourceCases])
        (by
          refine ⟨rfl, ?_⟩
          dsimp [Q.tc, Q.nt, Q.t, Lang.Il.typcase.nottyp, P4SpecTec.Util.Source.mkPhrase]
          repeat' first
            | simp only [Domain.Mixfix.args]
            | dsimp only [List.flatMap, List.append, List.map, List.flatten]
          exact .cons (Representation.Source.Substitutes.named (Q.i "typeId") [] [] rfl (.nil))
            (.cons (Representation.Source.Substitutes.named (Q.i "objectState") [] [] rfl
            (.nil)) (.nil)))
      refine ⟨(.Seq [(.Atom (Prelude.Value.atom (.Keyword "PACKET"))), (.Arg
        ((NanoP4Spec.typeId.toValue) x0)), (.Arg ((@ToValue.toValue ExternValue
        P4SpecTec.Prelude.instToValueExternValue) x1))]), rfl, rfl, ?_⟩
      repeat' first
        | simp only [Domain.Mixfix.args]
        | dsimp only [List.flatMap, List.append, List.map, List.flatten]
      exact .cons _ _ _ _ ((@Representation.Codec.encodingValid (NanoP4Spec.typeId)
        ⟨NanoP4Spec.typeId.toValue⟩ ⟨NanoP4Spec.typeId.ofValue⟩ (Representation.Source.Valid
        NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT "typeId" [])).it) (fun _
        => True) (objectValue.fieldCodec0_0)) x0 admitted0) (.cons _ _ _ _
        ((@Representation.Codec.encodingValid (NanoP4Spec.objectState) ⟨@ToValue.toValue
        ExternValue P4SpecTec.Prelude.instToValueExternValue⟩ ⟨@OfValue.ofValue ExternValue
        P4SpecTec.Prelude.instOfValueExternValue⟩ (Representation.Source.Valid NanoP4Spec.spec
        Representation.Source.externDomain (Q.t (Q.varT "objectState" [])).it) (fun _ :
        ExternValue => True) (objectValue.fieldCodec0_1)) x1 admitted1) (.nil))
    | TABLE x0 x1 =>
      dsimp only [NanoP4Spec.objectValue.admitted] at hx
      obtain ⟨admitted0, admitted1, _⟩ := hx
      apply Representation.Source.ConstructorDomain.valid (Q.i "objectValue") [] []
        objectValue.sourceCases (Q.tc (.Seq [.Atom (Q.a (.Keyword "TABLE")), .Arg (Q.t (Q.varT
        "nameIR" [])), .Arg (Q.t (Q.varT "tableProperties" []))]) "tableValue" []) [Q.t (Q.varT
        "nameIR" []), Q.t (Q.varT "tableProperties" [])] _ (by rfl)
        (by simp [objectValue.sourceCases])
        (by
          refine ⟨rfl, ?_⟩
          dsimp [Q.tc, Q.nt, Q.t, Lang.Il.typcase.nottyp, P4SpecTec.Util.Source.mkPhrase]
          repeat' first
            | simp only [Domain.Mixfix.args]
            | dsimp only [List.flatMap, List.append, List.map, List.flatten]
          exact .cons (Representation.Source.Substitutes.named (Q.i "nameIR") [] [] rfl (.nil))
            (.cons (Representation.Source.Substitutes.named (Q.i "tableProperties") [] [] rfl
            (.nil)) (.nil)))
      refine ⟨(.Seq [(.Atom (Prelude.Value.atom (.Keyword "TABLE"))), (.Arg
        ((NanoP4Spec.nameIR.toValue) x0)), (.Arg ((NanoP4Spec.tableProperties.toValue) x1))]),
        rfl, rfl, ?_⟩
      repeat' first
        | simp only [Domain.Mixfix.args]
        | dsimp only [List.flatMap, List.append, List.map, List.flatten]
      exact .cons _ _ _ _ ((@Representation.Codec.encodingValid (NanoP4Spec.nameIR)
        ⟨NanoP4Spec.nameIR.toValue⟩ ⟨NanoP4Spec.nameIR.ofValue⟩ (Representation.Source.Valid
        NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT "nameIR" [])).it) (fun _
        => True) (objectValue.fieldCodec1_0)) x0 admitted0) (.cons _ _ _ _
        ((@Representation.Codec.encodingValid (NanoP4Spec.tableProperties)
        ⟨NanoP4Spec.tableProperties.toValue⟩ ⟨NanoP4Spec.tableProperties.ofValue⟩
        (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t
        (Q.varT "tableProperties" [])).it) (NanoP4Spec.tableProperties.admitted)
        (objectValue.fieldCodec1_1)) x1 admitted1) (.nil))
  · intro fuel v x hv decoded
    change NanoP4Spec.objectValue.ofValue fuel v = some x at decoded
    cases fuel with
    | zero => cases decoded
    | succ fuel =>
      obtain ⟨c, member, tree, shape, matching, valid⟩ := objectValue.sourceCasesValid v hv
      simp only [objectValue.sourceCases, List.mem_cons, List.not_mem_nil, or_false] at member
      rcases member with rfl | rfl
      ·
        dsimp [Q.tc, Q.nt, Q.t, Lang.Il.typcase.nottyp, P4SpecTec.Util.Source.mkPhrase] at valid
        repeat' first
          | simp only [Domain.Mixfix.args] at valid
          | dsimp only [List.flatMap, List.append, List.map, List.flatten] at valid
        generalize hargs : Domain.Mixfix.args tree = args at valid
        cases valid with
        | cons _ v0 _ _ p0 tail =>
          cases tail with
          | cons _ v1 _ _ p1 tail =>
            cases tail
            rw [objectValue.decode0 fuel v tree v0 v1 shape (Representation.Source.mixopTrans
              tree _ _ matching rfl) hargs] at decoded
            cases d0 : (NanoP4Spec.typeId.ofValue) fuel v0 with
            | none => simp [d0] at decoded
            | some x0 =>
              cases d1 : (@OfValue.ofValue ExternValue P4SpecTec.Prelude.instOfValueExternValue)
                fuel v1 with
              | none => simp [d0, d1] at decoded
              | some x1 =>
                simp only [d0, d1] at decoded
                have same := Option.some.inj decoded
                subst x
                obtain ⟨admitted0, related0⟩ :=
                  (@Representation.DecoderCorrect.sound (NanoP4Spec.typeId)
                    ⟨NanoP4Spec.typeId.toValue⟩ (Representation.Source.Valid NanoP4Spec.spec
                    Representation.Source.externDomain (Q.t (Q.varT "typeId" [])).it) (fun _ =>
                    True) (NanoP4Spec.typeId.ofValue) (@Representation.Codec.decoder
                    (NanoP4Spec.typeId) ⟨NanoP4Spec.typeId.toValue⟩ ⟨NanoP4Spec.typeId.ofValue⟩
                    (Representation.Source.Valid NanoP4Spec.spec
                    Representation.Source.externDomain (Q.t (Q.varT "typeId" [])).it) (fun _ =>
                    True) (objectValue.fieldCodec0_0))) fuel v0 x0 p0 d0
                have canonical0 : canon v0 = canon ((NanoP4Spec.typeId.toValue) x0) := related0
                obtain ⟨admitted1, related1⟩ :=
                  (@Representation.DecoderCorrect.sound (NanoP4Spec.objectState)
                    ⟨@ToValue.toValue ExternValue P4SpecTec.Prelude.instToValueExternValue⟩
                    (Representation.Source.Valid NanoP4Spec.spec
                    Representation.Source.externDomain (Q.t (Q.varT "objectState" [])).it) (fun
                    _ : ExternValue => True) (@OfValue.ofValue ExternValue
                    P4SpecTec.Prelude.instOfValueExternValue) (@Representation.Codec.decoder
                    (NanoP4Spec.objectState) ⟨@ToValue.toValue ExternValue
                    P4SpecTec.Prelude.instToValueExternValue⟩ ⟨@OfValue.ofValue ExternValue
                    P4SpecTec.Prelude.instOfValueExternValue⟩ (Representation.Source.Valid
                    NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT
                    "objectState" [])).it) (fun _ : ExternValue => True)
                    (objectValue.fieldCodec0_1))) fuel v1 x1 p1 d1
                have canonical1 : canon v1 = canon ((@ToValue.toValue ExternValue
                  P4SpecTec.Prelude.instToValueExternValue) x1) := related1
                refine ⟨⟨admitted0, admitted1, trivial⟩, ?_⟩
                change Rel v (NanoP4Spec.objectValue.toValue (NanoP4Spec.objectValue.PACKET x0
                  x1))
                apply Representation.Source.caseRelation (rendered := (.Seq [(.Atom
                  (Prelude.Value.atom (.Keyword "PACKET"))), (.Arg ((NanoP4Spec.typeId.toValue)
                  x0)), (.Arg ((@ToValue.toValue ExternValue
                  P4SpecTec.Prelude.instToValueExternValue) x1))])) shape rfl
                · exact Representation.Source.mixopTrans tree _ _ matching rfl
                · rw [hargs]
                  repeat' first
                    | simp only [Domain.Mixfix.args]
                    | dsimp only [List.flatMap, List.append, List.map, List.flatten]
                  all_goals
                    dsimp only [canons]
                    exact congr (congrArg List.cons (canonical0)) (congr (congrArg List.cons
                      (canonical1)) (rfl))
      ·
        dsimp [Q.tc, Q.nt, Q.t, Lang.Il.typcase.nottyp, P4SpecTec.Util.Source.mkPhrase] at valid
        repeat' first
          | simp only [Domain.Mixfix.args] at valid
          | dsimp only [List.flatMap, List.append, List.map, List.flatten] at valid
        generalize hargs : Domain.Mixfix.args tree = args at valid
        cases valid with
        | cons _ v0 _ _ p0 tail =>
          cases tail with
          | cons _ v1 _ _ p1 tail =>
            cases tail
            rw [objectValue.decode1 fuel v tree v0 v1 shape (Representation.Source.mixopTrans
              tree _ _ matching rfl) hargs] at decoded
            cases d0 : (NanoP4Spec.nameIR.ofValue) fuel v0 with
            | none => simp [d0] at decoded
            | some x0 =>
              cases d1 : (NanoP4Spec.tableProperties.ofValue) fuel v1 with
              | none => simp [d0, d1] at decoded
              | some x1 =>
                simp only [d0, d1] at decoded
                have same := Option.some.inj decoded
                subst x
                obtain ⟨admitted0, related0⟩ :=
                  (@Representation.DecoderCorrect.sound (NanoP4Spec.nameIR)
                    ⟨NanoP4Spec.nameIR.toValue⟩ (Representation.Source.Valid NanoP4Spec.spec
                    Representation.Source.externDomain (Q.t (Q.varT "nameIR" [])).it) (fun _ =>
                    True) (NanoP4Spec.nameIR.ofValue) (@Representation.Codec.decoder
                    (NanoP4Spec.nameIR) ⟨NanoP4Spec.nameIR.toValue⟩ ⟨NanoP4Spec.nameIR.ofValue⟩
                    (Representation.Source.Valid NanoP4Spec.spec
                    Representation.Source.externDomain (Q.t (Q.varT "nameIR" [])).it) (fun _ =>
                    True) (objectValue.fieldCodec1_0))) fuel v0 x0 p0 d0
                have canonical0 : canon v0 = canon ((NanoP4Spec.nameIR.toValue) x0) := related0
                obtain ⟨admitted1, related1⟩ :=
                  (@Representation.DecoderCorrect.sound (NanoP4Spec.tableProperties)
                    ⟨NanoP4Spec.tableProperties.toValue⟩ (Representation.Source.Valid
                    NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT
                    "tableProperties" [])).it) (NanoP4Spec.tableProperties.admitted)
                    (NanoP4Spec.tableProperties.ofValue) (@Representation.Codec.decoder
                    (NanoP4Spec.tableProperties) ⟨NanoP4Spec.tableProperties.toValue⟩
                    ⟨NanoP4Spec.tableProperties.ofValue⟩ (Representation.Source.Valid
                    NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT
                    "tableProperties" [])).it) (NanoP4Spec.tableProperties.admitted)
                    (objectValue.fieldCodec1_1))) fuel v1 x1 p1 d1
                have canonical1 : canon v1 = canon ((NanoP4Spec.tableProperties.toValue) x1) :=
                  related1
                refine ⟨⟨admitted0, admitted1, trivial⟩, ?_⟩
                change Rel v (NanoP4Spec.objectValue.toValue (NanoP4Spec.objectValue.TABLE x0
                  x1))
                apply Representation.Source.caseRelation (rendered := (.Seq [(.Atom
                  (Prelude.Value.atom (.Keyword "TABLE"))), (.Arg ((NanoP4Spec.nameIR.toValue)
                  x0)), (.Arg ((NanoP4Spec.tableProperties.toValue) x1))])) shape rfl
                · exact Representation.Source.mixopTrans tree _ _ matching rfl
                · rw [hargs]
                  repeat' first
                    | simp only [Domain.Mixfix.args]
                    | dsimp only [List.flatMap, List.append, List.map, List.flatten]
                  all_goals
                    dsimp only [canons]
                    exact congr (congrArg List.cons (canonical0)) (congr (congrArg List.cons
                      (canonical1)) (rfl))
  · intro v hv
    obtain ⟨c, member, tree, shape, matching, valid⟩ := objectValue.sourceCasesValid v hv
    simp only [objectValue.sourceCases, List.mem_cons, List.not_mem_nil, or_false] at member
    rcases member with rfl | rfl
    ·
      dsimp [Q.tc, Q.nt, Q.t, Lang.Il.typcase.nottyp, P4SpecTec.Util.Source.mkPhrase] at valid
      repeat' first
        | simp only [Domain.Mixfix.args] at valid
        | dsimp only [List.flatMap, List.append, List.map, List.flatten] at valid
      generalize hargs : Domain.Mixfix.args tree = args at valid
      cases valid with
      | cons _ v0 _ _ p0 tail =>
        cases tail with
        | cons _ v1 _ _ p1 tail =>
          cases tail
          obtain ⟨x0, b0, h0⟩ :=
            (@Representation.DecoderCorrect.sufficient (NanoP4Spec.typeId)
              ⟨NanoP4Spec.typeId.toValue⟩ (Representation.Source.Valid NanoP4Spec.spec
              Representation.Source.externDomain (Q.t (Q.varT "typeId" [])).it) (fun _ => True)
              (NanoP4Spec.typeId.ofValue) (@Representation.Codec.decoder (NanoP4Spec.typeId)
              ⟨NanoP4Spec.typeId.toValue⟩ ⟨NanoP4Spec.typeId.ofValue⟩
              (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain
              (Q.t (Q.varT "typeId" [])).it) (fun _ => True) (objectValue.fieldCodec0_0))) v0 p0
          obtain ⟨x1, b1, h1⟩ :=
            (@Representation.DecoderCorrect.sufficient (NanoP4Spec.objectState)
              ⟨@ToValue.toValue ExternValue P4SpecTec.Prelude.instToValueExternValue⟩
              (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain
              (Q.t (Q.varT "objectState" [])).it) (fun _ : ExternValue => True)
              (@OfValue.ofValue ExternValue P4SpecTec.Prelude.instOfValueExternValue)
              (@Representation.Codec.decoder (NanoP4Spec.objectState) ⟨@ToValue.toValue
              ExternValue P4SpecTec.Prelude.instToValueExternValue⟩ ⟨@OfValue.ofValue
              ExternValue P4SpecTec.Prelude.instOfValueExternValue⟩ (Representation.Source.Valid
              NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT "objectState"
              [])).it) (fun _ : ExternValue => True) (objectValue.fieldCodec0_1))) v1 p1
          refine ⟨(NanoP4Spec.objectValue.PACKET x0 x1), (max b0 (max b1 (0))) + 1, ?_⟩
          intro fuel large
          cases fuel with
          | zero => omega
          | succ fuel =>
            have enough0 : b0 ≤ fuel := by omega
            have enough1 : b1 ≤ fuel := by omega
            change NanoP4Spec.objectValue.ofValue (fuel + 1) v = _
            rw [objectValue.decode0 fuel v tree v0 v1 shape (Representation.Source.mixopTrans
              tree _ _ matching rfl) hargs]
            rw [h0 fuel enough0, h1 fuel enough1]
            all_goals rfl
    ·
      dsimp [Q.tc, Q.nt, Q.t, Lang.Il.typcase.nottyp, P4SpecTec.Util.Source.mkPhrase] at valid
      repeat' first
        | simp only [Domain.Mixfix.args] at valid
        | dsimp only [List.flatMap, List.append, List.map, List.flatten] at valid
      generalize hargs : Domain.Mixfix.args tree = args at valid
      cases valid with
      | cons _ v0 _ _ p0 tail =>
        cases tail with
        | cons _ v1 _ _ p1 tail =>
          cases tail
          obtain ⟨x0, b0, h0⟩ :=
            (@Representation.DecoderCorrect.sufficient (NanoP4Spec.nameIR)
              ⟨NanoP4Spec.nameIR.toValue⟩ (Representation.Source.Valid NanoP4Spec.spec
              Representation.Source.externDomain (Q.t (Q.varT "nameIR" [])).it) (fun _ => True)
              (NanoP4Spec.nameIR.ofValue) (@Representation.Codec.decoder (NanoP4Spec.nameIR)
              ⟨NanoP4Spec.nameIR.toValue⟩ ⟨NanoP4Spec.nameIR.ofValue⟩
              (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain
              (Q.t (Q.varT "nameIR" [])).it) (fun _ => True) (objectValue.fieldCodec1_0))) v0 p0
          obtain ⟨x1, b1, h1⟩ :=
            (@Representation.DecoderCorrect.sufficient (NanoP4Spec.tableProperties)
              ⟨NanoP4Spec.tableProperties.toValue⟩ (Representation.Source.Valid NanoP4Spec.spec
              Representation.Source.externDomain (Q.t (Q.varT "tableProperties" [])).it)
              (NanoP4Spec.tableProperties.admitted) (NanoP4Spec.tableProperties.ofValue)
              (@Representation.Codec.decoder (NanoP4Spec.tableProperties)
              ⟨NanoP4Spec.tableProperties.toValue⟩ ⟨NanoP4Spec.tableProperties.ofValue⟩
              (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain
              (Q.t (Q.varT "tableProperties" [])).it) (NanoP4Spec.tableProperties.admitted)
              (objectValue.fieldCodec1_1))) v1 p1
          refine ⟨(NanoP4Spec.objectValue.TABLE x0 x1), (max b0 (max b1 (0))) + 1, ?_⟩
          intro fuel large
          cases fuel with
          | zero => omega
          | succ fuel =>
            have enough0 : b0 ≤ fuel := by omega
            have enough1 : b1 ≤ fuel := by omega
            change NanoP4Spec.objectValue.ofValue (fuel + 1) v = _
            rw [objectValue.decode1 fuel v tree v0 v1 shape (Representation.Source.mixopTrans
              tree _ _ matching rfl) hargs]
            rw [h0 fuel enough0, h1 fuel enough1]
            all_goals rfl


/-- Every carrier value is admitted under the stated child totals. -/
theorem objectValue.admittedAll : ∀ x : NanoP4Spec.objectValue,
  (NanoP4Spec.objectValue.admitted) x := by
  intro x
  cases x with
  | PACKET x0 x1 =>
    exact ⟨((show ∀ x : (NanoP4Spec.typeId), (fun _ => True) x from
      NanoP4Spec.typeId.admittedAll)) x0, ((show ∀ x : (NanoP4Spec.objectState), (fun _ :
      ExternValue => True) x from fun _ => True.intro)) x1, trivial⟩
  | TABLE x0 x1 =>
    exact ⟨((show ∀ x : (NanoP4Spec.nameIR), (fun _ => True) x from
      NanoP4Spec.nameIR.admittedAll)) x0, ((show ∀ x : (NanoP4Spec.tableProperties),
      (NanoP4Spec.tableProperties.admitted) x from NanoP4Spec.tableProperties.admittedAll)) x1,
      trivial⟩


#audit_axioms NanoP4Spec.objectValue.fieldCodec0_0
#audit_axioms NanoP4Spec.objectValue.fieldSubstitution0_0
#audit_axioms NanoP4Spec.objectValue.fieldCodec0_1
#audit_axioms NanoP4Spec.objectValue.fieldSubstitution0_1
#audit_axioms NanoP4Spec.objectValue.fieldCodec1_0
#audit_axioms NanoP4Spec.objectValue.fieldSubstitution1_0
#audit_axioms NanoP4Spec.objectValue.fieldCodec1_1
#audit_axioms NanoP4Spec.objectValue.fieldSubstitution1_1
#audit_axioms NanoP4Spec.objectValue.sourceCasesValid
#audit_axioms objectValue.decode0
#audit_axioms objectValue.decode1
#audit_axioms NanoP4Spec.objectValue.codec
#audit_axioms NanoP4Spec.objectValue.admittedAll

end NanoP4Spec
