-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group Representation.set
import P4SpecTec.Refine.Representation.Delay
import P4SpecTec.Refine.Representation.Source
import P4SpecTec.Refine.Representation.SourceAlias
import P4SpecTec.Refine.Representation.SourceAtomic
import P4SpecTec.Refine.Representation.SourceRecord
import P4SpecTec.Refine.Representation.SourceCodec
import P4SpecTec.Refine.Representation.SourceTuple
import P4SpecTec.Refine.Representation.SourceExtern
import P4SpecTec.Refine.Representation.SourceVariant
import P4SpecTec.Tactic.Audit
import P4SpecTec.Tactic.CarrierInduction
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality

/-! # NanoP4Spec.Refinement.Representation.set

Generated: refinement theorems, group Representation.set.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

open Lang.Il Domain Representation.Source

/-- Admitted containers have independently admitted elements. -/
def set.admitted {α : Type} (element : α → Prop) : NanoP4Spec.set α → Prop
  | .lbrace_rbrace xs => ∀ x ∈ xs, element x

private def set.sourceConstructor : typcase := Q.tc (.Brack (Q.a .LBrace) (.Arg (Q.t (.IterT
  (Q.t (Q.varT "K" [])) .List))) (Q.a .RBrace)) "set" [Q.t (Q.varT "K" [])]

private theorem set.sourceArgs : Mixfix.args set.sourceConstructor.nottyp.it =
    [Q.t (.IterT (Q.t (Q.varT "K" [])) .List)] := by
  simp [set.sourceConstructor, typcase.nottyp, Q.tc, Q.nt, Mixfix.args]

#audit_axioms set.sourceArgs

private theorem set.sourceFields (element : Lang.Il.typ) (v : Lang.Il.value)
    (valid : Valid NanoP4Spec.spec Representation.Source.externDomain (Q.varT "set" [element])
      v) :
    ∃ (tree : Mixfix.t Lang.Il.value) (a : Lang.Il.value), v.it = .CaseV tree ∧
      Mixfix.eq_mixop tree
        (.Brack (Prelude.Value.atom .LBrace) (.Arg ()) (Prelude.Value.atom .RBrace)) = true ∧
      Mixfix.args tree = [a] ∧
      Valid NanoP4Spec.spec Representation.Source.externDomain (.IterT element .List) a := by
  obtain ⟨tree, shape, matching, payload⟩ := valid.singleConstructor
    (Q.i "set") [element] [Q.i "K"] set.sourceConstructor [Q.t (.IterT element .List)] v
    (by rfl) (by
      intro instantiated subs
      unfold instantiatedFields at subs
      rw [set.sourceArgs] at subs
      obtain ⟨_, subs⟩ := subs
      cases subs with
      | cons first rest =>
        cases rest
        obtain ⟨child, hc, hs⟩ := first.iterResult (Q.t (Q.varT "K" [])) .List
        have he := hs.boundResult (Q.i "K") rfl
        refine .cons ?_ .nil
        intro value hv
        rw [hc] at hv
        exact hv.iterElement he)
  generalize hargs : Mixfix.args tree = args at payload
  cases payload with
  | cons type a types values ha tail =>
    cases tail
    exact ⟨tree, a, shape, mixopTrans _ _ _ matching rfl, hargs, ha⟩

#audit_axioms set.sourceFields

/-- Complete source codec for every legal element codec. -/
theorem set.codec {α : Type} [ToValue α] [OfValue α]
    (element : Lang.Il.typ) (accepted : α → Prop)
    (elementCodec : Representation.Codec
      (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain
        element.it) accepted) :
    @Representation.Codec (NanoP4Spec.set α) ⟨NanoP4Spec.set.toValue⟩
      ⟨NanoP4Spec.set.ofValue⟩
      (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.varT
        "set" [element]))
      (set.admitted accepted) := by
  letI : ToValue (NanoP4Spec.set α) := ⟨NanoP4Spec.set.toValue⟩
  letI : OfValue (NanoP4Spec.set α) := ⟨NanoP4Spec.set.ofValue⟩
  have contentsCodec := listCodec element accepted elementCodec
  constructor
  · intro x hx
    cases x with
    | lbrace_rbrace xs =>
      refine Valid.variant (Q.i "set") [element] [Q.i "K"] [set.sourceConstructor]
        set.sourceConstructor
        [Q.t (.IterT element .List)] _
        (.Brack (Prelude.Value.atom .LBrace) (.Arg (ToValue.toValue xs)) (Prelude.Value.atom
          .RBrace)) (by rfl) (by exact List.mem_cons_self) rfl rfl ?_ ?_
      · unfold instantiatedFields
        rw [set.sourceArgs]
        exact ⟨rfl, .cons (.iter _ _ _ (.bound (Q.i "K") element.it rfl)) .nil⟩
      · simpa [Mixfix.args] using
          (Values.cons (Q.t (.IterT element .List)) _ [] []
            (contentsCodec.encodingValid xs hx) .nil)
  · constructor
    · intro fuel v x hv hd
      obtain ⟨tree, a, shape, matching, fields, ha⟩ := set.sourceFields element v hv
      have args : Prelude.Value.caseArgs tree
          (.Brack (Prelude.Value.atom .LBrace) (.Arg ()) (Prelude.Value.atom .RBrace)) =
            some [a] := by
        simp [Prelude.Value.caseArgs, matching, fields]
      cases fuel with
      | zero => cases hd
      | succ fuel =>
        simp only [OfValue.ofValue, NanoP4Spec.set.ofValue, shape, args] at hd
        change (do let a' ← OfValue.ofValue (α := List α) fuel a
                   pure (NanoP4Spec.set.lbrace_rbrace a')) = some x at hd
        cases da : OfValue.ofValue (α := List α) fuel a with
        | none => simp [da] at hd
        | some a' =>
          simp only [da] at hd
          change some (NanoP4Spec.set.lbrace_rbrace a') = some x at hd
          cases Option.some.inj hd
          obtain ⟨aa, ra⟩ := contentsCodec.decoder.sound fuel a a' ha da
          refine ⟨aa, ?_⟩
          change Rel v (NanoP4Spec.set.toValue (.lbrace_rbrace a'))
          apply caseRelation (rendered := (.Brack (Prelude.Value.atom .LBrace) (.Arg
            (ToValue.toValue a')) (Prelude.Value.atom .RBrace))) shape (by rfl)
          · exact mixopTrans _ _ _ matching rfl
          · simp [fields, Mixfix.args, canons]
            rw [show canon a = canon (ToValue.toValue a') from ra]
    · intro v hv
      obtain ⟨tree, a, shape, matching, fields, ha⟩ := set.sourceFields element v hv
      obtain ⟨a', boundA, da⟩ := contentsCodec.decoder.sufficient a ha
      refine ⟨.lbrace_rbrace a', boundA + 1, ?_⟩
      intro fuel hbound
      have args : Prelude.Value.caseArgs tree
          (.Brack (Prelude.Value.atom .LBrace) (.Arg ()) (Prelude.Value.atom .RBrace)) =
            some [a] := by
        simp [Prelude.Value.caseArgs, matching, fields]
      cases fuel with
      | zero => omega
      | succ fuel =>
        have da' := da fuel (by omega)
        simp only [OfValue.ofValue, NanoP4Spec.set.ofValue, shape, args]
        change (do let a' ← OfValue.ofValue (α := List α) fuel a
                   pure (NanoP4Spec.set.lbrace_rbrace a')) = _
        rw [da']
        rfl
#audit_axioms NanoP4Spec.set.codec

/-- Encoded container validity is exactly independent validity of every encoded element. -/
theorem set.encodingSourceIff {α : Type} [ToValue α]
    (element : Lang.Il.typ) (x : NanoP4Spec.set α) :
    Valid NanoP4Spec.spec Representation.Source.externDomain
      (Q.varT "set" [element]) (NanoP4Spec.set.toValue x) ↔
    set.admitted
      (fun a => Valid NanoP4Spec.spec Representation.Source.externDomain
        element.it (ToValue.toValue a)) x := by
  cases x with
  | lbrace_rbrace xs =>
    constructor
    · intro valid
      obtain ⟨tree, contents, shape, _matching, fields, ha⟩ := set.sourceFields _ _ valid
      have same : (.Brack (Prelude.Value.atom .LBrace) (.Arg (ToValue.toValue xs))
        (Prelude.Value.atom .RBrace)) = tree := Lang.Il.value'.CaseV.inj shape
      subst tree
      have args : [ToValue.toValue xs] = [contents] := by
        simpa only [Mixfix.args, List.flatMap_cons, List.flatMap_nil,
          List.nil_append, List.cons_append] using fields
      cases (List.cons.inj args).1
      exact (Representation.Source.encodedListIff element xs).mp ha
    · intro accepted
      refine Valid.variant (Q.i "set") [element] [Q.i "K"]
        [set.sourceConstructor] set.sourceConstructor [Q.t (.IterT element .List)] _
        (.Brack (Prelude.Value.atom .LBrace) (.Arg (ToValue.toValue xs)) (Prelude.Value.atom
          .RBrace)) (by rfl) (by exact List.mem_cons_self) rfl rfl ?_ ?_
      · unfold instantiatedFields
        rw [set.sourceArgs]
        exact ⟨rfl, .cons (.iter _ _ _ (.bound (Q.i "K") element.it rfl)) .nil⟩
      · simpa only [Mixfix.args, List.flatMap_cons, List.flatMap_nil,
          List.nil_append, List.cons_append] using
          (Values.cons (Q.t (.IterT element .List)) _ [] []
            ((Representation.Source.encodedListIff element xs).mpr accepted) .nil)

#audit_axioms set.encodingSourceIff

/-- Every carrier value is admitted under the stated child totals. -/
theorem set.admittedAll {α : Type} (accepted : α → Prop)
    (all : ∀ x, accepted x) :
    ∀ x : NanoP4Spec.set α, NanoP4Spec.set.admitted accepted x := by
  intro x; cases x with | lbrace_rbrace xs => intro a ha; exact all a

#audit_axioms NanoP4Spec.set.admittedAll

end NanoP4Spec
