-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group Representation.typeField
import P4SpecTec.Refine.Representation.Delay
import P4SpecTec.Refine.Representation.Source
import P4SpecTec.Refine.Representation.SourceAlias
import P4SpecTec.Refine.Representation.SourceAtomic
import P4SpecTec.Refine.Representation.SourceRecord
import P4SpecTec.Refine.Representation.SourceCodec
import P4SpecTec.Refine.Representation.SourceTuple
import P4SpecTec.Refine.Representation.SourceExtern
import P4SpecTec.Refine.Representation.SourceVariant
import P4SpecTec.Tactic.Audit
import P4SpecTec.Tactic.CarrierInduction
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality
import NanoP4Spec.Refinement.Representation.type
import NanoP4Spec.Refinement.Representation.name

/-! # NanoP4Spec.Refinement.Representation.typeField

Generated: refinement theorems, group Representation.typeField.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

private def typeField.sourceCases : List Lang.Il.typcase := [Q.tc (.Seq [.Arg (Q.t (Q.varT
  "type" [])), .Arg (Q.t (Q.varT "name" [])), .Atom (Q.a (.Operator ";"))]) "typeField" []]

/-- The complete independent grammar of the actual quoted variant. -/
def typeField.source (v : Lang.Il.value) : Prop :=
  Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.varT
    "typeField" []) v

/-- Every constructor inherits exactly its positional fields' admission. -/
def typeField.admitted : NanoP4Spec.typeField → Prop
  | .semi x0 x1 => (NanoP4Spec.type.admitted) x0 ∧ (NanoP4Spec.name.admitted) x1 ∧ True

/-- The exact positional field codec on its independent source grammar. -/
private theorem typeField.fieldCodec0_0 : @Representation.Codec (NanoP4Spec.type)
  ⟨NanoP4Spec.type.toValue⟩ ⟨NanoP4Spec.type.ofValue⟩ (Representation.Source.Valid
  NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT "type" [])).it)
  (NanoP4Spec.type.admitted) :=
  NanoP4Spec.type.codec

#audit_axioms NanoP4Spec.typeField.fieldCodec0_0

/-- Empty substitution preserves the complete independent field domain. -/
private theorem typeField.fieldSubstitution0_0 : ∀ actual,
    Representation.Source.Substitutes [] (Q.t (Q.varT "type" [])).it actual → ∀ v,
    Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain actual v →
      (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t
      (Q.varT "type" [])).it) v :=
  (by
    intro actual substitution v valid
    rw [substitution.emptyNamedResult (Q.i "type")] at valid
    exact valid)

#audit_axioms NanoP4Spec.typeField.fieldSubstitution0_0

/-- The exact positional field codec on its independent source grammar. -/
private theorem typeField.fieldCodec0_1 : @Representation.Codec (NanoP4Spec.name)
  ⟨NanoP4Spec.name.toValue⟩ ⟨NanoP4Spec.name.ofValue⟩ (Representation.Source.Valid
  NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT "name" [])).it)
  (NanoP4Spec.name.admitted) :=
  NanoP4Spec.name.codec

#audit_axioms NanoP4Spec.typeField.fieldCodec0_1

/-- Empty substitution preserves the complete independent field domain. -/
private theorem typeField.fieldSubstitution0_1 : ∀ actual,
    Representation.Source.Substitutes [] (Q.t (Q.varT "name" [])).it actual → ∀ v,
    Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain actual v →
      (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t
      (Q.varT "name" [])).it) v :=
  (by
    intro actual substitution v valid
    rw [substitution.emptyNamedResult (Q.i "name")] at valid
    exact valid)

#audit_axioms NanoP4Spec.typeField.fieldSubstitution0_1

private theorem typeField.sourceCasesValid (v : Lang.Il.value) (hv : typeField.source v) :
    ∃ c ∈ typeField.sourceCases, Representation.Source.ConstructorDomain NanoP4Spec.spec
      Representation.Source.externDomain c (Domain.Mixfix.args c.nottyp.it) v := by
  obtain ⟨c, member, fields, sub, tree, shape, matching, valid⟩ :=
    hv.variantPayload (Q.i "typeField") [] [] typeField.sourceCases v (by rfl)
  refine ⟨c, member, tree, shape, matching, ?_⟩
  apply valid.domains
  simp only [typeField.sourceCases, List.mem_cons, List.not_mem_nil, or_false] at member
  rcases member with rfl
  ·
    dsimp [Representation.Source.instantiatedFields, Q.tc, Q.nt, Q.t,
      Lang.Il.typcase.nottyp, P4SpecTec.Util.Source.mkPhrase] at sub
    repeat' first
      | simp only [Domain.Mixfix.args] at sub
      | dsimp only [List.flatMap, List.append, List.map, List.flatten] at sub
    obtain ⟨_, sub⟩ := sub
    cases sub with
    | cons sub0 tail =>
      cases tail with
      | cons sub1 tail =>
        cases tail
        dsimp [Q.tc, Q.nt, Q.t, Lang.Il.typcase.nottyp, P4SpecTec.Util.Source.mkPhrase]
        repeat' first
          | simp only [Domain.Mixfix.args]
          | dsimp only [List.flatMap, List.append, List.map, List.flatten]
        exact .cons (typeField.fieldSubstitution0_0 _ sub0) (.cons
          (typeField.fieldSubstitution0_1 _ sub1) (.nil))

#audit_axioms NanoP4Spec.typeField.sourceCasesValid

private theorem typeField.decode0 (fuel : Nat) (v : Lang.Il.value) (tree : Domain.Mixfix.t
  Lang.Il.value) (v0 : Lang.Il.value) (v1 : Lang.Il.value)
    (shape : v.it = .CaseV tree) (matching : Domain.Mixfix.eq_mixop tree (((.Seq [(.Arg ()),
      (.Arg ()), (.Atom (Prelude.Value.atom (.Operator ";")))])) : Domain.Mixfix.mixop) = true)
    (fields : Domain.Mixfix.args tree = [v0, v1]) :
    NanoP4Spec.typeField.ofValue (fuel + 1) v = ((NanoP4Spec.type.ofValue) fuel v0).bind (fun x0
      => ((NanoP4Spec.name.ofValue) fuel v1).bind (fun x1 => some (NanoP4Spec.typeField.semi x0
      x1))) := by
  have selected : Prelude.Value.caseArgs tree ((.Seq [(.Arg ()), (.Arg ()), (.Atom
    (Prelude.Value.atom (.Operator ";")))])) = some [v0, v1] := by
    simp only [Prelude.Value.caseArgs, matching, ite_true, fields]
  simp only [NanoP4Spec.typeField.ofValue, shape, selected]
  change ((((NanoP4Spec.type.ofValue) fuel v0).bind (fun x0 => ((NanoP4Spec.name.ofValue) fuel
    v1).bind (fun x1 => some (NanoP4Spec.typeField.semi x0 x1))))) = ((NanoP4Spec.type.ofValue)
    fuel v0).bind (fun x0 => ((NanoP4Spec.name.ofValue) fuel v1).bind (fun x1 => some
    (NanoP4Spec.typeField.semi x0 x1)))
  cases ((NanoP4Spec.type.ofValue) fuel v0) <;> cases ((NanoP4Spec.name.ofValue) fuel v1) <;>
    rfl

#audit_axioms typeField.decode0

/-- The full codec fixes the actual named encoder and decoder dictionaries. -/
theorem typeField.codec : @Refine.Representation.Codec NanoP4Spec.typeField
  ⟨NanoP4Spec.typeField.toValue⟩ ⟨NanoP4Spec.typeField.ofValue⟩ NanoP4Spec.typeField.source
  NanoP4Spec.typeField.admitted := by
  letI : ToValue NanoP4Spec.typeField := ⟨NanoP4Spec.typeField.toValue⟩
  letI : OfValue NanoP4Spec.typeField := ⟨NanoP4Spec.typeField.ofValue⟩
  refine { encodingValid := ?_, decoder := { sound := ?_, sufficient := ?_ } }
  · intro x hx
    cases x with
    | semi x0 x1 =>
      dsimp only [NanoP4Spec.typeField.admitted] at hx
      obtain ⟨admitted0, admitted1, _⟩ := hx
      apply Representation.Source.ConstructorDomain.valid (Q.i "typeField") [] []
        typeField.sourceCases (Q.tc (.Seq [.Arg (Q.t (Q.varT "type" [])), .Arg (Q.t (Q.varT
        "name" [])), .Atom (Q.a (.Operator ";"))]) "typeField" []) [Q.t (Q.varT "type" []), Q.t
        (Q.varT "name" [])] _ (by rfl)
        (by simp [typeField.sourceCases])
        (by
          refine ⟨rfl, ?_⟩
          dsimp [Q.tc, Q.nt, Q.t, Lang.Il.typcase.nottyp, P4SpecTec.Util.Source.mkPhrase]
          repeat' first
            | simp only [Domain.Mixfix.args]
            | dsimp only [List.flatMap, List.append, List.map, List.flatten]
          exact .cons (Representation.Source.Substitutes.named (Q.i "type") [] [] rfl (.nil))
            (.cons (Representation.Source.Substitutes.named (Q.i "name") [] [] rfl (.nil))
            (.nil)))
      refine ⟨(.Seq [(.Arg ((NanoP4Spec.type.toValue) x0)), (.Arg ((NanoP4Spec.name.toValue)
        x1)), (.Atom (Prelude.Value.atom (.Operator ";")))]), rfl, rfl, ?_⟩
      repeat' first
        | simp only [Domain.Mixfix.args]
        | dsimp only [List.flatMap, List.append, List.map, List.flatten]
      exact .cons _ _ _ _ ((@Representation.Codec.encodingValid (NanoP4Spec.type)
        ⟨NanoP4Spec.type.toValue⟩ ⟨NanoP4Spec.type.ofValue⟩ (Representation.Source.Valid
        NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT "type" [])).it)
        (NanoP4Spec.type.admitted) (typeField.fieldCodec0_0)) x0 admitted0) (.cons _ _ _ _
        ((@Representation.Codec.encodingValid (NanoP4Spec.name) ⟨NanoP4Spec.name.toValue⟩
        ⟨NanoP4Spec.name.ofValue⟩ (Representation.Source.Valid NanoP4Spec.spec
        Representation.Source.externDomain (Q.t (Q.varT "name" [])).it)
        (NanoP4Spec.name.admitted) (typeField.fieldCodec0_1)) x1 admitted1) (.nil))
  · intro fuel v x hv decoded
    change NanoP4Spec.typeField.ofValue fuel v = some x at decoded
    cases fuel with
    | zero => cases decoded
    | succ fuel =>
      obtain ⟨c, member, tree, shape, matching, valid⟩ := typeField.sourceCasesValid v hv
      simp only [typeField.sourceCases, List.mem_cons, List.not_mem_nil, or_false] at member
      rcases member with rfl
      ·
        dsimp [Q.tc, Q.nt, Q.t, Lang.Il.typcase.nottyp, P4SpecTec.Util.Source.mkPhrase] at valid
        repeat' first
          | simp only [Domain.Mixfix.args] at valid
          | dsimp only [List.flatMap, List.append, List.map, List.flatten] at valid
        generalize hargs : Domain.Mixfix.args tree = args at valid
        cases valid with
        | cons _ v0 _ _ p0 tail =>
          cases tail with
          | cons _ v1 _ _ p1 tail =>
            cases tail
            rw [typeField.decode0 fuel v tree v0 v1 shape (Representation.Source.mixopTrans tree
              _ _ matching rfl) hargs] at decoded
            cases d0 : (NanoP4Spec.type.ofValue) fuel v0 with
            | none => simp [d0] at decoded
            | some x0 =>
              cases d1 : (NanoP4Spec.name.ofValue) fuel v1 with
              | none => simp [d0, d1] at decoded
              | some x1 =>
                simp only [d0, d1] at decoded
                have same := Option.some.inj decoded
                subst x
                obtain ⟨admitted0, related0⟩ :=
                  (@Representation.DecoderCorrect.sound (NanoP4Spec.type)
                    ⟨NanoP4Spec.type.toValue⟩ (Representation.Source.Valid NanoP4Spec.spec
                    Representation.Source.externDomain (Q.t (Q.varT "type" [])).it)
                    (NanoP4Spec.type.admitted) (NanoP4Spec.type.ofValue)
                    (@Representation.Codec.decoder (NanoP4Spec.type) ⟨NanoP4Spec.type.toValue⟩
                    ⟨NanoP4Spec.type.ofValue⟩ (Representation.Source.Valid NanoP4Spec.spec
                    Representation.Source.externDomain (Q.t (Q.varT "type" [])).it)
                    (NanoP4Spec.type.admitted) (typeField.fieldCodec0_0))) fuel v0 x0 p0 d0
                have canonical0 : canon v0 = canon ((NanoP4Spec.type.toValue) x0) := related0
                obtain ⟨admitted1, related1⟩ :=
                  (@Representation.DecoderCorrect.sound (NanoP4Spec.name)
                    ⟨NanoP4Spec.name.toValue⟩ (Representation.Source.Valid NanoP4Spec.spec
                    Representation.Source.externDomain (Q.t (Q.varT "name" [])).it)
                    (NanoP4Spec.name.admitted) (NanoP4Spec.name.ofValue)
                    (@Representation.Codec.decoder (NanoP4Spec.name) ⟨NanoP4Spec.name.toValue⟩
                    ⟨NanoP4Spec.name.ofValue⟩ (Representation.Source.Valid NanoP4Spec.spec
                    Representation.Source.externDomain (Q.t (Q.varT "name" [])).it)
                    (NanoP4Spec.name.admitted) (typeField.fieldCodec0_1))) fuel v1 x1 p1 d1
                have canonical1 : canon v1 = canon ((NanoP4Spec.name.toValue) x1) := related1
                refine ⟨⟨admitted0, admitted1, trivial⟩, ?_⟩
                change Rel v (NanoP4Spec.typeField.toValue (NanoP4Spec.typeField.semi x0 x1))
                apply Representation.Source.caseRelation (rendered := (.Seq [(.Arg
                  ((NanoP4Spec.type.toValue) x0)), (.Arg ((NanoP4Spec.name.toValue) x1)), (.Atom
                  (Prelude.Value.atom (.Operator ";")))])) shape rfl
                · exact Representation.Source.mixopTrans tree _ _ matching rfl
                · rw [hargs]
                  repeat' first
                    | simp only [Domain.Mixfix.args]
                    | dsimp only [List.flatMap, List.append, List.map, List.flatten]
                  all_goals
                    dsimp only [canons]
                    exact congr (congrArg List.cons (canonical0)) (congr (congrArg List.cons
                      (canonical1)) (rfl))
  · intro v hv
    obtain ⟨c, member, tree, shape, matching, valid⟩ := typeField.sourceCasesValid v hv
    simp only [typeField.sourceCases, List.mem_cons, List.not_mem_nil, or_false] at member
    rcases member with rfl
    ·
      dsimp [Q.tc, Q.nt, Q.t, Lang.Il.typcase.nottyp, P4SpecTec.Util.Source.mkPhrase] at valid
      repeat' first
        | simp only [Domain.Mixfix.args] at valid
        | dsimp only [List.flatMap, List.append, List.map, List.flatten] at valid
      generalize hargs : Domain.Mixfix.args tree = args at valid
      cases valid with
      | cons _ v0 _ _ p0 tail =>
        cases tail with
        | cons _ v1 _ _ p1 tail =>
          cases tail
          obtain ⟨x0, b0, h0⟩ :=
            (@Representation.DecoderCorrect.sufficient (NanoP4Spec.type)
              ⟨NanoP4Spec.type.toValue⟩ (Representation.Source.Valid NanoP4Spec.spec
              Representation.Source.externDomain (Q.t (Q.varT "type" [])).it)
              (NanoP4Spec.type.admitted) (NanoP4Spec.type.ofValue)
              (@Representation.Codec.decoder (NanoP4Spec.type) ⟨NanoP4Spec.type.toValue⟩
              ⟨NanoP4Spec.type.ofValue⟩ (Representation.Source.Valid NanoP4Spec.spec
              Representation.Source.externDomain (Q.t (Q.varT "type" [])).it)
              (NanoP4Spec.type.admitted) (typeField.fieldCodec0_0))) v0 p0
          obtain ⟨x1, b1, h1⟩ :=
            (@Representation.DecoderCorrect.sufficient (NanoP4Spec.name)
              ⟨NanoP4Spec.name.toValue⟩ (Representation.Source.Valid NanoP4Spec.spec
              Representation.Source.externDomain (Q.t (Q.varT "name" [])).it)
              (NanoP4Spec.name.admitted) (NanoP4Spec.name.ofValue)
              (@Representation.Codec.decoder (NanoP4Spec.name) ⟨NanoP4Spec.name.toValue⟩
              ⟨NanoP4Spec.name.ofValue⟩ (Representation.Source.Valid NanoP4Spec.spec
              Representation.Source.externDomain (Q.t (Q.varT "name" [])).it)
              (NanoP4Spec.name.admitted) (typeField.fieldCodec0_1))) v1 p1
          refine ⟨(NanoP4Spec.typeField.semi x0 x1), (max b0 (max b1 (0))) + 1, ?_⟩
          intro fuel large
          cases fuel with
          | zero => omega
          | succ fuel =>
            have enough0 : b0 ≤ fuel := by omega
            have enough1 : b1 ≤ fuel := by omega
            change NanoP4Spec.typeField.ofValue (fuel + 1) v = _
            rw [typeField.decode0 fuel v tree v0 v1 shape (Representation.Source.mixopTrans tree
              _ _ matching rfl) hargs]
            rw [h0 fuel enough0, h1 fuel enough1]
            all_goals rfl
#audit_axioms NanoP4Spec.typeField.codec


/-- Every carrier value is admitted under the stated child totals. -/
theorem typeField.admittedAll : ∀ x : NanoP4Spec.typeField, (NanoP4Spec.typeField.admitted) x :=
  by
  intro x
  cases x with
  | semi x0 x1 =>
    exact ⟨((show ∀ x : (NanoP4Spec.type), (NanoP4Spec.type.admitted) x from
      NanoP4Spec.type.admittedAll)) x0, ((show ∀ x : (NanoP4Spec.name),
      (NanoP4Spec.name.admitted) x from NanoP4Spec.name.admittedAll)) x1, trivial⟩


#audit_axioms NanoP4Spec.typeField.admittedAll

end NanoP4Spec
