-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group Forward.empty_typingContext
import P4SpecTec.Prelude
import P4SpecTec.Tactic.Audit
import P4SpecTec.Refine.Quote
import P4SpecTec.Refine.Calc
import P4SpecTec.Tactic.Refine
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality
import NanoP4Spec.Refinement.Forward.empty_typeDefEnv
import NanoP4Spec.Refinement.Forward.empty_callableTypeDefEnv
import NanoP4Spec.Refinement.Forward.empty_typeFrame

/-! # NanoP4Spec.Refinement.Forward.empty_typingContext

Generated: refinement theorems, group Forward.empty_typingContext.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

set_option maxHeartbeats 5000000 in
theorem «$empty_typingContext».refines
    (fuel : Nat)
    (cfg : Interp_al.Interp.Config) (ctx : Interp_al.Ctx.t) (internal : Bool)
    (hguard : cfg.guard = false) (hfenv : ctx.local.fenv = [])
    (hspec : HoldsSpec NanoP4Spec.spec ctx.global)
    (ht0 : ctx.global.tdtbl.get? "K" = none)
    (ht1 : ctx.global.tdtbl.get? "V" = none) :
    Refines Rel
      (Interp_al.Interp.invoke_func fuel cfg internal ctx (Q.i "empty_typingContext") [] [])
      (ExceptT.mk NanoP4Spec.«$empty_typingContext») :=
  by refine_al

#audit_axioms NanoP4Spec.«$empty_typingContext».refines

end NanoP4Spec
