-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group Forward.Expr_ok
import P4SpecTec.Prelude
import P4SpecTec.Tactic.Audit
import P4SpecTec.Refine.Quote
import P4SpecTec.Refine.Calc
import P4SpecTec.Tactic.Refine
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality
import NanoP4Spec.Refinement.Forward.id
import NanoP4Spec.Refinement.Forward.find_var_t
import NanoP4Spec.Refinement.assoc_
import NanoP4Spec.Refinement.Forward.find_callableTypeDef_t

/-! # NanoP4Spec.Refinement.Forward.Expr_ok

Generated: refinement theorems, group Forward.Expr_ok.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

set_option maxHeartbeats 27000000 in
theorem Expr_ok.refines_group :
    ∀ (fuel : Nat),
      (∀ (cfg : Interp_al.Interp.Config) (ctx : Interp_al.Ctx.t) (internal : Bool),
         cfg.guard = false → cfg.printHints = [] → ctx.local.fenv = [] →
         HoldsSpec NanoP4Spec.spec ctx.global →
         ∀ (v0 v1 v2 : Lang.Il.value)
         (p0 : NanoP4Spec.scope)
         (p1 : NanoP4Spec.typingContext)
         (p2 : NanoP4Spec.expression),
         Rel v0 p0 →
         Rel v1 p1 →
         Rel v2 p2 →
         Refines (fun vs (o : NanoP4Spec.typeIR) => Outs vs [toValue o])
           (Interp_al.Interp.invoke_rel fuel cfg internal ctx (Q.i "Expr_ok") [v0, v1, v2])
           (ExceptT.mk (NanoP4Spec.Expr_ok.run p0 p1 p2))) := by
  intro fuel
  induction fuel using Nat.strongRecOn with
  | ind fuel ih =>
      refine_al (subtypes) (iteration :=
        PairLookupRel
          (Q.i "id_field", []) (Q.i "typeIR_field", [])
          (fun x : NanoP4Spec.id × NanoP4Spec.typeIR => toValue x.1)
          (fun x : NanoP4Spec.id × NanoP4Spec.typeIR => toValue x.2))

set_option maxHeartbeats 27000000 in
theorem Expr_ok.refines
    (fuel : Nat)
    (cfg : Interp_al.Interp.Config) (ctx : Interp_al.Ctx.t) (internal : Bool)
    (hguard : cfg.guard = false) (hhints : cfg.printHints = []) (_hfenv : ctx.local.fenv = [])
    (hspec : HoldsSpec NanoP4Spec.spec ctx.global)
    (v0 v1 v2 : Lang.Il.value)
    (p0 : NanoP4Spec.scope)
    (p1 : NanoP4Spec.typingContext)
    (p2 : NanoP4Spec.expression)
    (h0 : Rel v0 p0)
    (h1 : Rel v1 p1)
    (h2 : Rel v2 p2) :
    Refines (fun vs (o : NanoP4Spec.typeIR) => Outs vs [toValue o])
      (Interp_al.Interp.invoke_rel fuel cfg internal ctx (Q.i "Expr_ok") [v0, v1, v2])
      (ExceptT.mk (NanoP4Spec.Expr_ok.run p0 p1 p2)) :=
  (NanoP4Spec.Expr_ok.refines_group fuel)
    cfg
    ctx
    internal
    hguard
    hhints
    _hfenv
    hspec
    v0
    v1
    v2
    p0
    p1
    p2
    h0
    h1
    h2

#audit_axioms NanoP4Spec.Expr_ok.refines_group
#audit_axioms NanoP4Spec.Expr_ok.refines

end NanoP4Spec
