-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, upstream/nano-p4-spec/0-stdlib.watsup
import P4SpecTec.Prelude
import P4SpecTec.Tactic.RunSound
import P4SpecTec.Tactic.Audit
import P4SpecTec.Tactic.Det
import P4SpecTec.Refine.Quote

/-! # NanoP4Spec.«0-stdlib»

The rendering of `upstream/nano-p4-spec/0-stdlib.watsup`.
Generated: every definition here mirrors one definition of that file, in
order, by the encodings of `docs/design.md`.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 1000000

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

inductive set (τK : Type) where
  | lbrace_rbrace (x : List τK)

def set.toValue {τK : Type} [ToValue τK] : NanoP4Spec.set τK → Lang.Il.value
  | .lbrace_rbrace x0 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "set")
        (.Brack
           (Prelude.Value.atom .LBrace)
           (.Arg (ToValue.toValue x0))
           (Prelude.Value.atom .RBrace))

instance {τK : Type} [ToValue τK] : ToValue (NanoP4Spec.set τK) := ⟨NanoP4Spec.set.toValue⟩
instance {τK : Type} [ToValue τK] : BEq (NanoP4Spec.set τK) := ⟨valueEq⟩

def set.ofValue {τK : Type} [OfValue τK] : Nat → Lang.Il.value → Option (NanoP4Spec.set τK)
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0] :=
             Prelude.Value.caseArgs
               c
               (.Brack (Prelude.Value.atom .LBrace) (.Arg ()) (Prelude.Value.atom .RBrace)) | none
         pure (NanoP4Spec.set.lbrace_rbrace (← OfValue.ofValue fuel a0)))
    | _ => none

instance {τK : Type} [OfValue τK] : OfValue (NanoP4Spec.set τK) := ⟨NanoP4Spec.set.ofValue⟩

def set.al : Lang.Al.def :=
  Q.d
    (.TypD
       (Q.i "set")
       [Q.i "K"]
       (Q.dt
          (.VariantT
             [Q.tc
                (.Brack
                   (Q.a .LBrace)
                   (.Arg (Q.t (.IterT (Q.t (Q.varT "K" [])) .List)))
                   (Q.a .RBrace))
                "set"
                [Q.t (Q.varT "K" [])]]))
       [])

inductive pair (τK : Type) (τV : Type) where
  | colon (x_1 : τK) (x_2 : τV)

def pair.toValue {τK τV : Type} [ToValue τK] [ToValue τV] : NanoP4Spec.pair τK τV → Lang.Il.value
  | .colon x0 x1 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "pair")
        (.Seq
           [(.Arg (ToValue.toValue x0)),
            (.Atom (Prelude.Value.atom (.Operator ":"))),
            (.Arg (ToValue.toValue x1))])

instance {τK τV : Type} [ToValue τK] [ToValue τV] : ToValue (NanoP4Spec.pair τK τV) :=
  ⟨NanoP4Spec.pair.toValue⟩
instance {τK τV : Type} [ToValue τK] [ToValue τV] : BEq (NanoP4Spec.pair τK τV) := ⟨valueEq⟩

def pair.ofValue {τK τV : Type} [OfValue τK] [OfValue τV] :
    Nat → Lang.Il.value → Option (NanoP4Spec.pair τK τV)
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0, a1] :=
             Prelude.Value.caseArgs
               c
               (.Seq [(.Arg ()), (.Atom (Prelude.Value.atom (.Operator ":"))), (.Arg ())]) | none
         pure (NanoP4Spec.pair.colon (← OfValue.ofValue fuel a0) (← OfValue.ofValue fuel a1)))
    | _ => none

instance {τK τV : Type} [OfValue τK] [OfValue τV] : OfValue (NanoP4Spec.pair τK τV) :=
  ⟨NanoP4Spec.pair.ofValue⟩

def pair.al : Lang.Al.def :=
  Q.d
    (.TypD
       (Q.i "pair")
       [Q.i "K", Q.i "V"]
       (Q.dt
          (.VariantT
             [Q.tc
                (.Seq
                   [.Arg (Q.t (Q.varT "K" [])),
                    .Atom (Q.a (.Operator ":")),
                    .Arg (Q.t (Q.varT "V" []))])
                "pair"
                [Q.t (Q.varT "K" []), Q.t (Q.varT "V" [])]]))
       [])

abbrev map (τK : Type) (τV : Type) : Type := NanoP4Spec.set (NanoP4Spec.pair τK τV)

def map.toValue {τK τV : Type} [ToValue τK] [ToValue τV] (x : NanoP4Spec.map
    τK
    τV) : Lang.Il.value :=
  ToValue.toValue x

instance {τK τV : Type} [ToValue τK] [ToValue τV] : ToValue (NanoP4Spec.map τK τV) :=
  ⟨NanoP4Spec.map.toValue⟩
instance {τK τV : Type} [ToValue τK] [ToValue τV] : BEq (NanoP4Spec.map τK τV) := ⟨valueEq⟩

def map.ofValue {τK τV : Type} [OfValue τK] [OfValue τV] :
    Nat → Lang.Il.value → Option (NanoP4Spec.map τK τV)
  | 0, _ => none
  | fuel + 1, v => OfValue.ofValue fuel v

instance {τK τV : Type} [OfValue τK] [OfValue τV] : OfValue (NanoP4Spec.map τK τV) :=
  ⟨NanoP4Spec.map.ofValue⟩

def map.al : Lang.Al.def :=
  Q.d
    (.TypD
       (Q.i "map")
       [Q.i "K", Q.i "V"]
       (Q.dt
          (.PlainT
             (Q.t (Q.varT "set" [Q.t (Q.varT "pair" [Q.t (Q.varT "K" []), Q.t (Q.varT "V" [])])]))))
       [])

def «$print_» {τX : Type} [ToValue τX] [BEq τX] (p0 : τX)
    : Option (Except Fail P4SpecTec.ByteText) :=
  ExceptT.run
    (Eval.err?
       (Option.map
          P4SpecTec.ByteText.ofString
          (Except.toOption (P4.Unparse.printWithHints [] (ToValue.toValue p0)))))

def «$print_».al : Lang.Al.def :=
  Q.d (.BuiltinDecD (Q.i "print_") [Q.i "X"] [Q.pm (.ExpP (Q.t (Q.varT "X" [])))] (Q.t .TextT) [])

def «$strip_all_whitespace» (p0 : P4SpecTec.ByteText) : Option (Except Fail P4SpecTec.ByteText) :=
  ExceptT.run
    (pure (Builtin.Texts.strip_all_whitespace p0))

def «$strip_all_whitespace».al : Lang.Al.def :=
  Q.d (.BuiltinDecD (Q.i "strip_all_whitespace") [] [Q.pm (.ExpP (Q.t .TextT))] (Q.t .TextT) [])

def «$ite» {τX : Type} [ToValue τX] [BEq τX] (p0 : Bool) (p1 : τX) (p2 : τX)
    : Option (Except Fail τX) :=
  ExceptT.run
    ((do
        have b := p0
        have X_t := p1
        have X_f := p2
        let _ ← Eval.check (b == true)
        pure X_t) <|>
     (do
        have b := p0
        have X_t := p1
        have X_f := p2
        let _ ← Eval.check (b == false)
        pure X_f))

def «$ite».al : Lang.Al.def :=
  Q.d
    (.FuncDecD
       (Q.i "ite")
       [Q.i "X"]
       [Q.pm (.ExpP (Q.t .BoolT)),
        Q.pm (.ExpP (Q.t (Q.varT "X" []))),
        Q.pm (.ExpP (Q.t (Q.varT "X" [])))]
       (Q.t (Q.varT "X" []))
       [Q.cl
          [Q.ar (.ExpA (Q.e (.VarE (Q.i "b")) .BoolT)),
           Q.ar (.ExpA (Q.e (.VarE (Q.i "X_t")) (Q.varT "X" []))),
           Q.ar (.ExpA (Q.e (.VarE (Q.i "X_f")) (Q.varT "X" [])))]
          (Q.e (.VarE (Q.i "X_t")) (Q.varT "X" []))
          [Q.pr
             (.IfPr
                (Q.e
                   (.CmpE .EqOp .BoolT (Q.e (.VarE (Q.i "b")) .BoolT) (Q.e (.BoolE true) .BoolT))
                   .BoolT))],
        Q.cl
          [Q.ar (.ExpA (Q.e (.VarE (Q.i "b")) .BoolT)),
           Q.ar (.ExpA (Q.e (.VarE (Q.i "X_t")) (Q.varT "X" []))),
           Q.ar (.ExpA (Q.e (.VarE (Q.i "X_f")) (Q.varT "X" [])))]
          (Q.e (.VarE (Q.i "X_f")) (Q.varT "X" []))
          [Q.pr
             (.IfPr
                (Q.e
                   (.CmpE .EqOp .BoolT (Q.e (.VarE (Q.i "b")) .BoolT) (Q.e (.BoolE false) .BoolT))
                   .BoolT))]]
       none
       [])

def «$repeat_» {τX : Type} [ToValue τX] [BEq τX] (p0 : τX) (p1 : Nat)
    : Option (Except Fail (List τX)) :=
  ExceptT.run
    ((do
        have X := p0
        have nat := p1
        let _ ← Eval.check (nat == (0 : Nat))
        pure ([] : List τX)) <|>
     (do
        have X := p0
        have n := p1
        let _ ← Eval.check (n != (0 : Nat))
        have i := Num.natSub n (1 : Nat)
        let _ ← Eval.check (decide (0 ≤ i))
        let tmp_0 ← Eval.err? (Num.toNat? i)
        have n' := tmp_0
        let tmp_1 ← ExceptT.mk (NanoP4Spec.«$repeat_» (τX := τX) X n')
        pure ([X] ++ tmp_1)))
  partial_fixpoint

def «$repeat_».al : Lang.Al.def :=
  Q.d
    (.FuncDecD
       (Q.i "repeat_")
       [Q.i "X"]
       [Q.pm (.ExpP (Q.t (Q.varT "X" []))), Q.pm (.ExpP (Q.t (.NumT .NatT)))]
       (Q.t (.IterT (Q.t (Q.varT "X" [])) .List))
       [Q.cl
          [Q.ar (.ExpA (Q.e (.VarE (Q.i "X")) (Q.varT "X" []))),
           Q.ar (.ExpA (Q.e (.VarE (Q.i "nat")) (.NumT .NatT)))]
          (Q.e (.ListE []) (.IterT (Q.t (Q.varT "X" [])) .List))
          [Q.pr
             (.IfPr
                (Q.e
                   (.CmpE
                      .EqOp
                      .BoolT
                      (Q.e (.VarE (Q.i "nat")) (.NumT .NatT))
                      (Q.e (.NumE (.Nat 0)) (.NumT .NatT)))
                   .BoolT))],
        Q.cl
          [Q.ar (.ExpA (Q.e (.VarE (Q.i "X")) (Q.varT "X" []))),
           Q.ar (.ExpA (Q.e (.VarE (Q.i "n")) (.NumT .NatT)))]
          (Q.e
             (.CatE
                (Q.e
                   (.ListE [Q.e (.VarE (Q.i "X")) (Q.varT "X" [])])
                   (.IterT (Q.t (Q.varT "X" [])) .List))
                (Q.e
                   (.CallE
                      (Q.i "repeat_")
                      [Q.t (Q.varT "X" [])]
                      [Q.ar (.ExpA (Q.e (.VarE (Q.i "X")) (Q.varT "X" []))),
                       Q.ar (.ExpA (Q.e (.VarE (Q.i "n'")) (.NumT .NatT)))])
                   (.IterT (Q.t (Q.varT "X" [])) .List)))
             (.IterT (Q.t (Q.varT "X" [])) .List))
          [Q.pr
             (.IfPr
                (Q.e
                   (.CmpE
                      .NeOp
                      .BoolT
                      (Q.e (.VarE (Q.i "n")) (.NumT .NatT))
                      (Q.e (.NumE (.Nat 0)) (.NumT .NatT)))
                   .BoolT)),
           Q.pr
             (.LetPr
                (Q.e (.VarE (Q.i "i")) (.NumT .IntT))
                (Q.e
                   (.BinE
                      .SubOp
                      .IntT
                      (Q.e (.VarE (Q.i "n")) (.NumT .NatT))
                      (Q.e (.NumE (.Nat 1)) (.NumT .NatT)))
                   (.NumT .IntT))),
           Q.pr
             (.IfPr
                (Q.e
                   (.SubE
                      (Q.e (.VarE (Q.i "i")) (.NumT .IntT))
                      (Q.t (.NumT .NatT))
                      (.RecurseSC (Q.t (.NumT .NatT))))
                   .BoolT)),
           Q.pr
             (.LetPr
                (Q.e (.VarE (Q.i "n'")) (.NumT .NatT))
                (Q.e
                   (.DownCastE (Q.t (.NumT .NatT)) (Q.e (.VarE (Q.i "i")) (.NumT .IntT)))
                   (.NumT .NatT)))]]
       none
       [])

def «$exists_» (p0 : List Bool) : Option (Except Fail Bool) :=
  ExceptT.run
    ((do
        have «b*» := p0
        let _ ← Eval.check (List.isEmpty «b*»)
        pure false) <|>
     (do
        have «b*» := p0
        let _ ← Eval.check (!(List.isEmpty «b*»))
        let b_h :: «b_t*» := «b*» | throw Fail.err
        let tmp_0 ← ExceptT.mk (NanoP4Spec.«$exists_» «b_t*»)
        pure (b_h || tmp_0)))
  partial_fixpoint

def «$exists_».al : Lang.Al.def :=
  Q.d
    (.FuncDecD
       (Q.i "exists_")
       []
       [Q.pm (.ExpP (Q.t (.IterT (Q.t .BoolT) .List)))]
       (Q.t .BoolT)
       [Q.cl
          [Q.ar
             (.ExpA
                (Q.e
                   (.IterE
                      (Q.e (.VarE (Q.i "b")) .BoolT)
                      (.mk .List [Q.v "b" (.IterT (Q.t .BoolT) .List) []]))
                   (.IterT (Q.t .BoolT) .List)))]
          (Q.e (.BoolE false) .BoolT)
          [Q.pr
             (.IfPr
                (Q.e
                   (.MatchE
                      (Q.e
                         (.IterE
                            (Q.e (.VarE (Q.i "b")) .BoolT)
                            (.mk .List [Q.v "b" (.IterT (Q.t .BoolT) .List) []]))
                         (.IterT (Q.t .BoolT) .List))
                      (.ListP .Nil))
                   .BoolT))],
        Q.cl
          [Q.ar
             (.ExpA
                (Q.e
                   (.IterE
                      (Q.e (.VarE (Q.i "b")) .BoolT)
                      (.mk .List [Q.v "b" (.IterT (Q.t .BoolT) .List) []]))
                   (.IterT (Q.t .BoolT) .List)))]
          (Q.e
             (.BinE
                .OrOp
                .BoolT
                (Q.e (.VarE (Q.i "b_h")) .BoolT)
                (Q.e
                   (.CallE
                      (Q.i "exists_")
                      []
                      [Q.ar
                         (.ExpA
                            (Q.e
                               (.IterE
                                  (Q.e (.VarE (Q.i "b_t")) .BoolT)
                                  (.mk .List [Q.v "b_t" .BoolT []]))
                               (.IterT (Q.t .BoolT) .List)))])
                   .BoolT))
             .BoolT)
          [Q.pr
             (.IfPr
                (Q.e
                   (.MatchE
                      (Q.e
                         (.IterE
                            (Q.e (.VarE (Q.i "b")) .BoolT)
                            (.mk .List [Q.v "b" (.IterT (Q.t .BoolT) .List) []]))
                         (.IterT (Q.t .BoolT) .List))
                      (.ListP .Cons))
                   .BoolT)),
           Q.pr
             (.LetPr
                (Q.e
                   (.ConsE
                      (Q.e (.VarE (Q.i "b_h")) .BoolT)
                      (Q.e
                         (.IterE (Q.e (.VarE (Q.i "b_t")) .BoolT) (.mk .List [Q.v "b_t" .BoolT []]))
                         (.IterT (Q.t .BoolT) .List)))
                   (.IterT (Q.t .BoolT) .List))
                (Q.e
                   (.IterE
                      (Q.e (.VarE (Q.i "b")) .BoolT)
                      (.mk .List [Q.v "b" (.IterT (Q.t .BoolT) .List) []]))
                   (.IterT (Q.t .BoolT) .List)))]]
       none
       [])

def «$forall_» (p0 : List Bool) : Option (Except Fail Bool) :=
  ExceptT.run
    ((do
        have «b*» := p0
        let _ ← Eval.check (List.isEmpty «b*»)
        pure true) <|>
     (do
        have «b*» := p0
        let _ ← Eval.check (!(List.isEmpty «b*»))
        let b_h :: «b_t*» := «b*» | throw Fail.err
        let tmp_0 ← ExceptT.mk (NanoP4Spec.«$forall_» «b_t*»)
        pure (b_h && tmp_0)))
  partial_fixpoint

def «$forall_».al : Lang.Al.def :=
  Q.d
    (.FuncDecD
       (Q.i "forall_")
       []
       [Q.pm (.ExpP (Q.t (.IterT (Q.t .BoolT) .List)))]
       (Q.t .BoolT)
       [Q.cl
          [Q.ar
             (.ExpA
                (Q.e
                   (.IterE
                      (Q.e (.VarE (Q.i "b")) .BoolT)
                      (.mk .List [Q.v "b" (.IterT (Q.t .BoolT) .List) []]))
                   (.IterT (Q.t .BoolT) .List)))]
          (Q.e (.BoolE true) .BoolT)
          [Q.pr
             (.IfPr
                (Q.e
                   (.MatchE
                      (Q.e
                         (.IterE
                            (Q.e (.VarE (Q.i "b")) .BoolT)
                            (.mk .List [Q.v "b" (.IterT (Q.t .BoolT) .List) []]))
                         (.IterT (Q.t .BoolT) .List))
                      (.ListP .Nil))
                   .BoolT))],
        Q.cl
          [Q.ar
             (.ExpA
                (Q.e
                   (.IterE
                      (Q.e (.VarE (Q.i "b")) .BoolT)
                      (.mk .List [Q.v "b" (.IterT (Q.t .BoolT) .List) []]))
                   (.IterT (Q.t .BoolT) .List)))]
          (Q.e
             (.BinE
                .AndOp
                .BoolT
                (Q.e (.VarE (Q.i "b_h")) .BoolT)
                (Q.e
                   (.CallE
                      (Q.i "forall_")
                      []
                      [Q.ar
                         (.ExpA
                            (Q.e
                               (.IterE
                                  (Q.e (.VarE (Q.i "b_t")) .BoolT)
                                  (.mk .List [Q.v "b_t" .BoolT []]))
                               (.IterT (Q.t .BoolT) .List)))])
                   .BoolT))
             .BoolT)
          [Q.pr
             (.IfPr
                (Q.e
                   (.MatchE
                      (Q.e
                         (.IterE
                            (Q.e (.VarE (Q.i "b")) .BoolT)
                            (.mk .List [Q.v "b" (.IterT (Q.t .BoolT) .List) []]))
                         (.IterT (Q.t .BoolT) .List))
                      (.ListP .Cons))
                   .BoolT)),
           Q.pr
             (.LetPr
                (Q.e
                   (.ConsE
                      (Q.e (.VarE (Q.i "b_h")) .BoolT)
                      (Q.e
                         (.IterE (Q.e (.VarE (Q.i "b_t")) .BoolT) (.mk .List [Q.v "b_t" .BoolT []]))
                         (.IterT (Q.t .BoolT) .List)))
                   (.IterT (Q.t .BoolT) .List))
                (Q.e
                   (.IterE
                      (Q.e (.VarE (Q.i "b")) .BoolT)
                      (.mk .List [Q.v "b" (.IterT (Q.t .BoolT) .List) []]))
                   (.IterT (Q.t .BoolT) .List)))]]
       none
       [])

def «$rev_» {τX : Type} [ToValue τX] [BEq τX] (p0 : List τX) : Option (Except Fail (List τX)) :=
  ExceptT.run
    (pure (Builtin.Lists.rev_ p0))

def «$rev_».al : Lang.Al.def :=
  Q.d
    (.BuiltinDecD
       (Q.i "rev_")
       [Q.i "X"]
       [Q.pm (.ExpP (Q.t (.IterT (Q.t (Q.varT "X" [])) .List)))]
       (Q.t (.IterT (Q.t (Q.varT "X" [])) .List))
       [])

def «$distinct_» {τK : Type} [ToValue τK] [BEq τK] (p0 : List τK) : Option (Except Fail Bool) :=
  ExceptT.run
    (pure (Builtin.Lists.distinct_ p0))

def «$distinct_».al : Lang.Al.def :=
  Q.d
    (.BuiltinDecD
       (Q.i "distinct_")
       [Q.i "K"]
       [Q.pm (.ExpP (Q.t (.IterT (Q.t (Q.varT "K" [])) .List)))]
       (Q.t .BoolT)
       [])

def «$assoc_» {τX τY : Type} [ToValue τX] [BEq τX] [ToValue τY] [BEq τY]
        (p0 : τX)
        (p1 : List (τX × τY))
    : Option (Except Fail (Option τY)) :=
  ExceptT.run
    (pure (Builtin.Lists.assoc_ p0 p1))

def «$assoc_».al : Lang.Al.def :=
  Q.d
    (.BuiltinDecD
       (Q.i "assoc_")
       [Q.i "X", Q.i "Y"]
       [Q.pm (.ExpP (Q.t (Q.varT "X" []))),
        Q.pm
          (.ExpP (Q.t (.IterT (Q.t (.TupleT [Q.t (Q.varT "X" []), Q.t (Q.varT "Y" [])])) .List)))]
       (Q.t (.IterT (Q.t (Q.varT "Y" [])) .Opt))
       [])

def «$empty_set» {τK : Type} [ToValue τK] [BEq τK] : Option (Except Fail (NanoP4Spec.set τK)) :=
  ExceptT.run
    (pure (NanoP4Spec.set.lbrace_rbrace ([] : List τK)))

def «$empty_set».al : Lang.Al.def :=
  Q.d
    (.FuncDecD
       (Q.i "empty_set")
       [Q.i "K"]
       []
       (Q.t (Q.varT "set" [Q.t (Q.varT "K" [])]))
       [Q.cl
          []
          (Q.e
             (.CaseE
                (.Brack
                   (Q.a .LBrace)
                   (.Arg (Q.e (.ListE []) (.IterT (Q.t (Q.varT "K" [])) .List)))
                   (Q.a .RBrace)))
             (Q.varT "set" [Q.t (Q.varT "K" [])]))
          []]
       none
       [])

def «$in_set» {τK : Type} [ToValue τK] [BEq τK] (p0 : NanoP4Spec.set τK) (p1 : τK)
    : Option (Except Fail Bool) :=
  ExceptT.run
    (do
       let .lbrace_rbrace «K_e*» := p0
       have K := p1
       pure (List.elem K «K_e*»))

def «$in_set».al : Lang.Al.def :=
  Q.d
    (.FuncDecD
       (Q.i "in_set")
       [Q.i "K"]
       [Q.pm (.ExpP (Q.t (Q.varT "set" [Q.t (Q.varT "K" [])]))), Q.pm (.ExpP (Q.t (Q.varT "K" [])))]
       (Q.t .BoolT)
       [Q.cl
          [Q.ar
             (.ExpA
                (Q.e
                   (.CaseE
                      (.Brack
                         (Q.a .LBrace)
                         (.Arg
                            (Q.e
                               (.IterE
                                  (Q.e (.VarE (Q.i "K_e")) (Q.varT "K" []))
                                  (.mk .List [Q.v "K_e" (Q.varT "K" []) []]))
                               (.IterT (Q.t (Q.varT "K" [])) .List)))
                         (Q.a .RBrace)))
                   (Q.varT "set" [Q.t (Q.varT "K" [])]))),
           Q.ar (.ExpA (Q.e (.VarE (Q.i "K")) (Q.varT "K" [])))]
          (Q.e
             (.MemE
                (Q.e (.VarE (Q.i "K")) (Q.varT "K" []))
                (Q.e
                   (.IterE
                      (Q.e (.VarE (Q.i "K_e")) (Q.varT "K" []))
                      (.mk .List [Q.v "K_e" (Q.varT "K" []) []]))
                   (.IterT (Q.t (Q.varT "K" [])) .List)))
             .BoolT)
          []]
       none
       [])

def «$intersect_set» {τK : Type} [ToValue τK] [BEq τK]
        (p0 : NanoP4Spec.set τK)
        (p1 : NanoP4Spec.set τK)
    : Option (Except Fail (NanoP4Spec.set τK)) :=
  ExceptT.run
    (pure
       (NanoP4Spec.set.lbrace_rbrace
          (Builtin.Sets.intersect_set
             (match p0 with
                | .lbrace_rbrace l => l)
             (match p1 with
                | .lbrace_rbrace l => l))))

def «$intersect_set».al : Lang.Al.def :=
  Q.d
    (.BuiltinDecD
       (Q.i "intersect_set")
       [Q.i "K"]
       [Q.pm (.ExpP (Q.t (Q.varT "set" [Q.t (Q.varT "K" [])]))),
        Q.pm (.ExpP (Q.t (Q.varT "set" [Q.t (Q.varT "K" [])])))]
       (Q.t (Q.varT "set" [Q.t (Q.varT "K" [])]))
       [])

def «$union_set» {τK : Type} [ToValue τK] [BEq τK] (p0 : NanoP4Spec.set τK) (p1 : NanoP4Spec.set τK)
    : Option (Except Fail (NanoP4Spec.set τK)) :=
  ExceptT.run
    (pure
       (NanoP4Spec.set.lbrace_rbrace
          (Builtin.Sets.union_set
             (match p0 with
                | .lbrace_rbrace l => l)
             (match p1 with
                | .lbrace_rbrace l => l))))

def «$union_set».al : Lang.Al.def :=
  Q.d
    (.BuiltinDecD
       (Q.i "union_set")
       [Q.i "K"]
       [Q.pm (.ExpP (Q.t (Q.varT "set" [Q.t (Q.varT "K" [])]))),
        Q.pm (.ExpP (Q.t (Q.varT "set" [Q.t (Q.varT "K" [])])))]
       (Q.t (Q.varT "set" [Q.t (Q.varT "K" [])]))
       [])

def «$unions_set» {τK : Type} [ToValue τK] [BEq τK] (p0 : List (NanoP4Spec.set τK))
    : Option (Except Fail (NanoP4Spec.set τK)) :=
  ExceptT.run
    (pure
       (NanoP4Spec.set.lbrace_rbrace
          (Builtin.Sets.unions_set
             (List.map
                (fun s =>
                   (match s with
                      | .lbrace_rbrace l => l))
                p0))))

def «$unions_set».al : Lang.Al.def :=
  Q.d
    (.BuiltinDecD
       (Q.i "unions_set")
       [Q.i "K"]
       [Q.pm (.ExpP (Q.t (.IterT (Q.t (Q.varT "set" [Q.t (Q.varT "K" [])])) .List)))]
       (Q.t (Q.varT "set" [Q.t (Q.varT "K" [])]))
       [])

def «$diff_set» {τK : Type} [ToValue τK] [BEq τK] (p0 : NanoP4Spec.set τK) (p1 : NanoP4Spec.set τK)
    : Option (Except Fail (NanoP4Spec.set τK)) :=
  ExceptT.run
    (pure
       (NanoP4Spec.set.lbrace_rbrace
          (Builtin.Sets.diff_set
             (match p0 with
                | .lbrace_rbrace l => l)
             (match p1 with
                | .lbrace_rbrace l => l))))

def «$diff_set».al : Lang.Al.def :=
  Q.d
    (.BuiltinDecD
       (Q.i "diff_set")
       [Q.i "K"]
       [Q.pm (.ExpP (Q.t (Q.varT "set" [Q.t (Q.varT "K" [])]))),
        Q.pm (.ExpP (Q.t (Q.varT "set" [Q.t (Q.varT "K" [])])))]
       (Q.t (Q.varT "set" [Q.t (Q.varT "K" [])]))
       [])

def «$sub_set» {τK : Type} [ToValue τK] [BEq τK] (p0 : NanoP4Spec.set τK) (p1 : NanoP4Spec.set τK)
    : Option (Except Fail Bool) :=
  ExceptT.run
    (pure
       (Builtin.Sets.sub_set
          (match p0 with
             | .lbrace_rbrace l => l)
          (match p1 with
             | .lbrace_rbrace l => l)))

def «$sub_set».al : Lang.Al.def :=
  Q.d
    (.BuiltinDecD
       (Q.i "sub_set")
       [Q.i "K"]
       [Q.pm (.ExpP (Q.t (Q.varT "set" [Q.t (Q.varT "K" [])]))),
        Q.pm (.ExpP (Q.t (Q.varT "set" [Q.t (Q.varT "K" [])])))]
       (Q.t .BoolT)
       [])

def «$eq_set» {τK : Type} [ToValue τK] [BEq τK] (p0 : NanoP4Spec.set τK) (p1 : NanoP4Spec.set τK)
    : Option (Except Fail Bool) :=
  ExceptT.run
    (pure
       (Builtin.Sets.eq_set
          (match p0 with
             | .lbrace_rbrace l => l)
          (match p1 with
             | .lbrace_rbrace l => l)))

def «$eq_set».al : Lang.Al.def :=
  Q.d
    (.BuiltinDecD
       (Q.i "eq_set")
       [Q.i "K"]
       [Q.pm (.ExpP (Q.t (Q.varT "set" [Q.t (Q.varT "K" [])]))),
        Q.pm (.ExpP (Q.t (Q.varT "set" [Q.t (Q.varT "K" [])])))]
       (Q.t .BoolT)
       [])

def «$empty_map» {τK τV : Type} [ToValue τK] [BEq τK] [ToValue τV] [BEq τV]
    : Option (Except Fail (NanoP4Spec.map τK τV)) :=
  ExceptT.run
    (pure (NanoP4Spec.set.lbrace_rbrace ([] : List (NanoP4Spec.pair τK τV))))

def «$empty_map».al : Lang.Al.def :=
  Q.d
    (.FuncDecD
       (Q.i "empty_map")
       [Q.i "K", Q.i "V"]
       []
       (Q.t (Q.varT "map" [Q.t (Q.varT "K" []), Q.t (Q.varT "V" [])]))
       [Q.cl
          []
          (Q.e
             (.CaseE
                (.Brack
                   (Q.a .LBrace)
                   (.Arg
                      (Q.e
                         (.ListE [])
                         (.IterT
                            (Q.t (Q.varT "pair" [Q.t (Q.varT "K" []), Q.t (Q.varT "V" [])]))
                            .List)))
                   (Q.a .RBrace)))
             (Q.varT "set" [Q.t (Q.varT "pair" [Q.t (Q.varT "K" []), Q.t (Q.varT "V" [])])]))
          []]
       none
       [])

def «$dom_map» {τK τV : Type} [ToValue τK] [BEq τK] [ToValue τV] [BEq τV]
        (p0 : NanoP4Spec.map τK τV)
    : Option (Except Fail (NanoP4Spec.set τK)) :=
  ExceptT.run
    (do
       let .lbrace_rbrace tmp_0 := p0
       let tmp_1 ←
           List.mapM
             (fun (elem : NanoP4Spec.pair τK τV) =>
                (do
                   let .colon K V := elem
                   pure (K, V)))
             tmp_0
       have «K*» := List.map (·.1) tmp_1
       have «V*» := List.map (·.2) tmp_1
       pure (NanoP4Spec.set.lbrace_rbrace «K*»))

def «$dom_map».al : Lang.Al.def :=
  Q.d
    (.FuncDecD
       (Q.i "dom_map")
       [Q.i "K", Q.i "V"]
       [Q.pm (.ExpP (Q.t (Q.varT "map" [Q.t (Q.varT "K" []), Q.t (Q.varT "V" [])])))]
       (Q.t (Q.varT "set" [Q.t (Q.varT "K" [])]))
       [Q.cl
          [Q.ar
             (.ExpA
                (Q.e
                   (.CaseE
                      (.Brack
                         (Q.a .LBrace)
                         (.Arg
                            (Q.e
                               (.IterE
                                  (Q.e
                                     (.CaseE
                                        (.Seq
                                           [.Arg (Q.e (.VarE (Q.i "K")) (Q.varT "K" [])),
                                            .Atom (Q.a (.Operator ":")),
                                            .Arg (Q.e (.VarE (Q.i "V")) (Q.varT "V" []))]))
                                     (Q.varT "pair" [Q.t (Q.varT "K" []), Q.t (Q.varT "V" [])]))
                                  (.mk
                                     .List
                                     [Q.v "K" (Q.varT "K" []) [], Q.v "V" (Q.varT "V" []) []]))
                               (.IterT
                                  (Q.t (Q.varT "pair" [Q.t (Q.varT "K" []), Q.t (Q.varT "V" [])]))
                                  .List)))
                         (Q.a .RBrace)))
                   (Q.varT
                      "set"
                      [Q.t (Q.varT "pair" [Q.t (Q.varT "K" []), Q.t (Q.varT "V" [])])])))]
          (Q.e
             (.CaseE
                (.Brack
                   (Q.a .LBrace)
                   (.Arg
                      (Q.e
                         (.IterE
                            (Q.e (.VarE (Q.i "K")) (Q.varT "K" []))
                            (.mk .List [Q.v "K" (Q.varT "K" []) []]))
                         (.IterT (Q.t (Q.varT "K" [])) .List)))
                   (Q.a .RBrace)))
             (Q.varT "set" [Q.t (Q.varT "K" [])]))
          []]
       none
       [])

def «$codom_map» {τK τV : Type} [ToValue τK] [BEq τK] [ToValue τV] [BEq τV]
        (p0 : NanoP4Spec.map τK τV)
    : Option (Except Fail (NanoP4Spec.set τV)) :=
  ExceptT.run
    (do
       let .lbrace_rbrace tmp_0 := p0
       let tmp_1 ←
           List.mapM
             (fun (elem : NanoP4Spec.pair τK τV) =>
                (do
                   let .colon K V := elem
                   pure (K, V)))
             tmp_0
       have «K*» := List.map (·.1) tmp_1
       have «V*» := List.map (·.2) tmp_1
       pure (NanoP4Spec.set.lbrace_rbrace «V*»))

def «$codom_map».al : Lang.Al.def :=
  Q.d
    (.FuncDecD
       (Q.i "codom_map")
       [Q.i "K", Q.i "V"]
       [Q.pm (.ExpP (Q.t (Q.varT "map" [Q.t (Q.varT "K" []), Q.t (Q.varT "V" [])])))]
       (Q.t (Q.varT "set" [Q.t (Q.varT "V" [])]))
       [Q.cl
          [Q.ar
             (.ExpA
                (Q.e
                   (.CaseE
                      (.Brack
                         (Q.a .LBrace)
                         (.Arg
                            (Q.e
                               (.IterE
                                  (Q.e
                                     (.CaseE
                                        (.Seq
                                           [.Arg (Q.e (.VarE (Q.i "K")) (Q.varT "K" [])),
                                            .Atom (Q.a (.Operator ":")),
                                            .Arg (Q.e (.VarE (Q.i "V")) (Q.varT "V" []))]))
                                     (Q.varT "pair" [Q.t (Q.varT "K" []), Q.t (Q.varT "V" [])]))
                                  (.mk
                                     .List
                                     [Q.v "K" (Q.varT "K" []) [], Q.v "V" (Q.varT "V" []) []]))
                               (.IterT
                                  (Q.t (Q.varT "pair" [Q.t (Q.varT "K" []), Q.t (Q.varT "V" [])]))
                                  .List)))
                         (Q.a .RBrace)))
                   (Q.varT
                      "set"
                      [Q.t (Q.varT "pair" [Q.t (Q.varT "K" []), Q.t (Q.varT "V" [])])])))]
          (Q.e
             (.CaseE
                (.Brack
                   (Q.a .LBrace)
                   (.Arg
                      (Q.e
                         (.IterE
                            (Q.e (.VarE (Q.i "V")) (Q.varT "V" []))
                            (.mk .List [Q.v "V" (Q.varT "V" []) []]))
                         (.IterT (Q.t (Q.varT "V" [])) .List)))
                   (Q.a .RBrace)))
             (Q.varT "set" [Q.t (Q.varT "V" [])]))
          []]
       none
       [])

def «$find_map» {τK τV : Type} [ToValue τK] [BEq τK] [ToValue τV] [BEq τV]
        (p0 : NanoP4Spec.map τK τV)
        (p1 : τK)
    : Option (Except Fail (Option τV)) :=
  ExceptT.run
    (pure
       (Builtin.Maps.find_map
          (match p0 with
             | .lbrace_rbrace l => List.map (fun | .colon k v => (k, v)) l)
          p1))

def «$find_map».al : Lang.Al.def :=
  Q.d
    (.BuiltinDecD
       (Q.i "find_map")
       [Q.i "K", Q.i "V"]
       [Q.pm (.ExpP (Q.t (Q.varT "map" [Q.t (Q.varT "K" []), Q.t (Q.varT "V" [])]))),
        Q.pm (.ExpP (Q.t (Q.varT "K" [])))]
       (Q.t (.IterT (Q.t (Q.varT "V" [])) .Opt))
       [])

def «$find_maps» {τK τV : Type} [ToValue τK] [BEq τK] [ToValue τV] [BEq τV]
        (p0 : List (NanoP4Spec.map τK τV))
        (p1 : τK)
    : Option (Except Fail (Option τV)) :=
  ExceptT.run
    (pure
       (Builtin.Maps.find_maps
          (List.map
             (fun m =>
                (match m with
                   | .lbrace_rbrace l => List.map (fun | .colon k v => (k, v)) l))
             p0)
          p1))

def «$find_maps».al : Lang.Al.def :=
  Q.d
    (.BuiltinDecD
       (Q.i "find_maps")
       [Q.i "K", Q.i "V"]
       [Q.pm
          (.ExpP
             (Q.t (.IterT (Q.t (Q.varT "map" [Q.t (Q.varT "K" []), Q.t (Q.varT "V" [])])) .List))),
        Q.pm (.ExpP (Q.t (Q.varT "K" [])))]
       (Q.t (.IterT (Q.t (Q.varT "V" [])) .Opt))
       [])

def «$add_map» {τK τV : Type} [ToValue τK] [BEq τK] [ToValue τV] [BEq τV]
        (p0 : NanoP4Spec.map τK τV)
        (p1 : τK)
        (p2 : τV)
    : Option (Except Fail (NanoP4Spec.map τK τV)) :=
  ExceptT.run
    (pure
       (NanoP4Spec.set.lbrace_rbrace
          (List.map
             (fun (k, v) => NanoP4Spec.pair.colon k v)
             (Builtin.Maps.add_map
                (match p0 with
                   | .lbrace_rbrace l => List.map (fun | .colon k v => (k, v)) l)
                p1
                p2))))

def «$add_map».al : Lang.Al.def :=
  Q.d
    (.BuiltinDecD
       (Q.i "add_map")
       [Q.i "K", Q.i "V"]
       [Q.pm (.ExpP (Q.t (Q.varT "map" [Q.t (Q.varT "K" []), Q.t (Q.varT "V" [])]))),
        Q.pm (.ExpP (Q.t (Q.varT "K" []))),
        Q.pm (.ExpP (Q.t (Q.varT "V" [])))]
       (Q.t (Q.varT "map" [Q.t (Q.varT "K" []), Q.t (Q.varT "V" [])]))
       [])

def «$update_map» {τK τV : Type} [ToValue τK] [BEq τK] [ToValue τV] [BEq τV]
        (p0 : NanoP4Spec.map τK τV)
        (p1 : τK)
        (p2 : τV)
    : Option (Except Fail (NanoP4Spec.map τK τV)) :=
  ExceptT.run
    (pure
       (NanoP4Spec.set.lbrace_rbrace
          (List.map
             (fun (k, v) => NanoP4Spec.pair.colon k v)
             (Builtin.Maps.update_map
                (match p0 with
                   | .lbrace_rbrace l => List.map (fun | .colon k v => (k, v)) l)
                p1
                p2))))

def «$update_map».al : Lang.Al.def :=
  Q.d
    (.BuiltinDecD
       (Q.i "update_map")
       [Q.i "K", Q.i "V"]
       [Q.pm (.ExpP (Q.t (Q.varT "map" [Q.t (Q.varT "K" []), Q.t (Q.varT "V" [])]))),
        Q.pm (.ExpP (Q.t (Q.varT "K" []))),
        Q.pm (.ExpP (Q.t (Q.varT "V" [])))]
       (Q.t (Q.varT "map" [Q.t (Q.varT "K" []), Q.t (Q.varT "V" [])]))
       [])

end NanoP4Spec
