-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, upstream/nano-p4-spec/3.0-value.watsup
import P4SpecTec.Prelude
import P4SpecTec.Tactic.RunSound
import P4SpecTec.Tactic.Audit
import P4SpecTec.Tactic.Det
import P4SpecTec.Refine.Quote
import NanoP4Spec.«2.1-ir»

/-! # NanoP4Spec.«3.0-value»

The rendering of `upstream/nano-p4-spec/3.0-value.watsup`.
Generated: every definition here mirrors one definition of that file, in
order, by the encodings of `docs/design.md`.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 1000000

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

abbrev integerValue : Type := NanoP4Spec.integerLiteral

def integerValue.toValue (x : NanoP4Spec.integerValue) : Lang.Il.value := ToValue.toValue x

instance : ToValue NanoP4Spec.integerValue := ⟨NanoP4Spec.integerValue.toValue⟩
instance : BEq NanoP4Spec.integerValue := ⟨valueEq⟩

def integerValue.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.integerValue
  | 0, _ => none
  | fuel + 1, v => OfValue.ofValue fuel v

instance : OfValue NanoP4Spec.integerValue := ⟨NanoP4Spec.integerValue.ofValue⟩

def integerValue.al : Lang.Al.def :=
  Q.d (.TypD (Q.i "integerValue") [] (Q.dt (.PlainT (Q.t (Q.varT "integerLiteral" [])))) [])

inductive boolValue where
  | _B (b : Bool)

def boolValue.toValue : NanoP4Spec.boolValue → Lang.Il.value
  | ._B x0 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "boolValue")
        (.Seq [(.Atom (Prelude.Value.atom (.Tag "B"))), (.Arg (ToValue.toValue x0))])

instance : ToValue NanoP4Spec.boolValue := ⟨NanoP4Spec.boolValue.toValue⟩
instance : BEq NanoP4Spec.boolValue := ⟨valueEq⟩

def boolValue.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.boolValue
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0] :=
             Prelude.Value.caseArgs
               c
               (.Seq [(.Atom (Prelude.Value.atom (.Tag "B"))), (.Arg ())]) | none
         pure (NanoP4Spec.boolValue._B (← OfValue.ofValue fuel a0)))
    | _ => none

instance : OfValue NanoP4Spec.boolValue := ⟨NanoP4Spec.boolValue.ofValue⟩

def boolValue.al : Lang.Al.def :=
  Q.d
    (.TypD
       (Q.i "boolValue")
       []
       (Q.dt (.VariantT [Q.tc (.Seq [.Atom (Q.a (.Tag "B")), .Arg (Q.t .BoolT)]) "boolValue" []]))
       [])

inductive matchKindValue where
  | MATCH_KIND_dot (nameIR : NanoP4Spec.nameIR)

def matchKindValue.toValue : NanoP4Spec.matchKindValue → Lang.Il.value
  | .MATCH_KIND_dot x0 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "matchKindValue")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "MATCH_KIND"))),
            (.Atom (Prelude.Value.atom (.Operator "."))),
            (.Arg (ToValue.toValue x0))])

instance : ToValue NanoP4Spec.matchKindValue := ⟨NanoP4Spec.matchKindValue.toValue⟩
instance : BEq NanoP4Spec.matchKindValue := ⟨valueEq⟩

def matchKindValue.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.matchKindValue
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0] :=
             Prelude.Value.caseArgs
               c
               (.Seq
                  [(.Atom (Prelude.Value.atom (.Keyword "MATCH_KIND"))),
                   (.Atom (Prelude.Value.atom (.Operator "."))),
                   (.Arg ())]) | none
         pure (NanoP4Spec.matchKindValue.MATCH_KIND_dot (← OfValue.ofValue fuel a0)))
    | _ => none

instance : OfValue NanoP4Spec.matchKindValue := ⟨NanoP4Spec.matchKindValue.ofValue⟩

def matchKindValue.al : Lang.Al.def :=
  Q.d
    (.TypD
       (Q.i "matchKindValue")
       []
       (Q.dt
          (.VariantT
             [Q.tc
                (.Seq
                   [.Atom (Q.a (.Keyword "MATCH_KIND")),
                    .Atom (Q.a (.Operator ".")),
                    .Arg (Q.t (Q.varT "nameIR" []))])
                "matchKindValue"
                []]))
       [])

inductive baseValue where
  | W (n : Nat) (i : Int)
  | S (n : Nat) (i : Int)
  | _B (b : Bool)
  | MATCH_KIND_dot (nameIR : NanoP4Spec.nameIR)

def baseValue.toValue : NanoP4Spec.baseValue → Lang.Il.value
  | .W x0 x1 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "baseValue")
        (.Seq
           [(.Arg (ToValue.toValue x0)),
            (.Atom (Prelude.Value.atom (.Keyword "W"))),
            (.Arg (ToValue.toValue x1))])
  | .S x0 x1 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "baseValue")
        (.Seq
           [(.Arg (ToValue.toValue x0)),
            (.Atom (Prelude.Value.atom (.Keyword "S"))),
            (.Arg (ToValue.toValue x1))])
  | ._B x0 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "baseValue")
        (.Seq [(.Atom (Prelude.Value.atom (.Tag "B"))), (.Arg (ToValue.toValue x0))])
  | .MATCH_KIND_dot x0 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "baseValue")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "MATCH_KIND"))),
            (.Atom (Prelude.Value.atom (.Operator "."))),
            (.Arg (ToValue.toValue x0))])

instance : ToValue NanoP4Spec.baseValue := ⟨NanoP4Spec.baseValue.toValue⟩
instance : BEq NanoP4Spec.baseValue := ⟨valueEq⟩

def baseValue.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.baseValue
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0, a1] :=
             Prelude.Value.caseArgs
               c
               (.Seq [(.Arg ()), (.Atom (Prelude.Value.atom (.Keyword "W"))), (.Arg ())]) | none
         pure (NanoP4Spec.baseValue.W (← OfValue.ofValue fuel a0) (← OfValue.ofValue fuel a1))) <|>
      ((do
          let some [a0, a1] :=
              Prelude.Value.caseArgs
                c
                (.Seq [(.Arg ()), (.Atom (Prelude.Value.atom (.Keyword "S"))), (.Arg ())]) | none
          pure (NanoP4Spec.baseValue.S (← OfValue.ofValue fuel a0) (← OfValue.ofValue fuel a1))) <|>
       ((do
           let some [a0] :=
               Prelude.Value.caseArgs
                 c
                 (.Seq [(.Atom (Prelude.Value.atom (.Tag "B"))), (.Arg ())]) | none
           pure (NanoP4Spec.baseValue._B (← OfValue.ofValue fuel a0))) <|>
        (do
           let some [a0] :=
               Prelude.Value.caseArgs
                 c
                 (.Seq
                    [(.Atom (Prelude.Value.atom (.Keyword "MATCH_KIND"))),
                     (.Atom (Prelude.Value.atom (.Operator "."))),
                     (.Arg ())]) | none
           pure (NanoP4Spec.baseValue.MATCH_KIND_dot (← OfValue.ofValue fuel a0)))))
    | _ => none

instance : OfValue NanoP4Spec.baseValue := ⟨NanoP4Spec.baseValue.ofValue⟩

def baseValue.al : Lang.Al.def :=
  Q.d
    (.TypD
       (Q.i "baseValue")
       []
       (Q.dt
          (.VariantT
             [Q.tc
                (.Seq
                   [.Arg (Q.t (.NumT .NatT)), .Atom (Q.a (.Keyword "W")), .Arg (Q.t (.NumT .IntT))])
                "integerLiteral"
                [],
              Q.tc
                (.Seq
                   [.Arg (Q.t (.NumT .NatT)), .Atom (Q.a (.Keyword "S")), .Arg (Q.t (.NumT .IntT))])
                "integerLiteral"
                [],
              Q.tc (.Seq [.Atom (Q.a (.Tag "B")), .Arg (Q.t .BoolT)]) "boolValue" [],
              Q.tc
                (.Seq
                   [.Atom (Q.a (.Keyword "MATCH_KIND")),
                    .Atom (Q.a (.Operator ".")),
                    .Arg (Q.t (Q.varT "nameIR" []))])
                "matchKindValue"
                []]))
       [])

abbrev objectState : Type := ExternValue



def objectState.al : Lang.Al.def := Q.d (.ExternTypD (Q.i "objectState") [])

mutual

inductive fieldValue where
  | semi (value : NanoP4Spec.value) (nameIR : P4SpecTec.ByteText)

inductive value where
  | W (n : Nat) (i : Int)
  | S (n : Nat) (i : Int)
  | _B (b : Bool)
  | MATCH_KIND_dot (nameIR : P4SpecTec.ByteText)
  | STRUCT_lbrace_rbrace (typeId : P4SpecTec.ByteText) (fieldValue : List NanoP4Spec.fieldValue)
  | HEADER_lbrace_rbrace (typeId : P4SpecTec.ByteText) (fieldValue : List NanoP4Spec.fieldValue)
  | PACKET (typeId : P4SpecTec.ByteText) (objectState : NanoP4Spec.objectState)
  | TABLE (nameIR : P4SpecTec.ByteText) (tableProperties : NanoP4Spec.tableProperties)

end

mutual

def fieldValue.toValue : NanoP4Spec.fieldValue → Lang.Il.value
  | .semi x0 x1 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "fieldValue")
        (.Seq
           [(.Arg (NanoP4Spec.value.toValue x0)),
            (.Arg (ToValue.toValue x1)),
            (.Atom (Prelude.Value.atom (.Operator ";")))])

def value.toValue : NanoP4Spec.value → Lang.Il.value
  | .W x0 x1 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "value")
        (.Seq
           [(.Arg (ToValue.toValue x0)),
            (.Atom (Prelude.Value.atom (.Keyword "W"))),
            (.Arg (ToValue.toValue x1))])
  | .S x0 x1 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "value")
        (.Seq
           [(.Arg (ToValue.toValue x0)),
            (.Atom (Prelude.Value.atom (.Keyword "S"))),
            (.Arg (ToValue.toValue x1))])
  | ._B x0 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "value")
        (.Seq [(.Atom (Prelude.Value.atom (.Tag "B"))), (.Arg (ToValue.toValue x0))])
  | .MATCH_KIND_dot x0 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "value")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "MATCH_KIND"))),
            (.Atom (Prelude.Value.atom (.Operator "."))),
            (.Arg (ToValue.toValue x0))])
  | .STRUCT_lbrace_rbrace x0 x1 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "value")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "STRUCT"))),
            (.Arg (ToValue.toValue x0)),
            (.Brack
               (Prelude.Value.atom .LBrace)
               (.Arg (Runtime.Value.Make.list Lang.Il.typ'.TextT (fieldValue.toValue_0 x1)))
               (Prelude.Value.atom .RBrace))])
  | .HEADER_lbrace_rbrace x0 x1 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "value")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "HEADER"))),
            (.Arg (ToValue.toValue x0)),
            (.Brack
               (Prelude.Value.atom .LBrace)
               (.Arg (Runtime.Value.Make.list Lang.Il.typ'.TextT (fieldValue.toValue_0 x1)))
               (Prelude.Value.atom .RBrace))])
  | .PACKET x0 x1 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "value")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "PACKET"))),
            (.Arg (ToValue.toValue x0)),
            (.Arg (ToValue.toValue x1))])
  | .TABLE x0 x1 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "value")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "TABLE"))),
            (.Arg (ToValue.toValue x0)),
            (.Arg (ToValue.toValue x1))])

def fieldValue.toValue_0 : List NanoP4Spec.fieldValue → List Lang.Il.value
  | [] => []
  | x :: xs => (NanoP4Spec.fieldValue.toValue x) :: fieldValue.toValue_0 xs

end

instance : ToValue NanoP4Spec.fieldValue := ⟨NanoP4Spec.fieldValue.toValue⟩
instance : BEq NanoP4Spec.fieldValue := ⟨valueEq⟩

instance : ToValue NanoP4Spec.value := ⟨NanoP4Spec.value.toValue⟩
instance : BEq NanoP4Spec.value := ⟨valueEq⟩

mutual

def fieldValue.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.fieldValue
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0, a1] :=
             Prelude.Value.caseArgs
               c
               (.Seq [(.Arg ()), (.Arg ()), (.Atom (Prelude.Value.atom (.Operator ";")))]) | none
         pure (NanoP4Spec.fieldValue.semi
            (← NanoP4Spec.value.ofValue fuel a0)
            (← OfValue.ofValue fuel a1)))
    | _ => none

def value.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.value
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0, a1] :=
             Prelude.Value.caseArgs
               c
               (.Seq [(.Arg ()), (.Atom (Prelude.Value.atom (.Keyword "W"))), (.Arg ())]) | none
         pure (NanoP4Spec.value.W (← OfValue.ofValue fuel a0) (← OfValue.ofValue fuel a1))) <|>
      ((do
          let some [a0, a1] :=
              Prelude.Value.caseArgs
                c
                (.Seq [(.Arg ()), (.Atom (Prelude.Value.atom (.Keyword "S"))), (.Arg ())]) | none
          pure (NanoP4Spec.value.S (← OfValue.ofValue fuel a0) (← OfValue.ofValue fuel a1))) <|>
       ((do
           let some [a0] :=
               Prelude.Value.caseArgs
                 c
                 (.Seq [(.Atom (Prelude.Value.atom (.Tag "B"))), (.Arg ())]) | none
           pure (NanoP4Spec.value._B (← OfValue.ofValue fuel a0))) <|>
        ((do
            let some [a0] :=
                Prelude.Value.caseArgs
                  c
                  (.Seq
                     [(.Atom (Prelude.Value.atom (.Keyword "MATCH_KIND"))),
                      (.Atom (Prelude.Value.atom (.Operator "."))),
                      (.Arg ())]) | none
            pure (NanoP4Spec.value.MATCH_KIND_dot (← OfValue.ofValue fuel a0))) <|>
         ((do
             let some [a0, a1] :=
                 Prelude.Value.caseArgs
                   c
                   (.Seq
                      [(.Atom (Prelude.Value.atom (.Keyword "STRUCT"))),
                       (.Arg ()),
                       (.Brack
                          (Prelude.Value.atom .LBrace)
                          (.Arg ())
                          (Prelude.Value.atom .RBrace))]) | none
             pure (NanoP4Spec.value.STRUCT_lbrace_rbrace
                (← OfValue.ofValue fuel a0)
                (← (match a1.it with
                   | .ListV vs => vs.mapM (fun x => NanoP4Spec.fieldValue.ofValue fuel x)
                   | _ => none)))) <|>
          ((do
              let some [a0, a1] :=
                  Prelude.Value.caseArgs
                    c
                    (.Seq
                       [(.Atom (Prelude.Value.atom (.Keyword "HEADER"))),
                        (.Arg ()),
                        (.Brack
                           (Prelude.Value.atom .LBrace)
                           (.Arg ())
                           (Prelude.Value.atom .RBrace))]) | none
              pure (NanoP4Spec.value.HEADER_lbrace_rbrace
                 (← OfValue.ofValue fuel a0)
                 (← (match a1.it with
                    | .ListV vs => vs.mapM (fun x => NanoP4Spec.fieldValue.ofValue fuel x)
                    | _ => none)))) <|>
           ((do
               let some [a0, a1] :=
                   Prelude.Value.caseArgs
                     c
                     (.Seq
                        [(.Atom (Prelude.Value.atom (.Keyword "PACKET"))),
                         (.Arg ()),
                         (.Arg ())]) | none
               pure (NanoP4Spec.value.PACKET
                  (← OfValue.ofValue fuel a0)
                  (← OfValue.ofValue fuel a1))) <|>
            (do
               let some [a0, a1] :=
                   Prelude.Value.caseArgs
                     c
                     (.Seq
                        [(.Atom (Prelude.Value.atom (.Keyword "TABLE"))),
                         (.Arg ()),
                         (.Arg ())]) | none
               pure (NanoP4Spec.value.TABLE
                  (← OfValue.ofValue fuel a0)
                  (← OfValue.ofValue fuel a1)))))))))
    | _ => none

end

instance : OfValue NanoP4Spec.fieldValue := ⟨NanoP4Spec.fieldValue.ofValue⟩

instance : OfValue NanoP4Spec.value := ⟨NanoP4Spec.value.ofValue⟩

def fieldValue.al : Lang.Al.def :=
  Q.d
    (.TypD
       (Q.i "fieldValue")
       []
       (Q.dt
          (.VariantT
             [Q.tc
                (.Seq
                   [.Arg (Q.t (Q.varT "value" [])),
                    .Arg (Q.t (Q.varT "nameIR" [])),
                    .Atom (Q.a (.Operator ";"))])
                "fieldValue"
                []]))
       [])

def value.al : Lang.Al.def :=
  Q.d
    (.TypD
       (Q.i "value")
       []
       (Q.dt
          (.VariantT
             [Q.tc
                (.Seq
                   [.Arg (Q.t (.NumT .NatT)), .Atom (Q.a (.Keyword "W")), .Arg (Q.t (.NumT .IntT))])
                "integerLiteral"
                [],
              Q.tc
                (.Seq
                   [.Arg (Q.t (.NumT .NatT)), .Atom (Q.a (.Keyword "S")), .Arg (Q.t (.NumT .IntT))])
                "integerLiteral"
                [],
              Q.tc (.Seq [.Atom (Q.a (.Tag "B")), .Arg (Q.t .BoolT)]) "boolValue" [],
              Q.tc
                (.Seq
                   [.Atom (Q.a (.Keyword "MATCH_KIND")),
                    .Atom (Q.a (.Operator ".")),
                    .Arg (Q.t (Q.varT "nameIR" []))])
                "matchKindValue"
                [],
              Q.tc
                (.Seq
                   [.Atom (Q.a (.Keyword "STRUCT")),
                    .Arg (Q.t (Q.varT "typeId" [])),
                    .Brack
                      (Q.a .LBrace)
                      (.Arg (Q.t (.IterT (Q.t (Q.varT "fieldValue" [])) .List)))
                      (Q.a .RBrace)])
                "structValue"
                [],
              Q.tc
                (.Seq
                   [.Atom (Q.a (.Keyword "HEADER")),
                    .Arg (Q.t (Q.varT "typeId" [])),
                    .Brack
                      (Q.a .LBrace)
                      (.Arg (Q.t (.IterT (Q.t (Q.varT "fieldValue" [])) .List)))
                      (Q.a .RBrace)])
                "headerValue"
                [],
              Q.tc
                (.Seq
                   [.Atom (Q.a (.Keyword "PACKET")),
                    .Arg (Q.t (Q.varT "typeId" [])),
                    .Arg (Q.t (Q.varT "objectState" []))])
                "packetValue"
                [],
              Q.tc
                (.Seq
                   [.Atom (Q.a (.Keyword "TABLE")),
                    .Arg (Q.t (Q.varT "nameIR" [])),
                    .Arg (Q.t (Q.varT "tableProperties" []))])
                "tableValue"
                []]))
       [])

inductive structValue where
  | STRUCT_lbrace_rbrace (typeId : NanoP4Spec.typeId) (fieldValue : List NanoP4Spec.fieldValue)

def structValue.toValue : NanoP4Spec.structValue → Lang.Il.value
  | .STRUCT_lbrace_rbrace x0 x1 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "structValue")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "STRUCT"))),
            (.Arg (ToValue.toValue x0)),
            (.Brack
               (Prelude.Value.atom .LBrace)
               (.Arg (ToValue.toValue x1))
               (Prelude.Value.atom .RBrace))])

instance : ToValue NanoP4Spec.structValue := ⟨NanoP4Spec.structValue.toValue⟩
instance : BEq NanoP4Spec.structValue := ⟨valueEq⟩

def structValue.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.structValue
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0, a1] :=
             Prelude.Value.caseArgs
               c
               (.Seq
                  [(.Atom (Prelude.Value.atom (.Keyword "STRUCT"))),
                   (.Arg ()),
                   (.Brack
                      (Prelude.Value.atom .LBrace)
                      (.Arg ())
                      (Prelude.Value.atom .RBrace))]) | none
         pure (NanoP4Spec.structValue.STRUCT_lbrace_rbrace
            (← OfValue.ofValue fuel a0)
            (← OfValue.ofValue fuel a1)))
    | _ => none

instance : OfValue NanoP4Spec.structValue := ⟨NanoP4Spec.structValue.ofValue⟩

def structValue.al : Lang.Al.def :=
  Q.d
    (.TypD
       (Q.i "structValue")
       []
       (Q.dt
          (.VariantT
             [Q.tc
                (.Seq
                   [.Atom (Q.a (.Keyword "STRUCT")),
                    .Arg (Q.t (Q.varT "typeId" [])),
                    .Brack
                      (Q.a .LBrace)
                      (.Arg (Q.t (.IterT (Q.t (Q.varT "fieldValue" [])) .List)))
                      (Q.a .RBrace)])
                "structValue"
                []]))
       [])

inductive headerValue where
  | HEADER_lbrace_rbrace (typeId : NanoP4Spec.typeId) (fieldValue : List NanoP4Spec.fieldValue)

def headerValue.toValue : NanoP4Spec.headerValue → Lang.Il.value
  | .HEADER_lbrace_rbrace x0 x1 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "headerValue")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "HEADER"))),
            (.Arg (ToValue.toValue x0)),
            (.Brack
               (Prelude.Value.atom .LBrace)
               (.Arg (ToValue.toValue x1))
               (Prelude.Value.atom .RBrace))])

instance : ToValue NanoP4Spec.headerValue := ⟨NanoP4Spec.headerValue.toValue⟩
instance : BEq NanoP4Spec.headerValue := ⟨valueEq⟩

def headerValue.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.headerValue
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0, a1] :=
             Prelude.Value.caseArgs
               c
               (.Seq
                  [(.Atom (Prelude.Value.atom (.Keyword "HEADER"))),
                   (.Arg ()),
                   (.Brack
                      (Prelude.Value.atom .LBrace)
                      (.Arg ())
                      (Prelude.Value.atom .RBrace))]) | none
         pure (NanoP4Spec.headerValue.HEADER_lbrace_rbrace
            (← OfValue.ofValue fuel a0)
            (← OfValue.ofValue fuel a1)))
    | _ => none

instance : OfValue NanoP4Spec.headerValue := ⟨NanoP4Spec.headerValue.ofValue⟩

def headerValue.al : Lang.Al.def :=
  Q.d
    (.TypD
       (Q.i "headerValue")
       []
       (Q.dt
          (.VariantT
             [Q.tc
                (.Seq
                   [.Atom (Q.a (.Keyword "HEADER")),
                    .Arg (Q.t (Q.varT "typeId" [])),
                    .Brack
                      (Q.a .LBrace)
                      (.Arg (Q.t (.IterT (Q.t (Q.varT "fieldValue" [])) .List)))
                      (Q.a .RBrace)])
                "headerValue"
                []]))
       [])

inductive dataValue where
  | STRUCT_lbrace_rbrace (typeId : NanoP4Spec.typeId) (fieldValue : List NanoP4Spec.fieldValue)
  | HEADER_lbrace_rbrace (typeId : NanoP4Spec.typeId) (fieldValue : List NanoP4Spec.fieldValue)

def dataValue.toValue : NanoP4Spec.dataValue → Lang.Il.value
  | .STRUCT_lbrace_rbrace x0 x1 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "dataValue")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "STRUCT"))),
            (.Arg (ToValue.toValue x0)),
            (.Brack
               (Prelude.Value.atom .LBrace)
               (.Arg (ToValue.toValue x1))
               (Prelude.Value.atom .RBrace))])
  | .HEADER_lbrace_rbrace x0 x1 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "dataValue")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "HEADER"))),
            (.Arg (ToValue.toValue x0)),
            (.Brack
               (Prelude.Value.atom .LBrace)
               (.Arg (ToValue.toValue x1))
               (Prelude.Value.atom .RBrace))])

instance : ToValue NanoP4Spec.dataValue := ⟨NanoP4Spec.dataValue.toValue⟩
instance : BEq NanoP4Spec.dataValue := ⟨valueEq⟩

def dataValue.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.dataValue
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0, a1] :=
             Prelude.Value.caseArgs
               c
               (.Seq
                  [(.Atom (Prelude.Value.atom (.Keyword "STRUCT"))),
                   (.Arg ()),
                   (.Brack
                      (Prelude.Value.atom .LBrace)
                      (.Arg ())
                      (Prelude.Value.atom .RBrace))]) | none
         pure (NanoP4Spec.dataValue.STRUCT_lbrace_rbrace
            (← OfValue.ofValue fuel a0)
            (← OfValue.ofValue fuel a1))) <|>
      (do
         let some [a0, a1] :=
             Prelude.Value.caseArgs
               c
               (.Seq
                  [(.Atom (Prelude.Value.atom (.Keyword "HEADER"))),
                   (.Arg ()),
                   (.Brack
                      (Prelude.Value.atom .LBrace)
                      (.Arg ())
                      (Prelude.Value.atom .RBrace))]) | none
         pure (NanoP4Spec.dataValue.HEADER_lbrace_rbrace
            (← OfValue.ofValue fuel a0)
            (← OfValue.ofValue fuel a1)))
    | _ => none

instance : OfValue NanoP4Spec.dataValue := ⟨NanoP4Spec.dataValue.ofValue⟩

def dataValue.al : Lang.Al.def :=
  Q.d
    (.TypD
       (Q.i "dataValue")
       []
       (Q.dt
          (.VariantT
             [Q.tc
                (.Seq
                   [.Atom (Q.a (.Keyword "STRUCT")),
                    .Arg (Q.t (Q.varT "typeId" [])),
                    .Brack
                      (Q.a .LBrace)
                      (.Arg (Q.t (.IterT (Q.t (Q.varT "fieldValue" [])) .List)))
                      (Q.a .RBrace)])
                "structValue"
                [],
              Q.tc
                (.Seq
                   [.Atom (Q.a (.Keyword "HEADER")),
                    .Arg (Q.t (Q.varT "typeId" [])),
                    .Brack
                      (Q.a .LBrace)
                      (.Arg (Q.t (.IterT (Q.t (Q.varT "fieldValue" [])) .List)))
                      (Q.a .RBrace)])
                "headerValue"
                []]))
       [])

inductive packetValue where
  | PACKET (typeId : NanoP4Spec.typeId) (objectState : NanoP4Spec.objectState)

def packetValue.toValue : NanoP4Spec.packetValue → Lang.Il.value
  | .PACKET x0 x1 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "packetValue")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "PACKET"))),
            (.Arg (ToValue.toValue x0)),
            (.Arg (ToValue.toValue x1))])

instance : ToValue NanoP4Spec.packetValue := ⟨NanoP4Spec.packetValue.toValue⟩
instance : BEq NanoP4Spec.packetValue := ⟨valueEq⟩

def packetValue.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.packetValue
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0, a1] :=
             Prelude.Value.caseArgs
               c
               (.Seq
                  [(.Atom (Prelude.Value.atom (.Keyword "PACKET"))), (.Arg ()), (.Arg ())]) | none
         pure (NanoP4Spec.packetValue.PACKET
            (← OfValue.ofValue fuel a0)
            (← OfValue.ofValue fuel a1)))
    | _ => none

instance : OfValue NanoP4Spec.packetValue := ⟨NanoP4Spec.packetValue.ofValue⟩

def packetValue.al : Lang.Al.def :=
  Q.d
    (.TypD
       (Q.i "packetValue")
       []
       (Q.dt
          (.VariantT
             [Q.tc
                (.Seq
                   [.Atom (Q.a (.Keyword "PACKET")),
                    .Arg (Q.t (Q.varT "typeId" [])),
                    .Arg (Q.t (Q.varT "objectState" []))])
                "packetValue"
                []]))
       [])

inductive tableValue where
  | TABLE (nameIR : NanoP4Spec.nameIR) (tableProperties : NanoP4Spec.tableProperties)

def tableValue.toValue : NanoP4Spec.tableValue → Lang.Il.value
  | .TABLE x0 x1 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "tableValue")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "TABLE"))),
            (.Arg (ToValue.toValue x0)),
            (.Arg (ToValue.toValue x1))])

instance : ToValue NanoP4Spec.tableValue := ⟨NanoP4Spec.tableValue.toValue⟩
instance : BEq NanoP4Spec.tableValue := ⟨valueEq⟩

def tableValue.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.tableValue
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0, a1] :=
             Prelude.Value.caseArgs
               c
               (.Seq [(.Atom (Prelude.Value.atom (.Keyword "TABLE"))), (.Arg ()), (.Arg ())]) | none
         pure (NanoP4Spec.tableValue.TABLE (← OfValue.ofValue fuel a0) (← OfValue.ofValue fuel a1)))
    | _ => none

instance : OfValue NanoP4Spec.tableValue := ⟨NanoP4Spec.tableValue.ofValue⟩

def tableValue.al : Lang.Al.def :=
  Q.d
    (.TypD
       (Q.i "tableValue")
       []
       (Q.dt
          (.VariantT
             [Q.tc
                (.Seq
                   [.Atom (Q.a (.Keyword "TABLE")),
                    .Arg (Q.t (Q.varT "nameIR" [])),
                    .Arg (Q.t (Q.varT "tableProperties" []))])
                "tableValue"
                []]))
       [])

inductive objectValue where
  | PACKET (typeId : NanoP4Spec.typeId) (objectState : NanoP4Spec.objectState)
  | TABLE (nameIR : NanoP4Spec.nameIR) (tableProperties : NanoP4Spec.tableProperties)

def objectValue.toValue : NanoP4Spec.objectValue → Lang.Il.value
  | .PACKET x0 x1 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "objectValue")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "PACKET"))),
            (.Arg (ToValue.toValue x0)),
            (.Arg (ToValue.toValue x1))])
  | .TABLE x0 x1 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "objectValue")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "TABLE"))),
            (.Arg (ToValue.toValue x0)),
            (.Arg (ToValue.toValue x1))])

instance : ToValue NanoP4Spec.objectValue := ⟨NanoP4Spec.objectValue.toValue⟩
instance : BEq NanoP4Spec.objectValue := ⟨valueEq⟩

def objectValue.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.objectValue
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0, a1] :=
             Prelude.Value.caseArgs
               c
               (.Seq
                  [(.Atom (Prelude.Value.atom (.Keyword "PACKET"))), (.Arg ()), (.Arg ())]) | none
         pure (NanoP4Spec.objectValue.PACKET
            (← OfValue.ofValue fuel a0)
            (← OfValue.ofValue fuel a1))) <|>
      (do
         let some [a0, a1] :=
             Prelude.Value.caseArgs
               c
               (.Seq [(.Atom (Prelude.Value.atom (.Keyword "TABLE"))), (.Arg ()), (.Arg ())]) | none
         pure (NanoP4Spec.objectValue.TABLE
            (← OfValue.ofValue fuel a0)
            (← OfValue.ofValue fuel a1)))
    | _ => none

instance : OfValue NanoP4Spec.objectValue := ⟨NanoP4Spec.objectValue.ofValue⟩

def objectValue.al : Lang.Al.def :=
  Q.d
    (.TypD
       (Q.i "objectValue")
       []
       (Q.dt
          (.VariantT
             [Q.tc
                (.Seq
                   [.Atom (Q.a (.Keyword "PACKET")),
                    .Arg (Q.t (Q.varT "typeId" [])),
                    .Arg (Q.t (Q.varT "objectState" []))])
                "packetValue"
                [],
              Q.tc
                (.Seq
                   [.Atom (Q.a (.Keyword "TABLE")),
                    .Arg (Q.t (Q.varT "nameIR" [])),
                    .Arg (Q.t (Q.varT "tableProperties" []))])
                "tableValue"
                []]))
       [])

def integerLiteral.to_value : NanoP4Spec.integerLiteral → NanoP4Spec.value
  | .W x0 x1 => .W x0 x1
  | .S x0 x1 => .S x0 x1

def value.of_integerLiteral : NanoP4Spec.value → Option NanoP4Spec.integerLiteral
  | .W x0 x1 => some (.W x0 x1)
  | .S x0 x1 => some (.S x0 x1)
  | _ => none

def value.is_integerLiteral : NanoP4Spec.value → Bool
  | .W _ _ => true
  | .S _ _ => true
  | _ => false

def boolValue.to_value : NanoP4Spec.boolValue → NanoP4Spec.value
  | ._B x0 => ._B x0

def value.of_boolValue : NanoP4Spec.value → Option NanoP4Spec.boolValue
  | ._B x0 => some (._B x0)
  | _ => none

def value.is_boolValue : NanoP4Spec.value → Bool
  | ._B _ => true
  | _ => false

def structValue.to_value : NanoP4Spec.structValue → NanoP4Spec.value
  | .STRUCT_lbrace_rbrace x0 x1 => .STRUCT_lbrace_rbrace x0 x1

def value.of_structValue : NanoP4Spec.value → Option NanoP4Spec.structValue
  | .STRUCT_lbrace_rbrace x0 x1 => some (.STRUCT_lbrace_rbrace x0 x1)
  | _ => none

def value.is_structValue : NanoP4Spec.value → Bool
  | .STRUCT_lbrace_rbrace _ _ => true
  | _ => false

def headerValue.to_value : NanoP4Spec.headerValue → NanoP4Spec.value
  | .HEADER_lbrace_rbrace x0 x1 => .HEADER_lbrace_rbrace x0 x1

def value.of_headerValue : NanoP4Spec.value → Option NanoP4Spec.headerValue
  | .HEADER_lbrace_rbrace x0 x1 => some (.HEADER_lbrace_rbrace x0 x1)
  | _ => none

def value.is_headerValue : NanoP4Spec.value → Bool
  | .HEADER_lbrace_rbrace _ _ => true
  | _ => false

def matchKindValue.to_value : NanoP4Spec.matchKindValue → NanoP4Spec.value
  | .MATCH_KIND_dot x0 => .MATCH_KIND_dot x0

def value.of_matchKindValue : NanoP4Spec.value → Option NanoP4Spec.matchKindValue
  | .MATCH_KIND_dot x0 => some (.MATCH_KIND_dot x0)
  | _ => none

def value.is_matchKindValue : NanoP4Spec.value → Bool
  | .MATCH_KIND_dot _ => true
  | _ => false

def packetValue.to_value : NanoP4Spec.packetValue → NanoP4Spec.value
  | .PACKET x0 x1 => .PACKET x0 x1

def value.of_packetValue : NanoP4Spec.value → Option NanoP4Spec.packetValue
  | .PACKET x0 x1 => some (.PACKET x0 x1)
  | _ => none

def value.is_packetValue : NanoP4Spec.value → Bool
  | .PACKET _ _ => true
  | _ => false

def tableValue.to_value : NanoP4Spec.tableValue → NanoP4Spec.value
  | .TABLE x0 x1 => .TABLE x0 x1

def value.of_tableValue : NanoP4Spec.value → Option NanoP4Spec.tableValue
  | .TABLE x0 x1 => some (.TABLE x0 x1)
  | _ => none

def value.is_tableValue : NanoP4Spec.value → Bool
  | .TABLE _ _ => true
  | _ => false

def «$default» (p0 : NanoP4Spec.typeIR) : Option (Except Fail NanoP4Spec.value) :=
  ExceptT.run
    ((do
        have typeIR := p0
        let _ ← Eval.check (NanoP4Spec.typeIR.is_integerTypeIR typeIR)
        let tmp_0 ← Eval.err? (NanoP4Spec.typeIR.of_integerTypeIR typeIR)
        have integerTypeIR := tmp_0
        let _ ← Eval.check (match integerTypeIR with
           | NanoP4Spec.integerTypeIR.BIT_langle_rangle _ => true
           | _ => false)
        let .BIT_langle_rangle w := integerTypeIR | throw Fail.err
        pure (NanoP4Spec.integerLiteral.to_value
           (NanoP4Spec.integerLiteral.W w (Int.ofNat (0 : Nat))))) <|>
     ((do
         have typeIR := p0
         let _ ← Eval.check (NanoP4Spec.typeIR.is_integerTypeIR typeIR)
         let tmp_1 ← Eval.err? (NanoP4Spec.typeIR.of_integerTypeIR typeIR)
         have integerTypeIR := tmp_1
         let _ ← Eval.check (match integerTypeIR with
            | NanoP4Spec.integerTypeIR.INT_langle_rangle _ => true
            | _ => false)
         let .INT_langle_rangle w := integerTypeIR | throw Fail.err
         pure (NanoP4Spec.integerLiteral.to_value
            (NanoP4Spec.integerLiteral.S w (Int.ofNat (0 : Nat))))) <|>
      ((do
          have typeIR := p0
          let _ ← Eval.check (NanoP4Spec.typeIR.is_baseTypeIR typeIR)
          let tmp_2 ← Eval.err? (NanoP4Spec.typeIR.of_baseTypeIR typeIR)
          have baseTypeIR := tmp_2
          let _ ← Eval.check (match baseTypeIR with
             | NanoP4Spec.baseTypeIR.BOOL => true
             | _ => false)
          pure (NanoP4Spec.boolValue.to_value (NanoP4Spec.boolValue._B false))) <|>
       ((do
           have typeIR' := p0
           let _ ← Eval.check (NanoP4Spec.typeIR.is_structTypeIR typeIR')
           let tmp_3 ← Eval.err? (NanoP4Spec.typeIR.of_structTypeIR typeIR')
           let .STRUCT_lbrace_rbrace typeId «fieldTypeIR*» := tmp_3
           let tmp_4 ←
               List.mapM
                 (fun (fieldTypeIR : NanoP4Spec.fieldTypeIR) =>
                    (do
                       let .semi typeIR id := fieldTypeIR
                       pure (id, typeIR)))
                 «fieldTypeIR*»
           have «id*» := List.map (·.1) tmp_4
           have «typeIR*» := List.map (·.2) tmp_4
           let tmp_6 ←
               List.mapM
                 (fun (typeIR : NanoP4Spec.typeIR) =>
                    (do
                       let tmp_5 ← ExceptT.mk (NanoP4Spec.«$default» typeIR)
                       have value := tmp_5
                       pure value))
                 «typeIR*»
           have «value*» := tmp_6
           let tmp_7 ←
               List.mapM
                 (fun ((id, value) : NanoP4Spec.id × NanoP4Spec.value) =>
                    (do
                       have fieldValue := NanoP4Spec.fieldValue.semi value id
                       pure fieldValue))
                 (List.zip «id*» «value*»)
           have «fieldValue*» := tmp_7
           pure (NanoP4Spec.structValue.to_value
              (NanoP4Spec.structValue.STRUCT_lbrace_rbrace typeId «fieldValue*»))) <|>
        (do
           have typeIR' := p0
           let _ ← Eval.check (NanoP4Spec.typeIR.is_headerTypeIR typeIR')
           let tmp_8 ← Eval.err? (NanoP4Spec.typeIR.of_headerTypeIR typeIR')
           let .HEADER_lbrace_rbrace typeId «fieldTypeIR*» := tmp_8
           let tmp_9 ←
               List.mapM
                 (fun (fieldTypeIR : NanoP4Spec.fieldTypeIR) =>
                    (do
                       let .semi typeIR id := fieldTypeIR
                       pure (id, typeIR)))
                 «fieldTypeIR*»
           have «id*» := List.map (·.1) tmp_9
           have «typeIR*» := List.map (·.2) tmp_9
           let tmp_11 ←
               List.mapM
                 (fun (typeIR : NanoP4Spec.typeIR) =>
                    (do
                       let tmp_10 ← ExceptT.mk (NanoP4Spec.«$default» typeIR)
                       have value := tmp_10
                       pure value))
                 «typeIR*»
           have «value*» := tmp_11
           let tmp_12 ←
               List.mapM
                 (fun ((id, value) : NanoP4Spec.id × NanoP4Spec.value) =>
                    (do
                       have fieldValue := NanoP4Spec.fieldValue.semi value id
                       pure fieldValue))
                 (List.zip «id*» «value*»)
           have «fieldValue*» := tmp_12
           pure (NanoP4Spec.headerValue.to_value
              (NanoP4Spec.headerValue.HEADER_lbrace_rbrace typeId «fieldValue*»)))))))
  partial_fixpoint

def «$default».al : Lang.Al.def :=
  Q.d
    (.FuncDecD
       (Q.i "default")
       []
       [Q.pm (.ExpP (Q.t (Q.varT "typeIR" [])))]
       (Q.t (Q.varT "value" []))
       [Q.cl
          [Q.ar (.ExpA (Q.e (.VarE (Q.i "typeIR")) (Q.varT "typeIR" [])))]
          (Q.e
             (.UpCastE
                (Q.t (Q.varT "value" []))
                (Q.e
                   (.CaseE
                      (.Seq
                         [.Arg (Q.e (.VarE (Q.i "w")) (.NumT .NatT)),
                          .Atom (Q.a (.Keyword "W")),
                          .Arg
                            (Q.e
                               (.UpCastE (Q.t (.NumT .IntT)) (Q.e (.NumE (.Nat 0)) (.NumT .NatT)))
                               (.NumT .IntT))]))
                   (Q.varT "integerLiteral" [])))
             (Q.varT "value" []))
          [Q.pr
             (.IfPr
                (Q.e
                   (.SubE
                      (Q.e (.VarE (Q.i "typeIR")) (Q.varT "typeIR" []))
                      (Q.t (Q.varT "integerTypeIR" []))
                      (.MixopSC
                         [.Seq
                            [.Atom (Q.a (.Keyword "INT")),
                             .Brack (Q.a .LAngle) (.Arg ()) (Q.a .RAngle)],
                          .Seq
                            [.Atom (Q.a (.Keyword "BIT")),
                             .Brack (Q.a .LAngle) (.Arg ()) (Q.a .RAngle)]]))
                   .BoolT)),
           Q.pr
             (.LetPr
                (Q.e (.VarE (Q.i "integerTypeIR")) (Q.varT "integerTypeIR" []))
                (Q.e
                   (.DownCastE
                      (Q.t (Q.varT "integerTypeIR" []))
                      (Q.e (.VarE (Q.i "typeIR")) (Q.varT "typeIR" [])))
                   (Q.varT "integerTypeIR" []))),
           Q.pr
             (.IfPr
                (Q.e
                   (.MatchE
                      (Q.e (.VarE (Q.i "integerTypeIR")) (Q.varT "integerTypeIR" []))
                      (.CaseP
                         (.Seq
                            [.Atom (Q.a (.Keyword "BIT")),
                             .Brack (Q.a .LAngle) (.Arg ()) (Q.a .RAngle)])))
                   .BoolT)),
           Q.pr
             (.LetPr
                (Q.e
                   (.CaseE
                      (.Seq
                         [.Atom (Q.a (.Keyword "BIT")),
                          .Brack
                            (Q.a .LAngle)
                            (.Arg (Q.e (.VarE (Q.i "w")) (.NumT .NatT)))
                            (Q.a .RAngle)]))
                   (Q.varT "integerTypeIR" []))
                (Q.e (.VarE (Q.i "integerTypeIR")) (Q.varT "integerTypeIR" [])))],
        Q.cl
          [Q.ar (.ExpA (Q.e (.VarE (Q.i "typeIR")) (Q.varT "typeIR" [])))]
          (Q.e
             (.UpCastE
                (Q.t (Q.varT "value" []))
                (Q.e
                   (.CaseE
                      (.Seq
                         [.Arg (Q.e (.VarE (Q.i "w")) (.NumT .NatT)),
                          .Atom (Q.a (.Keyword "S")),
                          .Arg
                            (Q.e
                               (.UpCastE (Q.t (.NumT .IntT)) (Q.e (.NumE (.Nat 0)) (.NumT .NatT)))
                               (.NumT .IntT))]))
                   (Q.varT "integerLiteral" [])))
             (Q.varT "value" []))
          [Q.pr
             (.IfPr
                (Q.e
                   (.SubE
                      (Q.e (.VarE (Q.i "typeIR")) (Q.varT "typeIR" []))
                      (Q.t (Q.varT "integerTypeIR" []))
                      (.MixopSC
                         [.Seq
                            [.Atom (Q.a (.Keyword "INT")),
                             .Brack (Q.a .LAngle) (.Arg ()) (Q.a .RAngle)],
                          .Seq
                            [.Atom (Q.a (.Keyword "BIT")),
                             .Brack (Q.a .LAngle) (.Arg ()) (Q.a .RAngle)]]))
                   .BoolT)),
           Q.pr
             (.LetPr
                (Q.e (.VarE (Q.i "integerTypeIR")) (Q.varT "integerTypeIR" []))
                (Q.e
                   (.DownCastE
                      (Q.t (Q.varT "integerTypeIR" []))
                      (Q.e (.VarE (Q.i "typeIR")) (Q.varT "typeIR" [])))
                   (Q.varT "integerTypeIR" []))),
           Q.pr
             (.IfPr
                (Q.e
                   (.MatchE
                      (Q.e (.VarE (Q.i "integerTypeIR")) (Q.varT "integerTypeIR" []))
                      (.CaseP
                         (.Seq
                            [.Atom (Q.a (.Keyword "INT")),
                             .Brack (Q.a .LAngle) (.Arg ()) (Q.a .RAngle)])))
                   .BoolT)),
           Q.pr
             (.LetPr
                (Q.e
                   (.CaseE
                      (.Seq
                         [.Atom (Q.a (.Keyword "INT")),
                          .Brack
                            (Q.a .LAngle)
                            (.Arg (Q.e (.VarE (Q.i "w")) (.NumT .NatT)))
                            (Q.a .RAngle)]))
                   (Q.varT "integerTypeIR" []))
                (Q.e (.VarE (Q.i "integerTypeIR")) (Q.varT "integerTypeIR" [])))],
        Q.cl
          [Q.ar (.ExpA (Q.e (.VarE (Q.i "typeIR")) (Q.varT "typeIR" [])))]
          (Q.e
             (.UpCastE
                (Q.t (Q.varT "value" []))
                (Q.e
                   (.CaseE (.Seq [.Atom (Q.a (.Tag "B")), .Arg (Q.e (.BoolE false) .BoolT)]))
                   (Q.varT "boolValue" [])))
             (Q.varT "value" []))
          [Q.pr
             (.IfPr
                (Q.e
                   (.SubE
                      (Q.e (.VarE (Q.i "typeIR")) (Q.varT "typeIR" []))
                      (Q.t (Q.varT "baseTypeIR" []))
                      (.MixopSC
                         [.Seq
                            [.Atom (Q.a (.Keyword "INT")),
                             .Brack (Q.a .LAngle) (.Arg ()) (Q.a .RAngle)],
                          .Seq
                            [.Atom (Q.a (.Keyword "BIT")),
                             .Brack (Q.a .LAngle) (.Arg ()) (Q.a .RAngle)],
                          .Atom (Q.a (.Keyword "BOOL")),
                          .Atom (Q.a (.Keyword "MATCH_KIND"))]))
                   .BoolT)),
           Q.pr
             (.LetPr
                (Q.e (.VarE (Q.i "baseTypeIR")) (Q.varT "baseTypeIR" []))
                (Q.e
                   (.DownCastE
                      (Q.t (Q.varT "baseTypeIR" []))
                      (Q.e (.VarE (Q.i "typeIR")) (Q.varT "typeIR" [])))
                   (Q.varT "baseTypeIR" []))),
           Q.pr
             (.IfPr
                (Q.e
                   (.MatchE
                      (Q.e (.VarE (Q.i "baseTypeIR")) (Q.varT "baseTypeIR" []))
                      (.CaseP (.Atom (Q.a (.Keyword "BOOL")))))
                   .BoolT))],
        Q.cl
          [Q.ar (.ExpA (Q.e (.VarE (Q.i "typeIR'")) (Q.varT "typeIR" [])))]
          (Q.e
             (.UpCastE
                (Q.t (Q.varT "value" []))
                (Q.e
                   (.CaseE
                      (.Seq
                         [.Atom (Q.a (.Keyword "STRUCT")),
                          .Arg (Q.e (.VarE (Q.i "typeId")) (Q.varT "typeId" [])),
                          .Brack
                            (Q.a .LBrace)
                            (.Arg
                               (Q.e
                                  (.IterE
                                     (Q.e (.VarE (Q.i "fieldValue")) (Q.varT "fieldValue" []))
                                     (.mk .List [Q.v "fieldValue" (Q.varT "fieldValue" []) []]))
                                  (.IterT (Q.t (Q.varT "fieldValue" [])) .List)))
                            (Q.a .RBrace)]))
                   (Q.varT "structValue" [])))
             (Q.varT "value" []))
          [Q.pr
             (.IfPr
                (Q.e
                   (.SubE
                      (Q.e (.VarE (Q.i "typeIR'")) (Q.varT "typeIR" []))
                      (Q.t (Q.varT "structTypeIR" []))
                      (.MixopSC
                         [.Seq
                            [.Atom (Q.a (.Keyword "STRUCT")),
                             .Arg (),
                             .Brack (Q.a .LBrace) (.Arg ()) (Q.a .RBrace)]]))
                   .BoolT)),
           Q.pr
             (.LetPr
                (Q.e
                   (.CaseE
                      (.Seq
                         [.Atom (Q.a (.Keyword "STRUCT")),
                          .Arg (Q.e (.VarE (Q.i "typeId")) (Q.varT "typeId" [])),
                          .Brack
                            (Q.a .LBrace)
                            (.Arg
                               (Q.e
                                  (.IterE
                                     (Q.e (.VarE (Q.i "fieldTypeIR")) (Q.varT "fieldTypeIR" []))
                                     (.mk .List [Q.v "fieldTypeIR" (Q.varT "fieldTypeIR" []) []]))
                                  (.IterT (Q.t (Q.varT "fieldTypeIR" [])) .List)))
                            (Q.a .RBrace)]))
                   (Q.varT "structTypeIR" []))
                (Q.e
                   (.DownCastE
                      (Q.t (Q.varT "structTypeIR" []))
                      (Q.e (.VarE (Q.i "typeIR'")) (Q.varT "typeIR" [])))
                   (Q.varT "structTypeIR" []))),
           Q.pr
             (.IterPr
                (Q.pr
                   (.LetPr
                      (Q.e
                         (.CaseE
                            (.Seq
                               [.Arg (Q.e (.VarE (Q.i "typeIR")) (Q.varT "typeIR" [])),
                                .Arg (Q.e (.VarE (Q.i "id")) (Q.varT "id" [])),
                                .Atom (Q.a (.Operator ";"))]))
                         (Q.varT "fieldTypeIR" []))
                      (Q.e (.VarE (Q.i "fieldTypeIR")) (Q.varT "fieldTypeIR" []))))
                (.mk
                   .List
                   [Q.v "fieldTypeIR" (Q.varT "fieldTypeIR" []) []]
                   [Q.v "id" (Q.varT "id" []) [], Q.v "typeIR" (Q.varT "typeIR" []) []])),
           Q.pr
             (.IterPr
                (Q.pr
                   (.LetPr
                      (Q.e (.VarE (Q.i "value")) (Q.varT "value" []))
                      (Q.e
                         (.CallE
                            (Q.i "default")
                            []
                            [Q.ar (.ExpA (Q.e (.VarE (Q.i "typeIR")) (Q.varT "typeIR" [])))])
                         (Q.varT "value" []))))
                (.mk
                   .List
                   [Q.v "typeIR" (Q.varT "typeIR" []) []]
                   [Q.v "value" (Q.varT "value" []) []])),
           Q.pr
             (.IterPr
                (Q.pr
                   (.LetPr
                      (Q.e (.VarE (Q.i "fieldValue")) (Q.varT "fieldValue" []))
                      (Q.e
                         (.CaseE
                            (.Seq
                               [.Arg (Q.e (.VarE (Q.i "value")) (Q.varT "value" [])),
                                .Arg (Q.e (.VarE (Q.i "id")) (Q.varT "id" [])),
                                .Atom (Q.a (.Operator ";"))]))
                         (Q.varT "fieldValue" []))))
                (.mk
                   .List
                   [Q.v "id" (Q.varT "id" []) [], Q.v "value" (Q.varT "value" []) []]
                   [Q.v "fieldValue" (Q.varT "fieldValue" []) []]))],
        Q.cl
          [Q.ar (.ExpA (Q.e (.VarE (Q.i "typeIR'")) (Q.varT "typeIR" [])))]
          (Q.e
             (.UpCastE
                (Q.t (Q.varT "value" []))
                (Q.e
                   (.CaseE
                      (.Seq
                         [.Atom (Q.a (.Keyword "HEADER")),
                          .Arg (Q.e (.VarE (Q.i "typeId")) (Q.varT "typeId" [])),
                          .Brack
                            (Q.a .LBrace)
                            (.Arg
                               (Q.e
                                  (.IterE
                                     (Q.e (.VarE (Q.i "fieldValue")) (Q.varT "fieldValue" []))
                                     (.mk .List [Q.v "fieldValue" (Q.varT "fieldValue" []) []]))
                                  (.IterT (Q.t (Q.varT "fieldValue" [])) .List)))
                            (Q.a .RBrace)]))
                   (Q.varT "headerValue" [])))
             (Q.varT "value" []))
          [Q.pr
             (.IfPr
                (Q.e
                   (.SubE
                      (Q.e (.VarE (Q.i "typeIR'")) (Q.varT "typeIR" []))
                      (Q.t (Q.varT "headerTypeIR" []))
                      (.MixopSC
                         [.Seq
                            [.Atom (Q.a (.Keyword "HEADER")),
                             .Arg (),
                             .Brack (Q.a .LBrace) (.Arg ()) (Q.a .RBrace)]]))
                   .BoolT)),
           Q.pr
             (.LetPr
                (Q.e
                   (.CaseE
                      (.Seq
                         [.Atom (Q.a (.Keyword "HEADER")),
                          .Arg (Q.e (.VarE (Q.i "typeId")) (Q.varT "typeId" [])),
                          .Brack
                            (Q.a .LBrace)
                            (.Arg
                               (Q.e
                                  (.IterE
                                     (Q.e (.VarE (Q.i "fieldTypeIR")) (Q.varT "fieldTypeIR" []))
                                     (.mk .List [Q.v "fieldTypeIR" (Q.varT "fieldTypeIR" []) []]))
                                  (.IterT (Q.t (Q.varT "fieldTypeIR" [])) .List)))
                            (Q.a .RBrace)]))
                   (Q.varT "headerTypeIR" []))
                (Q.e
                   (.DownCastE
                      (Q.t (Q.varT "headerTypeIR" []))
                      (Q.e (.VarE (Q.i "typeIR'")) (Q.varT "typeIR" [])))
                   (Q.varT "headerTypeIR" []))),
           Q.pr
             (.IterPr
                (Q.pr
                   (.LetPr
                      (Q.e
                         (.CaseE
                            (.Seq
                               [.Arg (Q.e (.VarE (Q.i "typeIR")) (Q.varT "typeIR" [])),
                                .Arg (Q.e (.VarE (Q.i "id")) (Q.varT "id" [])),
                                .Atom (Q.a (.Operator ";"))]))
                         (Q.varT "fieldTypeIR" []))
                      (Q.e (.VarE (Q.i "fieldTypeIR")) (Q.varT "fieldTypeIR" []))))
                (.mk
                   .List
                   [Q.v "fieldTypeIR" (Q.varT "fieldTypeIR" []) []]
                   [Q.v "id" (Q.varT "id" []) [], Q.v "typeIR" (Q.varT "typeIR" []) []])),
           Q.pr
             (.IterPr
                (Q.pr
                   (.LetPr
                      (Q.e (.VarE (Q.i "value")) (Q.varT "value" []))
                      (Q.e
                         (.CallE
                            (Q.i "default")
                            []
                            [Q.ar (.ExpA (Q.e (.VarE (Q.i "typeIR")) (Q.varT "typeIR" [])))])
                         (Q.varT "value" []))))
                (.mk
                   .List
                   [Q.v "typeIR" (Q.varT "typeIR" []) []]
                   [Q.v "value" (Q.varT "value" []) []])),
           Q.pr
             (.IterPr
                (Q.pr
                   (.LetPr
                      (Q.e (.VarE (Q.i "fieldValue")) (Q.varT "fieldValue" []))
                      (Q.e
                         (.CaseE
                            (.Seq
                               [.Arg (Q.e (.VarE (Q.i "value")) (Q.varT "value" [])),
                                .Arg (Q.e (.VarE (Q.i "id")) (Q.varT "id" [])),
                                .Atom (Q.a (.Operator ";"))]))
                         (Q.varT "fieldValue" []))))
                (.mk
                   .List
                   [Q.v "id" (Q.varT "id" []) [], Q.v "value" (Q.varT "value" []) []]
                   [Q.v "fieldValue" (Q.varT "fieldValue" []) []]))]]
       none
       [])

end NanoP4Spec
