-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, upstream/nano-p4-spec/3.1-operations.watsup
import P4SpecTec.Prelude
import NanoP4Spec.«3.0-value»

/-! # NanoP4Spec.«3.1-operations»

The rendering of `upstream/nano-p4-spec/3.1-operations.watsup`.
Generated: every definition here mirrors one definition of that file, in
order, by the encodings of `docs/design.md`.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 1000000

open P4SpecTec P4SpecTec.Prelude
open P4SpecTec.IL (value)

namespace NanoP4Spec

def «$bitstr_to_int» (fuel : Nat) (p0 : Int) (p1 : Int) : Option Int :=
  Builtins.Numerics.bitstr_to_int p0 p1

def «$int_to_bitstr» (fuel : Nat) (p0 : Int) (p1 : Int) : Option Int :=
  Builtins.Numerics.int_to_bitstr p0 p1

def «$pow2» (fuel : Nat) (p0 : Nat) : Option Int :=
  pure (Builtins.Numerics.pow2 (Int.ofNat p0))

def «$bneg» (fuel : Nat) (p0 : Int) : Option Int :=
  pure (Builtins.Numerics.bneg p0)

def «$band» (fuel : Nat) (p0 : Int) (p1 : Int) : Option Int :=
  pure (Builtins.Numerics.band p0 p1)

def «$bxor» (fuel : Nat) (p0 : Int) (p1 : Int) : Option Int :=
  pure (Builtins.Numerics.bxor p0 p1)

def «$bor» (fuel : Nat) (p0 : Int) (p1 : Int) : Option Int :=
  pure (Builtins.Numerics.bor p0 p1)

def «$un_op»
    (fuel : Nat)
    (p0 : NanoP4Spec.unop)
    (p1 : NanoP4Spec.value) : Option NanoP4Spec.value :=
  (do
     let unop := p0
     let value := p1
     let _ ← Iter.check (match unop with
        | NanoP4Spec.unop.bang => true
        | _ => false)
     let _ ← Iter.check (NanoP4Spec.value.is_boolValue value)
     let tmp_0 ← NanoP4Spec.value.of_boolValue value
     let ._B b := tmp_0
     pure (NanoP4Spec.boolValue.to_value (NanoP4Spec.boolValue._B (!b)))) <|>
  ((do
      let unop := p0
      let value := p1
      let _ ← Iter.check (match unop with
         | NanoP4Spec.unop.tilde => true
         | _ => false)
      let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
      let tmp_1 ← NanoP4Spec.value.of_integerLiteral value
      let integerLiteral := tmp_1
      let _ ← Iter.check (match integerLiteral with
         | NanoP4Spec.integerLiteral.W _ _ => true
         | _ => false)
      let .W w i := integerLiteral | none
      let tmp_2 ← NanoP4Spec.«$pow2» fuel w
      let i' := (tmp_2 - i) - (Int.ofNat (1 : Nat))
      pure (NanoP4Spec.integerLiteral.to_value (NanoP4Spec.integerLiteral.W w i'))) <|>
   ((do
       let unop := p0
       let value := p1
       let _ ← Iter.check (match unop with
          | NanoP4Spec.unop.tilde => true
          | _ => false)
       let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
       let tmp_3 ← NanoP4Spec.value.of_integerLiteral value
       let integerLiteral := tmp_3
       let _ ← Iter.check (match integerLiteral with
          | NanoP4Spec.integerLiteral.S _ _ => true
          | _ => false)
       let .S w i := integerLiteral | none
       let tmp_4 ← NanoP4Spec.«$int_to_bitstr» fuel (Int.ofNat w) (-(i + (Int.ofNat (1 : Nat))))
       let i' := tmp_4
       pure (NanoP4Spec.integerLiteral.to_value (NanoP4Spec.integerLiteral.S w i'))) <|>
    ((do
        let unop := p0
        let value := p1
        let _ ← Iter.check (match unop with
           | NanoP4Spec.unop.minus => true
           | _ => false)
        let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
        let tmp_5 ← NanoP4Spec.value.of_integerLiteral value
        let integerLiteral := tmp_5
        let _ ← Iter.check (match integerLiteral with
           | NanoP4Spec.integerLiteral.W _ _ => true
           | _ => false)
        let .W w i := integerLiteral | none
        let tmp_6 ← NanoP4Spec.«$pow2» fuel w
        let i' := tmp_6 - i
        pure (NanoP4Spec.integerLiteral.to_value (NanoP4Spec.integerLiteral.W w i'))) <|>
     ((do
         let unop := p0
         let value := p1
         let _ ← Iter.check (match unop with
            | NanoP4Spec.unop.minus => true
            | _ => false)
         let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
         let tmp_7 ← NanoP4Spec.value.of_integerLiteral value
         let integerLiteral := tmp_7
         let _ ← Iter.check (match integerLiteral with
            | NanoP4Spec.integerLiteral.S _ _ => true
            | _ => false)
         let .S w i := integerLiteral | none
         let tmp_8 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) (-i)
         let tmp_9 ← NanoP4Spec.«$int_to_bitstr» fuel (Int.ofNat w) tmp_8
         let i' := tmp_9
         pure (NanoP4Spec.integerLiteral.to_value (NanoP4Spec.integerLiteral.S w i'))) <|>
      ((do
          let unop := p0
          let value := p1
          let _ ← Iter.check (match unop with
             | NanoP4Spec.unop.plus => true
             | _ => false)
          let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
          let tmp_10 ← NanoP4Spec.value.of_integerLiteral value
          let integerLiteral := tmp_10
          let _ ← Iter.check (match integerLiteral with
             | NanoP4Spec.integerLiteral.W _ _ => true
             | _ => false)
          let .W w i := integerLiteral | none
          pure (NanoP4Spec.integerLiteral.to_value (NanoP4Spec.integerLiteral.W w i))) <|>
       (do
          let unop := p0
          let value := p1
          let _ ← Iter.check (match unop with
             | NanoP4Spec.unop.plus => true
             | _ => false)
          let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
          let tmp_11 ← NanoP4Spec.value.of_integerLiteral value
          let integerLiteral := tmp_11
          let _ ← Iter.check (match integerLiteral with
             | NanoP4Spec.integerLiteral.S _ _ => true
             | _ => false)
          let .S w i := integerLiteral | none
          pure (NanoP4Spec.integerLiteral.to_value (NanoP4Spec.integerLiteral.S w i))))))))

def «$bin_eq» (fuel : Nat) (p0 : NanoP4Spec.value) (p1 : NanoP4Spec.value) : Option Bool :=
  match fuel with
    | 0 => none
    | fuel + 1 =>
      (do
         let value := p0
         let value' := p1
         let _ ← Iter.check (NanoP4Spec.value.is_boolValue value)
         let tmp_0 ← NanoP4Spec.value.of_boolValue value
         let ._B b_a := tmp_0
         let _ ← Iter.check (NanoP4Spec.value.is_boolValue value')
         let tmp_1 ← NanoP4Spec.value.of_boolValue value'
         let ._B b_b := tmp_1
         pure (b_a == b_b)) <|>
      ((do
          let value := p0
          let value' := p1
          let _ ← Iter.check (NanoP4Spec.value.is_matchKindValue value)
          let tmp_2 ← NanoP4Spec.value.of_matchKindValue value
          let .MATCH_KIND_dot id_a := tmp_2
          let _ ← Iter.check (NanoP4Spec.value.is_matchKindValue value')
          let tmp_3 ← NanoP4Spec.value.of_matchKindValue value'
          let .MATCH_KIND_dot id_b := tmp_3
          pure (id_a == id_b)) <|>
       ((do
           let value := p0
           let value' := p1
           let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
           let tmp_4 ← NanoP4Spec.value.of_integerLiteral value
           let integerLiteral := tmp_4
           let _ ← Iter.check (match integerLiteral with
              | NanoP4Spec.integerLiteral.W _ _ => true
              | _ => false)
           let .W w_a i_a := integerLiteral | none
           let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
           let tmp_5 ← NanoP4Spec.value.of_integerLiteral value'
           let integerLiteral' := tmp_5
           let _ ← Iter.check (match integerLiteral' with
              | NanoP4Spec.integerLiteral.W _ _ => true
              | _ => false)
           let .W w_b i_b := integerLiteral' | none
           pure ((w_a == w_b) && (i_a == i_b))) <|>
        ((do
            let value := p0
            let value' := p1
            let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
            let tmp_6 ← NanoP4Spec.value.of_integerLiteral value
            let integerLiteral := tmp_6
            let _ ← Iter.check (match integerLiteral with
               | NanoP4Spec.integerLiteral.S _ _ => true
               | _ => false)
            let .S w_a i_a := integerLiteral | none
            let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
            let tmp_7 ← NanoP4Spec.value.of_integerLiteral value'
            let integerLiteral' := tmp_7
            let _ ← Iter.check (match integerLiteral' with
               | NanoP4Spec.integerLiteral.S _ _ => true
               | _ => false)
            let .S w_b i_b := integerLiteral' | none
            pure ((w_a == w_b) && (i_a == i_b))) <|>
         ((do
             let value := p0
             let value' := p1
             let _ ← Iter.check (NanoP4Spec.value.is_structValue value)
             let tmp_8 ← NanoP4Spec.value.of_structValue value
             let .STRUCT_lbrace_rbrace typeId_a «fieldValue_a*» := tmp_8
             let _ ← Iter.check (NanoP4Spec.value.is_structValue value')
             let tmp_9 ← NanoP4Spec.value.of_structValue value'
             let .STRUCT_lbrace_rbrace typeId_b «fieldValue_b*» := tmp_9
             let tmp_10 ←
                 List.mapM
                   (fun (fieldValue_a : NanoP4Spec.fieldValue) =>
                      (do
                         let .semi value_field_a nameIR_field_a := fieldValue_a
                         pure (nameIR_field_a, value_field_a)))
                   «fieldValue_a*»
             let «nameIR_field_a*» := List.map (·.1) tmp_10
             let «value_field_a*» := List.map (·.2) tmp_10
             let tmp_11 ←
                 List.mapM
                   (fun (fieldValue_b : NanoP4Spec.fieldValue) =>
                      (do
                         let .semi value_field_b nameIR_field_b := fieldValue_b
                         pure (nameIR_field_b, value_field_b)))
                   «fieldValue_b*»
             let «nameIR_field_b*» := List.map (·.1) tmp_11
             let «value_field_b*» := List.map (·.2) tmp_11
             let _ ← Iter.check ((List.length «value_field_a*») == (List.length «value_field_b*»))
             let _ ← Iter.check ((List.length «nameIR_field_a*») == (List.length «nameIR_field_b*»))
             let tmp_13 ←
                 List.mapM
                   (fun ((value_field_a, value_field_b) : NanoP4Spec.value × NanoP4Spec.value) =>
                      (do
                         let tmp_12 ← NanoP4Spec.«$bin_eq» fuel value_field_a value_field_b
                         pure tmp_12))
                   (List.zip «value_field_a*» «value_field_b*»)
             let tmp_14 ← NanoP4Spec.«$forall_» fuel tmp_13
             let tmp_15 ←
                 NanoP4Spec.«$forall_»
                   fuel
                   (List.map
                      (fun ((nameIR_field_a, nameIR_field_b) :
                            NanoP4Spec.nameIR × NanoP4Spec.nameIR) =>
                         nameIR_field_a == nameIR_field_b)
                      (List.zip «nameIR_field_a*» «nameIR_field_b*»))
             pure ((((typeId_a == typeId_b) &&
                ((List.length «fieldValue_a*») == (List.length «fieldValue_b*»))) &&
               tmp_14) &&
              tmp_15)) <|>
          (do
             let value := p0
             let value' := p1
             let _ ← Iter.check (NanoP4Spec.value.is_headerValue value)
             let tmp_16 ← NanoP4Spec.value.of_headerValue value
             let .HEADER_lbrace_rbrace typeId_a «fieldValue_a*» := tmp_16
             let _ ← Iter.check (NanoP4Spec.value.is_headerValue value')
             let tmp_17 ← NanoP4Spec.value.of_headerValue value'
             let .HEADER_lbrace_rbrace typeId_b «fieldValue_b*» := tmp_17
             let tmp_18 ←
                 List.mapM
                   (fun (fieldValue_a : NanoP4Spec.fieldValue) =>
                      (do
                         let .semi value_field_a nameIR_field_a := fieldValue_a
                         pure (nameIR_field_a, value_field_a)))
                   «fieldValue_a*»
             let «nameIR_field_a*» := List.map (·.1) tmp_18
             let «value_field_a*» := List.map (·.2) tmp_18
             let tmp_19 ←
                 List.mapM
                   (fun (fieldValue_b : NanoP4Spec.fieldValue) =>
                      (do
                         let .semi value_field_b nameIR_field_b := fieldValue_b
                         pure (nameIR_field_b, value_field_b)))
                   «fieldValue_b*»
             let «nameIR_field_b*» := List.map (·.1) tmp_19
             let «value_field_b*» := List.map (·.2) tmp_19
             let _ ← Iter.check ((List.length «value_field_a*») == (List.length «value_field_b*»))
             let _ ← Iter.check ((List.length «nameIR_field_a*») == (List.length «nameIR_field_b*»))
             let tmp_21 ←
                 List.mapM
                   (fun ((value_field_a, value_field_b) : NanoP4Spec.value × NanoP4Spec.value) =>
                      (do
                         let tmp_20 ← NanoP4Spec.«$bin_eq» fuel value_field_a value_field_b
                         pure tmp_20))
                   (List.zip «value_field_a*» «value_field_b*»)
             let tmp_22 ← NanoP4Spec.«$forall_» fuel tmp_21
             let tmp_23 ←
                 NanoP4Spec.«$forall_»
                   fuel
                   (List.map
                      (fun ((nameIR_field_a, nameIR_field_b) :
                            NanoP4Spec.nameIR × NanoP4Spec.nameIR) =>
                         nameIR_field_a == nameIR_field_b)
                      (List.zip «nameIR_field_a*» «nameIR_field_b*»))
             pure ((((typeId_a == typeId_b) &&
                ((List.length «fieldValue_a*») == (List.length «fieldValue_b*»))) &&
               tmp_22) &&
              tmp_23))))))

def «$bin_op»
    (fuel : Nat)
    (p0 : NanoP4Spec.binop)
    (p1 : NanoP4Spec.value)
    (p2 : NanoP4Spec.value) : Option NanoP4Spec.value :=
  (do
     let binop := p0
     let value := p1
     let value' := p2
     let _ ← Iter.check (match binop with
        | NanoP4Spec.binop.plus => true
        | _ => false)
     let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
     let tmp_0 ← NanoP4Spec.value.of_integerLiteral value
     let integerLiteral := tmp_0
     let _ ← Iter.check (match integerLiteral with
        | NanoP4Spec.integerLiteral.W _ _ => true
        | _ => false)
     let .W w i_l := integerLiteral | none
     let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
     let tmp_1 ← NanoP4Spec.value.of_integerLiteral value'
     let integerLiteral' := tmp_1
     let _ ← Iter.check (match integerLiteral' with
        | NanoP4Spec.integerLiteral.W _ _ => true
        | _ => false)
     let .W w' i_r := integerLiteral' | none
     let _ ← Iter.check (w == w')
     let tmp_2 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_l
     let i_l' := tmp_2
     let tmp_3 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_r
     let i_r' := tmp_3
     let tmp_4 ← NanoP4Spec.«$int_to_bitstr» fuel (Int.ofNat w) (i_l' + i_r')
     let i' := tmp_4
     pure (NanoP4Spec.integerLiteral.to_value (NanoP4Spec.integerLiteral.W w i'))) <|>
  ((do
      let binop := p0
      let value := p1
      let value' := p2
      let _ ← Iter.check (match binop with
         | NanoP4Spec.binop.plus => true
         | _ => false)
      let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
      let tmp_5 ← NanoP4Spec.value.of_integerLiteral value
      let integerLiteral := tmp_5
      let _ ← Iter.check (match integerLiteral with
         | NanoP4Spec.integerLiteral.S _ _ => true
         | _ => false)
      let .S w i_l := integerLiteral | none
      let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
      let tmp_6 ← NanoP4Spec.value.of_integerLiteral value'
      let integerLiteral' := tmp_6
      let _ ← Iter.check (match integerLiteral' with
         | NanoP4Spec.integerLiteral.S _ _ => true
         | _ => false)
      let .S w' i_r := integerLiteral' | none
      let _ ← Iter.check (w == w')
      let tmp_7 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_l
      let i_l' := tmp_7
      let tmp_8 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_r
      let i_r' := tmp_8
      let tmp_9 ← NanoP4Spec.«$int_to_bitstr» fuel (Int.ofNat w) (i_l' + i_r')
      let i' := tmp_9
      pure (NanoP4Spec.integerLiteral.to_value (NanoP4Spec.integerLiteral.S w i'))) <|>
   ((do
       let binop := p0
       let value := p1
       let value' := p2
       let _ ← Iter.check (match binop with
          | NanoP4Spec.binop.minus => true
          | _ => false)
       let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
       let tmp_10 ← NanoP4Spec.value.of_integerLiteral value
       let integerLiteral := tmp_10
       let _ ← Iter.check (match integerLiteral with
          | NanoP4Spec.integerLiteral.W _ _ => true
          | _ => false)
       let .W w i_l := integerLiteral | none
       let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
       let tmp_11 ← NanoP4Spec.value.of_integerLiteral value'
       let integerLiteral' := tmp_11
       let _ ← Iter.check (match integerLiteral' with
          | NanoP4Spec.integerLiteral.W _ _ => true
          | _ => false)
       let .W w' i_r := integerLiteral' | none
       let _ ← Iter.check (w == w')
       let tmp_12 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_l
       let i_l' := tmp_12
       let tmp_13 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_r
       let i_r' := tmp_13
       let tmp_14 ← NanoP4Spec.«$int_to_bitstr» fuel (Int.ofNat w) (i_l' - i_r')
       let i' := tmp_14
       pure (NanoP4Spec.integerLiteral.to_value (NanoP4Spec.integerLiteral.W w i'))) <|>
    ((do
        let binop := p0
        let value := p1
        let value' := p2
        let _ ← Iter.check (match binop with
           | NanoP4Spec.binop.minus => true
           | _ => false)
        let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
        let tmp_15 ← NanoP4Spec.value.of_integerLiteral value
        let integerLiteral := tmp_15
        let _ ← Iter.check (match integerLiteral with
           | NanoP4Spec.integerLiteral.S _ _ => true
           | _ => false)
        let .S w i_l := integerLiteral | none
        let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
        let tmp_16 ← NanoP4Spec.value.of_integerLiteral value'
        let integerLiteral' := tmp_16
        let _ ← Iter.check (match integerLiteral' with
           | NanoP4Spec.integerLiteral.S _ _ => true
           | _ => false)
        let .S w' i_r := integerLiteral' | none
        let _ ← Iter.check (w == w')
        let tmp_17 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_l
        let i_l' := tmp_17
        let tmp_18 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_r
        let i_r' := tmp_18
        let tmp_19 ← NanoP4Spec.«$int_to_bitstr» fuel (Int.ofNat w) (i_l' - i_r')
        let i' := tmp_19
        pure (NanoP4Spec.integerLiteral.to_value (NanoP4Spec.integerLiteral.S w i'))) <|>
     ((do
         let binop := p0
         let value := p1
         let value' := p2
         let _ ← Iter.check (match binop with
            | NanoP4Spec.binop.minus => true
            | _ => false)
         let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
         let tmp_20 ← NanoP4Spec.value.of_integerLiteral value
         let integerLiteral := tmp_20
         let _ ← Iter.check (match integerLiteral with
            | NanoP4Spec.integerLiteral.W _ _ => true
            | _ => false)
         let .W w i_l := integerLiteral | none
         let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
         let tmp_21 ← NanoP4Spec.value.of_integerLiteral value'
         let integerLiteral' := tmp_21
         let _ ← Iter.check (match integerLiteral' with
            | NanoP4Spec.integerLiteral.W _ _ => true
            | _ => false)
         let .W w' i_r := integerLiteral' | none
         let _ ← Iter.check (w == w')
         let tmp_22 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_l
         let i_l' := tmp_22
         let tmp_23 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_r
         let i_r' := tmp_23
         let tmp_24 ← NanoP4Spec.«$int_to_bitstr» fuel (Int.ofNat w) (i_l' - i_r')
         let i' := tmp_24
         pure (NanoP4Spec.integerLiteral.to_value (NanoP4Spec.integerLiteral.W w i'))) <|>
      ((do
          let binop := p0
          let value := p1
          let value' := p2
          let _ ← Iter.check (match binop with
             | NanoP4Spec.binop.minus => true
             | _ => false)
          let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
          let tmp_25 ← NanoP4Spec.value.of_integerLiteral value
          let integerLiteral := tmp_25
          let _ ← Iter.check (match integerLiteral with
             | NanoP4Spec.integerLiteral.S _ _ => true
             | _ => false)
          let .S w i_l := integerLiteral | none
          let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
          let tmp_26 ← NanoP4Spec.value.of_integerLiteral value'
          let integerLiteral' := tmp_26
          let _ ← Iter.check (match integerLiteral' with
             | NanoP4Spec.integerLiteral.S _ _ => true
             | _ => false)
          let .S w' i_r := integerLiteral' | none
          let _ ← Iter.check (w == w')
          let tmp_27 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_l
          let i_l' := tmp_27
          let tmp_28 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_r
          let i_r' := tmp_28
          let tmp_29 ← NanoP4Spec.«$int_to_bitstr» fuel (Int.ofNat w) (i_l' - i_r')
          let i' := tmp_29
          pure (NanoP4Spec.integerLiteral.to_value (NanoP4Spec.integerLiteral.S w i'))) <|>
       ((do
           let binop := p0
           let value := p1
           let value' := p2
           let _ ← Iter.check (match binop with
              | NanoP4Spec.binop.star => true
              | _ => false)
           let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
           let tmp_30 ← NanoP4Spec.value.of_integerLiteral value
           let integerLiteral := tmp_30
           let _ ← Iter.check (match integerLiteral with
              | NanoP4Spec.integerLiteral.W _ _ => true
              | _ => false)
           let .W w i_l := integerLiteral | none
           let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
           let tmp_31 ← NanoP4Spec.value.of_integerLiteral value'
           let integerLiteral' := tmp_31
           let _ ← Iter.check (match integerLiteral' with
              | NanoP4Spec.integerLiteral.W _ _ => true
              | _ => false)
           let .W w' i_r := integerLiteral' | none
           let _ ← Iter.check (w == w')
           let tmp_32 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_l
           let i_l' := tmp_32
           let tmp_33 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_r
           let i_r' := tmp_33
           let tmp_34 ← NanoP4Spec.«$int_to_bitstr» fuel (Int.ofNat w) (i_l' * i_r')
           let i' := tmp_34
           pure (NanoP4Spec.integerLiteral.to_value (NanoP4Spec.integerLiteral.W w i'))) <|>
        ((do
            let binop := p0
            let value := p1
            let value' := p2
            let _ ← Iter.check (match binop with
               | NanoP4Spec.binop.star => true
               | _ => false)
            let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
            let tmp_35 ← NanoP4Spec.value.of_integerLiteral value
            let integerLiteral := tmp_35
            let _ ← Iter.check (match integerLiteral with
               | NanoP4Spec.integerLiteral.S _ _ => true
               | _ => false)
            let .S w i_l := integerLiteral | none
            let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
            let tmp_36 ← NanoP4Spec.value.of_integerLiteral value'
            let integerLiteral' := tmp_36
            let _ ← Iter.check (match integerLiteral' with
               | NanoP4Spec.integerLiteral.S _ _ => true
               | _ => false)
            let .S w' i_r := integerLiteral' | none
            let _ ← Iter.check (w == w')
            let tmp_37 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_l
            let i_l' := tmp_37
            let tmp_38 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_r
            let i_r' := tmp_38
            let tmp_39 ← NanoP4Spec.«$int_to_bitstr» fuel (Int.ofNat w) (i_l' * i_r')
            let i' := tmp_39
            pure (NanoP4Spec.integerLiteral.to_value (NanoP4Spec.integerLiteral.S w i'))) <|>
         ((do
             let binop := p0
             let value := p1
             let value' := p2
             let _ ← Iter.check (match binop with
                | NanoP4Spec.binop.lteq => true
                | _ => false)
             let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
             let tmp_40 ← NanoP4Spec.value.of_integerLiteral value
             let integerLiteral := tmp_40
             let _ ← Iter.check (match integerLiteral with
                | NanoP4Spec.integerLiteral.W _ _ => true
                | _ => false)
             let .W w i_l := integerLiteral | none
             let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
             let tmp_41 ← NanoP4Spec.value.of_integerLiteral value'
             let integerLiteral' := tmp_41
             let _ ← Iter.check (match integerLiteral' with
                | NanoP4Spec.integerLiteral.W _ _ => true
                | _ => false)
             let .W w' i_r := integerLiteral' | none
             let _ ← Iter.check (w == w')
             pure (NanoP4Spec.boolValue.to_value
                (NanoP4Spec.boolValue._B (decide (i_l ≤ i_r))))) <|>
          ((do
              let binop := p0
              let value := p1
              let value' := p2
              let _ ← Iter.check (match binop with
                 | NanoP4Spec.binop.lteq => true
                 | _ => false)
              let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
              let tmp_42 ← NanoP4Spec.value.of_integerLiteral value
              let integerLiteral := tmp_42
              let _ ← Iter.check (match integerLiteral with
                 | NanoP4Spec.integerLiteral.S _ _ => true
                 | _ => false)
              let .S w i_l := integerLiteral | none
              let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
              let tmp_43 ← NanoP4Spec.value.of_integerLiteral value'
              let integerLiteral' := tmp_43
              let _ ← Iter.check (match integerLiteral' with
                 | NanoP4Spec.integerLiteral.S _ _ => true
                 | _ => false)
              let .S w' i_r := integerLiteral' | none
              let _ ← Iter.check (w == w')
              let tmp_44 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_l
              let i_l' := tmp_44
              let tmp_45 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_r
              let i_r' := tmp_45
              pure (NanoP4Spec.boolValue.to_value
                 (NanoP4Spec.boolValue._B (decide (i_l' ≤ i_r'))))) <|>
           ((do
               let binop := p0
               let value := p1
               let value' := p2
               let _ ← Iter.check (match binop with
                  | NanoP4Spec.binop.gteq => true
                  | _ => false)
               let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
               let tmp_46 ← NanoP4Spec.value.of_integerLiteral value
               let integerLiteral := tmp_46
               let _ ← Iter.check (match integerLiteral with
                  | NanoP4Spec.integerLiteral.W _ _ => true
                  | _ => false)
               let .W w i_l := integerLiteral | none
               let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
               let tmp_47 ← NanoP4Spec.value.of_integerLiteral value'
               let integerLiteral' := tmp_47
               let _ ← Iter.check (match integerLiteral' with
                  | NanoP4Spec.integerLiteral.W _ _ => true
                  | _ => false)
               let .W w' i_r := integerLiteral' | none
               let _ ← Iter.check (w == w')
               pure (NanoP4Spec.boolValue.to_value
                  (NanoP4Spec.boolValue._B (decide (i_l ≥ i_r))))) <|>
            ((do
                let binop := p0
                let value := p1
                let value' := p2
                let _ ← Iter.check (match binop with
                   | NanoP4Spec.binop.gteq => true
                   | _ => false)
                let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
                let tmp_48 ← NanoP4Spec.value.of_integerLiteral value
                let integerLiteral := tmp_48
                let _ ← Iter.check (match integerLiteral with
                   | NanoP4Spec.integerLiteral.S _ _ => true
                   | _ => false)
                let .S w i_l := integerLiteral | none
                let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
                let tmp_49 ← NanoP4Spec.value.of_integerLiteral value'
                let integerLiteral' := tmp_49
                let _ ← Iter.check (match integerLiteral' with
                   | NanoP4Spec.integerLiteral.S _ _ => true
                   | _ => false)
                let .S w' i_r := integerLiteral' | none
                let _ ← Iter.check (w == w')
                let tmp_50 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_l
                let i_l' := tmp_50
                let tmp_51 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_r
                let i_r' := tmp_51
                pure (NanoP4Spec.boolValue.to_value
                   (NanoP4Spec.boolValue._B (decide (i_l' ≥ i_r'))))) <|>
             ((do
                 let binop := p0
                 let value := p1
                 let value' := p2
                 let _ ← Iter.check (match binop with
                    | NanoP4Spec.binop.lt => true
                    | _ => false)
                 let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
                 let tmp_52 ← NanoP4Spec.value.of_integerLiteral value
                 let integerLiteral := tmp_52
                 let _ ← Iter.check (match integerLiteral with
                    | NanoP4Spec.integerLiteral.W _ _ => true
                    | _ => false)
                 let .W w i_l := integerLiteral | none
                 let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
                 let tmp_53 ← NanoP4Spec.value.of_integerLiteral value'
                 let integerLiteral' := tmp_53
                 let _ ← Iter.check (match integerLiteral' with
                    | NanoP4Spec.integerLiteral.W _ _ => true
                    | _ => false)
                 let .W w' i_r := integerLiteral' | none
                 let _ ← Iter.check (w == w')
                 pure (NanoP4Spec.boolValue.to_value
                    (NanoP4Spec.boolValue._B (decide (i_l < i_r))))) <|>
              ((do
                  let binop := p0
                  let value := p1
                  let value' := p2
                  let _ ← Iter.check (match binop with
                     | NanoP4Spec.binop.lt => true
                     | _ => false)
                  let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
                  let tmp_54 ← NanoP4Spec.value.of_integerLiteral value
                  let integerLiteral := tmp_54
                  let _ ← Iter.check (match integerLiteral with
                     | NanoP4Spec.integerLiteral.S _ _ => true
                     | _ => false)
                  let .S w i_l := integerLiteral | none
                  let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
                  let tmp_55 ← NanoP4Spec.value.of_integerLiteral value'
                  let integerLiteral' := tmp_55
                  let _ ← Iter.check (match integerLiteral' with
                     | NanoP4Spec.integerLiteral.S _ _ => true
                     | _ => false)
                  let .S w' i_r := integerLiteral' | none
                  let _ ← Iter.check (w == w')
                  let tmp_56 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_l
                  let i_l' := tmp_56
                  let tmp_57 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_r
                  let i_r' := tmp_57
                  pure (NanoP4Spec.boolValue.to_value
                     (NanoP4Spec.boolValue._B (decide (i_l' < i_r'))))) <|>
               ((do
                   let binop := p0
                   let value := p1
                   let value' := p2
                   let _ ← Iter.check (match binop with
                      | NanoP4Spec.binop.gt => true
                      | _ => false)
                   let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
                   let tmp_58 ← NanoP4Spec.value.of_integerLiteral value
                   let integerLiteral := tmp_58
                   let _ ← Iter.check (match integerLiteral with
                      | NanoP4Spec.integerLiteral.W _ _ => true
                      | _ => false)
                   let .W w i_l := integerLiteral | none
                   let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
                   let tmp_59 ← NanoP4Spec.value.of_integerLiteral value'
                   let integerLiteral' := tmp_59
                   let _ ← Iter.check (match integerLiteral' with
                      | NanoP4Spec.integerLiteral.W _ _ => true
                      | _ => false)
                   let .W w' i_r := integerLiteral' | none
                   let _ ← Iter.check (w == w')
                   pure (NanoP4Spec.boolValue.to_value
                      (NanoP4Spec.boolValue._B (decide (i_l > i_r))))) <|>
                ((do
                    let binop := p0
                    let value := p1
                    let value' := p2
                    let _ ← Iter.check (match binop with
                       | NanoP4Spec.binop.gt => true
                       | _ => false)
                    let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
                    let tmp_60 ← NanoP4Spec.value.of_integerLiteral value
                    let integerLiteral := tmp_60
                    let _ ← Iter.check (match integerLiteral with
                       | NanoP4Spec.integerLiteral.S _ _ => true
                       | _ => false)
                    let .S w i_l := integerLiteral | none
                    let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
                    let tmp_61 ← NanoP4Spec.value.of_integerLiteral value'
                    let integerLiteral' := tmp_61
                    let _ ← Iter.check (match integerLiteral' with
                       | NanoP4Spec.integerLiteral.S _ _ => true
                       | _ => false)
                    let .S w' i_r := integerLiteral' | none
                    let _ ← Iter.check (w == w')
                    let tmp_62 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_l
                    let i_l' := tmp_62
                    let tmp_63 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_r
                    let i_r' := tmp_63
                    pure (NanoP4Spec.boolValue.to_value
                       (NanoP4Spec.boolValue._B (decide (i_l' > i_r'))))) <|>
                 ((do
                     let binop := p0
                     let value_l := p1
                     let value_r := p2
                     let _ ← Iter.check (match binop with
                        | NanoP4Spec.binop.eqeq => true
                        | _ => false)
                     let tmp_64 ← NanoP4Spec.«$bin_eq» fuel value_l value_r
                     pure (NanoP4Spec.boolValue.to_value (NanoP4Spec.boolValue._B tmp_64))) <|>
                  ((do
                      let binop := p0
                      let value_l := p1
                      let value_r := p2
                      let _ ← Iter.check (match binop with
                         | NanoP4Spec.binop.bangeq => true
                         | _ => false)
                      let tmp_65 ← NanoP4Spec.«$bin_eq» fuel value_l value_r
                      pure (NanoP4Spec.boolValue.to_value (NanoP4Spec.boolValue._B (!tmp_65)))) <|>
                   ((do
                       let binop := p0
                       let value := p1
                       let value' := p2
                       let _ ← Iter.check (match binop with
                          | NanoP4Spec.binop.amp => true
                          | _ => false)
                       let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
                       let tmp_66 ← NanoP4Spec.value.of_integerLiteral value
                       let integerLiteral := tmp_66
                       let _ ← Iter.check (match integerLiteral with
                          | NanoP4Spec.integerLiteral.W _ _ => true
                          | _ => false)
                       let .W w i_l := integerLiteral | none
                       let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
                       let tmp_67 ← NanoP4Spec.value.of_integerLiteral value'
                       let integerLiteral' := tmp_67
                       let _ ← Iter.check (match integerLiteral' with
                          | NanoP4Spec.integerLiteral.W _ _ => true
                          | _ => false)
                       let .W w' i_r := integerLiteral' | none
                       let _ ← Iter.check (w == w')
                       let tmp_68 ← NanoP4Spec.«$band» fuel i_l i_r
                       let tmp_69 ← NanoP4Spec.«$int_to_bitstr» fuel (Int.ofNat w) tmp_68
                       let i' := tmp_69
                       pure (NanoP4Spec.integerLiteral.to_value
                          (NanoP4Spec.integerLiteral.W w i'))) <|>
                    ((do
                        let binop := p0
                        let value := p1
                        let value' := p2
                        let _ ← Iter.check (match binop with
                           | NanoP4Spec.binop.amp => true
                           | _ => false)
                        let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
                        let tmp_70 ← NanoP4Spec.value.of_integerLiteral value
                        let integerLiteral := tmp_70
                        let _ ← Iter.check (match integerLiteral with
                           | NanoP4Spec.integerLiteral.S _ _ => true
                           | _ => false)
                        let .S w i_l := integerLiteral | none
                        let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
                        let tmp_71 ← NanoP4Spec.value.of_integerLiteral value'
                        let integerLiteral' := tmp_71
                        let _ ← Iter.check (match integerLiteral' with
                           | NanoP4Spec.integerLiteral.S _ _ => true
                           | _ => false)
                        let .S w' i_r := integerLiteral' | none
                        let _ ← Iter.check (w == w')
                        let tmp_72 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_l
                        let i_l' := tmp_72
                        let tmp_73 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_r
                        let i_r' := tmp_73
                        let tmp_74 ← NanoP4Spec.«$band» fuel i_l' i_r'
                        let tmp_75 ← NanoP4Spec.«$int_to_bitstr» fuel (Int.ofNat w) tmp_74
                        let i' := tmp_75
                        pure (NanoP4Spec.integerLiteral.to_value
                           (NanoP4Spec.integerLiteral.S w i'))) <|>
                     ((do
                         let binop := p0
                         let value := p1
                         let value' := p2
                         let _ ← Iter.check (match binop with
                            | NanoP4Spec.binop.caret => true
                            | _ => false)
                         let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
                         let tmp_76 ← NanoP4Spec.value.of_integerLiteral value
                         let integerLiteral := tmp_76
                         let _ ← Iter.check (match integerLiteral with
                            | NanoP4Spec.integerLiteral.W _ _ => true
                            | _ => false)
                         let .W w i_l := integerLiteral | none
                         let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
                         let tmp_77 ← NanoP4Spec.value.of_integerLiteral value'
                         let integerLiteral' := tmp_77
                         let _ ← Iter.check (match integerLiteral' with
                            | NanoP4Spec.integerLiteral.W _ _ => true
                            | _ => false)
                         let .W w' i_r := integerLiteral' | none
                         let _ ← Iter.check (w == w')
                         let tmp_78 ← NanoP4Spec.«$bxor» fuel i_l i_r
                         let tmp_79 ← NanoP4Spec.«$int_to_bitstr» fuel (Int.ofNat w) tmp_78
                         let i' := tmp_79
                         pure (NanoP4Spec.integerLiteral.to_value
                            (NanoP4Spec.integerLiteral.W w i'))) <|>
                      ((do
                          let binop := p0
                          let value := p1
                          let value' := p2
                          let _ ← Iter.check (match binop with
                             | NanoP4Spec.binop.caret => true
                             | _ => false)
                          let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
                          let tmp_80 ← NanoP4Spec.value.of_integerLiteral value
                          let integerLiteral := tmp_80
                          let _ ← Iter.check (match integerLiteral with
                             | NanoP4Spec.integerLiteral.S _ _ => true
                             | _ => false)
                          let .S w i_l := integerLiteral | none
                          let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
                          let tmp_81 ← NanoP4Spec.value.of_integerLiteral value'
                          let integerLiteral' := tmp_81
                          let _ ← Iter.check (match integerLiteral' with
                             | NanoP4Spec.integerLiteral.S _ _ => true
                             | _ => false)
                          let .S w' i_r := integerLiteral' | none
                          let _ ← Iter.check (w == w')
                          let tmp_82 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_l
                          let i_l' := tmp_82
                          let tmp_83 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_r
                          let i_r' := tmp_83
                          let tmp_84 ← NanoP4Spec.«$bxor» fuel i_l' i_r'
                          let tmp_85 ← NanoP4Spec.«$int_to_bitstr» fuel (Int.ofNat w) tmp_84
                          let i' := tmp_85
                          pure (NanoP4Spec.integerLiteral.to_value
                             (NanoP4Spec.integerLiteral.S w i'))) <|>
                       ((do
                           let binop := p0
                           let value := p1
                           let value' := p2
                           let _ ← Iter.check (match binop with
                              | NanoP4Spec.binop.bar => true
                              | _ => false)
                           let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
                           let tmp_86 ← NanoP4Spec.value.of_integerLiteral value
                           let integerLiteral := tmp_86
                           let _ ← Iter.check (match integerLiteral with
                              | NanoP4Spec.integerLiteral.W _ _ => true
                              | _ => false)
                           let .W w i_l := integerLiteral | none
                           let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
                           let tmp_87 ← NanoP4Spec.value.of_integerLiteral value'
                           let integerLiteral' := tmp_87
                           let _ ← Iter.check (match integerLiteral' with
                              | NanoP4Spec.integerLiteral.W _ _ => true
                              | _ => false)
                           let .W w' i_r := integerLiteral' | none
                           let _ ← Iter.check (w == w')
                           let tmp_88 ← NanoP4Spec.«$bor» fuel i_l i_r
                           let tmp_89 ← NanoP4Spec.«$int_to_bitstr» fuel (Int.ofNat w) tmp_88
                           let i' := tmp_89
                           pure (NanoP4Spec.integerLiteral.to_value
                              (NanoP4Spec.integerLiteral.W w i'))) <|>
                        ((do
                            let binop := p0
                            let value := p1
                            let value' := p2
                            let _ ← Iter.check (match binop with
                               | NanoP4Spec.binop.bar => true
                               | _ => false)
                            let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value)
                            let tmp_90 ← NanoP4Spec.value.of_integerLiteral value
                            let integerLiteral := tmp_90
                            let _ ← Iter.check (match integerLiteral with
                               | NanoP4Spec.integerLiteral.S _ _ => true
                               | _ => false)
                            let .S w i_l := integerLiteral | none
                            let _ ← Iter.check (NanoP4Spec.value.is_integerLiteral value')
                            let tmp_91 ← NanoP4Spec.value.of_integerLiteral value'
                            let integerLiteral' := tmp_91
                            let _ ← Iter.check (match integerLiteral' with
                               | NanoP4Spec.integerLiteral.S _ _ => true
                               | _ => false)
                            let .S w' i_r := integerLiteral' | none
                            let _ ← Iter.check (w == w')
                            let tmp_92 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_l
                            let i_l' := tmp_92
                            let tmp_93 ← NanoP4Spec.«$bitstr_to_int» fuel (Int.ofNat w) i_r
                            let i_r' := tmp_93
                            let tmp_94 ← NanoP4Spec.«$bor» fuel i_l' i_r'
                            let tmp_95 ← NanoP4Spec.«$int_to_bitstr» fuel (Int.ofNat w) tmp_94
                            let i' := tmp_95
                            pure (NanoP4Spec.integerLiteral.to_value
                               (NanoP4Spec.integerLiteral.S w i'))) <|>
                         ((do
                             let binop := p0
                             let value := p1
                             let value' := p2
                             let _ ← Iter.check (match binop with
                                | NanoP4Spec.binop.ampamp => true
                                | _ => false)
                             let _ ← Iter.check (NanoP4Spec.value.is_boolValue value)
                             let tmp_96 ← NanoP4Spec.value.of_boolValue value
                             let ._B b_l := tmp_96
                             let _ ← Iter.check (NanoP4Spec.value.is_boolValue value')
                             let tmp_97 ← NanoP4Spec.value.of_boolValue value'
                             let ._B b_r := tmp_97
                             pure (NanoP4Spec.boolValue.to_value
                                (NanoP4Spec.boolValue._B (b_l && b_r)))) <|>
                          (do
                             let binop := p0
                             let value := p1
                             let value' := p2
                             let _ ← Iter.check (match binop with
                                | NanoP4Spec.binop.barbar => true
                                | _ => false)
                             let _ ← Iter.check (NanoP4Spec.value.is_boolValue value)
                             let tmp_98 ← NanoP4Spec.value.of_boolValue value
                             let ._B b_l := tmp_98
                             let _ ← Iter.check (NanoP4Spec.value.is_boolValue value')
                             let tmp_99 ← NanoP4Spec.value.of_boolValue value'
                             let ._B b_r := tmp_99
                             pure (NanoP4Spec.boolValue.to_value
                                (NanoP4Spec.boolValue._B (b_l || b_r))))))))))))))))))))))))))))

end NanoP4Spec
