-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, upstream/nano-p4-spec/5.00-typing-context.watsup
import P4SpecTec.Prelude
import P4SpecTec.Tactic.RunSound
import P4SpecTec.Tactic.Audit
import NanoP4Spec.«3.2-bits»

/-! # NanoP4Spec.«5.00-typing-context»

The rendering of `upstream/nano-p4-spec/5.00-typing-context.watsup`.
Generated: every definition here mirrors one definition of that file, in
order, by the encodings of `docs/design.md`.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 1000000

open P4SpecTec P4SpecTec.Prelude

namespace NanoP4Spec

abbrev typeDefEnv : Type := NanoP4Spec.map NanoP4Spec.typeId NanoP4Spec.typeDefIR

def typeDefEnv.toValue (x : NanoP4Spec.typeDefEnv) : Lang.Il.value := ToValue.toValue x

instance : ToValue NanoP4Spec.typeDefEnv := ⟨NanoP4Spec.typeDefEnv.toValue⟩
instance : BEq NanoP4Spec.typeDefEnv := ⟨valueEq⟩

def typeDefEnv.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.typeDefEnv
  | 0, _ => none
  | fuel + 1, v => OfValue.ofValue fuel v

instance : OfValue NanoP4Spec.typeDefEnv := ⟨NanoP4Spec.typeDefEnv.ofValue⟩

inductive callableTypeDef where
  | ACTION (parameterIR : List NanoP4Spec.parameterIR)
  | PARSER (parameterIR : List NanoP4Spec.parameterIR)
  | CONTROL (parameterIR : List NanoP4Spec.parameterIR)

def callableTypeDef.toValue : NanoP4Spec.callableTypeDef → Lang.Il.value
  | .ACTION x0 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "callableTypeDef")
        (.Seq [(.Atom (Prelude.Value.atom (.Keyword "ACTION"))), (.Arg (ToValue.toValue x0))])
  | .PARSER x0 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "callableTypeDef")
        (.Seq [(.Atom (Prelude.Value.atom (.Keyword "PARSER"))), (.Arg (ToValue.toValue x0))])
  | .CONTROL x0 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "callableTypeDef")
        (.Seq [(.Atom (Prelude.Value.atom (.Keyword "CONTROL"))), (.Arg (ToValue.toValue x0))])

instance : ToValue NanoP4Spec.callableTypeDef := ⟨NanoP4Spec.callableTypeDef.toValue⟩
instance : BEq NanoP4Spec.callableTypeDef := ⟨valueEq⟩

def callableTypeDef.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.callableTypeDef
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0] :=
             Prelude.Value.caseArgs
               c
               (.Seq [(.Atom (Prelude.Value.atom (.Keyword "ACTION"))), (.Arg ())]) | none
         pure (NanoP4Spec.callableTypeDef.ACTION (← OfValue.ofValue fuel a0))) <|>
      ((do
          let some [a0] :=
              Prelude.Value.caseArgs
                c
                (.Seq [(.Atom (Prelude.Value.atom (.Keyword "PARSER"))), (.Arg ())]) | none
          pure (NanoP4Spec.callableTypeDef.PARSER (← OfValue.ofValue fuel a0))) <|>
       (do
          let some [a0] :=
              Prelude.Value.caseArgs
                c
                (.Seq [(.Atom (Prelude.Value.atom (.Keyword "CONTROL"))), (.Arg ())]) | none
          pure (NanoP4Spec.callableTypeDef.CONTROL (← OfValue.ofValue fuel a0))))
    | _ => none

instance : OfValue NanoP4Spec.callableTypeDef := ⟨NanoP4Spec.callableTypeDef.ofValue⟩

abbrev callableTypeDefEnv : Type := NanoP4Spec.map NanoP4Spec.callableId NanoP4Spec.callableTypeDef

def callableTypeDefEnv.toValue (x : NanoP4Spec.callableTypeDefEnv) : Lang.Il.value :=
  ToValue.toValue x

instance : ToValue NanoP4Spec.callableTypeDefEnv := ⟨NanoP4Spec.callableTypeDefEnv.toValue⟩
instance : BEq NanoP4Spec.callableTypeDefEnv := ⟨valueEq⟩

def callableTypeDefEnv.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.callableTypeDefEnv
  | 0, _ => none
  | fuel + 1, v => OfValue.ofValue fuel v

instance : OfValue NanoP4Spec.callableTypeDefEnv := ⟨NanoP4Spec.callableTypeDefEnv.ofValue⟩

inductive varTypeIR where
  | mk (direction : NanoP4Spec.direction) (typeIR : NanoP4Spec.typeIR)

def varTypeIR.toValue : NanoP4Spec.varTypeIR → Lang.Il.value
  | .mk x0 x1 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "varTypeIR")
        (.Seq [(.Arg (ToValue.toValue x0)), (.Arg (ToValue.toValue x1))])

instance : ToValue NanoP4Spec.varTypeIR := ⟨NanoP4Spec.varTypeIR.toValue⟩
instance : BEq NanoP4Spec.varTypeIR := ⟨valueEq⟩

def varTypeIR.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.varTypeIR
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0, a1] := Prelude.Value.caseArgs c (.Seq [(.Arg ()), (.Arg ())]) | none
         pure (NanoP4Spec.varTypeIR.mk (← OfValue.ofValue fuel a0) (← OfValue.ofValue fuel a1)))
    | _ => none

instance : OfValue NanoP4Spec.varTypeIR := ⟨NanoP4Spec.varTypeIR.ofValue⟩

abbrev typeFrame : Type := NanoP4Spec.map NanoP4Spec.id NanoP4Spec.varTypeIR

def typeFrame.toValue (x : NanoP4Spec.typeFrame) : Lang.Il.value := ToValue.toValue x

instance : ToValue NanoP4Spec.typeFrame := ⟨NanoP4Spec.typeFrame.toValue⟩
instance : BEq NanoP4Spec.typeFrame := ⟨valueEq⟩

def typeFrame.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.typeFrame
  | 0, _ => none
  | fuel + 1, v => OfValue.ofValue fuel v

instance : OfValue NanoP4Spec.typeFrame := ⟨NanoP4Spec.typeFrame.ofValue⟩

structure globalTypingLayer where
  TYPE : NanoP4Spec.typeDefEnv
  CALLABLE : NanoP4Spec.callableTypeDefEnv
  FRAME : NanoP4Spec.typeFrame

def globalTypingLayer.toValue : NanoP4Spec.globalTypingLayer → Lang.Il.value
  | ⟨x0, x1, x2⟩ =>
      Runtime.Value.Make.str
        (Prelude.Value.varT "globalTypingLayer")
        [("TYPE", ToValue.toValue x0),
         ("CALLABLE", ToValue.toValue x1),
         ("FRAME", ToValue.toValue x2)]

instance : ToValue NanoP4Spec.globalTypingLayer := ⟨NanoP4Spec.globalTypingLayer.toValue⟩
instance : BEq NanoP4Spec.globalTypingLayer := ⟨valueEq⟩

def globalTypingLayer.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.globalTypingLayer
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .StructV [(_, f0), (_, f1), (_, f2)] =>
      (do
         pure ⟨(← OfValue.ofValue
           fuel
           f0), (← OfValue.ofValue fuel f1), (← OfValue.ofValue fuel f2)⟩)
    | _ => none

instance : OfValue NanoP4Spec.globalTypingLayer := ⟨NanoP4Spec.globalTypingLayer.ofValue⟩

structure blockTypingLayer where
  FRAME : NanoP4Spec.typeFrame

def blockTypingLayer.toValue : NanoP4Spec.blockTypingLayer → Lang.Il.value
  | ⟨x0⟩ =>
      Runtime.Value.Make.str (Prelude.Value.varT "blockTypingLayer") [("FRAME", ToValue.toValue x0)]

instance : ToValue NanoP4Spec.blockTypingLayer := ⟨NanoP4Spec.blockTypingLayer.toValue⟩
instance : BEq NanoP4Spec.blockTypingLayer := ⟨valueEq⟩

def blockTypingLayer.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.blockTypingLayer
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .StructV [(_, f0)] =>
      (do
         pure ⟨(← OfValue.ofValue fuel f0)⟩)
    | _ => none

instance : OfValue NanoP4Spec.blockTypingLayer := ⟨NanoP4Spec.blockTypingLayer.ofValue⟩

structure localTypingLayer where
  FRAMES : List NanoP4Spec.typeFrame

def localTypingLayer.toValue : NanoP4Spec.localTypingLayer → Lang.Il.value
  | ⟨x0⟩ =>
      Runtime.Value.Make.str
        (Prelude.Value.varT "localTypingLayer")
        [("FRAMES", ToValue.toValue x0)]

instance : ToValue NanoP4Spec.localTypingLayer := ⟨NanoP4Spec.localTypingLayer.toValue⟩
instance : BEq NanoP4Spec.localTypingLayer := ⟨valueEq⟩

def localTypingLayer.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.localTypingLayer
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .StructV [(_, f0)] =>
      (do
         pure ⟨(← OfValue.ofValue fuel f0)⟩)
    | _ => none

instance : OfValue NanoP4Spec.localTypingLayer := ⟨NanoP4Spec.localTypingLayer.ofValue⟩

structure typingContext where
  GLOBAL : NanoP4Spec.globalTypingLayer
  BLOCK : NanoP4Spec.blockTypingLayer
  LOCAL : NanoP4Spec.localTypingLayer

def typingContext.toValue : NanoP4Spec.typingContext → Lang.Il.value
  | ⟨x0, x1, x2⟩ =>
      Runtime.Value.Make.str
        (Prelude.Value.varT "typingContext")
        [("GLOBAL", ToValue.toValue x0),
         ("BLOCK", ToValue.toValue x1),
         ("LOCAL", ToValue.toValue x2)]

instance : ToValue NanoP4Spec.typingContext := ⟨NanoP4Spec.typingContext.toValue⟩
instance : BEq NanoP4Spec.typingContext := ⟨valueEq⟩

def typingContext.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.typingContext
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .StructV [(_, f0), (_, f1), (_, f2)] =>
      (do
         pure ⟨(← OfValue.ofValue
           fuel
           f0), (← OfValue.ofValue fuel f1), (← OfValue.ofValue fuel f2)⟩)
    | _ => none

instance : OfValue NanoP4Spec.typingContext := ⟨NanoP4Spec.typingContext.ofValue⟩

inductive matchKey where
  | colon (typeIR : NanoP4Spec.typeIR) (nameIR : NanoP4Spec.nameIR)

def matchKey.toValue : NanoP4Spec.matchKey → Lang.Il.value
  | .colon x0 x1 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "matchKey")
        (.Seq
           [(.Arg (ToValue.toValue x0)),
            (.Atom (Prelude.Value.atom (.Operator ":"))),
            (.Arg (ToValue.toValue x1))])

instance : ToValue NanoP4Spec.matchKey := ⟨NanoP4Spec.matchKey.toValue⟩
instance : BEq NanoP4Spec.matchKey := ⟨valueEq⟩

def matchKey.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.matchKey
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0, a1] :=
             Prelude.Value.caseArgs
               c
               (.Seq [(.Arg ()), (.Atom (Prelude.Value.atom (.Operator ":"))), (.Arg ())]) | none
         pure (NanoP4Spec.matchKey.colon (← OfValue.ofValue fuel a0) (← OfValue.ofValue fuel a1)))
    | _ => none

instance : OfValue NanoP4Spec.matchKey := ⟨NanoP4Spec.matchKey.ofValue⟩

inductive matchAction where
  | lparen_at_rparen
      (callableId : NanoP4Spec.callableId)
      (parameterIR : List NanoP4Spec.parameterIR)
      (argumentIR : List NanoP4Spec.argumentIR)

def matchAction.toValue : NanoP4Spec.matchAction → Lang.Il.value
  | .lparen_at_rparen x0 x1 x2 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "matchAction")
        (.Seq
           [(.Arg (ToValue.toValue x0)),
            (.Brack
               (Prelude.Value.atom .LParen)
               (.Seq
                  [(.Arg (ToValue.toValue x1)),
                   (.Atom (Prelude.Value.atom (.Operator "@"))),
                   (.Arg (ToValue.toValue x2))])
               (Prelude.Value.atom .RParen))])

instance : ToValue NanoP4Spec.matchAction := ⟨NanoP4Spec.matchAction.toValue⟩
instance : BEq NanoP4Spec.matchAction := ⟨valueEq⟩

def matchAction.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.matchAction
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0, a1, a2] :=
             Prelude.Value.caseArgs
               c
               (.Seq
                  [(.Arg ()),
                   (.Brack
                      (Prelude.Value.atom .LParen)
                      (.Seq [(.Arg ()), (.Atom (Prelude.Value.atom (.Operator "@"))), (.Arg ())])
                      (Prelude.Value.atom .RParen))]) | none
         pure (NanoP4Spec.matchAction.lparen_at_rparen
            (← OfValue.ofValue fuel a0)
            (← OfValue.ofValue fuel a1)
            (← OfValue.ofValue fuel a2)))
    | _ => none

instance : OfValue NanoP4Spec.matchAction := ⟨NanoP4Spec.matchAction.ofValue⟩

structure tableContext where
  KEY : NanoP4Spec.matchKey
  ACTIONS : List NanoP4Spec.matchAction

def tableContext.toValue : NanoP4Spec.tableContext → Lang.Il.value
  | ⟨x0, x1⟩ =>
      Runtime.Value.Make.str
        (Prelude.Value.varT "tableContext")
        [("KEY", ToValue.toValue x0), ("ACTIONS", ToValue.toValue x1)]

instance : ToValue NanoP4Spec.tableContext := ⟨NanoP4Spec.tableContext.toValue⟩
instance : BEq NanoP4Spec.tableContext := ⟨valueEq⟩

def tableContext.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.tableContext
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .StructV [(_, f0), (_, f1)] =>
      (do
         pure ⟨(← OfValue.ofValue fuel f0), (← OfValue.ofValue fuel f1)⟩)
    | _ => none

instance : OfValue NanoP4Spec.tableContext := ⟨NanoP4Spec.tableContext.ofValue⟩

def «$empty_typeDefEnv»
    : Option (Except Fail (NanoP4Spec.map NanoP4Spec.typeId NanoP4Spec.typeDefIR)) :=
  ExceptT.run
    (do
       let tmp_0 ←
           ExceptT.mk
             (NanoP4Spec.«$empty_map» (τK := NanoP4Spec.typeId) (τV := NanoP4Spec.typeDefIR))
       pure tmp_0)

def «$params_of_callableTypeDef» (p0 : NanoP4Spec.callableTypeDef)
    : Option (Except Fail (List NanoP4Spec.parameterIR)) :=
  ExceptT.run
    ((do
        have callableTypeDef := p0
        let _ ← Eval.check (match callableTypeDef with
           | NanoP4Spec.callableTypeDef.ACTION _ => true
           | _ => false)
        let .ACTION «parameterIR*» := callableTypeDef | throw Fail.err
        pure «parameterIR*») <|>
     ((do
         have callableTypeDef := p0
         let _ ← Eval.check (match callableTypeDef with
            | NanoP4Spec.callableTypeDef.PARSER _ => true
            | _ => false)
         let .PARSER «parameterIR*» := callableTypeDef | throw Fail.err
         pure «parameterIR*») <|>
      (do
         have callableTypeDef := p0
         let _ ← Eval.check (match callableTypeDef with
            | NanoP4Spec.callableTypeDef.CONTROL _ => true
            | _ => false)
         let .CONTROL «parameterIR*» := callableTypeDef | throw Fail.err
         pure «parameterIR*»)))

def «$empty_callableTypeDefEnv»
    : Option (Except Fail (NanoP4Spec.map NanoP4Spec.callableId NanoP4Spec.callableTypeDef)) :=
  ExceptT.run
    (do
       let tmp_0 ←
           ExceptT.mk
             (NanoP4Spec.«$empty_map»
                (τK := NanoP4Spec.callableId)
                (τV := NanoP4Spec.callableTypeDef))
       pure tmp_0)

def «$empty_typeFrame» : Option (Except Fail (NanoP4Spec.map NanoP4Spec.id NanoP4Spec.varTypeIR)) :=
  ExceptT.run
    (do
       let tmp_0 ←
           ExceptT.mk (NanoP4Spec.«$empty_map» (τK := NanoP4Spec.id) (τV := NanoP4Spec.varTypeIR))
       pure tmp_0)

def «$empty_typingContext» : Option (Except Fail NanoP4Spec.typingContext) :=
  ExceptT.run
    (do
       let tmp_0 ← ExceptT.mk NanoP4Spec.«$empty_typeDefEnv»
       let tmp_1 ← ExceptT.mk NanoP4Spec.«$empty_callableTypeDefEnv»
       let tmp_2 ← ExceptT.mk NanoP4Spec.«$empty_typeFrame»
       have globalTypingLayer :=
           ({
              TYPE := tmp_0,
              CALLABLE := tmp_1,
              FRAME := tmp_2, } : NanoP4Spec.globalTypingLayer)
       let tmp_3 ← ExceptT.mk NanoP4Spec.«$empty_typeFrame»
       have blockTypingLayer :=
           ({
              FRAME := tmp_3, } : NanoP4Spec.blockTypingLayer)
       let tmp_4 ← ExceptT.mk NanoP4Spec.«$empty_typeFrame»
       have localTypingLayer :=
           ({
              FRAMES := [tmp_4], } : NanoP4Spec.localTypingLayer)
       have TC :=
           ({
              GLOBAL := globalTypingLayer,
              BLOCK := blockTypingLayer,
              LOCAL := localTypingLayer, } : NanoP4Spec.typingContext)
       pure TC)

def «$enter_t» (p0 : NanoP4Spec.typingContext) : Option (Except Fail NanoP4Spec.typingContext) :=
  ExceptT.run
    (do
       have TC := p0
       let tmp_0 ← ExceptT.mk NanoP4Spec.«$empty_typeFrame»
       pure { TC with
         LOCAL.FRAMES := tmp_0 :: TC.LOCAL.FRAMES, })

def «$exit_t» (p0 : NanoP4Spec.typingContext) : Option (Except Fail NanoP4Spec.typingContext) :=
  ExceptT.run
    (do
       have TC := p0
       have «typeFrame*» := TC.LOCAL.FRAMES
       let _ ← Eval.check (!(List.isEmpty «typeFrame*»))
       let typeFrame_h :: «typeFrame_t*» := «typeFrame*» | throw Fail.err
       pure { TC with
         LOCAL.FRAMES := «typeFrame_t*», })

def «$add_var_t»
        (p0 : NanoP4Spec.scope)
        (p1 : NanoP4Spec.typingContext)
        (p2 : NanoP4Spec.id)
        (p3 : NanoP4Spec.varTypeIR)
    : Option (Except Fail NanoP4Spec.typingContext) :=
  ExceptT.run
    ((do
        have scope := p0
        have TC := p1
        have id := p2
        have varTypeIR := p3
        let _ ← Eval.check (match scope with
           | NanoP4Spec.scope.GLOBAL => true
           | _ => false)
        have typeFrame := TC.GLOBAL.FRAME
        let tmp_0 ←
            ExceptT.mk
              (NanoP4Spec.«$dom_map» (τK := NanoP4Spec.id) (τV := NanoP4Spec.varTypeIR) typeFrame)
        let tmp_1 ← ExceptT.mk (NanoP4Spec.«$in_set» (τK := NanoP4Spec.id) tmp_0 id)
        let _ ← Eval.check (!tmp_1)
        let tmp_2 ←
            ExceptT.mk
              (NanoP4Spec.«$add_map»
                 (τK := NanoP4Spec.id)
                 (τV := NanoP4Spec.varTypeIR)
                 typeFrame
                 id
                 varTypeIR)
        have typeFrame' := tmp_2
        have TC' :=
            { TC with
              GLOBAL.FRAME := typeFrame', }
        pure TC') <|>
     ((do
         have scope := p0
         have TC := p1
         have id := p2
         have varTypeIR := p3
         let _ ← Eval.check (match scope with
            | NanoP4Spec.scope.BLOCK => true
            | _ => false)
         have typeFrame := TC.BLOCK.FRAME
         let tmp_3 ←
             ExceptT.mk
               (NanoP4Spec.«$dom_map» (τK := NanoP4Spec.id) (τV := NanoP4Spec.varTypeIR) typeFrame)
         let tmp_4 ← ExceptT.mk (NanoP4Spec.«$in_set» (τK := NanoP4Spec.id) tmp_3 id)
         let _ ← Eval.check (!tmp_4)
         let tmp_5 ←
             ExceptT.mk
               (NanoP4Spec.«$add_map»
                  (τK := NanoP4Spec.id)
                  (τV := NanoP4Spec.varTypeIR)
                  typeFrame
                  id
                  varTypeIR)
         have typeFrame' := tmp_5
         have TC' :=
             { TC with
               BLOCK.FRAME := typeFrame', }
         pure TC') <|>
      (do
         have scope := p0
         have TC := p1
         have id := p2
         have varTypeIR := p3
         let _ ← Eval.check (match scope with
            | NanoP4Spec.scope.LOCAL => true
            | _ => false)
         have «typeFrame*» := TC.LOCAL.FRAMES
         let _ ← Eval.check (!(List.isEmpty «typeFrame*»))
         let typeFrame_h :: «typeFrame_t*» := «typeFrame*» | throw Fail.err
         let tmp_6 ←
             ExceptT.mk
               (NanoP4Spec.«$dom_map»
                  (τK := NanoP4Spec.id)
                  (τV := NanoP4Spec.varTypeIR)
                  typeFrame_h)
         let tmp_7 ← ExceptT.mk (NanoP4Spec.«$in_set» (τK := NanoP4Spec.id) tmp_6 id)
         let _ ← Eval.check (!tmp_7)
         let tmp_8 ←
             ExceptT.mk
               (NanoP4Spec.«$add_map»
                  (τK := NanoP4Spec.id)
                  (τV := NanoP4Spec.varTypeIR)
                  typeFrame_h
                  id
                  varTypeIR)
         have typeFrame_h' := tmp_8
         have TC' :=
             { TC with
               LOCAL.FRAMES := typeFrame_h' :: «typeFrame_t*», }
         pure TC')))

def «$add_vars_t»
        (p0 : NanoP4Spec.scope)
        (p1 : NanoP4Spec.typingContext)
        (p2 : List NanoP4Spec.id)
        (p3 : List NanoP4Spec.varTypeIR)
    : Option (Except Fail NanoP4Spec.typingContext) :=
  ExceptT.run
    ((do
        have scope := p0
        have TC := p1
        have «id*» := p2
        have «varTypeIR*» := p3
        let _ ← Eval.check (List.isEmpty «id*»)
        let _ ← Eval.check (List.isEmpty «varTypeIR*»)
        pure TC) <|>
     (do
        have scope := p0
        have TC := p1
        have «id*» := p2
        have «varTypeIR*» := p3
        let _ ← Eval.check (!(List.isEmpty «id*»))
        let id_h :: «id_t*» := «id*» | throw Fail.err
        let _ ← Eval.check (!(List.isEmpty «varTypeIR*»))
        let varTypeIR_h :: «varTypeIR_t*» := «varTypeIR*» | throw Fail.err
        let tmp_0 ← ExceptT.mk (NanoP4Spec.«$add_var_t» scope TC id_h varTypeIR_h)
        have TC' := tmp_0
        let tmp_1 ← ExceptT.mk (NanoP4Spec.«$add_vars_t» scope TC' «id_t*» «varTypeIR_t*»)
        have TC'' := tmp_1
        pure TC''))
  partial_fixpoint

def «$add_callableDef_t»
        (p0 : NanoP4Spec.typingContext)
        (p1 : NanoP4Spec.callableId)
        (p2 : NanoP4Spec.callableTypeDef)
    : Option (Except Fail NanoP4Spec.typingContext) :=
  ExceptT.run
    (do
       have TC := p0
       have callableId := p1
       have callableTypeDef := p2
       have callableTypeDefEnv := TC.GLOBAL.CALLABLE
       let tmp_0 ←
           ExceptT.mk
             (NanoP4Spec.«$dom_map»
                (τK := NanoP4Spec.callableId)
                (τV := NanoP4Spec.callableTypeDef)
                callableTypeDefEnv)
       let tmp_1 ← ExceptT.mk (NanoP4Spec.«$in_set» (τK := NanoP4Spec.callableId) tmp_0 callableId)
       let _ ← Eval.check (!tmp_1)
       let tmp_2 ←
           ExceptT.mk
             (NanoP4Spec.«$add_map»
                (τK := NanoP4Spec.callableId)
                (τV := NanoP4Spec.callableTypeDef)
                callableTypeDefEnv
                callableId
                callableTypeDef)
       have callableTypeDefEnv' := tmp_2
       have TC' :=
           { TC with
             GLOBAL.CALLABLE := callableTypeDefEnv', }
       pure TC')

def «$add_typeDef_t»
        (p0 : NanoP4Spec.typingContext)
        (p1 : NanoP4Spec.typeId)
        (p2 : NanoP4Spec.typeDefIR)
    : Option (Except Fail NanoP4Spec.typingContext) :=
  ExceptT.run
    (do
       have TC := p0
       have typeId := p1
       have typeDefIR := p2
       have typeDefEnv := TC.GLOBAL.TYPE
       let tmp_0 ←
           ExceptT.mk
             (NanoP4Spec.«$dom_map»
                (τK := NanoP4Spec.typeId)
                (τV := NanoP4Spec.typeDefIR)
                typeDefEnv)
       let tmp_1 ← ExceptT.mk (NanoP4Spec.«$in_set» (τK := NanoP4Spec.typeId) tmp_0 typeId)
       let _ ← Eval.check (!tmp_1)
       let tmp_2 ←
           ExceptT.mk
             (NanoP4Spec.«$add_map»
                (τK := NanoP4Spec.typeId)
                (τV := NanoP4Spec.typeDefIR)
                typeDefEnv
                typeId
                typeDefIR)
       have typeDefEnv' := tmp_2
       have TC' :=
           { TC with
             GLOBAL.TYPE := typeDefEnv', }
       pure TC')

def «$find_var_t» (p0 : NanoP4Spec.scope) (p1 : NanoP4Spec.typingContext) (p2 : NanoP4Spec.id)
    : Option (Except Fail NanoP4Spec.varTypeIR) :=
  ExceptT.run
    ((do
        have scope := p0
        have TC := p1
        have id := p2
        let _ ← Eval.check (match scope with
           | NanoP4Spec.scope.GLOBAL => true
           | _ => false)
        have typeFrame := TC.GLOBAL.FRAME
        let tmp_0 ←
            ExceptT.mk
              (NanoP4Spec.«$find_map»
                 (τK := NanoP4Spec.id)
                 (τV := NanoP4Spec.varTypeIR)
                 typeFrame
                 id)
        have varTypeIR'? := tmp_0
        let _ ← Eval.check (Option.isSome varTypeIR'?)
        let some varTypeIR := varTypeIR'? | throw Fail.err
        pure varTypeIR) <|>
     ((do
         have scope := p0
         have TC := p1
         have id := p2
         let _ ← Eval.check (match scope with
            | NanoP4Spec.scope.BLOCK => true
            | _ => false)
         have typeFrame := TC.BLOCK.FRAME
         let tmp_1 ←
             ExceptT.mk
               (NanoP4Spec.«$find_map»
                  (τK := NanoP4Spec.id)
                  (τV := NanoP4Spec.varTypeIR)
                  typeFrame
                  id)
         have varTypeIR'? := tmp_1
         let _ ← Eval.check (Option.isSome varTypeIR'?)
         let some varTypeIR := varTypeIR'? | throw Fail.err
         pure varTypeIR) <|>
      ((do
          have scope := p0
          have TC := p1
          have id := p2
          let _ ← Eval.check (match scope with
             | NanoP4Spec.scope.BLOCK => true
             | _ => false)
          have typeFrame := TC.BLOCK.FRAME
          let tmp_2 ←
              ExceptT.mk
                (NanoP4Spec.«$find_map»
                   (τK := NanoP4Spec.id)
                   (τV := NanoP4Spec.varTypeIR)
                   typeFrame
                   id)
          let _ ← Eval.check ((none : Option NanoP4Spec.varTypeIR) == tmp_2)
          let tmp_3 ← ExceptT.mk (NanoP4Spec.«$find_var_t» NanoP4Spec.scope.GLOBAL TC id)
          pure tmp_3) <|>
       ((do
           have scope := p0
           have TC := p1
           have id := p2
           let _ ← Eval.check (match scope with
              | NanoP4Spec.scope.LOCAL => true
              | _ => false)
           have «typeFrame*» := TC.LOCAL.FRAMES
           let tmp_4 ←
               ExceptT.mk
                 (NanoP4Spec.«$find_maps»
                    (τK := NanoP4Spec.id)
                    (τV := NanoP4Spec.varTypeIR)
                    «typeFrame*»
                    id)
           have varTypeIR'? := tmp_4
           let _ ← Eval.check (Option.isSome varTypeIR'?)
           let some varTypeIR := varTypeIR'? | throw Fail.err
           pure varTypeIR) <|>
        (do
           have scope := p0
           have TC := p1
           have id := p2
           let _ ← Eval.check (match scope with
              | NanoP4Spec.scope.LOCAL => true
              | _ => false)
           have «typeFrame*» := TC.LOCAL.FRAMES
           let tmp_5 ←
               ExceptT.mk
                 (NanoP4Spec.«$find_maps»
                    (τK := NanoP4Spec.id)
                    (τV := NanoP4Spec.varTypeIR)
                    «typeFrame*»
                    id)
           let _ ← Eval.check ((none : Option NanoP4Spec.varTypeIR) == tmp_5)
           let tmp_6 ← ExceptT.mk (NanoP4Spec.«$find_var_t» NanoP4Spec.scope.BLOCK TC id)
           pure tmp_6)))))
  partial_fixpoint

def «$find_typeDef_t» (p0 : NanoP4Spec.typingContext) (p1 : NanoP4Spec.typeId)
    : Option (Except Fail NanoP4Spec.typeDefIR) :=
  ExceptT.run
    (do
       have TC := p0
       have typeId := p1
       let tmp_0 ←
           ExceptT.mk
             (NanoP4Spec.«$find_map»
                (τK := NanoP4Spec.typeId)
                (τV := NanoP4Spec.typeDefIR)
                TC.GLOBAL.TYPE
                typeId)
       have typeDefIR'? := tmp_0
       let _ ← Eval.check (Option.isSome typeDefIR'?)
       let some typeDefIR := typeDefIR'? | throw Fail.err
       pure typeDefIR)

def «$find_callableTypeDef_t» (p0 : NanoP4Spec.typingContext) (p1 : NanoP4Spec.callableId)
    : Option (Except Fail NanoP4Spec.callableTypeDef) :=
  ExceptT.run
    (do
       have TC := p0
       have callableId := p1
       let tmp_0 ←
           ExceptT.mk
             (NanoP4Spec.«$find_map»
                (τK := NanoP4Spec.callableId)
                (τV := NanoP4Spec.callableTypeDef)
                TC.GLOBAL.CALLABLE
                callableId)
       have callableTypeDef'? := tmp_0
       let _ ← Eval.check (Option.isSome callableTypeDef'?)
       let some callableTypeDef := callableTypeDef'? | throw Fail.err
       pure callableTypeDef)

def «$typeIR_of_typeDefIR» (p0 : NanoP4Spec.typeDefIR) : Option (Except Fail NanoP4Spec.typeIR) :=
  ExceptT.run
    ((do
        have typeDefIR := p0
        let _ ← Eval.check (NanoP4Spec.typeDefIR.is_dataTypeIR typeDefIR)
        let tmp_0 ← Eval.err? (NanoP4Spec.typeDefIR.of_dataTypeIR typeDefIR)
        have dataTypeIR := tmp_0
        pure (NanoP4Spec.dataTypeIR.to_typeIR dataTypeIR)) <|>
     (do
        have typeDefIR := p0
        let _ ← Eval.check (NanoP4Spec.typeDefIR.is_objectTypeDefIR typeDefIR)
        let tmp_1 ← Eval.err? (NanoP4Spec.typeDefIR.of_objectTypeDefIR typeDefIR)
        have objectTypeDefIR := tmp_1
        pure (NanoP4Spec.objectTypeDefIR.to_typeIR objectTypeDefIR)))

end NanoP4Spec
