-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, upstream/nano-p4-spec/5.06-typing-parameter.watsup
import P4SpecTec.Prelude
import NanoP4Spec.«5.04-typing-lvalue»

/-! # NanoP4Spec.«5.06-typing-parameter»

The rendering of `upstream/nano-p4-spec/5.06-typing-parameter.watsup`.
Generated: every definition here mirrors one definition of that file, in
order, by the encodings of `docs/design.md`.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 1000000

open P4SpecTec P4SpecTec.Prelude

namespace NanoP4Spec

def Parameter_ok.run
    (fuel : Nat)
    (p0 : NanoP4Spec.scope)
    (p1 : NanoP4Spec.typingContext)
    (p2 : NanoP4Spec.parameter) : Option (NanoP4Spec.parameterIR × NanoP4Spec.typingContext) :=
  (do
     let scope := p0
     let TC_0 := p1
     let .mk direction type name := p2
     (do
        let tmp_0 ← NanoP4Spec.Type_ok.run fuel TC_0 type
        let typeIR := tmp_0
        let tmp_1 ← NanoP4Spec.«$id» fuel name
        let nameIR := tmp_1
        let parameterIR := NanoP4Spec.parameterIR.mk direction typeIR nameIR
        let varTypeIR := NanoP4Spec.varTypeIR.mk direction typeIR
        let tmp_2 ← NanoP4Spec.«$add_var_t» fuel scope TC_0 nameIR varTypeIR
        let TC_1 := tmp_2
        pure (parameterIR, TC_1)))

def Parameters_ok.run
    (fuel : Nat)
    (p0 : NanoP4Spec.scope)
    (p1 : NanoP4Spec.typingContext)
    (p2 : List
       NanoP4Spec.parameter) : Option ((List NanoP4Spec.parameterIR) × NanoP4Spec.typingContext) :=
  match fuel with
    | 0 => none
    | fuel + 1 =>
      (do
         let scope := p0
         let TC' := p1
         let «parameter*» := p2
         (do
            let TC := TC'
            let _ ← Iter.check («parameter*» == ([] : List NanoP4Spec.parameter))
            pure (([] : List NanoP4Spec.parameterIR), TC)) <|>
         (do
            let TC_0 := TC'
            let «parameter'*» := «parameter*»
            let _ ← Iter.check (!(List.isEmpty «parameter'*»))
            let parameter_h :: «parameter_t*» := «parameter'*» | none
            let tmp_0 ← NanoP4Spec.Parameter_ok.run fuel scope TC_0 parameter_h
            let (parameterIR_h, TC_1) := tmp_0
            let tmp_1 ← NanoP4Spec.Parameters_ok.run fuel scope TC_1 «parameter_t*»
            let («parameterIR_t*», TC_2) := tmp_1
            pure (parameterIR_h :: «parameterIR_t*», TC_2)))

def «$distinct_params» (fuel : Nat) (p0 : List NanoP4Spec.parameterIR) : Option Bool :=
  (do
     let «parameterIR*» := p0
     let tmp_0 ←
         List.mapM
           (fun (parameterIR : NanoP4Spec.parameterIR) =>
              (do
                 let .mk _direction _typeIR nameIR := parameterIR
                 pure (_direction, _typeIR, nameIR)))
           «parameterIR*»
     let «_direction*» := List.map (·.1) tmp_0
     let «_typeIR*» := List.map (·.2.1) tmp_0
     let «nameIR*» := List.map (·.2.2) tmp_0
     let tmp_1 ← NanoP4Spec.«$distinct_» (τK := NanoP4Spec.nameIR) fuel «nameIR*»
     pure tmp_1)

def ParameterList_ok.run
    (fuel : Nat)
    (p0 : NanoP4Spec.scope)
    (p1 : NanoP4Spec.typingContext)
    (p2 : NanoP4Spec.parameterList) : Option ((List NanoP4Spec.parameterIR) ×
 NanoP4Spec.typingContext) :=
  (do
     let scope := p0
     let TC_0 := p1
     let parameterList := p2
     (do
        let tmp_0 ← NanoP4Spec.«$flatten_parameterList» fuel parameterList
        let «parameter*» := tmp_0
        let tmp_1 ← NanoP4Spec.Parameters_ok.run fuel scope TC_0 «parameter*»
        let («parameterIR*», TC_1) := tmp_1
        let tmp_2 ← NanoP4Spec.«$distinct_params» fuel «parameterIR*»
        let _ ← Iter.check tmp_2
        pure («parameterIR*», TC_1)))

def ExternMethod_ok.run
    (fuel : Nat)
    (p0 : NanoP4Spec.typingContext)
    (p1 : NanoP4Spec.externMethodPrototype) : Option NanoP4Spec.externMethodTypeDefIR :=
  (do
     let TC := p0
     let .semi functionPrototype := p1
     (do
        let .VOID_lparen_rparen name parameterList := functionPrototype
        let tmp_0 ← NanoP4Spec.ParameterList_ok.run fuel NanoP4Spec.scope.LOCAL TC parameterList
        let («parameterIR*», TC_body) := tmp_0
        let tmp_1 ← NanoP4Spec.«$id» fuel name
        let callableId := tmp_1
        let externMethodTypeDefIR :=
            NanoP4Spec.externMethodTypeDefIR.VOID_lparen_rparen callableId «parameterIR*»
        pure externMethodTypeDefIR))

def «$is_object_typeIR» (fuel : Nat) (p0 : NanoP4Spec.typeIR) : Option Bool :=
  (do
     let typeIR := p0
     let _ ← Iter.check (NanoP4Spec.typeIR.is_parserObjectTypeIR typeIR)
     let tmp_0 ← NanoP4Spec.typeIR.of_parserObjectTypeIR typeIR
     let parserObjectTypeIR := tmp_0
     pure true) <|>
  ((do
      let typeIR := p0
      let _ ← Iter.check (NanoP4Spec.typeIR.is_controlObjectTypeIR typeIR)
      let tmp_1 ← NanoP4Spec.typeIR.of_controlObjectTypeIR typeIR
      let controlObjectTypeIR := tmp_1
      pure true) <|>
   ((do
       let typeIR := p0
       let _ ← Iter.check (NanoP4Spec.typeIR.is_packageObjectTypeIR typeIR)
       let tmp_2 ← NanoP4Spec.typeIR.of_packageObjectTypeIR typeIR
       let packageObjectTypeIR := tmp_2
       pure true) <|>
    (do
       let typeIR := p0
       pure false)))

def «$no_object_params» (fuel : Nat) (p0 : List NanoP4Spec.parameterIR) : Option Bool :=
  match fuel with
    | 0 => none
    | fuel + 1 =>
      (do
         let «parameterIR*» := p0
         let _ ← Iter.check (List.isEmpty «parameterIR*»)
         pure true) <|>
      (do
         let «parameterIR*» := p0
         let _ ← Iter.check (!(List.isEmpty «parameterIR*»))
         let tmp_0 :: «parameterIR_t*» := «parameterIR*» | none
         let .mk direction typeIR nameIR := tmp_0
         let tmp_1 ← NanoP4Spec.«$is_object_typeIR» fuel typeIR
         let _ ← Iter.check (!tmp_1)
         let tmp_2 ← NanoP4Spec.«$no_object_params» fuel «parameterIR_t*»
         pure tmp_2)

end NanoP4Spec
