-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, upstream/nano-p4-spec/5.07-typing-argument.watsup
import P4SpecTec.Prelude
import NanoP4Spec.«5.06-typing-parameter»

/-! # NanoP4Spec.«5.07-typing-argument»

The rendering of `upstream/nano-p4-spec/5.07-typing-argument.watsup`.
Generated: every definition here mirrors one definition of that file, in
order, by the encodings of `docs/design.md`.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 1000000

open P4SpecTec P4SpecTec.Prelude
open P4SpecTec.IL (value)

namespace NanoP4Spec

def Argument_ok.run
    (fuel : Nat)
    (p0 : NanoP4Spec.scope)
    (p1 : NanoP4Spec.typingContext)
    (p2 : NanoP4Spec.argument) : Option NanoP4Spec.argumentIR :=
  (do
     let scope := p0
     let TC := p1
     let expression := p2
     (do
        let tmp_0 ← NanoP4Spec.Expr_ok.run fuel scope TC expression
        let typeIR := tmp_0
        let argumentIR := NanoP4Spec.argumentIR.hash expression typeIR
        pure argumentIR))

def ArgumentList_ok.run
    (fuel : Nat)
    (p0 : NanoP4Spec.scope)
    (p1 : NanoP4Spec.typingContext)
    (p2 : NanoP4Spec.argumentList) : Option (List NanoP4Spec.argumentIR) :=
  (do
     let scope := p0
     let TC := p1
     let argumentList := p2
     (do
        let tmp_0 ← NanoP4Spec.«$flatten_argumentList» fuel argumentList
        let «argument*» := tmp_0
        let tmp_2 ←
            List.mapM
              (fun (argument : NanoP4Spec.argument) =>
                 (do
                    let tmp_1 ← NanoP4Spec.Argument_ok.run fuel scope TC argument
                    let argumentIR := tmp_1
                    pure argumentIR))
              «argument*»
        let «argumentIR*» := List.map (·) tmp_2
        pure «argumentIR*»))

end NanoP4Spec
