-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, upstream/nano-p4-spec/5.07-typing-argument.watsup
import P4SpecTec.Prelude
import P4SpecTec.Tactic.RunSound
import P4SpecTec.Tactic.Audit
import NanoP4Spec.«5.06-typing-parameter»

/-! # NanoP4Spec.«5.07-typing-argument»

The rendering of `upstream/nano-p4-spec/5.07-typing-argument.watsup`.
Generated: every definition here mirrors one definition of that file, in
order, by the encodings of `docs/design.md`.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 1000000

open P4SpecTec P4SpecTec.Prelude

namespace NanoP4Spec

def Argument_ok.run
        (p0 : NanoP4Spec.scope)
        (p1 : NanoP4Spec.typingContext)
        (p2 : NanoP4Spec.argument)
    : Option (Except Fail NanoP4Spec.argumentIR) :=
  ExceptT.run
    (do
       have scope := p0
       have TC := p1
       have expression := p2
       (do
          let tmp_0 ← ExceptT.mk (NanoP4Spec.Expr_ok.run scope TC expression)
          have typeIR := tmp_0
          have argumentIR := NanoP4Spec.argumentIR.hash expression typeIR
          pure argumentIR))

inductive Argument_ok : NanoP4Spec.scope →
  NanoP4Spec.typingContext →
  NanoP4Spec.argument →
  NanoP4Spec.argumentIR →
  Prop where
  | rule0
      {scope : NanoP4Spec.scope}
      {TC : NanoP4Spec.typingContext}
      {expression : NanoP4Spec.argument}
      {typeIR : NanoP4Spec.typeIR} :
        (NanoP4Spec.Expr_ok scope TC expression typeIR) →
        NanoP4Spec.Argument_ok scope TC expression (NanoP4Spec.argumentIR.hash expression typeIR)

theorem Argument_ok.run_sound
    (p0 : NanoP4Spec.scope)
    (p1 : NanoP4Spec.typingContext)
    (p2 : NanoP4Spec.argument)
    (o : NanoP4Spec.argumentIR) :
    NanoP4Spec.Argument_ok.run p0 p1 p2 = some (.ok o) → NanoP4Spec.Argument_ok p0 p1 p2 o :=
  by run_sound

#audit_axioms NanoP4Spec.Argument_ok.run_sound

def ArgumentList_ok.run
        (p0 : NanoP4Spec.scope)
        (p1 : NanoP4Spec.typingContext)
        (p2 : NanoP4Spec.argumentList)
    : Option (Except Fail (List NanoP4Spec.argumentIR)) :=
  ExceptT.run
    (do
       have scope := p0
       have TC := p1
       have argumentList := p2
       (do
          let tmp_0 ← ExceptT.mk (NanoP4Spec.«$flatten_argumentList» argumentList)
          have «argument*» := tmp_0
          let tmp_2 ←
              List.mapM
                (fun (argument : NanoP4Spec.argument) =>
                   (do
                      let tmp_1 ← ExceptT.mk (NanoP4Spec.Argument_ok.run scope TC argument)
                      have argumentIR := tmp_1
                      pure argumentIR))
                «argument*»
          have «argumentIR*» := tmp_2
          pure «argumentIR*»))

inductive ArgumentList_ok : NanoP4Spec.scope →
  NanoP4Spec.typingContext →
  NanoP4Spec.argumentList →
  (List NanoP4Spec.argumentIR) →
  Prop where
  | rule0
      {scope : NanoP4Spec.scope}
      {TC : NanoP4Spec.typingContext}
      {argumentList : NanoP4Spec.argumentList}
      {«argument*» : List NanoP4Spec.argument}
      {«argumentIR*» : List NanoP4Spec.argumentIR} :
        (NanoP4Spec.«$flatten_argumentList» argumentList = some (.ok «argument*»)) →
        (List.length «argument*» = List.length «argumentIR*») →
        (∀
           (argument : NanoP4Spec.argument)
           (argumentIR : NanoP4Spec.argumentIR),
           (argument, argumentIR) ∈ (List.zip «argument*» «argumentIR*») →
           NanoP4Spec.Argument_ok scope TC argument argumentIR) →
        NanoP4Spec.ArgumentList_ok scope TC argumentList «argumentIR*»

theorem ArgumentList_ok.run_sound
    (p0 : NanoP4Spec.scope)
    (p1 : NanoP4Spec.typingContext)
    (p2 : NanoP4Spec.argumentList)
    (o : List NanoP4Spec.argumentIR) :
    NanoP4Spec.ArgumentList_ok.run p0 p1 p2 = some (.ok o) →
        NanoP4Spec.ArgumentList_ok p0 p1 p2 o :=
  by run_sound

#audit_axioms NanoP4Spec.ArgumentList_ok.run_sound

end NanoP4Spec
