-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, upstream/nano-p4-spec/5.09-typing-parser.watsup
import P4SpecTec.Prelude
import P4SpecTec.Tactic.RunSound
import P4SpecTec.Tactic.Audit
import P4SpecTec.Tactic.Det
import P4SpecTec.Refine.Quote
import P4SpecTec.Refine.Calc
import P4SpecTec.Tactic.Refine
import NanoP4Spec.«5.08-typing-declaration»

/-! # NanoP4Spec.«5.09-typing-parser»

The rendering of `upstream/nano-p4-spec/5.09-typing-parser.watsup`.
Generated: every definition here mirrors one definition of that file, in
order, by the encodings of `docs/design.md`.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 1000000

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

def ParserLocalDecl_ok.run (p0 : NanoP4Spec.typingContext) (p1 : NanoP4Spec.parserLocalDeclaration)
    : Option (Except Fail NanoP4Spec.typingContext) :=
  ExceptT.run
    (do
       have TC_0 := p0
       have variableDeclaration := p1
       (do
          let tmp_0 ←
              ExceptT.mk (NanoP4Spec.VarDecl_ok.run NanoP4Spec.scope.BLOCK TC_0 variableDeclaration)
          have TC_1 := tmp_0
          pure TC_1))

inductive ParserLocalDecl_ok : NanoP4Spec.typingContext →
  NanoP4Spec.parserLocalDeclaration →
  NanoP4Spec.typingContext →
  Prop where
  | rule0
      {TC_0 : NanoP4Spec.typingContext}
      {variableDeclaration : NanoP4Spec.parserLocalDeclaration}
      {TC_1 : NanoP4Spec.typingContext} :
        (NanoP4Spec.VarDecl_ok NanoP4Spec.scope.BLOCK TC_0 variableDeclaration TC_1) →
        NanoP4Spec.ParserLocalDecl_ok TC_0 variableDeclaration TC_1

theorem ParserLocalDecl_ok.run_sound
    (p0 : NanoP4Spec.typingContext)
    (p1 : NanoP4Spec.parserLocalDeclaration)
    (o : NanoP4Spec.typingContext) :
    NanoP4Spec.ParserLocalDecl_ok.run p0 p1 = some (.ok o) →
        NanoP4Spec.ParserLocalDecl_ok p0 p1 o :=
  by run_sound

#audit_axioms NanoP4Spec.ParserLocalDecl_ok.run_sound

-- no determinism theorem: ParserLocalDecl_ok
--   calls VarDecl_ok, which has no determinism theorem

def ParserLocalDecl_ok.al : Lang.Al.def :=
  Q.d
    (.RelD
       (Q.i "ParserLocalDecl_ok")
       (Q.nt
          (.Infix
             (.Arg (Q.t (Q.varT "typingContext" [])))
             (Q.a .Turnstile)
             (.Infix
                (.Arg (Q.t (Q.varT "parserLocalDeclaration" [])))
                (Q.a .Tilesturn)
                (.Arg (Q.t (Q.varT "typingContext" []))))))
       [0, 1]
       [Q.rg
          ""
          ([Q.e (.VarE (Q.i "TC_0")) (Q.varT "typingContext" []),
            Q.e (.VarE (Q.i "variableDeclaration")) (Q.varT "variableDeclaration" [])],
           [Q.e (.VarE (Q.i "TC_0")) (Q.varT "typingContext" []),
            Q.e (.VarE (Q.i "variableDeclaration")) (Q.varT "variableDeclaration" [])],
           [])
          [Q.rp
             ""
             [Q.pr
                (.RulePr
                   (Q.i "VarDecl_ok")
                   (.Infix
                      (.Seq
                         [.Arg (Q.e (.CaseE (.Atom (Q.a (.Keyword "BLOCK")))) (Q.varT "scope" [])),
                          .Arg (Q.e (.VarE (Q.i "TC_0")) (Q.varT "typingContext" []))])
                      (Q.a .Turnstile)
                      (.Infix
                         (.Arg
                            (Q.e
                               (.VarE (Q.i "variableDeclaration"))
                               (Q.varT "variableDeclaration" [])))
                         (Q.a .Tilesturn)
                         (.Arg (Q.e (.VarE (Q.i "TC_1")) (Q.varT "typingContext" [])))))
                   [0, 1, 2])]
             [Q.e (.VarE (Q.i "TC_1")) (Q.varT "typingContext" [])]]]
       none
       [])

def ParserLocalDecls_ok.run
        (p0 : NanoP4Spec.typingContext)
        (p1 : List NanoP4Spec.parserLocalDeclaration)
    : Option (Except Fail NanoP4Spec.typingContext) :=
  ExceptT.run
    (do
       have TC_0 := p0
       have «parserLocalDeclaration*» := p1
       (do
          let _ ← Eval.check («parserLocalDeclaration*» ==
           ([] : List NanoP4Spec.parserLocalDeclaration))
          pure TC_0) <|>
       (do
          have «parserLocalDeclaration'*» := «parserLocalDeclaration*»
          let _ ← Eval.check (!(List.isEmpty «parserLocalDeclaration'*»))
          let parserLocalDeclaration_h :: «parserLocalDeclaration_t*» :=
              «parserLocalDeclaration'*» | throw Fail.err
          let tmp_0 ← ExceptT.mk (NanoP4Spec.ParserLocalDecl_ok.run TC_0 parserLocalDeclaration_h)
          have TC_1 := tmp_0
          let tmp_1 ←
              ExceptT.mk (NanoP4Spec.ParserLocalDecls_ok.run TC_1 «parserLocalDeclaration_t*»)
          have TC_2 := tmp_1
          pure TC_2))
  partial_fixpoint

inductive ParserLocalDecls_ok : NanoP4Spec.typingContext →
  (List NanoP4Spec.parserLocalDeclaration) →
  NanoP4Spec.typingContext →
  Prop where
  | nil
      {TC_0 : NanoP4Spec.typingContext}
      {«parserLocalDeclaration*» : List NanoP4Spec.parserLocalDeclaration} :
        ((«parserLocalDeclaration*» == ([] : List NanoP4Spec.parserLocalDeclaration) : Bool) =
           true) →
        NanoP4Spec.ParserLocalDecls_ok TC_0 «parserLocalDeclaration*» TC_0
  | cons
      {TC_0 : NanoP4Spec.typingContext}
      {parserLocalDeclaration_h : NanoP4Spec.parserLocalDeclaration}
      {«parserLocalDeclaration_t*» : List NanoP4Spec.parserLocalDeclaration}
      {TC_1 : NanoP4Spec.typingContext}
      {TC_2 : NanoP4Spec.typingContext} :
        ((!(List.isEmpty (parserLocalDeclaration_h :: «parserLocalDeclaration_t*»)) : Bool) =
           true) →
        (NanoP4Spec.ParserLocalDecl_ok TC_0 parserLocalDeclaration_h TC_1) →
        (NanoP4Spec.ParserLocalDecls_ok TC_1 «parserLocalDeclaration_t*» TC_2) →
        NanoP4Spec.ParserLocalDecls_ok
          TC_0
          (parserLocalDeclaration_h :: «parserLocalDeclaration_t*»)
          TC_2

theorem ParserLocalDecls_ok.run_sound_group :
    (∀
         (p0 : NanoP4Spec.typingContext)
         (p1 : List NanoP4Spec.parserLocalDeclaration)
         (r : Except Fail NanoP4Spec.typingContext),
         NanoP4Spec.ParserLocalDecls_ok.run p0 p1 = some r →
         ∀ (o : NanoP4Spec.typingContext), r = .ok o →
         NanoP4Spec.ParserLocalDecls_ok p0 p1 o) := by
  run_sound_group NanoP4Spec.ParserLocalDecls_ok.run.partial_correctness

#audit_axioms NanoP4Spec.ParserLocalDecls_ok.run_sound_group

theorem ParserLocalDecls_ok.run_sound
    (p0 : NanoP4Spec.typingContext)
    (p1 : List NanoP4Spec.parserLocalDeclaration)
    (o : NanoP4Spec.typingContext) :
    NanoP4Spec.ParserLocalDecls_ok.run p0 p1 = some (.ok o) →
        NanoP4Spec.ParserLocalDecls_ok p0 p1 o :=
  fun h => NanoP4Spec.ParserLocalDecls_ok.run_sound_group p0 p1 _ h o rfl

#audit_axioms NanoP4Spec.ParserLocalDecls_ok.run_sound

def ParserLocalDecls_ok.al : Lang.Al.def :=
  Q.d
    (.RelD
       (Q.i "ParserLocalDecls_ok")
       (Q.nt
          (.Infix
             (.Arg (Q.t (Q.varT "typingContext" [])))
             (Q.a .Turnstile)
             (.Infix
                (.Arg (Q.t (.IterT (Q.t (Q.varT "parserLocalDeclaration" [])) .List)))
                (Q.a .Tilesturn)
                (.Arg (Q.t (Q.varT "typingContext" []))))))
       [0, 1]
       [Q.rg
          ""
          ([Q.e (.VarE (Q.i "TC_0")) (Q.varT "typingContext" []),
            Q.e
              (.IterE
                 (Q.e (.VarE (Q.i "parserLocalDeclaration")) (Q.varT "parserLocalDeclaration" []))
                 (.mk
                    .List
                    [Q.v
                       "parserLocalDeclaration"
                       (.IterT (Q.t (Q.varT "parserLocalDeclaration" [])) .List)
                       []]))
              (.IterT (Q.t (Q.varT "parserLocalDeclaration" [])) .List)],
           [Q.e (.VarE (Q.i "TC_0")) (Q.varT "typingContext" []),
            Q.e
              (.IterE
                 (Q.e (.VarE (Q.i "parserLocalDeclaration")) (Q.varT "parserLocalDeclaration" []))
                 (.mk
                    .List
                    [Q.v
                       "parserLocalDeclaration"
                       (.IterT (Q.t (Q.varT "parserLocalDeclaration" [])) .List)
                       []]))
              (.IterT (Q.t (Q.varT "parserLocalDeclaration" [])) .List)],
           [])
          [Q.rp
             "nil"
             [Q.pr
                (.IfPr
                   (Q.e
                      (.CmpE
                         .EqOp
                         .BoolT
                         (Q.e
                            (.IterE
                               (Q.e
                                  (.VarE (Q.i "parserLocalDeclaration"))
                                  (Q.varT "parserLocalDeclaration" []))
                               (.mk
                                  .List
                                  [Q.v
                                     "parserLocalDeclaration"
                                     (.IterT (Q.t (Q.varT "parserLocalDeclaration" [])) .List)
                                     []]))
                            (.IterT (Q.t (Q.varT "parserLocalDeclaration" [])) .List))
                         (Q.e
                            (.ListE [])
                            (.IterT (Q.t (Q.varT "parserLocalDeclaration" [])) .List)))
                      .BoolT))]
             [Q.e (.VarE (Q.i "TC_0")) (Q.varT "typingContext" [])],
           Q.rp
             "cons"
             [Q.pr
                (.LetPr
                   (Q.e
                      (.IterE
                         (Q.e
                            (.VarE (Q.i "parserLocalDeclaration'"))
                            (Q.varT "parserLocalDeclaration" []))
                         (.mk
                            .List
                            [Q.v
                               "parserLocalDeclaration'"
                               (.IterT (Q.t (Q.varT "parserLocalDeclaration" [])) .List)
                               []]))
                      (.IterT (Q.t (Q.varT "parserLocalDeclaration" [])) .List))
                   (Q.e
                      (.IterE
                         (Q.e
                            (.VarE (Q.i "parserLocalDeclaration"))
                            (Q.varT "parserLocalDeclaration" []))
                         (.mk
                            .List
                            [Q.v
                               "parserLocalDeclaration"
                               (.IterT (Q.t (Q.varT "parserLocalDeclaration" [])) .List)
                               []]))
                      (.IterT (Q.t (Q.varT "parserLocalDeclaration" [])) .List))),
              Q.pr
                (.IfPr
                   (Q.e
                      (.MatchE
                         (Q.e
                            (.IterE
                               (Q.e
                                  (.VarE (Q.i "parserLocalDeclaration'"))
                                  (Q.varT "parserLocalDeclaration" []))
                               (.mk
                                  .List
                                  [Q.v
                                     "parserLocalDeclaration'"
                                     (.IterT (Q.t (Q.varT "parserLocalDeclaration" [])) .List)
                                     []]))
                            (.IterT (Q.t (Q.varT "parserLocalDeclaration" [])) .List))
                         (.ListP .Cons))
                      .BoolT)),
              Q.pr
                (.LetPr
                   (Q.e
                      (.ConsE
                         (Q.e
                            (.VarE (Q.i "parserLocalDeclaration_h"))
                            (Q.varT "parserLocalDeclaration" []))
                         (Q.e
                            (.IterE
                               (Q.e
                                  (.VarE (Q.i "parserLocalDeclaration_t"))
                                  (Q.varT "parserLocalDeclaration" []))
                               (.mk
                                  .List
                                  [Q.v
                                     "parserLocalDeclaration_t"
                                     (Q.varT "parserLocalDeclaration" [])
                                     []]))
                            (.IterT (Q.t (Q.varT "parserLocalDeclaration" [])) .List)))
                      (.IterT (Q.t (Q.varT "parserLocalDeclaration" [])) .List))
                   (Q.e
                      (.IterE
                         (Q.e
                            (.VarE (Q.i "parserLocalDeclaration'"))
                            (Q.varT "parserLocalDeclaration" []))
                         (.mk
                            .List
                            [Q.v
                               "parserLocalDeclaration'"
                               (.IterT (Q.t (Q.varT "parserLocalDeclaration" [])) .List)
                               []]))
                      (.IterT (Q.t (Q.varT "parserLocalDeclaration" [])) .List))),
              Q.pr
                (.RulePr
                   (Q.i "ParserLocalDecl_ok")
                   (.Infix
                      (.Arg (Q.e (.VarE (Q.i "TC_0")) (Q.varT "typingContext" [])))
                      (Q.a .Turnstile)
                      (.Infix
                         (.Arg
                            (Q.e
                               (.VarE (Q.i "parserLocalDeclaration_h"))
                               (Q.varT "parserLocalDeclaration" [])))
                         (Q.a .Tilesturn)
                         (.Arg (Q.e (.VarE (Q.i "TC_1")) (Q.varT "typingContext" [])))))
                   [0, 1]),
              Q.pr
                (.RulePr
                   (Q.i "ParserLocalDecls_ok")
                   (.Infix
                      (.Arg (Q.e (.VarE (Q.i "TC_1")) (Q.varT "typingContext" [])))
                      (Q.a .Turnstile)
                      (.Infix
                         (.Arg
                            (Q.e
                               (.IterE
                                  (Q.e
                                     (.VarE (Q.i "parserLocalDeclaration_t"))
                                     (Q.varT "parserLocalDeclaration" []))
                                  (.mk
                                     .List
                                     [Q.v
                                        "parserLocalDeclaration_t"
                                        (Q.varT "parserLocalDeclaration" [])
                                        []]))
                               (.IterT (Q.t (Q.varT "parserLocalDeclaration" [])) .List)))
                         (Q.a .Tilesturn)
                         (.Arg (Q.e (.VarE (Q.i "TC_2")) (Q.varT "typingContext" [])))))
                   [0, 1])]
             [Q.e (.VarE (Q.i "TC_2")) (Q.varT "typingContext" [])]]]
       none
       [])

def ParserLocalDeclList_ok.run
        (p0 : NanoP4Spec.typingContext)
        (p1 : NanoP4Spec.parserLocalDeclarationList)
    : Option (Except Fail NanoP4Spec.typingContext) :=
  ExceptT.run
    (do
       have TC_0 := p0
       have parserLocalDeclarationList := p1
       (do
          let tmp_0 ←
              ExceptT.mk
                (NanoP4Spec.«$flatten_parserLocalDeclarationList» parserLocalDeclarationList)
          have «parserLocalDeclaration*» := tmp_0
          let tmp_1 ← ExceptT.mk (NanoP4Spec.ParserLocalDecls_ok.run TC_0 «parserLocalDeclaration*»)
          have TC_1 := tmp_1
          pure TC_1))

inductive ParserLocalDeclList_ok : NanoP4Spec.typingContext →
  NanoP4Spec.parserLocalDeclarationList →
  NanoP4Spec.typingContext →
  Prop where
  | rule0
      {TC_0 : NanoP4Spec.typingContext}
      {parserLocalDeclarationList : NanoP4Spec.parserLocalDeclarationList}
      {«parserLocalDeclaration*» : List NanoP4Spec.parserLocalDeclaration}
      {TC_1 : NanoP4Spec.typingContext} :
        (NanoP4Spec.«$flatten_parserLocalDeclarationList» parserLocalDeclarationList =
           some (.ok «parserLocalDeclaration*»)) →
        (NanoP4Spec.ParserLocalDecls_ok TC_0 «parserLocalDeclaration*» TC_1) →
        NanoP4Spec.ParserLocalDeclList_ok TC_0 parserLocalDeclarationList TC_1

theorem ParserLocalDeclList_ok.run_sound
    (p0 : NanoP4Spec.typingContext)
    (p1 : NanoP4Spec.parserLocalDeclarationList)
    (o : NanoP4Spec.typingContext) :
    NanoP4Spec.ParserLocalDeclList_ok.run p0 p1 = some (.ok o) →
        NanoP4Spec.ParserLocalDeclList_ok p0 p1 o :=
  by run_sound

#audit_axioms NanoP4Spec.ParserLocalDeclList_ok.run_sound

-- no determinism theorem: ParserLocalDeclList_ok
--   calls ParserLocalDecls_ok, which has no determinism theorem

def ParserLocalDeclList_ok.al : Lang.Al.def :=
  Q.d
    (.RelD
       (Q.i "ParserLocalDeclList_ok")
       (Q.nt
          (.Infix
             (.Arg (Q.t (Q.varT "typingContext" [])))
             (Q.a .Turnstile)
             (.Infix
                (.Arg (Q.t (Q.varT "parserLocalDeclarationList" [])))
                (Q.a .Tilesturn)
                (.Arg (Q.t (Q.varT "typingContext" []))))))
       [0, 1]
       [Q.rg
          ""
          ([Q.e (.VarE (Q.i "TC_0")) (Q.varT "typingContext" []),
            Q.e
              (.VarE (Q.i "parserLocalDeclarationList"))
              (Q.varT "parserLocalDeclarationList" [])],
           [Q.e (.VarE (Q.i "TC_0")) (Q.varT "typingContext" []),
            Q.e
              (.VarE (Q.i "parserLocalDeclarationList"))
              (Q.varT "parserLocalDeclarationList" [])],
           [])
          [Q.rp
             ""
             [Q.pr
                (.LetPr
                   (Q.e
                      (.IterE
                         (Q.e
                            (.VarE (Q.i "parserLocalDeclaration"))
                            (Q.varT "parserLocalDeclaration" []))
                         (.mk
                            .List
                            [Q.v "parserLocalDeclaration" (Q.varT "parserLocalDeclaration" []) []]))
                      (.IterT (Q.t (Q.varT "parserLocalDeclaration" [])) .List))
                   (Q.e
                      (.CallE
                         (Q.i "flatten_parserLocalDeclarationList")
                         []
                         [Q.ar
                            (.ExpA
                               (Q.e
                                  (.VarE (Q.i "parserLocalDeclarationList"))
                                  (Q.varT "parserLocalDeclarationList" [])))])
                      (.IterT (Q.t (Q.varT "parserLocalDeclaration" [])) .List))),
              Q.pr
                (.RulePr
                   (Q.i "ParserLocalDecls_ok")
                   (.Infix
                      (.Arg (Q.e (.VarE (Q.i "TC_0")) (Q.varT "typingContext" [])))
                      (Q.a .Turnstile)
                      (.Infix
                         (.Arg
                            (Q.e
                               (.IterE
                                  (Q.e
                                     (.VarE (Q.i "parserLocalDeclaration"))
                                     (Q.varT "parserLocalDeclaration" []))
                                  (.mk
                                     .List
                                     [Q.v
                                        "parserLocalDeclaration"
                                        (Q.varT "parserLocalDeclaration" [])
                                        []]))
                               (.IterT (Q.t (Q.varT "parserLocalDeclaration" [])) .List)))
                         (Q.a .Tilesturn)
                         (.Arg (Q.e (.VarE (Q.i "TC_1")) (Q.varT "typingContext" [])))))
                   [0, 1])]
             [Q.e (.VarE (Q.i "TC_1")) (Q.varT "typingContext" [])]]]
       none
       [])

end NanoP4Spec
