-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, upstream/nano-p4-spec/5.09-typing-parser.watsup
import P4SpecTec.Prelude
import NanoP4Spec.«5.08-typing-declaration»

/-! # NanoP4Spec.«5.09-typing-parser»

The rendering of `upstream/nano-p4-spec/5.09-typing-parser.watsup`.
Generated: every definition here mirrors one definition of that file, in
order, by the encodings of `docs/design.md`.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 1000000

open P4SpecTec P4SpecTec.Prelude

namespace NanoP4Spec

def ParserLocalDecl_ok.run
    (fuel : Nat)
    (p0 : NanoP4Spec.typingContext)
    (p1 : NanoP4Spec.parserLocalDeclaration) : Option NanoP4Spec.typingContext :=
  (do
     let TC_0 := p0
     let variableDeclaration := p1
     (do
        let tmp_0 ← NanoP4Spec.VarDecl_ok.run fuel NanoP4Spec.scope.BLOCK TC_0 variableDeclaration
        let TC_1 := tmp_0
        pure TC_1))

def ParserLocalDecls_ok.run
    (fuel : Nat)
    (p0 : NanoP4Spec.typingContext)
    (p1 : List NanoP4Spec.parserLocalDeclaration) : Option NanoP4Spec.typingContext :=
  match fuel with
    | 0 => none
    | fuel + 1 =>
      (do
         let TC_0 := p0
         let «parserLocalDeclaration*» := p1
         (do
            let _ ← Iter.check («parserLocalDeclaration*» ==
             ([] : List NanoP4Spec.parserLocalDeclaration))
            pure TC_0) <|>
         (do
            let «parserLocalDeclaration'*» := «parserLocalDeclaration*»
            let _ ← Iter.check (!(List.isEmpty «parserLocalDeclaration'*»))
            let parserLocalDeclaration_h :: «parserLocalDeclaration_t*» :=
                «parserLocalDeclaration'*» | none
            let tmp_0 ← NanoP4Spec.ParserLocalDecl_ok.run fuel TC_0 parserLocalDeclaration_h
            let TC_1 := tmp_0
            let tmp_1 ← NanoP4Spec.ParserLocalDecls_ok.run fuel TC_1 «parserLocalDeclaration_t*»
            let TC_2 := tmp_1
            pure TC_2))

def ParserLocalDeclList_ok.run
    (fuel : Nat)
    (p0 : NanoP4Spec.typingContext)
    (p1 : NanoP4Spec.parserLocalDeclarationList) : Option NanoP4Spec.typingContext :=
  (do
     let TC_0 := p0
     let parserLocalDeclarationList := p1
     (do
        let tmp_0 ← NanoP4Spec.«$flatten_parserLocalDeclarationList» fuel parserLocalDeclarationList
        let «parserLocalDeclaration*» := tmp_0
        let tmp_1 ← NanoP4Spec.ParserLocalDecls_ok.run fuel TC_0 «parserLocalDeclaration*»
        let TC_1 := tmp_1
        pure TC_1))

end NanoP4Spec
