-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, upstream/nano-p4-spec/7.0-load-context.watsup
import P4SpecTec.Prelude
import NanoP4Spec.«5.13-typing-call-convention»

/-! # NanoP4Spec.«7.0-load-context»

The rendering of `upstream/nano-p4-spec/7.0-load-context.watsup`.
Generated: every definition here mirrors one definition of that file, in
order, by the encodings of `docs/design.md`.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 1000000

open P4SpecTec P4SpecTec.Prelude

namespace NanoP4Spec

inductive actionDeclarationIR where
  | ACTION_lparen_rparen
      (nameIR : NanoP4Spec.nameIR)
      (parameterIR : List NanoP4Spec.parameterIR)
      (blockStatement : NanoP4Spec.blockStatement)

def actionDeclarationIR.toValue : NanoP4Spec.actionDeclarationIR → Lang.Il.value
  | .ACTION_lparen_rparen x0 x1 x2 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "actionDeclarationIR")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "ACTION"))),
            (.Arg (ToValue.toValue x0)),
            (.Brack
               (Prelude.Value.atom .LParen)
               (.Arg (ToValue.toValue x1))
               (Prelude.Value.atom .RParen)),
            (.Arg (ToValue.toValue x2))])

instance : ToValue NanoP4Spec.actionDeclarationIR := ⟨NanoP4Spec.actionDeclarationIR.toValue⟩
instance : BEq NanoP4Spec.actionDeclarationIR := ⟨valueEq⟩

def actionDeclarationIR.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.actionDeclarationIR
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0, a1, a2] :=
             Prelude.Value.caseArgs
               c
               (.Seq
                  [(.Atom (Prelude.Value.atom (.Keyword "ACTION"))),
                   (.Arg ()),
                   (.Brack (Prelude.Value.atom .LParen) (.Arg ()) (Prelude.Value.atom .RParen)),
                   (.Arg ())]) | none
         pure (NanoP4Spec.actionDeclarationIR.ACTION_lparen_rparen
            (← OfValue.ofValue fuel a0)
            (← OfValue.ofValue fuel a1)
            (← OfValue.ofValue fuel a2)))
    | _ => none

instance : OfValue NanoP4Spec.actionDeclarationIR := ⟨NanoP4Spec.actionDeclarationIR.ofValue⟩

inductive parserDeclarationIR where
  | PARSER_lparen_rparen_lbrace_rbrace
      (nameIR : NanoP4Spec.nameIR)
      (parameterIR : List NanoP4Spec.parameterIR)
      (parserLocalDeclarationList : NanoP4Spec.parserLocalDeclarationList)
      (parserStateList : NanoP4Spec.parserStateList)

def parserDeclarationIR.toValue : NanoP4Spec.parserDeclarationIR → Lang.Il.value
  | .PARSER_lparen_rparen_lbrace_rbrace x0 x1 x2 x3 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "parserDeclarationIR")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "PARSER"))),
            (.Arg (ToValue.toValue x0)),
            (.Brack
               (Prelude.Value.atom .LParen)
               (.Arg (ToValue.toValue x1))
               (Prelude.Value.atom .RParen)),
            (.Brack
               (Prelude.Value.atom .LBrace)
               (.Seq [(.Arg (ToValue.toValue x2)), (.Arg (ToValue.toValue x3))])
               (Prelude.Value.atom .RBrace))])

instance : ToValue NanoP4Spec.parserDeclarationIR := ⟨NanoP4Spec.parserDeclarationIR.toValue⟩
instance : BEq NanoP4Spec.parserDeclarationIR := ⟨valueEq⟩

def parserDeclarationIR.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.parserDeclarationIR
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0, a1, a2, a3] :=
             Prelude.Value.caseArgs
               c
               (.Seq
                  [(.Atom (Prelude.Value.atom (.Keyword "PARSER"))),
                   (.Arg ()),
                   (.Brack (Prelude.Value.atom .LParen) (.Arg ()) (Prelude.Value.atom .RParen)),
                   (.Brack
                      (Prelude.Value.atom .LBrace)
                      (.Seq [(.Arg ()), (.Arg ())])
                      (Prelude.Value.atom .RBrace))]) | none
         pure (NanoP4Spec.parserDeclarationIR.PARSER_lparen_rparen_lbrace_rbrace
            (← OfValue.ofValue fuel a0)
            (← OfValue.ofValue fuel a1)
            (← OfValue.ofValue fuel a2)
            (← OfValue.ofValue fuel a3)))
    | _ => none

instance : OfValue NanoP4Spec.parserDeclarationIR := ⟨NanoP4Spec.parserDeclarationIR.ofValue⟩

inductive controlDeclarationIR where
  | CONTROL_lparen_rparen_lbrace_APPLY_rbrace
      (nameIR : NanoP4Spec.nameIR)
      (parameterIR : List NanoP4Spec.parameterIR)
      (controlLocalDeclarationList : NanoP4Spec.controlLocalDeclarationList)
      (controlBody : NanoP4Spec.controlBody)

def controlDeclarationIR.toValue : NanoP4Spec.controlDeclarationIR → Lang.Il.value
  | .CONTROL_lparen_rparen_lbrace_APPLY_rbrace x0 x1 x2 x3 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "controlDeclarationIR")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "CONTROL"))),
            (.Arg (ToValue.toValue x0)),
            (.Brack
               (Prelude.Value.atom .LParen)
               (.Arg (ToValue.toValue x1))
               (Prelude.Value.atom .RParen)),
            (.Brack
               (Prelude.Value.atom .LBrace)
               (.Seq
                  [(.Arg (ToValue.toValue x2)),
                   (.Atom (Prelude.Value.atom (.Keyword "APPLY"))),
                   (.Arg (ToValue.toValue x3))])
               (Prelude.Value.atom .RBrace))])

instance : ToValue NanoP4Spec.controlDeclarationIR := ⟨NanoP4Spec.controlDeclarationIR.toValue⟩
instance : BEq NanoP4Spec.controlDeclarationIR := ⟨valueEq⟩

def controlDeclarationIR.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.controlDeclarationIR
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0, a1, a2, a3] :=
             Prelude.Value.caseArgs
               c
               (.Seq
                  [(.Atom (Prelude.Value.atom (.Keyword "CONTROL"))),
                   (.Arg ()),
                   (.Brack (Prelude.Value.atom .LParen) (.Arg ()) (Prelude.Value.atom .RParen)),
                   (.Brack
                      (Prelude.Value.atom .LBrace)
                      (.Seq [(.Arg ()), (.Atom (Prelude.Value.atom (.Keyword "APPLY"))), (.Arg ())])
                      (Prelude.Value.atom .RBrace))]) | none
         pure (NanoP4Spec.controlDeclarationIR.CONTROL_lparen_rparen_lbrace_APPLY_rbrace
            (← OfValue.ofValue fuel a0)
            (← OfValue.ofValue fuel a1)
            (← OfValue.ofValue fuel a2)
            (← OfValue.ofValue fuel a3)))
    | _ => none

instance : OfValue NanoP4Spec.controlDeclarationIR := ⟨NanoP4Spec.controlDeclarationIR.ofValue⟩

inductive callableDef where
  | ACTION_lparen_rparen
      (nameIR : NanoP4Spec.nameIR)
      (parameterIR : List NanoP4Spec.parameterIR)
      (blockStatement : NanoP4Spec.blockStatement)
  | PARSER_lparen_rparen_lbrace_rbrace
      (nameIR : NanoP4Spec.nameIR)
      (parameterIR : List NanoP4Spec.parameterIR)
      (parserLocalDeclarationList : NanoP4Spec.parserLocalDeclarationList)
      (parserStateList : NanoP4Spec.parserStateList)
  | CONTROL_lparen_rparen_lbrace_APPLY_rbrace
      (nameIR : NanoP4Spec.nameIR)
      (parameterIR : List NanoP4Spec.parameterIR)
      (controlLocalDeclarationList : NanoP4Spec.controlLocalDeclarationList)
      (controlBody : NanoP4Spec.controlBody)

def callableDef.toValue : NanoP4Spec.callableDef → Lang.Il.value
  | .ACTION_lparen_rparen x0 x1 x2 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "callableDef")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "ACTION"))),
            (.Arg (ToValue.toValue x0)),
            (.Brack
               (Prelude.Value.atom .LParen)
               (.Arg (ToValue.toValue x1))
               (Prelude.Value.atom .RParen)),
            (.Arg (ToValue.toValue x2))])
  | .PARSER_lparen_rparen_lbrace_rbrace x0 x1 x2 x3 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "callableDef")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "PARSER"))),
            (.Arg (ToValue.toValue x0)),
            (.Brack
               (Prelude.Value.atom .LParen)
               (.Arg (ToValue.toValue x1))
               (Prelude.Value.atom .RParen)),
            (.Brack
               (Prelude.Value.atom .LBrace)
               (.Seq [(.Arg (ToValue.toValue x2)), (.Arg (ToValue.toValue x3))])
               (Prelude.Value.atom .RBrace))])
  | .CONTROL_lparen_rparen_lbrace_APPLY_rbrace x0 x1 x2 x3 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "callableDef")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "CONTROL"))),
            (.Arg (ToValue.toValue x0)),
            (.Brack
               (Prelude.Value.atom .LParen)
               (.Arg (ToValue.toValue x1))
               (Prelude.Value.atom .RParen)),
            (.Brack
               (Prelude.Value.atom .LBrace)
               (.Seq
                  [(.Arg (ToValue.toValue x2)),
                   (.Atom (Prelude.Value.atom (.Keyword "APPLY"))),
                   (.Arg (ToValue.toValue x3))])
               (Prelude.Value.atom .RBrace))])

instance : ToValue NanoP4Spec.callableDef := ⟨NanoP4Spec.callableDef.toValue⟩
instance : BEq NanoP4Spec.callableDef := ⟨valueEq⟩

def callableDef.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.callableDef
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0, a1, a2] :=
             Prelude.Value.caseArgs
               c
               (.Seq
                  [(.Atom (Prelude.Value.atom (.Keyword "ACTION"))),
                   (.Arg ()),
                   (.Brack (Prelude.Value.atom .LParen) (.Arg ()) (Prelude.Value.atom .RParen)),
                   (.Arg ())]) | none
         pure (NanoP4Spec.callableDef.ACTION_lparen_rparen
            (← OfValue.ofValue fuel a0)
            (← OfValue.ofValue fuel a1)
            (← OfValue.ofValue fuel a2))) <|>
      ((do
          let some [a0, a1, a2, a3] :=
              Prelude.Value.caseArgs
                c
                (.Seq
                   [(.Atom (Prelude.Value.atom (.Keyword "PARSER"))),
                    (.Arg ()),
                    (.Brack (Prelude.Value.atom .LParen) (.Arg ()) (Prelude.Value.atom .RParen)),
                    (.Brack
                       (Prelude.Value.atom .LBrace)
                       (.Seq [(.Arg ()), (.Arg ())])
                       (Prelude.Value.atom .RBrace))]) | none
          pure (NanoP4Spec.callableDef.PARSER_lparen_rparen_lbrace_rbrace
             (← OfValue.ofValue fuel a0)
             (← OfValue.ofValue fuel a1)
             (← OfValue.ofValue fuel a2)
             (← OfValue.ofValue fuel a3))) <|>
       (do
          let some [a0, a1, a2, a3] :=
              Prelude.Value.caseArgs
                c
                (.Seq
                   [(.Atom (Prelude.Value.atom (.Keyword "CONTROL"))),
                    (.Arg ()),
                    (.Brack (Prelude.Value.atom .LParen) (.Arg ()) (Prelude.Value.atom .RParen)),
                    (.Brack
                       (Prelude.Value.atom .LBrace)
                       (.Seq
                          [(.Arg ()), (.Atom (Prelude.Value.atom (.Keyword "APPLY"))), (.Arg ())])
                       (Prelude.Value.atom .RBrace))]) | none
          pure (NanoP4Spec.callableDef.CONTROL_lparen_rparen_lbrace_APPLY_rbrace
             (← OfValue.ofValue fuel a0)
             (← OfValue.ofValue fuel a1)
             (← OfValue.ofValue fuel a2)
             (← OfValue.ofValue fuel a3))))
    | _ => none

instance : OfValue NanoP4Spec.callableDef := ⟨NanoP4Spec.callableDef.ofValue⟩

abbrev callableDefEnv : Type := NanoP4Spec.map NanoP4Spec.callableId NanoP4Spec.callableDef

def callableDefEnv.toValue (x : NanoP4Spec.callableDefEnv) : Lang.Il.value := ToValue.toValue x

instance : ToValue NanoP4Spec.callableDefEnv := ⟨NanoP4Spec.callableDefEnv.toValue⟩
instance : BEq NanoP4Spec.callableDefEnv := ⟨valueEq⟩

def callableDefEnv.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.callableDefEnv
  | 0, _ => none
  | fuel + 1, v => OfValue.ofValue fuel v

instance : OfValue NanoP4Spec.callableDefEnv := ⟨NanoP4Spec.callableDefEnv.ofValue⟩

structure globalLoadLayer where
  CALLABLE_TYPE : NanoP4Spec.callableTypeDefEnv
  CALLABLE : NanoP4Spec.callableDefEnv
  PARSER : Option NanoP4Spec.parserDeclarationIR
  CONTROL : Option NanoP4Spec.controlDeclarationIR

def globalLoadLayer.toValue : NanoP4Spec.globalLoadLayer → Lang.Il.value
  | ⟨x0, x1, x2, x3⟩ =>
      Runtime.Value.Make.str
        (Prelude.Value.varT "globalLoadLayer")
        [("CALLABLE_TYPE", ToValue.toValue x0),
         ("CALLABLE", ToValue.toValue x1),
         ("PARSER", ToValue.toValue x2),
         ("CONTROL", ToValue.toValue x3)]

instance : ToValue NanoP4Spec.globalLoadLayer := ⟨NanoP4Spec.globalLoadLayer.toValue⟩
instance : BEq NanoP4Spec.globalLoadLayer := ⟨valueEq⟩

def globalLoadLayer.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.globalLoadLayer
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .StructV [(_, f0), (_, f1), (_, f2), (_, f3)] =>
      (do
         pure ⟨(← OfValue.ofValue
           fuel
           f0), (← OfValue.ofValue
           fuel
           f1), (← OfValue.ofValue fuel f2), (← OfValue.ofValue fuel f3)⟩)
    | _ => none

instance : OfValue NanoP4Spec.globalLoadLayer := ⟨NanoP4Spec.globalLoadLayer.ofValue⟩

abbrev loadContext : Type := NanoP4Spec.globalLoadLayer

def loadContext.toValue (x : NanoP4Spec.loadContext) : Lang.Il.value := ToValue.toValue x

instance : ToValue NanoP4Spec.loadContext := ⟨NanoP4Spec.loadContext.toValue⟩
instance : BEq NanoP4Spec.loadContext := ⟨valueEq⟩

def loadContext.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.loadContext
  | 0, _ => none
  | fuel + 1, v => OfValue.ofValue fuel v

instance : OfValue NanoP4Spec.loadContext := ⟨NanoP4Spec.loadContext.ofValue⟩

def parserDeclarationIR.to_callableDef : NanoP4Spec.parserDeclarationIR → NanoP4Spec.callableDef
  | .PARSER_lparen_rparen_lbrace_rbrace x0 x1 x2 x3 =>
    .PARSER_lparen_rparen_lbrace_rbrace x0 x1 x2 x3

def callableDef.of_parserDeclarationIR :
    NanoP4Spec.callableDef → Option NanoP4Spec.parserDeclarationIR
  | .PARSER_lparen_rparen_lbrace_rbrace x0 x1 x2 x3 =>
    some (.PARSER_lparen_rparen_lbrace_rbrace x0 x1 x2 x3)
  | _ => none

def callableDef.is_parserDeclarationIR : NanoP4Spec.callableDef → Bool
  | .PARSER_lparen_rparen_lbrace_rbrace _ _ _ _ => true
  | _ => false

def controlDeclarationIR.to_callableDef : NanoP4Spec.controlDeclarationIR → NanoP4Spec.callableDef
  | .CONTROL_lparen_rparen_lbrace_APPLY_rbrace x0 x1 x2 x3 =>
    .CONTROL_lparen_rparen_lbrace_APPLY_rbrace x0 x1 x2 x3

def callableDef.of_controlDeclarationIR :
    NanoP4Spec.callableDef → Option NanoP4Spec.controlDeclarationIR
  | .CONTROL_lparen_rparen_lbrace_APPLY_rbrace x0 x1 x2 x3 =>
    some (.CONTROL_lparen_rparen_lbrace_APPLY_rbrace x0 x1 x2 x3)
  | _ => none

def callableDef.is_controlDeclarationIR : NanoP4Spec.callableDef → Bool
  | .CONTROL_lparen_rparen_lbrace_APPLY_rbrace _ _ _ _ => true
  | _ => false

def actionDeclarationIR.to_callableDef : NanoP4Spec.actionDeclarationIR → NanoP4Spec.callableDef
  | .ACTION_lparen_rparen x0 x1 x2 => .ACTION_lparen_rparen x0 x1 x2

def callableDef.of_actionDeclarationIR :
    NanoP4Spec.callableDef → Option NanoP4Spec.actionDeclarationIR
  | .ACTION_lparen_rparen x0 x1 x2 => some (.ACTION_lparen_rparen x0 x1 x2)
  | _ => none

def callableDef.is_actionDeclarationIR : NanoP4Spec.callableDef → Bool
  | .ACTION_lparen_rparen _ _ _ => true
  | _ => false

def «$empty_callableDefEnv»
    (fuel : Nat) : Option (NanoP4Spec.map NanoP4Spec.callableId NanoP4Spec.callableDef) :=
  (do
     let tmp_0 ←
         NanoP4Spec.«$empty_map» (τK := NanoP4Spec.callableId) (τV := NanoP4Spec.callableDef) fuel
     pure tmp_0)

def «$make_loadContext»
    (fuel : Nat)
    (p0 : NanoP4Spec.typingContext) : Option NanoP4Spec.loadContext :=
  (do
     let TC := p0
     let tmp_0 ← NanoP4Spec.«$empty_callableDefEnv» fuel
     let LC :=
         ({
            CALLABLE_TYPE := TC.GLOBAL.CALLABLE,
            CALLABLE := tmp_0,
            PARSER := (none : Option NanoP4Spec.parserDeclarationIR),
            CONTROL := (none : Option
               NanoP4Spec.controlDeclarationIR), } : NanoP4Spec.globalLoadLayer)
     pure LC)

def «$find_callableDef_l»
    (fuel : Nat)
    (p0 : NanoP4Spec.loadContext)
    (p1 : NanoP4Spec.callableId) : Option NanoP4Spec.callableDef :=
  (do
     let LC := p0
     let callableId := p1
     let tmp_0 ←
         NanoP4Spec.«$find_map»
           (τK := NanoP4Spec.callableId)
           (τV := NanoP4Spec.callableDef)
           fuel
           LC.CALLABLE
           callableId
     let callableDef'? := tmp_0
     let _ ← Iter.check (Option.isSome callableDef'?)
     let some callableDef := callableDef'? | none
     pure callableDef)

def «$add_callableDef_l»
    (fuel : Nat)
    (p0 : NanoP4Spec.loadContext)
    (p1 : NanoP4Spec.callableId)
    (p2 : NanoP4Spec.callableDef) : Option NanoP4Spec.loadContext :=
  (do
     let LC := p0
     let callableId := p1
     let callableDef := p2
     let callableDefEnv := LC.CALLABLE
     let tmp_0 ←
         NanoP4Spec.«$dom_map»
           (τK := NanoP4Spec.callableId)
           (τV := NanoP4Spec.callableDef)
           fuel
           callableDefEnv
     let tmp_1 ← NanoP4Spec.«$in_set» (τK := NanoP4Spec.callableId) fuel tmp_0 callableId
     let _ ← Iter.check (!tmp_1)
     let tmp_2 ←
         NanoP4Spec.«$add_map»
           (τK := NanoP4Spec.callableId)
           (τV := NanoP4Spec.callableDef)
           fuel
           callableDefEnv
           callableId
           callableDef
     let callableDefEnv' := tmp_2
     let LC' :=
         { LC with
           CALLABLE := callableDefEnv', }
     pure LC')

def «$find_callableTypeDef_l»
    (fuel : Nat)
    (p0 : NanoP4Spec.loadContext)
    (p1 : NanoP4Spec.callableId) : Option NanoP4Spec.callableTypeDef :=
  (do
     let LC := p0
     let callableId := p1
     let tmp_0 ←
         NanoP4Spec.«$find_map»
           (τK := NanoP4Spec.callableId)
           (τV := NanoP4Spec.callableTypeDef)
           fuel
           LC.CALLABLE_TYPE
           callableId
     let callableTypeDef'? := tmp_0
     let _ ← Iter.check (Option.isSome callableTypeDef'?)
     let some callableTypeDef := callableTypeDef'? | none
     pure callableTypeDef)

end NanoP4Spec
