-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, upstream/nano-p4-spec/7.0-load-context.watsup
import P4SpecTec.Prelude
import P4SpecTec.Tactic.RunSound
import P4SpecTec.Tactic.Audit
import P4SpecTec.Refine.Quote
import NanoP4Spec.«5.13-typing-call-convention»

/-! # NanoP4Spec.«7.0-load-context»

The rendering of `upstream/nano-p4-spec/7.0-load-context.watsup`.
Generated: every definition here mirrors one definition of that file, in
order, by the encodings of `docs/design.md`.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 1000000

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

inductive actionDeclarationIR where
  | ACTION_lparen_rparen
      (nameIR : NanoP4Spec.nameIR)
      (parameterIR : List NanoP4Spec.parameterIR)
      (blockStatement : NanoP4Spec.blockStatement)

def actionDeclarationIR.toValue : NanoP4Spec.actionDeclarationIR → Lang.Il.value
  | .ACTION_lparen_rparen x0 x1 x2 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "actionDeclarationIR")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "ACTION"))),
            (.Arg (ToValue.toValue x0)),
            (.Brack
               (Prelude.Value.atom .LParen)
               (.Arg (ToValue.toValue x1))
               (Prelude.Value.atom .RParen)),
            (.Arg (ToValue.toValue x2))])

instance : ToValue NanoP4Spec.actionDeclarationIR := ⟨NanoP4Spec.actionDeclarationIR.toValue⟩
instance : BEq NanoP4Spec.actionDeclarationIR := ⟨valueEq⟩

def actionDeclarationIR.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.actionDeclarationIR
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0, a1, a2] :=
             Prelude.Value.caseArgs
               c
               (.Seq
                  [(.Atom (Prelude.Value.atom (.Keyword "ACTION"))),
                   (.Arg ()),
                   (.Brack (Prelude.Value.atom .LParen) (.Arg ()) (Prelude.Value.atom .RParen)),
                   (.Arg ())]) | none
         pure (NanoP4Spec.actionDeclarationIR.ACTION_lparen_rparen
            (← OfValue.ofValue fuel a0)
            (← OfValue.ofValue fuel a1)
            (← OfValue.ofValue fuel a2)))
    | _ => none

instance : OfValue NanoP4Spec.actionDeclarationIR := ⟨NanoP4Spec.actionDeclarationIR.ofValue⟩

inductive parserDeclarationIR where
  | PARSER_lparen_rparen_lbrace_rbrace
      (nameIR : NanoP4Spec.nameIR)
      (parameterIR : List NanoP4Spec.parameterIR)
      (parserLocalDeclarationList : NanoP4Spec.parserLocalDeclarationList)
      (parserStateList : NanoP4Spec.parserStateList)

def parserDeclarationIR.toValue : NanoP4Spec.parserDeclarationIR → Lang.Il.value
  | .PARSER_lparen_rparen_lbrace_rbrace x0 x1 x2 x3 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "parserDeclarationIR")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "PARSER"))),
            (.Arg (ToValue.toValue x0)),
            (.Brack
               (Prelude.Value.atom .LParen)
               (.Arg (ToValue.toValue x1))
               (Prelude.Value.atom .RParen)),
            (.Brack
               (Prelude.Value.atom .LBrace)
               (.Seq [(.Arg (ToValue.toValue x2)), (.Arg (ToValue.toValue x3))])
               (Prelude.Value.atom .RBrace))])

instance : ToValue NanoP4Spec.parserDeclarationIR := ⟨NanoP4Spec.parserDeclarationIR.toValue⟩
instance : BEq NanoP4Spec.parserDeclarationIR := ⟨valueEq⟩

def parserDeclarationIR.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.parserDeclarationIR
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0, a1, a2, a3] :=
             Prelude.Value.caseArgs
               c
               (.Seq
                  [(.Atom (Prelude.Value.atom (.Keyword "PARSER"))),
                   (.Arg ()),
                   (.Brack (Prelude.Value.atom .LParen) (.Arg ()) (Prelude.Value.atom .RParen)),
                   (.Brack
                      (Prelude.Value.atom .LBrace)
                      (.Seq [(.Arg ()), (.Arg ())])
                      (Prelude.Value.atom .RBrace))]) | none
         pure (NanoP4Spec.parserDeclarationIR.PARSER_lparen_rparen_lbrace_rbrace
            (← OfValue.ofValue fuel a0)
            (← OfValue.ofValue fuel a1)
            (← OfValue.ofValue fuel a2)
            (← OfValue.ofValue fuel a3)))
    | _ => none

instance : OfValue NanoP4Spec.parserDeclarationIR := ⟨NanoP4Spec.parserDeclarationIR.ofValue⟩

inductive controlDeclarationIR where
  | CONTROL_lparen_rparen_lbrace_APPLY_rbrace
      (nameIR : NanoP4Spec.nameIR)
      (parameterIR : List NanoP4Spec.parameterIR)
      (controlLocalDeclarationList : NanoP4Spec.controlLocalDeclarationList)
      (controlBody : NanoP4Spec.controlBody)

def controlDeclarationIR.toValue : NanoP4Spec.controlDeclarationIR → Lang.Il.value
  | .CONTROL_lparen_rparen_lbrace_APPLY_rbrace x0 x1 x2 x3 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "controlDeclarationIR")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "CONTROL"))),
            (.Arg (ToValue.toValue x0)),
            (.Brack
               (Prelude.Value.atom .LParen)
               (.Arg (ToValue.toValue x1))
               (Prelude.Value.atom .RParen)),
            (.Brack
               (Prelude.Value.atom .LBrace)
               (.Seq
                  [(.Arg (ToValue.toValue x2)),
                   (.Atom (Prelude.Value.atom (.Keyword "APPLY"))),
                   (.Arg (ToValue.toValue x3))])
               (Prelude.Value.atom .RBrace))])

instance : ToValue NanoP4Spec.controlDeclarationIR := ⟨NanoP4Spec.controlDeclarationIR.toValue⟩
instance : BEq NanoP4Spec.controlDeclarationIR := ⟨valueEq⟩

def controlDeclarationIR.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.controlDeclarationIR
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0, a1, a2, a3] :=
             Prelude.Value.caseArgs
               c
               (.Seq
                  [(.Atom (Prelude.Value.atom (.Keyword "CONTROL"))),
                   (.Arg ()),
                   (.Brack (Prelude.Value.atom .LParen) (.Arg ()) (Prelude.Value.atom .RParen)),
                   (.Brack
                      (Prelude.Value.atom .LBrace)
                      (.Seq [(.Arg ()), (.Atom (Prelude.Value.atom (.Keyword "APPLY"))), (.Arg ())])
                      (Prelude.Value.atom .RBrace))]) | none
         pure (NanoP4Spec.controlDeclarationIR.CONTROL_lparen_rparen_lbrace_APPLY_rbrace
            (← OfValue.ofValue fuel a0)
            (← OfValue.ofValue fuel a1)
            (← OfValue.ofValue fuel a2)
            (← OfValue.ofValue fuel a3)))
    | _ => none

instance : OfValue NanoP4Spec.controlDeclarationIR := ⟨NanoP4Spec.controlDeclarationIR.ofValue⟩

inductive callableDef where
  | ACTION_lparen_rparen
      (nameIR : NanoP4Spec.nameIR)
      (parameterIR : List NanoP4Spec.parameterIR)
      (blockStatement : NanoP4Spec.blockStatement)
  | PARSER_lparen_rparen_lbrace_rbrace
      (nameIR : NanoP4Spec.nameIR)
      (parameterIR : List NanoP4Spec.parameterIR)
      (parserLocalDeclarationList : NanoP4Spec.parserLocalDeclarationList)
      (parserStateList : NanoP4Spec.parserStateList)
  | CONTROL_lparen_rparen_lbrace_APPLY_rbrace
      (nameIR : NanoP4Spec.nameIR)
      (parameterIR : List NanoP4Spec.parameterIR)
      (controlLocalDeclarationList : NanoP4Spec.controlLocalDeclarationList)
      (controlBody : NanoP4Spec.controlBody)

def callableDef.toValue : NanoP4Spec.callableDef → Lang.Il.value
  | .ACTION_lparen_rparen x0 x1 x2 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "callableDef")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "ACTION"))),
            (.Arg (ToValue.toValue x0)),
            (.Brack
               (Prelude.Value.atom .LParen)
               (.Arg (ToValue.toValue x1))
               (Prelude.Value.atom .RParen)),
            (.Arg (ToValue.toValue x2))])
  | .PARSER_lparen_rparen_lbrace_rbrace x0 x1 x2 x3 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "callableDef")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "PARSER"))),
            (.Arg (ToValue.toValue x0)),
            (.Brack
               (Prelude.Value.atom .LParen)
               (.Arg (ToValue.toValue x1))
               (Prelude.Value.atom .RParen)),
            (.Brack
               (Prelude.Value.atom .LBrace)
               (.Seq [(.Arg (ToValue.toValue x2)), (.Arg (ToValue.toValue x3))])
               (Prelude.Value.atom .RBrace))])
  | .CONTROL_lparen_rparen_lbrace_APPLY_rbrace x0 x1 x2 x3 =>
      Runtime.Value.Make.case
        (Prelude.Value.varT "callableDef")
        (.Seq
           [(.Atom (Prelude.Value.atom (.Keyword "CONTROL"))),
            (.Arg (ToValue.toValue x0)),
            (.Brack
               (Prelude.Value.atom .LParen)
               (.Arg (ToValue.toValue x1))
               (Prelude.Value.atom .RParen)),
            (.Brack
               (Prelude.Value.atom .LBrace)
               (.Seq
                  [(.Arg (ToValue.toValue x2)),
                   (.Atom (Prelude.Value.atom (.Keyword "APPLY"))),
                   (.Arg (ToValue.toValue x3))])
               (Prelude.Value.atom .RBrace))])

instance : ToValue NanoP4Spec.callableDef := ⟨NanoP4Spec.callableDef.toValue⟩
instance : BEq NanoP4Spec.callableDef := ⟨valueEq⟩

def callableDef.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.callableDef
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .CaseV c =>
      (do
         let some [a0, a1, a2] :=
             Prelude.Value.caseArgs
               c
               (.Seq
                  [(.Atom (Prelude.Value.atom (.Keyword "ACTION"))),
                   (.Arg ()),
                   (.Brack (Prelude.Value.atom .LParen) (.Arg ()) (Prelude.Value.atom .RParen)),
                   (.Arg ())]) | none
         pure (NanoP4Spec.callableDef.ACTION_lparen_rparen
            (← OfValue.ofValue fuel a0)
            (← OfValue.ofValue fuel a1)
            (← OfValue.ofValue fuel a2))) <|>
      ((do
          let some [a0, a1, a2, a3] :=
              Prelude.Value.caseArgs
                c
                (.Seq
                   [(.Atom (Prelude.Value.atom (.Keyword "PARSER"))),
                    (.Arg ()),
                    (.Brack (Prelude.Value.atom .LParen) (.Arg ()) (Prelude.Value.atom .RParen)),
                    (.Brack
                       (Prelude.Value.atom .LBrace)
                       (.Seq [(.Arg ()), (.Arg ())])
                       (Prelude.Value.atom .RBrace))]) | none
          pure (NanoP4Spec.callableDef.PARSER_lparen_rparen_lbrace_rbrace
             (← OfValue.ofValue fuel a0)
             (← OfValue.ofValue fuel a1)
             (← OfValue.ofValue fuel a2)
             (← OfValue.ofValue fuel a3))) <|>
       (do
          let some [a0, a1, a2, a3] :=
              Prelude.Value.caseArgs
                c
                (.Seq
                   [(.Atom (Prelude.Value.atom (.Keyword "CONTROL"))),
                    (.Arg ()),
                    (.Brack (Prelude.Value.atom .LParen) (.Arg ()) (Prelude.Value.atom .RParen)),
                    (.Brack
                       (Prelude.Value.atom .LBrace)
                       (.Seq
                          [(.Arg ()), (.Atom (Prelude.Value.atom (.Keyword "APPLY"))), (.Arg ())])
                       (Prelude.Value.atom .RBrace))]) | none
          pure (NanoP4Spec.callableDef.CONTROL_lparen_rparen_lbrace_APPLY_rbrace
             (← OfValue.ofValue fuel a0)
             (← OfValue.ofValue fuel a1)
             (← OfValue.ofValue fuel a2)
             (← OfValue.ofValue fuel a3))))
    | _ => none

instance : OfValue NanoP4Spec.callableDef := ⟨NanoP4Spec.callableDef.ofValue⟩

abbrev callableDefEnv : Type := NanoP4Spec.map NanoP4Spec.callableId NanoP4Spec.callableDef

def callableDefEnv.toValue (x : NanoP4Spec.callableDefEnv) : Lang.Il.value := ToValue.toValue x

instance : ToValue NanoP4Spec.callableDefEnv := ⟨NanoP4Spec.callableDefEnv.toValue⟩
instance : BEq NanoP4Spec.callableDefEnv := ⟨valueEq⟩

def callableDefEnv.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.callableDefEnv
  | 0, _ => none
  | fuel + 1, v => OfValue.ofValue fuel v

instance : OfValue NanoP4Spec.callableDefEnv := ⟨NanoP4Spec.callableDefEnv.ofValue⟩

structure globalLoadLayer where
  CALLABLE_TYPE : NanoP4Spec.callableTypeDefEnv
  CALLABLE : NanoP4Spec.callableDefEnv
  PARSER : Option NanoP4Spec.parserDeclarationIR
  CONTROL : Option NanoP4Spec.controlDeclarationIR

def globalLoadLayer.toValue : NanoP4Spec.globalLoadLayer → Lang.Il.value
  | ⟨x0, x1, x2, x3⟩ =>
      Runtime.Value.Make.str
        (Prelude.Value.varT "globalLoadLayer")
        [("CALLABLE_TYPE", ToValue.toValue x0),
         ("CALLABLE", ToValue.toValue x1),
         ("PARSER", ToValue.toValue x2),
         ("CONTROL", ToValue.toValue x3)]

instance : ToValue NanoP4Spec.globalLoadLayer := ⟨NanoP4Spec.globalLoadLayer.toValue⟩
instance : BEq NanoP4Spec.globalLoadLayer := ⟨valueEq⟩

def globalLoadLayer.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.globalLoadLayer
  | 0, _ => none
  | fuel + 1, v => match v.it with
    | .StructV [(_, f0), (_, f1), (_, f2), (_, f3)] =>
      (do
         pure ⟨(← OfValue.ofValue
           fuel
           f0), (← OfValue.ofValue
           fuel
           f1), (← OfValue.ofValue fuel f2), (← OfValue.ofValue fuel f3)⟩)
    | _ => none

instance : OfValue NanoP4Spec.globalLoadLayer := ⟨NanoP4Spec.globalLoadLayer.ofValue⟩

abbrev loadContext : Type := NanoP4Spec.globalLoadLayer

def loadContext.toValue (x : NanoP4Spec.loadContext) : Lang.Il.value := ToValue.toValue x

instance : ToValue NanoP4Spec.loadContext := ⟨NanoP4Spec.loadContext.toValue⟩
instance : BEq NanoP4Spec.loadContext := ⟨valueEq⟩

def loadContext.ofValue : Nat → Lang.Il.value → Option NanoP4Spec.loadContext
  | 0, _ => none
  | fuel + 1, v => OfValue.ofValue fuel v

instance : OfValue NanoP4Spec.loadContext := ⟨NanoP4Spec.loadContext.ofValue⟩

def parserDeclarationIR.to_callableDef : NanoP4Spec.parserDeclarationIR → NanoP4Spec.callableDef
  | .PARSER_lparen_rparen_lbrace_rbrace x0 x1 x2 x3 =>
    .PARSER_lparen_rparen_lbrace_rbrace x0 x1 x2 x3

def callableDef.of_parserDeclarationIR :
    NanoP4Spec.callableDef → Option NanoP4Spec.parserDeclarationIR
  | .PARSER_lparen_rparen_lbrace_rbrace x0 x1 x2 x3 =>
    some (.PARSER_lparen_rparen_lbrace_rbrace x0 x1 x2 x3)
  | _ => none

def callableDef.is_parserDeclarationIR : NanoP4Spec.callableDef → Bool
  | .PARSER_lparen_rparen_lbrace_rbrace _ _ _ _ => true
  | _ => false

def controlDeclarationIR.to_callableDef : NanoP4Spec.controlDeclarationIR → NanoP4Spec.callableDef
  | .CONTROL_lparen_rparen_lbrace_APPLY_rbrace x0 x1 x2 x3 =>
    .CONTROL_lparen_rparen_lbrace_APPLY_rbrace x0 x1 x2 x3

def callableDef.of_controlDeclarationIR :
    NanoP4Spec.callableDef → Option NanoP4Spec.controlDeclarationIR
  | .CONTROL_lparen_rparen_lbrace_APPLY_rbrace x0 x1 x2 x3 =>
    some (.CONTROL_lparen_rparen_lbrace_APPLY_rbrace x0 x1 x2 x3)
  | _ => none

def callableDef.is_controlDeclarationIR : NanoP4Spec.callableDef → Bool
  | .CONTROL_lparen_rparen_lbrace_APPLY_rbrace _ _ _ _ => true
  | _ => false

def actionDeclarationIR.to_callableDef : NanoP4Spec.actionDeclarationIR → NanoP4Spec.callableDef
  | .ACTION_lparen_rparen x0 x1 x2 => .ACTION_lparen_rparen x0 x1 x2

def callableDef.of_actionDeclarationIR :
    NanoP4Spec.callableDef → Option NanoP4Spec.actionDeclarationIR
  | .ACTION_lparen_rparen x0 x1 x2 => some (.ACTION_lparen_rparen x0 x1 x2)
  | _ => none

def callableDef.is_actionDeclarationIR : NanoP4Spec.callableDef → Bool
  | .ACTION_lparen_rparen _ _ _ => true
  | _ => false

def «$empty_callableDefEnv»
    : Option (Except Fail (NanoP4Spec.map NanoP4Spec.callableId NanoP4Spec.callableDef)) :=
  ExceptT.run
    (do
       let tmp_0 ←
           ExceptT.mk
             (NanoP4Spec.«$empty_map» (τK := NanoP4Spec.callableId) (τV := NanoP4Spec.callableDef))
       pure tmp_0)

def «$empty_callableDefEnv».al : Lang.Al.def :=
  Q.d
    (.FuncDecD
       (Q.i "empty_callableDefEnv")
       []
       []
       (Q.t (Q.varT "map" [Q.t (Q.varT "callableId" []), Q.t (Q.varT "callableDef" [])]))
       [Q.cl
          []
          (Q.e
             (.CallE
                (Q.i "empty_map")
                [Q.t (Q.varT "callableId" []), Q.t (Q.varT "callableDef" [])]
                [])
             (Q.varT "map" [Q.t (Q.varT "callableId" []), Q.t (Q.varT "callableDef" [])]))
          []]
       none
       [])

def «$make_loadContext» (p0 : NanoP4Spec.typingContext)
    : Option (Except Fail NanoP4Spec.loadContext) :=
  ExceptT.run
    (do
       have TC := p0
       let tmp_0 ← ExceptT.mk NanoP4Spec.«$empty_callableDefEnv»
       have LC :=
           ({
              CALLABLE_TYPE := TC.GLOBAL.CALLABLE,
              CALLABLE := tmp_0,
              PARSER := (none : Option NanoP4Spec.parserDeclarationIR),
              CONTROL := (none : Option
                 NanoP4Spec.controlDeclarationIR), } : NanoP4Spec.globalLoadLayer)
       pure LC)

def «$make_loadContext».al : Lang.Al.def :=
  Q.d
    (.FuncDecD
       (Q.i "make_loadContext")
       []
       [Q.pm (.ExpP (Q.t (Q.varT "typingContext" [])))]
       (Q.t (Q.varT "loadContext" []))
       [Q.cl
          [Q.ar (.ExpA (Q.e (.VarE (Q.i "TC")) (Q.varT "typingContext" [])))]
          (Q.e (.VarE (Q.i "LC")) (Q.varT "loadContext" []))
          [Q.pr
             (.LetPr
                (Q.e (.VarE (Q.i "LC")) (Q.varT "loadContext" []))
                (Q.e
                   (.StrE
                      [(Q.a (.Keyword "CALLABLE_TYPE"),
                        Q.e
                          (.DotE
                             (Q.e
                                (.DotE
                                   (Q.e (.VarE (Q.i "TC")) (Q.varT "typingContext" []))
                                   (Q.a (.Keyword "GLOBAL")))
                                (Q.varT "globalTypingLayer" []))
                             (Q.a (.Keyword "CALLABLE")))
                          (Q.varT "callableTypeDefEnv" [])),
                       (Q.a (.Keyword "CALLABLE"),
                        Q.e
                          (.CallE (Q.i "empty_callableDefEnv") [] [])
                          (Q.varT
                             "map"
                             [Q.t (Q.varT "callableId" []), Q.t (Q.varT "callableDef" [])])),
                       (Q.a (.Keyword "PARSER"),
                        Q.e (.OptE none) (.IterT (Q.t (Q.varT "parserDeclarationIR" [])) .Opt)),
                       (Q.a (.Keyword "CONTROL"),
                        Q.e (.OptE none) (.IterT (Q.t (Q.varT "controlDeclarationIR" [])) .Opt))])
                   (Q.varT "globalLoadLayer" [])))]]
       none
       [])

def «$find_callableDef_l» (p0 : NanoP4Spec.loadContext) (p1 : NanoP4Spec.callableId)
    : Option (Except Fail NanoP4Spec.callableDef) :=
  ExceptT.run
    (do
       have LC := p0
       have callableId := p1
       let tmp_0 ←
           ExceptT.mk
             (NanoP4Spec.«$find_map»
                (τK := NanoP4Spec.callableId)
                (τV := NanoP4Spec.callableDef)
                LC.CALLABLE
                callableId)
       have callableDef'? := tmp_0
       let _ ← Eval.check (Option.isSome callableDef'?)
       let some callableDef := callableDef'? | throw Fail.err
       pure callableDef)

def «$find_callableDef_l».al : Lang.Al.def :=
  Q.d
    (.FuncDecD
       (Q.i "find_callableDef_l")
       []
       [Q.pm (.ExpP (Q.t (Q.varT "loadContext" []))), Q.pm (.ExpP (Q.t (Q.varT "callableId" [])))]
       (Q.t (Q.varT "callableDef" []))
       [Q.cl
          [Q.ar (.ExpA (Q.e (.VarE (Q.i "LC")) (Q.varT "loadContext" []))),
           Q.ar (.ExpA (Q.e (.VarE (Q.i "callableId")) (Q.varT "callableId" [])))]
          (Q.e (.VarE (Q.i "callableDef")) (Q.varT "callableDef" []))
          [Q.pr
             (.LetPr
                (Q.e
                   (.IterE
                      (Q.e (.VarE (Q.i "callableDef'")) (Q.varT "callableDef" []))
                      (.mk
                         .Opt
                         [Q.v "callableDef'" (.IterT (Q.t (Q.varT "callableDef" [])) .Opt) []]))
                   (.IterT (Q.t (Q.varT "callableDef" [])) .Opt))
                (Q.e
                   (.CallE
                      (Q.i "find_map")
                      [Q.t (Q.varT "callableId" []), Q.t (Q.varT "callableDef" [])]
                      [Q.ar
                         (.ExpA
                            (Q.e
                               (.DotE
                                  (Q.e (.VarE (Q.i "LC")) (Q.varT "loadContext" []))
                                  (Q.a (.Keyword "CALLABLE")))
                               (Q.varT "callableDefEnv" []))),
                       Q.ar (.ExpA (Q.e (.VarE (Q.i "callableId")) (Q.varT "callableId" [])))])
                   (.IterT (Q.t (Q.varT "callableDef" [])) .Opt))),
           Q.pr
             (.IfPr
                (Q.e
                   (.MatchE
                      (Q.e
                         (.IterE
                            (Q.e (.VarE (Q.i "callableDef'")) (Q.varT "callableDef" []))
                            (.mk
                               .Opt
                               [Q.v
                                  "callableDef'"
                                  (.IterT (Q.t (Q.varT "callableDef" [])) .Opt)
                                  []]))
                         (.IterT (Q.t (Q.varT "callableDef" [])) .Opt))
                      (.OptP .Some))
                   .BoolT)),
           Q.pr
             (.LetPr
                (Q.e
                   (.OptE (some (Q.e (.VarE (Q.i "callableDef")) (Q.varT "callableDef" []))))
                   (.IterT (Q.t (Q.varT "callableDef" [])) .Opt))
                (Q.e
                   (.IterE
                      (Q.e (.VarE (Q.i "callableDef'")) (Q.varT "callableDef" []))
                      (.mk
                         .Opt
                         [Q.v "callableDef'" (.IterT (Q.t (Q.varT "callableDef" [])) .Opt) []]))
                   (.IterT (Q.t (Q.varT "callableDef" [])) .Opt)))]]
       none
       [])

def «$add_callableDef_l»
        (p0 : NanoP4Spec.loadContext)
        (p1 : NanoP4Spec.callableId)
        (p2 : NanoP4Spec.callableDef)
    : Option (Except Fail NanoP4Spec.loadContext) :=
  ExceptT.run
    (do
       have LC := p0
       have callableId := p1
       have callableDef := p2
       have callableDefEnv := LC.CALLABLE
       let tmp_0 ←
           ExceptT.mk
             (NanoP4Spec.«$dom_map»
                (τK := NanoP4Spec.callableId)
                (τV := NanoP4Spec.callableDef)
                callableDefEnv)
       let tmp_1 ← ExceptT.mk (NanoP4Spec.«$in_set» (τK := NanoP4Spec.callableId) tmp_0 callableId)
       let _ ← Eval.check (!tmp_1)
       let tmp_2 ←
           ExceptT.mk
             (NanoP4Spec.«$add_map»
                (τK := NanoP4Spec.callableId)
                (τV := NanoP4Spec.callableDef)
                callableDefEnv
                callableId
                callableDef)
       have callableDefEnv' := tmp_2
       have LC' :=
           { LC with
             CALLABLE := callableDefEnv', }
       pure LC')

def «$add_callableDef_l».al : Lang.Al.def :=
  Q.d
    (.FuncDecD
       (Q.i "add_callableDef_l")
       []
       [Q.pm (.ExpP (Q.t (Q.varT "loadContext" []))),
        Q.pm (.ExpP (Q.t (Q.varT "callableId" []))),
        Q.pm (.ExpP (Q.t (Q.varT "callableDef" [])))]
       (Q.t (Q.varT "loadContext" []))
       [Q.cl
          [Q.ar (.ExpA (Q.e (.VarE (Q.i "LC")) (Q.varT "loadContext" []))),
           Q.ar (.ExpA (Q.e (.VarE (Q.i "callableId")) (Q.varT "callableId" []))),
           Q.ar (.ExpA (Q.e (.VarE (Q.i "callableDef")) (Q.varT "callableDef" [])))]
          (Q.e (.VarE (Q.i "LC'")) (Q.varT "loadContext" []))
          [Q.pr
             (.LetPr
                (Q.e (.VarE (Q.i "callableDefEnv")) (Q.varT "callableDefEnv" []))
                (Q.e
                   (.DotE
                      (Q.e (.VarE (Q.i "LC")) (Q.varT "loadContext" []))
                      (Q.a (.Keyword "CALLABLE")))
                   (Q.varT "callableDefEnv" []))),
           Q.pr
             (.IfPr
                (Q.e
                   (.UnE
                      .NotOp
                      .BoolT
                      (Q.e
                         (.CallE
                            (Q.i "in_set")
                            [Q.t (Q.varT "callableId" [])]
                            [Q.ar
                               (.ExpA
                                  (Q.e
                                     (.CallE
                                        (Q.i "dom_map")
                                        [Q.t (Q.varT "callableId" []),
                                         Q.t (Q.varT "callableDef" [])]
                                        [Q.ar
                                           (.ExpA
                                              (Q.e
                                                 (.VarE (Q.i "callableDefEnv"))
                                                 (Q.varT "callableDefEnv" [])))])
                                     (Q.varT "set" [Q.t (Q.varT "callableId" [])]))),
                             Q.ar
                               (.ExpA (Q.e (.VarE (Q.i "callableId")) (Q.varT "callableId" [])))])
                         .BoolT))
                   .BoolT)),
           Q.pr
             (.LetPr
                (Q.e (.VarE (Q.i "callableDefEnv'")) (Q.varT "callableDefEnv" []))
                (Q.e
                   (.CallE
                      (Q.i "add_map")
                      [Q.t (Q.varT "callableId" []), Q.t (Q.varT "callableDef" [])]
                      [Q.ar
                         (.ExpA (Q.e (.VarE (Q.i "callableDefEnv")) (Q.varT "callableDefEnv" []))),
                       Q.ar (.ExpA (Q.e (.VarE (Q.i "callableId")) (Q.varT "callableId" []))),
                       Q.ar (.ExpA (Q.e (.VarE (Q.i "callableDef")) (Q.varT "callableDef" [])))])
                   (Q.varT "map" [Q.t (Q.varT "callableId" []), Q.t (Q.varT "callableDef" [])]))),
           Q.pr
             (.LetPr
                (Q.e (.VarE (Q.i "LC'")) (Q.varT "loadContext" []))
                (Q.e
                   (.UpdE
                      (Q.e (.VarE (Q.i "LC")) (Q.varT "loadContext" []))
                      (Q.pa
                         (.DotP (Q.pa .RootP (Q.varT "loadContext" [])) (Q.a (.Keyword "CALLABLE")))
                         (Q.varT "callableDefEnv" []))
                      (Q.e (.VarE (Q.i "callableDefEnv'")) (Q.varT "callableDefEnv" [])))
                   (Q.varT "loadContext" [])))]]
       none
       [])

def «$find_callableTypeDef_l» (p0 : NanoP4Spec.loadContext) (p1 : NanoP4Spec.callableId)
    : Option (Except Fail NanoP4Spec.callableTypeDef) :=
  ExceptT.run
    (do
       have LC := p0
       have callableId := p1
       let tmp_0 ←
           ExceptT.mk
             (NanoP4Spec.«$find_map»
                (τK := NanoP4Spec.callableId)
                (τV := NanoP4Spec.callableTypeDef)
                LC.CALLABLE_TYPE
                callableId)
       have callableTypeDef'? := tmp_0
       let _ ← Eval.check (Option.isSome callableTypeDef'?)
       let some callableTypeDef := callableTypeDef'? | throw Fail.err
       pure callableTypeDef)

def «$find_callableTypeDef_l».al : Lang.Al.def :=
  Q.d
    (.FuncDecD
       (Q.i "find_callableTypeDef_l")
       []
       [Q.pm (.ExpP (Q.t (Q.varT "loadContext" []))), Q.pm (.ExpP (Q.t (Q.varT "callableId" [])))]
       (Q.t (Q.varT "callableTypeDef" []))
       [Q.cl
          [Q.ar (.ExpA (Q.e (.VarE (Q.i "LC")) (Q.varT "loadContext" []))),
           Q.ar (.ExpA (Q.e (.VarE (Q.i "callableId")) (Q.varT "callableId" [])))]
          (Q.e (.VarE (Q.i "callableTypeDef")) (Q.varT "callableTypeDef" []))
          [Q.pr
             (.LetPr
                (Q.e
                   (.IterE
                      (Q.e (.VarE (Q.i "callableTypeDef'")) (Q.varT "callableTypeDef" []))
                      (.mk
                         .Opt
                         [Q.v
                            "callableTypeDef'"
                            (.IterT (Q.t (Q.varT "callableTypeDef" [])) .Opt)
                            []]))
                   (.IterT (Q.t (Q.varT "callableTypeDef" [])) .Opt))
                (Q.e
                   (.CallE
                      (Q.i "find_map")
                      [Q.t (Q.varT "callableId" []), Q.t (Q.varT "callableTypeDef" [])]
                      [Q.ar
                         (.ExpA
                            (Q.e
                               (.DotE
                                  (Q.e (.VarE (Q.i "LC")) (Q.varT "loadContext" []))
                                  (Q.a (.Keyword "CALLABLE_TYPE")))
                               (Q.varT "callableTypeDefEnv" []))),
                       Q.ar (.ExpA (Q.e (.VarE (Q.i "callableId")) (Q.varT "callableId" [])))])
                   (.IterT (Q.t (Q.varT "callableTypeDef" [])) .Opt))),
           Q.pr
             (.IfPr
                (Q.e
                   (.MatchE
                      (Q.e
                         (.IterE
                            (Q.e (.VarE (Q.i "callableTypeDef'")) (Q.varT "callableTypeDef" []))
                            (.mk
                               .Opt
                               [Q.v
                                  "callableTypeDef'"
                                  (.IterT (Q.t (Q.varT "callableTypeDef" [])) .Opt)
                                  []]))
                         (.IterT (Q.t (Q.varT "callableTypeDef" [])) .Opt))
                      (.OptP .Some))
                   .BoolT)),
           Q.pr
             (.LetPr
                (Q.e
                   (.OptE
                      (some (Q.e (.VarE (Q.i "callableTypeDef")) (Q.varT "callableTypeDef" []))))
                   (.IterT (Q.t (Q.varT "callableTypeDef" [])) .Opt))
                (Q.e
                   (.IterE
                      (Q.e (.VarE (Q.i "callableTypeDef'")) (Q.varT "callableTypeDef" []))
                      (.mk
                         .Opt
                         [Q.v
                            "callableTypeDef'"
                            (.IterT (Q.t (Q.varT "callableTypeDef" [])) .Opt)
                            []]))
                   (.IterT (Q.t (Q.varT "callableTypeDef" [])) .Opt)))]]
       none
       [])

end NanoP4Spec
