-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group bneg
import P4SpecTec.Tactic.Audit
import P4SpecTec.Refine.Builtin.Invoke
import P4SpecTec.Refine.Builtin.Numeric
import NanoP4Spec.Refinement.Spec

/-! # NanoP4Spec.Refinement.bneg

Generated: refinement theorems, group bneg.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

theorem «$bneg».dispatch (p0 : Int)
   (v0 : Lang.Il.value) (h0 : Rel v0 p0) (cfg : Interp_al.Interp.Config) :
  (Interp_al.Effects.builtinEval cfg.printHints "bneg" [] [v0]).run.map (Except.map canon) =
    (NanoP4Spec.«$bneg» p0).map (Except.map (fun x => canon (toValue x))) := by
  rw [Refine.Builtin.Numeric.bnegRun h0 cfg.printHints]
  simp only [Option.map_map, Function.comp_def]
  congr 1
  funext result
  cases result <;> rfl

#audit_axioms NanoP4Spec.«$bneg».dispatch

theorem «$bneg».refines (fuel : Nat) (p0 : Int)
   (v0 : Lang.Il.value) (h0 : Rel v0 p0) (cfg : Interp_al.Interp.Config) (ctx : Interp_al.Ctx.t)
     (internal : Bool) (hguard : cfg.guard = false) (hfenv : ctx.local.fenv = []) (hdecl : Holds
     ctx.global NanoP4Spec.«$bneg».al) :
  Refines Rel (Interp_al.Interp.invoke_func fuel cfg internal ctx (Q.i "bneg") [] [v0])
    (ExceptT.mk (NanoP4Spec.«$bneg» p0)) := by
  exact Refine.Builtin.refinesInvokeOfCanonicalRun fuel cfg hguard ctx internal "bneg" _ _ _ []
    [v0] hfenv hdecl (NanoP4Spec.«$bneg».dispatch p0 v0 h0 cfg)

#audit_axioms NanoP4Spec.«$bneg».refines

theorem «$bneg».realizes (p0 : Int)
   (v0 : Lang.Il.value) (h0 : Rel v0 p0) (cfg : Interp_al.Interp.Config) (ctx : Interp_al.Ctx.t)
     (internal : Bool) (hguard : cfg.guard = false) (hfenv : ctx.local.fenv = []) (hdecl : Holds
     ctx.global NanoP4Spec.«$bneg».al) :
  Realizes Rel (fun fuel => Interp_al.Interp.invoke_func fuel cfg internal ctx (Q.i "bneg") []
    [v0]) (ExceptT.mk (NanoP4Spec.«$bneg» p0)) := by
  exact Refine.Builtin.realizesOfCanonicalRun cfg hguard ctx internal "bneg" _ _ _ [] [v0] hfenv
    hdecl (NanoP4Spec.«$bneg».dispatch p0 v0 h0 cfg)

#audit_axioms NanoP4Spec.«$bneg».realizes

end NanoP4Spec
