-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group flatten_tableActionList
import P4SpecTec.Prelude
import P4SpecTec.Tactic.Audit
import P4SpecTec.Refine.Quote
import P4SpecTec.Refine.Calc
import P4SpecTec.Tactic.Refine
import P4SpecTec.Tactic.Realize
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality

/-! # NanoP4Spec.Refinement.flatten_tableActionList

Generated: refinement theorems, group flatten_tableActionList.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

set_option maxHeartbeats 6000000 in
theorem «$flatten_tableActionList».refines_group :
    ∀ (fuel : Nat),
      (∀ (cfg : Interp_al.Interp.Config) (ctx : Interp_al.Ctx.t) (internal : Bool),
         cfg.guard = false → ctx.local.fenv = [] →
         HoldsSpec NanoP4Spec.spec ctx.global →
         ∀ (v0 : Lang.Il.value)
         (p0 : NanoP4Spec.tableActionList),
         Rel v0 p0 →
         Refines Rel
           (Interp_al.Interp.invoke_func fuel cfg internal ctx
              (Q.i "flatten_tableActionList")
              []
              [v0])
           (ExceptT.mk (NanoP4Spec.«$flatten_tableActionList» p0))) := by
  intro fuel
  induction fuel using Nat.strongRecOn with
  | ind fuel ih => refine_al (subtypes)

#audit_axioms NanoP4Spec.«$flatten_tableActionList».refines_group

set_option maxHeartbeats 6000000 in
theorem «$flatten_tableActionList».refines
    (fuel : Nat)
    (cfg : Interp_al.Interp.Config) (ctx : Interp_al.Ctx.t) (internal : Bool)
    (hguard : cfg.guard = false) (hfenv : ctx.local.fenv = [])
    (hspec : HoldsSpec NanoP4Spec.spec ctx.global)
    (v0 : Lang.Il.value)
    (p0 : NanoP4Spec.tableActionList)
    (h0 : Rel v0 p0) :
    Refines Rel
      (Interp_al.Interp.invoke_func fuel cfg internal ctx (Q.i "flatten_tableActionList") [] [v0])
      (ExceptT.mk (NanoP4Spec.«$flatten_tableActionList» p0)) :=
  (NanoP4Spec.«$flatten_tableActionList».refines_group fuel)
    cfg
    ctx
    internal
    hguard
    hfenv
    hspec
    v0
    p0
    h0

#audit_axioms NanoP4Spec.«$flatten_tableActionList».refines

private def «$flatten_tableActionList».realizesMotive
    (p0 : NanoP4Spec.tableActionList)
    (q : Except Fail (List NanoP4Spec.tableAction)) : Prop :=
  ∀ (cfg : Interp_al.Interp.Config) (ctx : Interp_al.Ctx.t) (internal : Bool),
    cfg.guard = false → ctx.local.fenv = [] →
    HoldsSpec NanoP4Spec.spec ctx.global →
    ∀ (v0 : Lang.Il.value),
    Rel v0 p0 →
    ∃ r, EventuallyRuns (fun fuel => (Interp_al.Interp.invoke_func fuel cfg internal ctx
        (Q.i "flatten_tableActionList")
        []
        [v0])) r ∧
    ResRel Rel r q

set_option maxHeartbeats 6000000 in
theorem «$flatten_tableActionList».realizes
    (cfg : Interp_al.Interp.Config) (ctx : Interp_al.Ctx.t) (internal : Bool)
    (hguard : cfg.guard = false) (hfenv : ctx.local.fenv = [])
    (hspec : HoldsSpec NanoP4Spec.spec ctx.global)
    (v0 : Lang.Il.value)
    (p0 : NanoP4Spec.tableActionList)
    (h0 : Rel v0 p0) :
    Realizes Rel
      (fun fuel => (Interp_al.Interp.invoke_func fuel cfg internal ctx
          (Q.i "flatten_tableActionList")
          []
          [v0]))
      (ExceptT.mk (NanoP4Spec.«$flatten_tableActionList» p0)) := by
  intro q hq
  exact NanoP4Spec.«$flatten_tableActionList».partial_correctness
    (motive := «$flatten_tableActionList».realizesMotive) (by
      intro rec ih p0 q hq cfg ctx internal hguard hfenv hspec v0 h0
      realize_step (relations) hq)
    p0 q hq cfg ctx internal hguard hfenv hspec v0 h0

#audit_axioms NanoP4Spec.«$flatten_tableActionList».realizes

end NanoP4Spec
