-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group flatten_tableEntryList
import P4SpecTec.Prelude
import P4SpecTec.Tactic.Audit
import P4SpecTec.Refine.Quote
import P4SpecTec.Refine.Calc
import P4SpecTec.Tactic.Refine
import NanoP4Spec.Refinement.Spec

/-! # NanoP4Spec.Refinement.flatten_tableEntryList

Generated: refinement theorems, group flatten_tableEntryList.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

theorem «$flatten_tableEntryList».refines_group :
    ∀ (fuel : Nat),
      (∀ (cfg : Interp_al.Interp.Config) (ctx : Interp_al.Ctx.t) (internal : Bool),
         cfg.guard = false → ctx.local.fenv = [] →
         HoldsSpec NanoP4Spec.spec ctx.global →
         ∀ (v0 : Lang.Il.value)
         (p0 : NanoP4Spec.tableEntryList),
         Rel v0 p0 →
         Refines Rel
           (Interp_al.Interp.invoke_func fuel cfg internal ctx
              (Q.i "flatten_tableEntryList")
              []
              [v0])
           (ExceptT.mk (NanoP4Spec.«$flatten_tableEntryList» p0))) := by
  intro fuel
  induction fuel using Nat.strongRecOn with
  | ind fuel ih => refine_al

theorem «$flatten_tableEntryList».refines
    (fuel : Nat)
    (cfg : Interp_al.Interp.Config) (ctx : Interp_al.Ctx.t) (internal : Bool)
    (hguard : cfg.guard = false) (hfenv : ctx.local.fenv = [])
    (hspec : HoldsSpec NanoP4Spec.spec ctx.global)
    (v0 : Lang.Il.value)
    (p0 : NanoP4Spec.tableEntryList)
    (h0 : Rel v0 p0) :
    Refines Rel
      (Interp_al.Interp.invoke_func fuel cfg internal ctx (Q.i "flatten_tableEntryList") [] [v0])
      (ExceptT.mk (NanoP4Spec.«$flatten_tableEntryList» p0)) :=
  (NanoP4Spec.«$flatten_tableEntryList».refines_group fuel)
    cfg
    ctx
    internal
    hguard
    hfenv
    hspec
    v0
    p0
    h0

#audit_axioms NanoP4Spec.«$flatten_tableEntryList».refines

end NanoP4Spec
