-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group in_set
import P4SpecTec.Prelude
import P4SpecTec.Tactic.Audit
import P4SpecTec.Refine.Quote
import P4SpecTec.Refine.Calc
import P4SpecTec.Tactic.Refine
import P4SpecTec.Tactic.Realize
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality

/-! # NanoP4Spec.Refinement.in_set

Generated: refinement theorems, group in_set.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

theorem «$in_set».refines
    (fuel : Nat)
    {τK : Type}
    [ToValue τK] [BEq τK]
    [Representation.ValueBEq τK]
    (cfg : Interp_al.Interp.Config) (ctx : Interp_al.Ctx.t) (internal : Bool)
    (hguard : cfg.guard = false) (hfenv : ctx.local.fenv = [])
    (hspec : HoldsSpec NanoP4Spec.spec ctx.global)
    (t0 : Lang.Il.typ)
    (ht0 : ctx.global.tdtbl.get? "K" = none)
    (v0 v1 : Lang.Il.value)
    (p0 : NanoP4Spec.set τK)
    (p1 : τK)
    (h0 : Rel v0 p0)
    (h1 : Rel v1 p1) :
    Refines Rel
      (Interp_al.Interp.invoke_func fuel cfg internal ctx (Q.i "in_set") [t0] [v0, v1])
      (ExceptT.mk (NanoP4Spec.«$in_set» (τK := τK) p0 p1)) :=
  by refine_al

#audit_axioms NanoP4Spec.«$in_set».refines

theorem «$in_set».realizes
    {τK : Type}
    [ToValue τK] [BEq τK]
    [Representation.ValueBEq τK]
    (cfg : Interp_al.Interp.Config) (ctx : Interp_al.Ctx.t) (internal : Bool)
    (hguard : cfg.guard = false) (hfenv : ctx.local.fenv = [])
    (hspec : HoldsSpec NanoP4Spec.spec ctx.global)
    (t0 : Lang.Il.typ)
    (ht0 : ctx.global.tdtbl.get? "K" = none)
    (v0 v1 : Lang.Il.value)
    (p0 : NanoP4Spec.set τK)
    (p1 : τK)
    (h0 : Rel v0 p0)
    (h1 : Rel v1 p1) :
    Realizes Rel
      (fun fuel => (Interp_al.Interp.invoke_func fuel cfg internal ctx
          (Q.i "in_set")
          [t0]
          [v0, v1]))
      (ExceptT.mk (NanoP4Spec.«$in_set» (τK := τK) p0 p1)) := by
  realize_al

#audit_axioms NanoP4Spec.«$in_set».realizes

end NanoP4Spec
