-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group TableActionList_ok
import P4SpecTec.Prelude
import P4SpecTec.Tactic.Audit
import P4SpecTec.Refine.Quote
import P4SpecTec.Refine.Calc
import P4SpecTec.Tactic.Refine
import P4SpecTec.Tactic.Realize
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality
import NanoP4Spec.Refinement.flatten_tableActionList
import NanoP4Spec.Refinement.TableActions_ok
import NanoP4Spec.Refinement.distinct_

/-! # NanoP4Spec.Refinement.TableActionList_ok

Generated: refinement theorems, group TableActionList_ok.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

set_option maxHeartbeats 6000000 in
theorem TableActionList_ok.refines
    (fuel : Nat)
    (cfg : Interp_al.Interp.Config) (ctx : Interp_al.Ctx.t) (internal : Bool)
    (hguard : cfg.guard = false) (hhints : cfg.printHints = []) (_hfenv : ctx.local.fenv = [])
    (hspec : HoldsSpec NanoP4Spec.spec ctx.global)
    (v0 v1 : Lang.Il.value)
    (p0 : NanoP4Spec.typingContext)
    (p1 : NanoP4Spec.tableActionList)
    (h0 : Rel v0 p0)
    (h1 : Rel v1 p1) :
    Refines (fun vs (o : List NanoP4Spec.matchAction) => Outs vs [toValue o])
      (Interp_al.Interp.invoke_rel fuel cfg internal ctx (Q.i "TableActionList_ok") [v0, v1])
      (ExceptT.mk (NanoP4Spec.TableActionList_ok.run p0 p1)) :=
  by refine_al (columns)

#audit_axioms NanoP4Spec.TableActionList_ok.refines

set_option maxHeartbeats 6000000 in
theorem TableActionList_ok.realizes
    (cfg : Interp_al.Interp.Config) (ctx : Interp_al.Ctx.t) (internal : Bool)
    (hguard : cfg.guard = false) (hhints : cfg.printHints = []) (_hfenv : ctx.local.fenv = [])
    (hspec : HoldsSpec NanoP4Spec.spec ctx.global)
    (v0 v1 : Lang.Il.value)
    (p0 : NanoP4Spec.typingContext)
    (p1 : NanoP4Spec.tableActionList)
    (h0 : Rel v0 p0)
    (h1 : Rel v1 p1) :
    Realizes (fun vs (o : List NanoP4Spec.matchAction) => Outs vs [toValue o])
      (fun fuel => (Interp_al.Interp.invoke_rel fuel cfg internal ctx
          (Q.i "TableActionList_ok")
          [v0, v1]))
      (ExceptT.mk (NanoP4Spec.TableActionList_ok.run p0 p1)) := by
  realize_al (columns)

#audit_axioms NanoP4Spec.TableActionList_ok.realizes

end NanoP4Spec
