-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group CallAdmission.ActionDecl_ok
import P4SpecTec.Refine.Representation.Delay
import P4SpecTec.Refine.Representation.Source
import P4SpecTec.Refine.Representation.SourceAlias
import P4SpecTec.Refine.Representation.SourceAtomic
import P4SpecTec.Refine.Representation.SourceRecord
import P4SpecTec.Refine.Representation.SourceCodec
import P4SpecTec.Refine.Representation.SourceTuple
import P4SpecTec.Refine.Representation.SourceExtern
import P4SpecTec.Refine.Representation.SourceVariant
import P4SpecTec.Tactic.Audit
import P4SpecTec.Tactic.CarrierInduction
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality
import NanoP4Spec.Refinement.Representation.parameterList
import NanoP4Spec.Refinement.Representation.direction
import NanoP4Spec.Refinement.Representation.name
import NanoP4Spec.Refinement.Representation.typingContext
import NanoP4Spec.Refinement.Representation.callableId
import NanoP4Spec.Refinement.Representation.callableTypeDef
import NanoP4Spec.Refinement.Representation.scope
import NanoP4Spec.Refinement.Representation.parameter
import NanoP4Spec.Refinement.Representation.blockStatement

/-! # NanoP4Spec.Refinement.CallAdmission.ActionDecl_ok

Generated: refinement theorems, group CallAdmission.ActionDecl_ok.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

/-- All values of the actual call argument carriers are source-valid. -/
theorem ActionDecl_ok.callArgumentsSource :
    (∀ x : (NanoP4Spec.parameterList), (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "parameterList" [])).it)
      ((NanoP4Spec.parameterList.toValue) x)) ∧
    (∀ x : (List (NanoP4Spec.direction)), (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (.IterT (Q.t (Q.varT "direction" [])) .List)).it)
      ((@ToValue.toValue (List (NanoP4Spec.direction)) (@P4SpecTec.Prelude.instToValueList
      (NanoP4Spec.direction) ⟨NanoP4Spec.direction.toValue⟩)) x)) ∧
    (∀ x : (NanoP4Spec.name), (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "name" [])).it) ((NanoP4Spec.name.toValue)
      x)) ∧
    (∀ x : (NanoP4Spec.typingContext), (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "typingContext" [])).it)
      ((NanoP4Spec.typingContext.toValue) x)) ∧
    (∀ x : (NanoP4Spec.callableId), (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "callableId" [])).it)
      ((NanoP4Spec.callableId.toValue) x)) ∧
    (∀ x : (NanoP4Spec.callableTypeDef), (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "callableTypeDef" [])).it)
      ((NanoP4Spec.callableTypeDef.toValue) x)) ∧
    (∀ x : (NanoP4Spec.scope), (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "scope" [])).it)
      ((NanoP4Spec.scope.toValue) x)) ∧
    (∀ x : (List (NanoP4Spec.parameter)), (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (.IterT (Q.t (Q.varT "parameter" [])) .List)).it)
      ((@ToValue.toValue (List (NanoP4Spec.parameter)) (@P4SpecTec.Prelude.instToValueList
      (NanoP4Spec.parameter) ⟨NanoP4Spec.parameter.toValue⟩)) x)) ∧
    (∀ x : (NanoP4Spec.blockStatement), (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "blockStatement" [])).it)
      ((NanoP4Spec.blockStatement.toValue) x)) ∧
    True :=
  ⟨(fun x => (@Representation.Codec.encodingValid (NanoP4Spec.parameterList)
    ⟨NanoP4Spec.parameterList.toValue⟩ ⟨NanoP4Spec.parameterList.ofValue⟩
    (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT
    "parameterList" [])).it) (NanoP4Spec.parameterList.admitted)
    (NanoP4Spec.parameterList.codec)) x (((show ∀ x : (NanoP4Spec.parameterList),
    (NanoP4Spec.parameterList.admitted) x from NanoP4Spec.parameterList.admittedAll)) x)), (fun
    x => (@Representation.Codec.encodingValid (List (NanoP4Spec.direction)) ⟨@ToValue.toValue
    (List (NanoP4Spec.direction)) (@P4SpecTec.Prelude.instToValueList (NanoP4Spec.direction)
    ⟨NanoP4Spec.direction.toValue⟩)⟩ ⟨@OfValue.ofValue (List (NanoP4Spec.direction))
    (@P4SpecTec.Prelude.instOfValueList (NanoP4Spec.direction) ⟨NanoP4Spec.direction.ofValue⟩)⟩
    (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t (.IterT
    (Q.t (Q.varT "direction" [])) .List)).it) (fun xs : List (NanoP4Spec.direction) => ∀ x ∈ xs,
    (fun _ => True) x) (@Representation.Source.listCodec NanoP4Spec.spec
    Representation.Source.externDomain (NanoP4Spec.direction) ⟨NanoP4Spec.direction.toValue⟩
    ⟨NanoP4Spec.direction.ofValue⟩ (Q.t (Q.varT "direction" [])) (fun _ => True)
    (NanoP4Spec.direction.sourceCodec))) x (((show ∀ x : (List (NanoP4Spec.direction)), (fun xs
    : List (NanoP4Spec.direction) => ∀ x ∈ xs, (fun _ => True) x) x from (fun xs x _ => ((show ∀
    x : (NanoP4Spec.direction), (fun _ => True) x from NanoP4Spec.direction.admittedAll)) x)))
    x)), (fun x => (@Representation.Codec.encodingValid (NanoP4Spec.name)
    ⟨NanoP4Spec.name.toValue⟩ ⟨NanoP4Spec.name.ofValue⟩ (Representation.Source.Valid
    NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT "name" [])).it)
    (NanoP4Spec.name.admitted) (NanoP4Spec.name.codec)) x (((show ∀ x : (NanoP4Spec.name),
    (NanoP4Spec.name.admitted) x from NanoP4Spec.name.admittedAll)) x)), (fun x =>
    (@Representation.Codec.encodingValid (NanoP4Spec.typingContext)
    ⟨NanoP4Spec.typingContext.toValue⟩ ⟨NanoP4Spec.typingContext.ofValue⟩
    (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT
    "typingContext" [])).it) (NanoP4Spec.typingContext.admitted)
    (NanoP4Spec.typingContext.codec)) x (((show ∀ x : (NanoP4Spec.typingContext),
    (NanoP4Spec.typingContext.admitted) x from NanoP4Spec.typingContext.admittedAll)) x)), (fun
    x => (@Representation.Codec.encodingValid (NanoP4Spec.callableId)
    ⟨NanoP4Spec.callableId.toValue⟩ ⟨NanoP4Spec.callableId.ofValue⟩ (Representation.Source.Valid
    NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT "callableId" [])).it) (fun _
    => True) (NanoP4Spec.callableId.codec)) x (((show ∀ x : (NanoP4Spec.callableId), (fun _ =>
    True) x from NanoP4Spec.callableId.admittedAll)) x)), (fun x =>
    (@Representation.Codec.encodingValid (NanoP4Spec.callableTypeDef)
    ⟨NanoP4Spec.callableTypeDef.toValue⟩ ⟨NanoP4Spec.callableTypeDef.ofValue⟩
    (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT
    "callableTypeDef" [])).it) (NanoP4Spec.callableTypeDef.admitted)
    (NanoP4Spec.callableTypeDef.codec)) x (((show ∀ x : (NanoP4Spec.callableTypeDef),
    (NanoP4Spec.callableTypeDef.admitted) x from NanoP4Spec.callableTypeDef.admittedAll)) x)),
    (fun x => (@Representation.Codec.encodingValid (NanoP4Spec.scope) ⟨NanoP4Spec.scope.toValue⟩
    ⟨NanoP4Spec.scope.ofValue⟩ (Representation.Source.Valid NanoP4Spec.spec
    Representation.Source.externDomain (Q.t (Q.varT "scope" [])).it) (fun _ => True)
    (NanoP4Spec.scope.sourceCodec)) x (((show ∀ x : (NanoP4Spec.scope), (fun _ => True) x from
    NanoP4Spec.scope.admittedAll)) x)), (fun x => (@Representation.Codec.encodingValid (List
    (NanoP4Spec.parameter)) ⟨@ToValue.toValue (List (NanoP4Spec.parameter))
    (@P4SpecTec.Prelude.instToValueList (NanoP4Spec.parameter) ⟨NanoP4Spec.parameter.toValue⟩)⟩
    ⟨@OfValue.ofValue (List (NanoP4Spec.parameter)) (@P4SpecTec.Prelude.instOfValueList
    (NanoP4Spec.parameter) ⟨NanoP4Spec.parameter.ofValue⟩)⟩ (Representation.Source.Valid
    NanoP4Spec.spec Representation.Source.externDomain (Q.t (.IterT (Q.t (Q.varT "parameter"
    [])) .List)).it) (fun xs : List (NanoP4Spec.parameter) => ∀ x ∈ xs,
    (NanoP4Spec.parameter.admitted) x) (@Representation.Source.listCodec NanoP4Spec.spec
    Representation.Source.externDomain (NanoP4Spec.parameter) ⟨NanoP4Spec.parameter.toValue⟩
    ⟨NanoP4Spec.parameter.ofValue⟩ (Q.t (Q.varT "parameter" [])) (NanoP4Spec.parameter.admitted)
    (NanoP4Spec.parameter.codec))) x (((show ∀ x : (List (NanoP4Spec.parameter)), (fun xs : List
    (NanoP4Spec.parameter) => ∀ x ∈ xs, (NanoP4Spec.parameter.admitted) x) x from (fun xs x _ =>
    ((show ∀ x : (NanoP4Spec.parameter), (NanoP4Spec.parameter.admitted) x from
    NanoP4Spec.parameter.admittedAll)) x))) x)), (fun x => (@Representation.Codec.encodingValid
    (NanoP4Spec.blockStatement) ⟨NanoP4Spec.blockStatement.toValue⟩
    ⟨NanoP4Spec.blockStatement.ofValue⟩ (Representation.Source.Valid NanoP4Spec.spec
    Representation.Source.externDomain (Q.t (Q.varT "blockStatement" [])).it)
    (NanoP4Spec.blockStatement.admitted) (NanoP4Spec.blockStatement.codec)) x (((show ∀ x :
    (NanoP4Spec.blockStatement), (NanoP4Spec.blockStatement.admitted) x from
    NanoP4Spec.blockStatement.admittedAll)) x)), trivial⟩
#audit_axioms ActionDecl_ok.callArgumentsSource


end NanoP4Spec
