-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group CallAdmission.empty_callableDefEnv
import P4SpecTec.Refine.Representation.Delay
import P4SpecTec.Refine.Representation.Source
import P4SpecTec.Refine.Representation.SourceAlias
import P4SpecTec.Refine.Representation.SourceAtomic
import P4SpecTec.Refine.Representation.SourceRecord
import P4SpecTec.Refine.Representation.SourceCodec
import P4SpecTec.Refine.Representation.SourceTuple
import P4SpecTec.Refine.Representation.SourceExtern
import P4SpecTec.Refine.Representation.SourceVariant
import P4SpecTec.Tactic.Audit
import P4SpecTec.Tactic.CarrierInduction
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality

/-! # NanoP4Spec.Refinement.CallAdmission.empty_callableDefEnv

Generated: refinement theorems, group CallAdmission.empty_callableDefEnv.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

/-- All values of the actual call argument carriers are source-valid. -/
theorem «$empty_callableDefEnv».callArgumentsSource :
    True :=
  trivial
#audit_axioms «$empty_callableDefEnv».callArgumentsSource


end NanoP4Spec
