-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group CallAdmission.Program_ok
import P4SpecTec.Refine.Representation.Delay
import P4SpecTec.Refine.Representation.Source
import P4SpecTec.Refine.Representation.SourceAlias
import P4SpecTec.Refine.Representation.SourceAtomic
import P4SpecTec.Refine.Representation.SourceRecord
import P4SpecTec.Refine.Representation.SourceCodec
import P4SpecTec.Refine.Representation.SourceTuple
import P4SpecTec.Refine.Representation.SourceExtern
import P4SpecTec.Refine.Representation.SourceVariant
import P4SpecTec.Tactic.Audit
import P4SpecTec.Tactic.CarrierInduction
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality
import NanoP4Spec.Refinement.Representation.program
import NanoP4Spec.Refinement.Representation.typingContext
import NanoP4Spec.Refinement.Representation.declaration

/-! # NanoP4Spec.Refinement.CallAdmission.Program_ok

Generated: refinement theorems, group CallAdmission.Program_ok.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

/-- All values of the actual call argument carriers are source-valid. -/
theorem Program_ok.callArgumentsSource :
    (∀ x : (NanoP4Spec.program), (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "program" [])).it)
      ((NanoP4Spec.program.toValue) x)) ∧
    (∀ x : (NanoP4Spec.typingContext), (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "typingContext" [])).it)
      ((NanoP4Spec.typingContext.toValue) x)) ∧
    (∀ x : (List (NanoP4Spec.declaration)), (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (.IterT (Q.t (Q.varT "declaration" []))
      .List)).it) ((@ToValue.toValue (List (NanoP4Spec.declaration))
      (@P4SpecTec.Prelude.instToValueList (NanoP4Spec.declaration)
      ⟨NanoP4Spec.declaration.toValue⟩)) x)) ∧
    True :=
  ⟨(fun x => (@Representation.Codec.encodingValid (NanoP4Spec.program)
    ⟨NanoP4Spec.program.toValue⟩ ⟨NanoP4Spec.program.ofValue⟩ (Representation.Source.Valid
    NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT "program" [])).it)
    (NanoP4Spec.program.admitted) (NanoP4Spec.program.codec)) x (((show ∀ x :
    (NanoP4Spec.program), (NanoP4Spec.program.admitted) x from NanoP4Spec.program.admittedAll))
    x)), (fun x => (@Representation.Codec.encodingValid (NanoP4Spec.typingContext)
    ⟨NanoP4Spec.typingContext.toValue⟩ ⟨NanoP4Spec.typingContext.ofValue⟩
    (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT
    "typingContext" [])).it) (NanoP4Spec.typingContext.admitted)
    (NanoP4Spec.typingContext.codec)) x (((show ∀ x : (NanoP4Spec.typingContext),
    (NanoP4Spec.typingContext.admitted) x from NanoP4Spec.typingContext.admittedAll)) x)), (fun
    x => (@Representation.Codec.encodingValid (List (NanoP4Spec.declaration)) ⟨@ToValue.toValue
    (List (NanoP4Spec.declaration)) (@P4SpecTec.Prelude.instToValueList (NanoP4Spec.declaration)
    ⟨NanoP4Spec.declaration.toValue⟩)⟩ ⟨@OfValue.ofValue (List (NanoP4Spec.declaration))
    (@P4SpecTec.Prelude.instOfValueList (NanoP4Spec.declaration)
    ⟨NanoP4Spec.declaration.ofValue⟩)⟩ (Representation.Source.Valid NanoP4Spec.spec
    Representation.Source.externDomain (Q.t (.IterT (Q.t (Q.varT "declaration" [])) .List)).it)
    (fun xs : List (NanoP4Spec.declaration) => ∀ x ∈ xs, (NanoP4Spec.declaration.admitted) x)
    (@Representation.Source.listCodec NanoP4Spec.spec Representation.Source.externDomain
    (NanoP4Spec.declaration) ⟨NanoP4Spec.declaration.toValue⟩ ⟨NanoP4Spec.declaration.ofValue⟩
    (Q.t (Q.varT "declaration" [])) (NanoP4Spec.declaration.admitted)
    (NanoP4Spec.declaration.codec))) x (((show ∀ x : (List (NanoP4Spec.declaration)), (fun xs :
    List (NanoP4Spec.declaration) => ∀ x ∈ xs, (NanoP4Spec.declaration.admitted) x) x from (fun
    xs x _ => ((show ∀ x : (NanoP4Spec.declaration), (NanoP4Spec.declaration.admitted) x from
    NanoP4Spec.declaration.admittedAll)) x))) x)), trivial⟩


#audit_axioms Program_ok.callArgumentsSource

end NanoP4Spec
