-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group CallAdmission.TableEntries_ok
import P4SpecTec.Refine.Representation.Delay
import P4SpecTec.Refine.Representation.Source
import P4SpecTec.Refine.Representation.SourceAlias
import P4SpecTec.Refine.Representation.SourceAtomic
import P4SpecTec.Refine.Representation.SourceRecord
import P4SpecTec.Refine.Representation.SourceCodec
import P4SpecTec.Refine.Representation.SourceTuple
import P4SpecTec.Refine.Representation.SourceExtern
import P4SpecTec.Refine.Representation.SourceVariant
import P4SpecTec.Tactic.Audit
import P4SpecTec.Tactic.CarrierInduction
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality
import NanoP4Spec.Refinement.Representation.typingContext
import NanoP4Spec.Refinement.Representation.tableContext
import NanoP4Spec.Refinement.Representation.tableEntry

/-! # NanoP4Spec.Refinement.CallAdmission.TableEntries_ok

Generated: refinement theorems, group CallAdmission.TableEntries_ok.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

/-- All values of the actual call argument carriers are source-valid. -/
theorem TableEntries_ok.callArgumentsSource :
    (∀ x : (NanoP4Spec.typingContext), (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "typingContext" [])).it)
      ((NanoP4Spec.typingContext.toValue) x)) ∧
    (∀ x : (NanoP4Spec.tableContext), (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "tableContext" [])).it)
      ((NanoP4Spec.tableContext.toValue) x)) ∧
    (∀ x : (NanoP4Spec.tableEntry), (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "tableEntry" [])).it)
      ((NanoP4Spec.tableEntry.toValue) x)) ∧
    (∀ x : (List (NanoP4Spec.tableEntry)), (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (.IterT (Q.t (Q.varT "tableEntry" [])) .List)).it)
      ((@ToValue.toValue (List (NanoP4Spec.tableEntry)) (@P4SpecTec.Prelude.instToValueList
      (NanoP4Spec.tableEntry) ⟨NanoP4Spec.tableEntry.toValue⟩)) x)) ∧
    True :=
  ⟨(fun x => (@Representation.Codec.encodingValid (NanoP4Spec.typingContext)
    ⟨NanoP4Spec.typingContext.toValue⟩ ⟨NanoP4Spec.typingContext.ofValue⟩
    (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT
    "typingContext" [])).it) (NanoP4Spec.typingContext.admitted)
    (NanoP4Spec.typingContext.codec)) x (((show ∀ x : (NanoP4Spec.typingContext),
    (NanoP4Spec.typingContext.admitted) x from NanoP4Spec.typingContext.admittedAll)) x)), (fun
    x => (@Representation.Codec.encodingValid (NanoP4Spec.tableContext)
    ⟨NanoP4Spec.tableContext.toValue⟩ ⟨NanoP4Spec.tableContext.ofValue⟩
    (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT
    "tableContext" [])).it) (NanoP4Spec.tableContext.admitted) (NanoP4Spec.tableContext.codec))
    x (((show ∀ x : (NanoP4Spec.tableContext), (NanoP4Spec.tableContext.admitted) x from
    NanoP4Spec.tableContext.admittedAll)) x)), (fun x => (@Representation.Codec.encodingValid
    (NanoP4Spec.tableEntry) ⟨NanoP4Spec.tableEntry.toValue⟩ ⟨NanoP4Spec.tableEntry.ofValue⟩
    (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT
    "tableEntry" [])).it) (NanoP4Spec.tableEntry.admitted) (NanoP4Spec.tableEntry.codec)) x
    (((show ∀ x : (NanoP4Spec.tableEntry), (NanoP4Spec.tableEntry.admitted) x from
    NanoP4Spec.tableEntry.admittedAll)) x)), (fun x => (@Representation.Codec.encodingValid
    (List (NanoP4Spec.tableEntry)) ⟨@ToValue.toValue (List (NanoP4Spec.tableEntry))
    (@P4SpecTec.Prelude.instToValueList (NanoP4Spec.tableEntry)
    ⟨NanoP4Spec.tableEntry.toValue⟩)⟩ ⟨@OfValue.ofValue (List (NanoP4Spec.tableEntry))
    (@P4SpecTec.Prelude.instOfValueList (NanoP4Spec.tableEntry)
    ⟨NanoP4Spec.tableEntry.ofValue⟩)⟩ (Representation.Source.Valid NanoP4Spec.spec
    Representation.Source.externDomain (Q.t (.IterT (Q.t (Q.varT "tableEntry" [])) .List)).it)
    (fun xs : List (NanoP4Spec.tableEntry) => ∀ x ∈ xs, (NanoP4Spec.tableEntry.admitted) x)
    (@Representation.Source.listCodec NanoP4Spec.spec Representation.Source.externDomain
    (NanoP4Spec.tableEntry) ⟨NanoP4Spec.tableEntry.toValue⟩ ⟨NanoP4Spec.tableEntry.ofValue⟩ (Q.t
    (Q.varT "tableEntry" [])) (NanoP4Spec.tableEntry.admitted) (NanoP4Spec.tableEntry.codec))) x
    (((show ∀ x : (List (NanoP4Spec.tableEntry)), (fun xs : List (NanoP4Spec.tableEntry) => ∀ x
    ∈ xs, (NanoP4Spec.tableEntry.admitted) x) x from (fun xs x _ => ((show ∀ x :
    (NanoP4Spec.tableEntry), (NanoP4Spec.tableEntry.admitted) x from
    NanoP4Spec.tableEntry.admittedAll)) x))) x)), trivial⟩
#audit_axioms TableEntries_ok.callArgumentsSource


end NanoP4Spec
