import P4SpecTec.Codegen.Rels
import P4SpecTec.Codegen.Props
import P4SpecTec.Codegen.Graph

/-!
The plan and the modules: definitions are grouped into recursion groups
(types, then subtype bridges, then the `Externs` class, then functions and
relations, each followed by the `Prop` encoding of its relations and
their run-soundness theorems), every group is assigned to the module of
the last spec file it or its dependencies come from, and one module is
written per spec file that has something to say, in spec order, each
importing the previous. Design section 4.1 and the deviation "a recursive group
spanning files is emitted in the module of the last file".
-/

namespace P4SpecTec.Codegen.Emit

open Std (Format)
open P4SpecTec.Util.Source
open P4SpecTec.Domain
open P4SpecTec.Lang.Il
open P4SpecTec.Lang.Al
open P4SpecTec.Codegen.Types
open P4SpecTec.Codegen.Exp
open P4SpecTec.Codegen.Funcs
open P4SpecTec.Codegen.Rels

/-- A generated file. -/
structure Output where
  /-- The path relative to the output directory. -/
  path : String
  /-- The text. -/
  text : String

/-- A unit of the plan. -/
structure Unit where
  /-- The unit's id. -/
  id : String
  /-- The index of the spec file it is emitted into. -/
  file : Nat
  /-- The text. -/
  decls : Format
  /-- Whether it needs the `Externs` class. -/
  externs : Bool := false

/-- The header comment every generated file starts with: two grep-able
lines, the generator and the inputs. -/
def headerLine (lib exportPath file : String) : String :=
  s!"-- GENERATED by p4spectec-gen for {lib}; do not edit, regenerate.\n" ++
    s!"-- source: {exportPath}, {file}"

/-- The preamble after the imports. -/
def preamble (lib module file : String) : String :=
  String.join [
    s!"/-! # {lib}.{module}\n\nThe rendering of `{file}`.\n",
    "Generated: every definition here mirrors one definition of that file, in\n",
    "order, by the encodings of `docs/design.md`.\n-/\n\n",
    "set_option linter.missingDocs false\nset_option linter.unusedVariables false\n",
    "set_option autoImplicit false\nset_option maxHeartbeats 1000000\n\n",
    "open P4SpecTec P4SpecTec.Prelude\n\n",
    s!"namespace {lib}\n\n"]

/-- The types named by casts inside an expression. -/
partial def castTypes (e : exp) : List String :=
  (match e.it with
    | .UpCastE t _ | .DownCastE t _ | .SubE _ t _ => Env.typeRefs t.it
    | .CallE _ targs _ => targs.flatMap fun t => Env.typeRefs t.it
    | _ => []) ++ (pairsOfExp.children e).flatMap castTypes

/-- The types a definition's signature and body mention. -/
def typesOfDef (d : Lang.Al.def) : List String :=
  let sig := match d.it with
    | .TypD _ _ dt _ => Env.deftypRefs dt.it
    | .VarD _ t _ => Env.typeRefs t.it
    | .ExternRelD _ n _ _ | .RelD _ n _ _ _ _ =>
      (Mixfix.args n.it).flatMap fun t => Env.typeRefs t.it
    | .ExternDecD _ _ ps t _ | .BuiltinDecD _ _ ps t _ | .FuncDecD _ _ ps t _ _ _ =>
      Env.typeRefs t.it ++ (paramTypes (ps.map (·.it))).flatMap Env.typeRefs
    | .TableDecD _ ps t _ _ =>
      Env.typeRefs t.it ++ (paramTypes (ps.map (·.it))).flatMap Env.typeRefs
    | _ => []
  let body := (expsOfDef d).flatMap fun e => Env.typeRefs e.note ++ castTypes e
  sig ++ body

/-- The `print` hints of a definition: not supported yet, so their presence
fails generation loudly rather than printing values the wrong way. -/
def printHints (d : Lang.Al.def) : List String :=
  let hintsOf (hs : List Lang.Il.hint) : List String :=
    hs.filterMap fun h =>
      match h.getObjVal? "it" >>= (·.getObjVal? "hintid") >>= (·.getObjVal? "it") with
      | .ok (.str "print") => some d.it.id.it
      | _ => none
  match d.it with
  | .TypD _ _ dt hs =>
    hintsOf hs ++ (match dt.it with
      | .VariantT cases => cases.flatMap fun c => match c with | .mk _ _ chs => hintsOf chs
      | _ => [])
  | _ => []

/-- Generate the plan for a spec. -/
def plan (env : Env) (spec : Lang.Al.spec) : Except String (List Unit × List String) := do
  let withPrint := spec.flatMap printHints
  if !withPrint.isEmpty then
    throw s!"print hints are not supported yet (design 5.4); found on {withPrint}"
  let files := (spec.map Env.fileOf).eraseDups
  let fileIdx (f : String) : Nat := (files.idxOf? f).getD 0
  let defById : Std.HashMap String Lang.Al.def :=
    Std.HashMap.ofList (spec.map fun d => (d.it.id.it, d))
  let defFile (id : String) : Nat := match defById.get? id with
    | some d => fileIdx (Env.fileOf d)
    | none => 0
  -- types
  let typeIds := spec.filterMap fun d => match d.it with
    | .TypD i .. | .ExternTypD i _ => some i.it
    | _ => none
  let typeDeps (id : String) : List String := match env.types.get? id with
    | some info => match info.deftyp with
      | some dt => (Env.deftypRefs dt).eraseDups.filter (· != id)
      | none => []
    | none => []
  let typeGroups := Graph.sccs typeIds typeDeps
  let mut units : List Unit := []
  let mut unitOfType : Std.HashMap String Nat := {}   -- type id → unit index
  let mut typeUnitFile : Std.HashMap String Nat := {}
  for group in typeGroups do
    let members := group.filterMap fun id => match env.types.get? id with
      | some info => match info.deftyp with
        | some dt => some (id, info.tparams, dt)
        | none => none
      | none => none
    let externTypes := group.filter fun id => match env.types.get? id with
      | some info => info.deftyp.isNone
      | none => false
    let recursive := Graph.isRecursive group typeDeps
    let unfold := if recursive then [Types.unfoldAll] else []
    let depFiles := group.flatMap fun id => (typeDeps id).map fun d => typeUnitFile.getD d 0
    let file := (group.map defFile ++ depFiles).foldl max 0
    let externDecls := externTypes.map fun tid =>
      Format.text s!"abbrev {Names.typeName tid} : Type := ExternValue"
    let decls := if recursive then
      let inductives := members.filter fun (_, _, dt) =>
        match dt with | .PlainT _ => false | _ => true
      let block := mutualBlock (inductives.map fun (tid, tparams, dt) =>
        typeDecl env unfold tid tparams dt)
      let aliasDecls := members.filterMap fun (tid, tparams, dt) => match dt with
        | .PlainT _ => some (typeDecl env [] tid tparams dt)
        | _ => none
      joinDecls ([block] ++ aliasDecls)
    else joinDecls (members.map fun (tid, tparams, dt) => typeDecl env [] tid tparams dt)
    let encoders := if members.isEmpty then []
      else [toValueDecls env members, ofValueDecls env members]
    let unitIdx := units.length
    let allDecls := joinDecls (externDecls ++ [decls] ++ encoders)
    let u : Unit := { id := "T:" ++ ",".intercalate group, file := file, decls := allDecls }
    units := units ++ [u]
    for id in group do
      unitOfType := unitOfType.insert id unitIdx
      typeUnitFile := typeUnitFile.insert id file
  -- subtype bridges
  let pairs := (spec.flatMap fun d => (expsOfDef d).flatMap (pairsOfExp env)).eraseDups
  for (s, t) in pairs do
    let isVariant (id : String) : Bool := match env.types.get? id with
      | some info => match info.deftyp with
        | some (.VariantT _) => true
        | _ => false
      | none => false
    if isVariant s && isVariant t then
      let file := max (typeUnitFile.getD s 0) (typeUnitFile.getD t 0)
      let decls ← subtypeDecls env s t
      let u : Unit := { id := s!"S:{s}:{t}", file := file, decls := decls }
      units := units ++ [u]
    else throw s!"cast between non-variant types {s} and {t}"
  -- externs
  let externDefs := spec.filter fun d => match d.it with
    | .ExternDecD .. | .ExternRelD .. => true
    | _ => false
  let externNames := externDefs.map fun d => d.it.id.it
  let externsUnitFile := (externDefs.map fun d =>
    (typesOfDef d).map (typeUnitFile.getD · 0) ++ [fileIdx (Env.fileOf d)]).flatten.foldl max 0
  if !externDefs.isEmpty then
    let u : Unit := { id := "X", file := externsUnitFile, decls := externsClass env externDefs }
    units := units ++ [u]
  -- functions and relations
  let funIds := spec.filterMap fun d => match d.it with
    | .FuncDecD i .. | .BuiltinDecD i .. | .TableDecD i .. | .RelD i .. => some i.it
    | _ => none
  let calls (id : String) : List String := match defById.get? id with
    | some d => (callsOfDef d).eraseDups
    | none => []
  let funDeps (id : String) : List String := (calls id).filter funIds.contains
  let funGroups := Graph.sccs funIds funDeps
  let mut unitFile : Std.HashMap String Nat := {}
  let mut needsExt : Std.HashMap String Bool := {}
  let ctxBase : Ctx := { env, externs := externNames }
  for group in funGroups do
    let recursive := Graph.isRecursive group funDeps
    let ext := group.any fun id =>
      (calls id).any fun c => externNames.contains c || needsExt.getD c false
    let depFiles := group.flatMap fun id =>
      (calls id).map (fun c => unitFile.getD c 0) ++ (match defById.get? id with
        | some d => (typesOfDef d).map (typeUnitFile.getD · 0)
        | none => [])
    let extFile := if ext then [externsUnitFile] else []
    let file := (group.map defFile ++ depFiles ++ extFile).foldl max 0
    let tmpPrefix := if (group.any fun id => match defById.get? id with
        | some d => (expsOfDef d).any fun e => match e.it with
          | .VarE v => v.it.startsWith "tmp_"
          | _ => false
        | none => false) then "tmp__" else "tmp_"
    let ctx := { ctxBase with tmpPrefix }
    let mut decls : List Format := []
    let mut props : List Format := []
    let mut members : List Props.Member := []
    for id in group do
      let some d := defById.get? id | throw s!"unknown definition {id}"
      let f ← match d.it with
        | .FuncDecD i tparams params ret clauses ec _ =>
          funcDecl ctx recursive ext i.it (tparams.map (·.it)) (params.map (·.it)) ret.it clauses ec
        | .BuiltinDecD i tparams params ret _ =>
          builtinDecl env i.it (tparams.map (·.it)) (params.map (·.it)) ret.it
        | .TableDecD i params ret rows _ =>
          tableDecl ctx recursive ext i.it (params.map (·.it)) ret.it rows
        | .RelD i nottyp inputs groups eg _ =>
          relDecl ctx recursive ext i.it nottyp (inputs.map (·.toNat)) groups eg
        | _ => throw s!"unexpected definition kind for {id}"
      decls := decls ++ [f]
      if let .RelD i nottyp inputs groups eg _ := d.it then
        props := props ++
          [← Props.relInductive ctx ext i.it nottyp (inputs.map (·.toNat)) groups eg]
      members := members ++ [← Props.memberOf ctx d]
    let theorems := Props.groupTheorems ext recursive members
    let text := joinDecls ([if recursive then mutualBlock decls else joinDecls decls] ++
      (if props.isEmpty then [] else [mutualBlock props]) ++ theorems)
    let u : Unit :=
      { id := "F:" ++ ",".intercalate group, file := file, decls := text, externs := ext }
    units := units ++ [u]
    for id in group do
      unitFile := unitFile.insert id file
      needsExt := needsExt.insert id ext
  pure (units, files)


/-- Generate every output file of a library. -/
def generate (lib exportPath : String) (spec : Lang.Al.spec) : Except String (List Output) := do
  let env := Env.ofSpec lib spec
  let (units, files) ← plan env spec
  let used := (units.map (·.file)).eraseDups.mergeSort (· ≤ ·)
  let specRoot := Names.specRoot files
  let mut outs : List Output := []
  let mut prev : Option String := none
  let mut modules : List String := []
  for i in used do
    let file := files.getD i ""
    let components := Names.moduleComponents file specRoot
    let module := ".".intercalate components
    -- the file path uses the unquoted components: Lake maps `«3.2-bits»` to `3.2-bits.lean`
    let path := "/".intercalate (components.map fun c =>
      if c.startsWith "«" then String.ofList (c.toList.drop 1 |>.dropLast) else c)
    let body := units.filter (·.file == i)
    let imports := "import P4SpecTec.Prelude\nimport P4SpecTec.Tactic.RunSound\n" ++
      "import P4SpecTec.Tactic.Audit\n" ++ (match prev with
      | some p => s!"import {lib}.{p}\n"
      | none => "")
    let text := headerLine lib exportPath file ++ "\n" ++ imports ++ "\n" ++
      preamble lib module file ++ render (joinDecls (body.map (·.decls))) ++ s!"\n\nend {lib}\n"
    outs := outs ++ [{ path := s!"{lib}/{path}.lean", text }]
    prev := some module
    modules := modules ++ [module]
  let root := headerLine lib exportPath "all files" ++ "\n" ++
    String.join (modules.map fun m => s!"import {lib}.{m}\n") ++
    s!"\n/-!\n# {lib}\n\nThe rendering of the specification exported to `{exportPath}`, " ++
    "one module\nper spec file, generated by `lake exe p4spectec-gen`. Never hand-edited.\n-/\n"
  outs := outs ++ [{ path := s!"{lib}.lean", text := root }]
  pure outs

end P4SpecTec.Codegen.Emit
