-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group CallAdmission.Runtime.Copy_out
import P4SpecTec.Refine.Representation.Delay
import P4SpecTec.Refine.Representation.Source
import P4SpecTec.Refine.Representation.SourceAlias
import P4SpecTec.Refine.Representation.SourceAtomic
import P4SpecTec.Refine.Representation.SourceRecord
import P4SpecTec.Refine.Representation.SourceCodec
import P4SpecTec.Refine.Representation.SourceTuple
import P4SpecTec.Refine.Representation.SourceExtern
import P4SpecTec.Refine.Representation.SourceVariant
import P4SpecTec.Tactic.Audit
import P4SpecTec.Tactic.CarrierInduction
import P4SpecTec.Refine.Representation.SourceRuntime
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality
import NanoP4Spec.Refinement.Representation.Runtime
import NanoP4Spec.Refinement.Representation.scope
import NanoP4Spec.Refinement.Representation.Runtime.evalContext
import NanoP4Spec.Refinement.Representation.parameterIR
import NanoP4Spec.Refinement.Representation.lvalue

/-! # NanoP4Spec.Refinement.CallAdmission.Runtime.Copy_out

Generated: refinement theorems, group CallAdmission.Runtime.Copy_out.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

/-- All values of the actual call argument carriers are source-valid. -/
theorem Copy_out.runtimeCallArgumentsSource :
    (∀ x : (NanoP4Spec.scope), (Representation.Source.Valid NanoP4Spec.spec
      (Representation.Source.runtimeDomain ["value"]) (Q.t (Q.varT "scope" [])).it)
      ((NanoP4Spec.scope.toValue) x)) ∧
    (∀ x : (NanoP4Spec.evalContext), (Representation.Source.Valid NanoP4Spec.spec
      (Representation.Source.runtimeDomain ["value"]) (Q.t (Q.varT "evalContext" [])).it)
      ((NanoP4Spec.evalContext.toValue) x)) ∧
    (∀ x : (NanoP4Spec.parameterIR), (Representation.Source.Valid NanoP4Spec.spec
      (Representation.Source.runtimeDomain ["value"]) (Q.t (Q.varT "parameterIR" [])).it)
      ((NanoP4Spec.parameterIR.toValue) x)) ∧
    (∀ x : (Option (NanoP4Spec.lvalue)), (Representation.Source.Valid NanoP4Spec.spec
      (Representation.Source.runtimeDomain ["value"]) (Q.t (.IterT (Q.t (Q.varT "lvalue" []))
      .Opt)).it) ((@ToValue.toValue (Option (NanoP4Spec.lvalue))
      (@P4SpecTec.Prelude.instToValueOption (NanoP4Spec.lvalue) ⟨NanoP4Spec.lvalue.toValue⟩))
      x)) ∧
    (∀ x : (List (NanoP4Spec.parameterIR)), (Representation.Source.Valid NanoP4Spec.spec
      (Representation.Source.runtimeDomain ["value"]) (Q.t (.IterT (Q.t (Q.varT "parameterIR"
      [])) .List)).it) ((@ToValue.toValue (List (NanoP4Spec.parameterIR))
      (@P4SpecTec.Prelude.instToValueList (NanoP4Spec.parameterIR)
      ⟨NanoP4Spec.parameterIR.toValue⟩)) x)) ∧
    (∀ x : (List (Option (NanoP4Spec.lvalue))), (Representation.Source.Valid NanoP4Spec.spec
      (Representation.Source.runtimeDomain ["value"]) (Q.t (.IterT (Q.t (.IterT (Q.t (Q.varT
      "lvalue" [])) .Opt)) .List)).it) ((@ToValue.toValue (List (Option NanoP4Spec.lvalue))
      (@P4SpecTec.Prelude.instToValueList (Option NanoP4Spec.lvalue) ⟨@ToValue.toValue (Option
      (NanoP4Spec.lvalue)) (@P4SpecTec.Prelude.instToValueOption (NanoP4Spec.lvalue)
      ⟨NanoP4Spec.lvalue.toValue⟩)⟩)) x)) ∧
    True :=
  ⟨(fun x => (@Representation.Codec.encodingValid (NanoP4Spec.scope) ⟨NanoP4Spec.scope.toValue⟩
    ⟨NanoP4Spec.scope.ofValue⟩ (Representation.Source.Valid NanoP4Spec.spec
    (Representation.Source.runtimeDomain ["value"]) (Q.t (Q.varT "scope" [])).it) (fun _ =>
    True) ((@Representation.Source.Codec.toRuntime (NanoP4Spec.scope) ⟨NanoP4Spec.scope.toValue⟩
    ⟨NanoP4Spec.scope.ofValue⟩ _ _ _ NanoP4Spec.runtimeClosed _
    (Representation.Source.namesInCheckSound _ _ (by closure_check)) _
    (NanoP4Spec.scope.sourceCodec)))) x (((show ∀ x : (NanoP4Spec.scope), (fun _ => True) x from
    NanoP4Spec.scope.admittedAll)) x)), (fun x => (@Representation.Codec.encodingValid
    (NanoP4Spec.evalContext) ⟨NanoP4Spec.evalContext.toValue⟩ ⟨NanoP4Spec.evalContext.ofValue⟩
    (Representation.Source.Valid NanoP4Spec.spec (Representation.Source.runtimeDomain ["value"])
    (Q.t (Q.varT "evalContext" [])).it) (NanoP4Spec.evalContext.runtimeAdmitted)
    (NanoP4Spec.evalContext.runtimeCodec)) x (((show ∀ x : (NanoP4Spec.evalContext),
    (NanoP4Spec.evalContext.runtimeAdmitted) x from NanoP4Spec.evalContext.runtimeAdmittedAll))
    x)), (fun x => (@Representation.Codec.encodingValid (NanoP4Spec.parameterIR)
    ⟨NanoP4Spec.parameterIR.toValue⟩ ⟨NanoP4Spec.parameterIR.ofValue⟩
    (Representation.Source.Valid NanoP4Spec.spec (Representation.Source.runtimeDomain ["value"])
    (Q.t (Q.varT "parameterIR" [])).it) (NanoP4Spec.parameterIR.admitted)
    ((@Representation.Source.Codec.toRuntime (NanoP4Spec.parameterIR)
    ⟨NanoP4Spec.parameterIR.toValue⟩ ⟨NanoP4Spec.parameterIR.ofValue⟩ _ _ _
    NanoP4Spec.runtimeClosed _ (Representation.Source.namesInCheckSound _ _ (by closure_check))
    _ (NanoP4Spec.parameterIR.codec)))) x (((show ∀ x : (NanoP4Spec.parameterIR),
    (NanoP4Spec.parameterIR.admitted) x from NanoP4Spec.parameterIR.admittedAll)) x)), (fun x =>
    (@Representation.Codec.encodingValid (Option (NanoP4Spec.lvalue)) ⟨@ToValue.toValue (Option
    (NanoP4Spec.lvalue)) (@P4SpecTec.Prelude.instToValueOption (NanoP4Spec.lvalue)
    ⟨NanoP4Spec.lvalue.toValue⟩)⟩ ⟨@OfValue.ofValue (Option (NanoP4Spec.lvalue))
    (@P4SpecTec.Prelude.instOfValueOption (NanoP4Spec.lvalue) ⟨NanoP4Spec.lvalue.ofValue⟩)⟩
    (Representation.Source.Valid NanoP4Spec.spec (Representation.Source.runtimeDomain ["value"])
    (Q.t (.IterT (Q.t (Q.varT "lvalue" [])) .Opt)).it) (fun xs : Option (NanoP4Spec.lvalue) => ∀
    x ∈ xs, (NanoP4Spec.lvalue.admitted) x) (@Representation.Source.optionCodec NanoP4Spec.spec
    (Representation.Source.runtimeDomain ["value"]) (NanoP4Spec.lvalue)
    ⟨NanoP4Spec.lvalue.toValue⟩ ⟨NanoP4Spec.lvalue.ofValue⟩ (Q.t (Q.varT "lvalue" []))
    (NanoP4Spec.lvalue.admitted) ((@Representation.Source.Codec.toRuntime (NanoP4Spec.lvalue)
    ⟨NanoP4Spec.lvalue.toValue⟩ ⟨NanoP4Spec.lvalue.ofValue⟩ _ _ _ NanoP4Spec.runtimeClosed _
    (Representation.Source.namesInCheckSound _ _ (by closure_check)) _
    (NanoP4Spec.lvalue.codec))))) x (((show ∀ x : (Option (NanoP4Spec.lvalue)), (fun xs : Option
    (NanoP4Spec.lvalue) => ∀ x ∈ xs, (NanoP4Spec.lvalue.admitted) x) x from (fun xs x _ =>
    ((show ∀ x : (NanoP4Spec.lvalue), (NanoP4Spec.lvalue.admitted) x from
    NanoP4Spec.lvalue.admittedAll)) x))) x)), (fun x => (@Representation.Codec.encodingValid
    (List (NanoP4Spec.parameterIR)) ⟨@ToValue.toValue (List (NanoP4Spec.parameterIR))
    (@P4SpecTec.Prelude.instToValueList (NanoP4Spec.parameterIR)
    ⟨NanoP4Spec.parameterIR.toValue⟩)⟩ ⟨@OfValue.ofValue (List (NanoP4Spec.parameterIR))
    (@P4SpecTec.Prelude.instOfValueList (NanoP4Spec.parameterIR)
    ⟨NanoP4Spec.parameterIR.ofValue⟩)⟩ (Representation.Source.Valid NanoP4Spec.spec
    (Representation.Source.runtimeDomain ["value"]) (Q.t (.IterT (Q.t (Q.varT "parameterIR" []))
    .List)).it) (fun xs : List (NanoP4Spec.parameterIR) => ∀ x ∈ xs,
    (NanoP4Spec.parameterIR.admitted) x) (@Representation.Source.listCodec NanoP4Spec.spec
    (Representation.Source.runtimeDomain ["value"]) (NanoP4Spec.parameterIR)
    ⟨NanoP4Spec.parameterIR.toValue⟩ ⟨NanoP4Spec.parameterIR.ofValue⟩ (Q.t (Q.varT "parameterIR"
    [])) (NanoP4Spec.parameterIR.admitted) ((@Representation.Source.Codec.toRuntime
    (NanoP4Spec.parameterIR) ⟨NanoP4Spec.parameterIR.toValue⟩ ⟨NanoP4Spec.parameterIR.ofValue⟩ _
    _ _ NanoP4Spec.runtimeClosed _ (Representation.Source.namesInCheckSound _ _ (by
    closure_check)) _ (NanoP4Spec.parameterIR.codec))))) x (((show ∀ x : (List
    (NanoP4Spec.parameterIR)), (fun xs : List (NanoP4Spec.parameterIR) => ∀ x ∈ xs,
    (NanoP4Spec.parameterIR.admitted) x) x from (fun xs x _ => ((show ∀ x :
    (NanoP4Spec.parameterIR), (NanoP4Spec.parameterIR.admitted) x from
    NanoP4Spec.parameterIR.admittedAll)) x))) x)), (fun x =>
    (@Representation.Codec.encodingValid (List (Option (NanoP4Spec.lvalue))) ⟨@ToValue.toValue
    (List (Option (NanoP4Spec.lvalue))) (@P4SpecTec.Prelude.instToValueList (Option
    (NanoP4Spec.lvalue)) ⟨@ToValue.toValue (Option (NanoP4Spec.lvalue))
    (@P4SpecTec.Prelude.instToValueOption (NanoP4Spec.lvalue) ⟨NanoP4Spec.lvalue.toValue⟩)⟩)⟩
    ⟨@OfValue.ofValue (List (Option (NanoP4Spec.lvalue))) (@P4SpecTec.Prelude.instOfValueList
    (Option (NanoP4Spec.lvalue)) ⟨@OfValue.ofValue (Option (NanoP4Spec.lvalue))
    (@P4SpecTec.Prelude.instOfValueOption (NanoP4Spec.lvalue) ⟨NanoP4Spec.lvalue.ofValue⟩)⟩)⟩
    (Representation.Source.Valid NanoP4Spec.spec (Representation.Source.runtimeDomain ["value"])
    (Q.t (.IterT (Q.t (.IterT (Q.t (Q.varT "lvalue" [])) .Opt)) .List)).it) (fun xs : List
    (Option (NanoP4Spec.lvalue)) => ∀ x ∈ xs, (fun xs : Option (NanoP4Spec.lvalue) => ∀ x ∈ xs,
    (NanoP4Spec.lvalue.admitted) x) x) (@Representation.Source.listCodec NanoP4Spec.spec
    (Representation.Source.runtimeDomain ["value"]) (Option (NanoP4Spec.lvalue))
    ⟨@ToValue.toValue (Option (NanoP4Spec.lvalue)) (@P4SpecTec.Prelude.instToValueOption
    (NanoP4Spec.lvalue) ⟨NanoP4Spec.lvalue.toValue⟩)⟩ ⟨@OfValue.ofValue (Option
    (NanoP4Spec.lvalue)) (@P4SpecTec.Prelude.instOfValueOption (NanoP4Spec.lvalue)
    ⟨NanoP4Spec.lvalue.ofValue⟩)⟩ (Q.t (.IterT (Q.t (Q.varT "lvalue" [])) .Opt)) (fun xs :
    Option (NanoP4Spec.lvalue) => ∀ x ∈ xs, (NanoP4Spec.lvalue.admitted) x)
    (@Representation.Source.optionCodec NanoP4Spec.spec (Representation.Source.runtimeDomain
    ["value"]) (NanoP4Spec.lvalue) ⟨NanoP4Spec.lvalue.toValue⟩ ⟨NanoP4Spec.lvalue.ofValue⟩ (Q.t
    (Q.varT "lvalue" [])) (NanoP4Spec.lvalue.admitted) ((@Representation.Source.Codec.toRuntime
    (NanoP4Spec.lvalue) ⟨NanoP4Spec.lvalue.toValue⟩ ⟨NanoP4Spec.lvalue.ofValue⟩ _ _ _
    NanoP4Spec.runtimeClosed _ (Representation.Source.namesInCheckSound _ _ (by closure_check))
    _ (NanoP4Spec.lvalue.codec)))))) x (((show ∀ x : (List (Option (NanoP4Spec.lvalue))), (fun
    xs : List (Option (NanoP4Spec.lvalue)) => ∀ x ∈ xs, (fun xs : Option (NanoP4Spec.lvalue) =>
    ∀ x ∈ xs, (NanoP4Spec.lvalue.admitted) x) x) x from (fun xs x _ => ((show ∀ x : (Option
    (NanoP4Spec.lvalue)), (fun xs : Option (NanoP4Spec.lvalue) => ∀ x ∈ xs,
    (NanoP4Spec.lvalue.admitted) x) x from (fun xs x _ => ((show ∀ x : (NanoP4Spec.lvalue),
    (NanoP4Spec.lvalue.admitted) x from NanoP4Spec.lvalue.admittedAll)) x))) x))) x)), trivial⟩


#audit_axioms Copy_out.runtimeCallArgumentsSource

end NanoP4Spec
