-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group CallAdmission.Runtime.Parser_apply
import P4SpecTec.Refine.Representation.Delay
import P4SpecTec.Refine.Representation.Source
import P4SpecTec.Refine.Representation.SourceAlias
import P4SpecTec.Refine.Representation.SourceAtomic
import P4SpecTec.Refine.Representation.SourceRecord
import P4SpecTec.Refine.Representation.SourceCodec
import P4SpecTec.Refine.Representation.SourceTuple
import P4SpecTec.Refine.Representation.SourceExtern
import P4SpecTec.Refine.Representation.SourceVariant
import P4SpecTec.Tactic.Audit
import P4SpecTec.Tactic.CarrierInduction
import P4SpecTec.Refine.Representation.SourceRuntime
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality
import NanoP4Spec.Refinement.Representation.Runtime
import NanoP4Spec.Refinement.Representation.scope
import NanoP4Spec.Refinement.Representation.Runtime.evalContext
import NanoP4Spec.Refinement.Representation.parserStateList
import NanoP4Spec.Refinement.Representation.parameterIR
import NanoP4Spec.Refinement.Representation.argument
import NanoP4Spec.Refinement.Representation.parserLocalDeclarationList
import NanoP4Spec.Refinement.Representation.parserState
import NanoP4Spec.Refinement.Representation.nameIR
import NanoP4Spec.Refinement.Representation.lvalue

/-! # NanoP4Spec.Refinement.CallAdmission.Runtime.Parser_apply

Generated: refinement theorems, group CallAdmission.Runtime.Parser_apply.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

/-- All values of the actual call argument carriers are source-valid. -/
theorem Parser_apply.runtimeCallArgumentsSource :
    (∀ x : (NanoP4Spec.scope), (Representation.Source.Valid NanoP4Spec.spec
      (Representation.Source.runtimeDomain ["value"]) (Q.t (Q.varT "scope" [])).it)
      ((NanoP4Spec.scope.toValue) x)) ∧
    (∀ x : (NanoP4Spec.evalContext), (Representation.Source.Valid NanoP4Spec.spec
      (Representation.Source.runtimeDomain ["value"]) (Q.t (Q.varT "evalContext" [])).it)
      ((NanoP4Spec.evalContext.toValue) x)) ∧
    (∀ x : (NanoP4Spec.parserStateList), (Representation.Source.Valid NanoP4Spec.spec
      (Representation.Source.runtimeDomain ["value"]) (Q.t (Q.varT "parserStateList" [])).it)
      ((NanoP4Spec.parserStateList.toValue) x)) ∧
    (∀ x : (List (NanoP4Spec.parameterIR)), (Representation.Source.Valid NanoP4Spec.spec
      (Representation.Source.runtimeDomain ["value"]) (Q.t (.IterT (Q.t (Q.varT "parameterIR"
      [])) .List)).it) ((@ToValue.toValue (List (NanoP4Spec.parameterIR))
      (@P4SpecTec.Prelude.instToValueList (NanoP4Spec.parameterIR)
      ⟨NanoP4Spec.parameterIR.toValue⟩)) x)) ∧
    (∀ x : (List (NanoP4Spec.argument)), (Representation.Source.Valid NanoP4Spec.spec
      (Representation.Source.runtimeDomain ["value"]) (Q.t (.IterT (Q.t (Q.varT "argument" []))
      .List)).it) ((@ToValue.toValue (List (NanoP4Spec.argument))
      (@P4SpecTec.Prelude.instToValueList (NanoP4Spec.argument) ⟨NanoP4Spec.argument.toValue⟩))
      x)) ∧
    (∀ x : (NanoP4Spec.parserLocalDeclarationList), (Representation.Source.Valid NanoP4Spec.spec
      (Representation.Source.runtimeDomain ["value"]) (Q.t (Q.varT "parserLocalDeclarationList"
      [])).it) ((NanoP4Spec.parserLocalDeclarationList.toValue) x)) ∧
    (∀ x : (List (NanoP4Spec.parserState)), (Representation.Source.Valid NanoP4Spec.spec
      (Representation.Source.runtimeDomain ["value"]) (Q.t (.IterT (Q.t (Q.varT "parserState"
      [])) .List)).it) ((@ToValue.toValue (List (NanoP4Spec.parserState))
      (@P4SpecTec.Prelude.instToValueList (NanoP4Spec.parserState)
      ⟨NanoP4Spec.parserState.toValue⟩)) x)) ∧
    (∀ x : (NanoP4Spec.nameIR), (Representation.Source.Valid NanoP4Spec.spec
      (Representation.Source.runtimeDomain ["value"]) (Q.t (Q.varT "nameIR" [])).it)
      ((NanoP4Spec.nameIR.toValue) x)) ∧
    (∀ x : (List (Option (NanoP4Spec.lvalue))), (Representation.Source.Valid NanoP4Spec.spec
      (Representation.Source.runtimeDomain ["value"]) (Q.t (.IterT (Q.t (.IterT (Q.t (Q.varT
      "lvalue" [])) .Opt)) .List)).it) ((@ToValue.toValue (List (Option NanoP4Spec.lvalue))
      (@P4SpecTec.Prelude.instToValueList (Option NanoP4Spec.lvalue) ⟨@ToValue.toValue (Option
      (NanoP4Spec.lvalue)) (@P4SpecTec.Prelude.instToValueOption (NanoP4Spec.lvalue)
      ⟨NanoP4Spec.lvalue.toValue⟩)⟩)) x)) ∧
    True :=
  ⟨(fun x => (@Representation.Codec.encodingValid (NanoP4Spec.scope) ⟨NanoP4Spec.scope.toValue⟩
    ⟨NanoP4Spec.scope.ofValue⟩ (Representation.Source.Valid NanoP4Spec.spec
    (Representation.Source.runtimeDomain ["value"]) (Q.t (Q.varT "scope" [])).it) (fun _ =>
    True) ((@Representation.Source.Codec.toRuntime (NanoP4Spec.scope) ⟨NanoP4Spec.scope.toValue⟩
    ⟨NanoP4Spec.scope.ofValue⟩ _ _ _ NanoP4Spec.runtimeClosed _
    (Representation.Source.namesInCheckSound _ _ (by closure_check)) _
    (NanoP4Spec.scope.sourceCodec)))) x (((show ∀ x : (NanoP4Spec.scope), (fun _ => True) x from
    NanoP4Spec.scope.admittedAll)) x)), (fun x => (@Representation.Codec.encodingValid
    (NanoP4Spec.evalContext) ⟨NanoP4Spec.evalContext.toValue⟩ ⟨NanoP4Spec.evalContext.ofValue⟩
    (Representation.Source.Valid NanoP4Spec.spec (Representation.Source.runtimeDomain ["value"])
    (Q.t (Q.varT "evalContext" [])).it) (NanoP4Spec.evalContext.runtimeAdmitted)
    (NanoP4Spec.evalContext.runtimeCodec)) x (((show ∀ x : (NanoP4Spec.evalContext),
    (NanoP4Spec.evalContext.runtimeAdmitted) x from NanoP4Spec.evalContext.runtimeAdmittedAll))
    x)), (fun x => (@Representation.Codec.encodingValid (NanoP4Spec.parserStateList)
    ⟨NanoP4Spec.parserStateList.toValue⟩ ⟨NanoP4Spec.parserStateList.ofValue⟩
    (Representation.Source.Valid NanoP4Spec.spec (Representation.Source.runtimeDomain ["value"])
    (Q.t (Q.varT "parserStateList" [])).it) (NanoP4Spec.parserStateList.admitted)
    ((@Representation.Source.Codec.toRuntime (NanoP4Spec.parserStateList)
    ⟨NanoP4Spec.parserStateList.toValue⟩ ⟨NanoP4Spec.parserStateList.ofValue⟩ _ _ _
    NanoP4Spec.runtimeClosed _ (Representation.Source.namesInCheckSound _ _ (by closure_check))
    _ (NanoP4Spec.parserStateList.codec)))) x (((show ∀ x : (NanoP4Spec.parserStateList),
    (NanoP4Spec.parserStateList.admitted) x from NanoP4Spec.parserStateList.admittedAll)) x)),
    (fun x => (@Representation.Codec.encodingValid (List (NanoP4Spec.parameterIR))
    ⟨@ToValue.toValue (List (NanoP4Spec.parameterIR)) (@P4SpecTec.Prelude.instToValueList
    (NanoP4Spec.parameterIR) ⟨NanoP4Spec.parameterIR.toValue⟩)⟩ ⟨@OfValue.ofValue (List
    (NanoP4Spec.parameterIR)) (@P4SpecTec.Prelude.instOfValueList (NanoP4Spec.parameterIR)
    ⟨NanoP4Spec.parameterIR.ofValue⟩)⟩ (Representation.Source.Valid NanoP4Spec.spec
    (Representation.Source.runtimeDomain ["value"]) (Q.t (.IterT (Q.t (Q.varT "parameterIR" []))
    .List)).it) (fun xs : List (NanoP4Spec.parameterIR) => ∀ x ∈ xs,
    (NanoP4Spec.parameterIR.admitted) x) (@Representation.Source.listCodec NanoP4Spec.spec
    (Representation.Source.runtimeDomain ["value"]) (NanoP4Spec.parameterIR)
    ⟨NanoP4Spec.parameterIR.toValue⟩ ⟨NanoP4Spec.parameterIR.ofValue⟩ (Q.t (Q.varT "parameterIR"
    [])) (NanoP4Spec.parameterIR.admitted) ((@Representation.Source.Codec.toRuntime
    (NanoP4Spec.parameterIR) ⟨NanoP4Spec.parameterIR.toValue⟩ ⟨NanoP4Spec.parameterIR.ofValue⟩ _
    _ _ NanoP4Spec.runtimeClosed _ (Representation.Source.namesInCheckSound _ _ (by
    closure_check)) _ (NanoP4Spec.parameterIR.codec))))) x (((show ∀ x : (List
    (NanoP4Spec.parameterIR)), (fun xs : List (NanoP4Spec.parameterIR) => ∀ x ∈ xs,
    (NanoP4Spec.parameterIR.admitted) x) x from (fun xs x _ => ((show ∀ x :
    (NanoP4Spec.parameterIR), (NanoP4Spec.parameterIR.admitted) x from
    NanoP4Spec.parameterIR.admittedAll)) x))) x)), (fun x =>
    (@Representation.Codec.encodingValid (List (NanoP4Spec.argument)) ⟨@ToValue.toValue (List
    (NanoP4Spec.argument)) (@P4SpecTec.Prelude.instToValueList (NanoP4Spec.argument)
    ⟨NanoP4Spec.argument.toValue⟩)⟩ ⟨@OfValue.ofValue (List (NanoP4Spec.argument))
    (@P4SpecTec.Prelude.instOfValueList (NanoP4Spec.argument) ⟨NanoP4Spec.argument.ofValue⟩)⟩
    (Representation.Source.Valid NanoP4Spec.spec (Representation.Source.runtimeDomain ["value"])
    (Q.t (.IterT (Q.t (Q.varT "argument" [])) .List)).it) (fun xs : List (NanoP4Spec.argument)
    => ∀ x ∈ xs, (NanoP4Spec.argument.admitted) x) (@Representation.Source.listCodec
    NanoP4Spec.spec (Representation.Source.runtimeDomain ["value"]) (NanoP4Spec.argument)
    ⟨NanoP4Spec.argument.toValue⟩ ⟨NanoP4Spec.argument.ofValue⟩ (Q.t (Q.varT "argument" []))
    (NanoP4Spec.argument.admitted) ((@Representation.Source.Codec.toRuntime
    (NanoP4Spec.argument) ⟨NanoP4Spec.argument.toValue⟩ ⟨NanoP4Spec.argument.ofValue⟩ _ _ _
    NanoP4Spec.runtimeClosed _ (Representation.Source.namesInCheckSound _ _ (by closure_check))
    _ (NanoP4Spec.argument.codec))))) x (((show ∀ x : (List (NanoP4Spec.argument)), (fun xs :
    List (NanoP4Spec.argument) => ∀ x ∈ xs, (NanoP4Spec.argument.admitted) x) x from (fun xs x _
    => ((show ∀ x : (NanoP4Spec.argument), (NanoP4Spec.argument.admitted) x from
    NanoP4Spec.argument.admittedAll)) x))) x)), (fun x => (@Representation.Codec.encodingValid
    (NanoP4Spec.parserLocalDeclarationList) ⟨NanoP4Spec.parserLocalDeclarationList.toValue⟩
    ⟨NanoP4Spec.parserLocalDeclarationList.ofValue⟩ (Representation.Source.Valid NanoP4Spec.spec
    (Representation.Source.runtimeDomain ["value"]) (Q.t (Q.varT "parserLocalDeclarationList"
    [])).it) (NanoP4Spec.parserLocalDeclarationList.admitted)
    ((@Representation.Source.Codec.toRuntime (NanoP4Spec.parserLocalDeclarationList)
    ⟨NanoP4Spec.parserLocalDeclarationList.toValue⟩
    ⟨NanoP4Spec.parserLocalDeclarationList.ofValue⟩ _ _ _ NanoP4Spec.runtimeClosed _
    (Representation.Source.namesInCheckSound _ _ (by closure_check)) _
    (NanoP4Spec.parserLocalDeclarationList.codec)))) x (((show ∀ x :
    (NanoP4Spec.parserLocalDeclarationList), (NanoP4Spec.parserLocalDeclarationList.admitted) x
    from NanoP4Spec.parserLocalDeclarationList.admittedAll)) x)), (fun x =>
    (@Representation.Codec.encodingValid (List (NanoP4Spec.parserState)) ⟨@ToValue.toValue (List
    (NanoP4Spec.parserState)) (@P4SpecTec.Prelude.instToValueList (NanoP4Spec.parserState)
    ⟨NanoP4Spec.parserState.toValue⟩)⟩ ⟨@OfValue.ofValue (List (NanoP4Spec.parserState))
    (@P4SpecTec.Prelude.instOfValueList (NanoP4Spec.parserState)
    ⟨NanoP4Spec.parserState.ofValue⟩)⟩ (Representation.Source.Valid NanoP4Spec.spec
    (Representation.Source.runtimeDomain ["value"]) (Q.t (.IterT (Q.t (Q.varT "parserState" []))
    .List)).it) (fun xs : List (NanoP4Spec.parserState) => ∀ x ∈ xs,
    (NanoP4Spec.parserState.admitted) x) (@Representation.Source.listCodec NanoP4Spec.spec
    (Representation.Source.runtimeDomain ["value"]) (NanoP4Spec.parserState)
    ⟨NanoP4Spec.parserState.toValue⟩ ⟨NanoP4Spec.parserState.ofValue⟩ (Q.t (Q.varT "parserState"
    [])) (NanoP4Spec.parserState.admitted) ((@Representation.Source.Codec.toRuntime
    (NanoP4Spec.parserState) ⟨NanoP4Spec.parserState.toValue⟩ ⟨NanoP4Spec.parserState.ofValue⟩ _
    _ _ NanoP4Spec.runtimeClosed _ (Representation.Source.namesInCheckSound _ _ (by
    closure_check)) _ (NanoP4Spec.parserState.codec))))) x (((show ∀ x : (List
    (NanoP4Spec.parserState)), (fun xs : List (NanoP4Spec.parserState) => ∀ x ∈ xs,
    (NanoP4Spec.parserState.admitted) x) x from (fun xs x _ => ((show ∀ x :
    (NanoP4Spec.parserState), (NanoP4Spec.parserState.admitted) x from
    NanoP4Spec.parserState.admittedAll)) x))) x)), (fun x =>
    (@Representation.Codec.encodingValid (NanoP4Spec.nameIR) ⟨NanoP4Spec.nameIR.toValue⟩
    ⟨NanoP4Spec.nameIR.ofValue⟩ (Representation.Source.Valid NanoP4Spec.spec
    (Representation.Source.runtimeDomain ["value"]) (Q.t (Q.varT "nameIR" [])).it) (fun _ =>
    True) ((@Representation.Source.Codec.toRuntime (NanoP4Spec.nameIR)
    ⟨NanoP4Spec.nameIR.toValue⟩ ⟨NanoP4Spec.nameIR.ofValue⟩ _ _ _ NanoP4Spec.runtimeClosed _
    (Representation.Source.namesInCheckSound _ _ (by closure_check)) _
    (NanoP4Spec.nameIR.codec)))) x (((show ∀ x : (NanoP4Spec.nameIR), (fun _ => True) x from
    NanoP4Spec.nameIR.admittedAll)) x)), (fun x => (@Representation.Codec.encodingValid (List
    (Option (NanoP4Spec.lvalue))) ⟨@ToValue.toValue (List (Option (NanoP4Spec.lvalue)))
    (@P4SpecTec.Prelude.instToValueList (Option (NanoP4Spec.lvalue)) ⟨@ToValue.toValue (Option
    (NanoP4Spec.lvalue)) (@P4SpecTec.Prelude.instToValueOption (NanoP4Spec.lvalue)
    ⟨NanoP4Spec.lvalue.toValue⟩)⟩)⟩ ⟨@OfValue.ofValue (List (Option (NanoP4Spec.lvalue)))
    (@P4SpecTec.Prelude.instOfValueList (Option (NanoP4Spec.lvalue)) ⟨@OfValue.ofValue (Option
    (NanoP4Spec.lvalue)) (@P4SpecTec.Prelude.instOfValueOption (NanoP4Spec.lvalue)
    ⟨NanoP4Spec.lvalue.ofValue⟩)⟩)⟩ (Representation.Source.Valid NanoP4Spec.spec
    (Representation.Source.runtimeDomain ["value"]) (Q.t (.IterT (Q.t (.IterT (Q.t (Q.varT
    "lvalue" [])) .Opt)) .List)).it) (fun xs : List (Option (NanoP4Spec.lvalue)) => ∀ x ∈ xs,
    (fun xs : Option (NanoP4Spec.lvalue) => ∀ x ∈ xs, (NanoP4Spec.lvalue.admitted) x) x)
    (@Representation.Source.listCodec NanoP4Spec.spec (Representation.Source.runtimeDomain
    ["value"]) (Option (NanoP4Spec.lvalue)) ⟨@ToValue.toValue (Option (NanoP4Spec.lvalue))
    (@P4SpecTec.Prelude.instToValueOption (NanoP4Spec.lvalue) ⟨NanoP4Spec.lvalue.toValue⟩)⟩
    ⟨@OfValue.ofValue (Option (NanoP4Spec.lvalue)) (@P4SpecTec.Prelude.instOfValueOption
    (NanoP4Spec.lvalue) ⟨NanoP4Spec.lvalue.ofValue⟩)⟩ (Q.t (.IterT (Q.t (Q.varT "lvalue" []))
    .Opt)) (fun xs : Option (NanoP4Spec.lvalue) => ∀ x ∈ xs, (NanoP4Spec.lvalue.admitted) x)
    (@Representation.Source.optionCodec NanoP4Spec.spec (Representation.Source.runtimeDomain
    ["value"]) (NanoP4Spec.lvalue) ⟨NanoP4Spec.lvalue.toValue⟩ ⟨NanoP4Spec.lvalue.ofValue⟩ (Q.t
    (Q.varT "lvalue" [])) (NanoP4Spec.lvalue.admitted) ((@Representation.Source.Codec.toRuntime
    (NanoP4Spec.lvalue) ⟨NanoP4Spec.lvalue.toValue⟩ ⟨NanoP4Spec.lvalue.ofValue⟩ _ _ _
    NanoP4Spec.runtimeClosed _ (Representation.Source.namesInCheckSound _ _ (by closure_check))
    _ (NanoP4Spec.lvalue.codec)))))) x (((show ∀ x : (List (Option (NanoP4Spec.lvalue))), (fun
    xs : List (Option (NanoP4Spec.lvalue)) => ∀ x ∈ xs, (fun xs : Option (NanoP4Spec.lvalue) =>
    ∀ x ∈ xs, (NanoP4Spec.lvalue.admitted) x) x) x from (fun xs x _ => ((show ∀ x : (Option
    (NanoP4Spec.lvalue)), (fun xs : Option (NanoP4Spec.lvalue) => ∀ x ∈ xs,
    (NanoP4Spec.lvalue.admitted) x) x from (fun xs x _ => ((show ∀ x : (NanoP4Spec.lvalue),
    (NanoP4Spec.lvalue.admitted) x from NanoP4Spec.lvalue.admittedAll)) x))) x))) x)), trivial⟩
#audit_axioms Parser_apply.runtimeCallArgumentsSource


end NanoP4Spec
