-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group SourceEntry.find_action
import P4SpecTec.Refine.Representation.Delay
import P4SpecTec.Refine.Representation.Source
import P4SpecTec.Refine.Representation.SourceAlias
import P4SpecTec.Refine.Representation.SourceAtomic
import P4SpecTec.Refine.Representation.SourceRecord
import P4SpecTec.Refine.Representation.SourceCodec
import P4SpecTec.Refine.Representation.SourceTuple
import P4SpecTec.Refine.Representation.SourceExtern
import P4SpecTec.Refine.Representation.SourceVariant
import P4SpecTec.Tactic.Audit
import P4SpecTec.Tactic.CarrierInduction
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality
import NanoP4Spec.Refinement.find_action
import NanoP4Spec.Refinement.Representation.tableContext
import NanoP4Spec.Refinement.Representation.callableId

/-! # NanoP4Spec.Refinement.SourceEntry.find_action

Generated: refinement theorems, group SourceEntry.find_action.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

/-- Every declared source input has admitted witnesses with both execution directions. -/
theorem «$find_action».sourceCorrespondence
    (cfg : Interp_al.Interp.Config) (ctx : Interp_al.Ctx.t) (internal : Bool)
    (hguard : cfg.guard = false) (hfenv : ctx.local.fenv = [])
    (hspec : HoldsSpec NanoP4Spec.spec ctx.global)
    (v0 : Lang.Il.value) (hv0 : (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "tableContext" [])).it) v0)
    (v1 : Lang.Il.value) (hv1 : (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "callableId" [])).it) v1) :
    ∃ p0 : NanoP4Spec.tableContext, ∃ p1 : NanoP4Spec.callableId,
      (NanoP4Spec.tableContext.admitted) p0 ∧ Rel v0 p0 ∧ (fun _ => True) p1 ∧ Rel v1 p1 ∧ (∀
      fuel : Nat, Refines Rel (Interp_al.Interp.invoke_func fuel cfg internal ctx (Q.i
      "find_action") [] [v0, v1]) (ExceptT.mk (NanoP4Spec.«$find_action» p0 p1))) ∧
      Realizes Rel (fun fuel => (Interp_al.Interp.invoke_func fuel cfg internal ctx (Q.i
        "find_action") [] [v0, v1])) (ExceptT.mk (NanoP4Spec.«$find_action» p0 p1)) := by
  obtain ⟨p0, admitted0, h0⟩ :=
    (@Representation.Codec.adequate (NanoP4Spec.tableContext) ⟨NanoP4Spec.tableContext.toValue⟩
      ⟨NanoP4Spec.tableContext.ofValue⟩ (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "tableContext" [])).it)
      (NanoP4Spec.tableContext.admitted) (NanoP4Spec.tableContext.codec)).coverage v0 hv0
  obtain ⟨p1, admitted1, h1⟩ :=
    (@Representation.Codec.adequate (NanoP4Spec.callableId) ⟨NanoP4Spec.callableId.toValue⟩
      ⟨NanoP4Spec.callableId.ofValue⟩ (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "callableId" [])).it) (fun _ => True)
      (NanoP4Spec.callableId.codec)).coverage v1 hv1
  refine ⟨p0, p1, admitted0, h0, admitted1, h1, ?_, ?_⟩
  · intro fuel
    exact NanoP4Spec.«$find_action».refines fuel cfg ctx internal hguard hfenv hspec v0 v1 p0 p1
      h0 h1
  · exact NanoP4Spec.«$find_action».realizes cfg ctx internal hguard hfenv hspec v0 v1 p0 p1 h0
      h1

#audit_axioms NanoP4Spec.«$find_action».sourceCorrespondence

end NanoP4Spec
