-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group SourceEntry.TableDecl_ok
import P4SpecTec.Refine.Representation.Delay
import P4SpecTec.Refine.Representation.Source
import P4SpecTec.Refine.Representation.SourceAlias
import P4SpecTec.Refine.Representation.SourceAtomic
import P4SpecTec.Refine.Representation.SourceRecord
import P4SpecTec.Refine.Representation.SourceCodec
import P4SpecTec.Refine.Representation.SourceTuple
import P4SpecTec.Refine.Representation.SourceExtern
import P4SpecTec.Refine.Representation.SourceVariant
import P4SpecTec.Tactic.Audit
import P4SpecTec.Tactic.CarrierInduction
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality
import NanoP4Spec.Refinement.TableDecl_ok
import NanoP4Spec.Refinement.Representation.typingContext
import NanoP4Spec.Refinement.Representation.tableDeclaration

/-! # NanoP4Spec.Refinement.SourceEntry.TableDecl_ok

Generated: refinement theorems, group SourceEntry.TableDecl_ok.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

/-- Every declared source input has admitted witnesses with both execution directions. -/
theorem TableDecl_ok.sourceCorrespondence
    (cfg : Interp_al.Interp.Config) (ctx : Interp_al.Ctx.t) (internal : Bool)
    (hguard : cfg.guard = false) (hhints : cfg.printHints = []) (hfenv : ctx.local.fenv = [])
    (hspec : HoldsSpec NanoP4Spec.spec ctx.global)
    (ht0 : ctx.global.tdtbl.get? "K" = none)
    (ht1 : ctx.global.tdtbl.get? "V" = none)
    (v0 : Lang.Il.value) (hv0 : (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "typingContext" [])).it) v0)
    (v1 : Lang.Il.value) (hv1 : (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "tableDeclaration" [])).it) v1) :
    ∃ p0 : NanoP4Spec.typingContext, ∃ p1 : NanoP4Spec.tableDeclaration,
      (NanoP4Spec.typingContext.admitted) p0 ∧ Rel v0 p0 ∧
      (NanoP4Spec.tableDeclaration.admitted) p1 ∧ Rel v1 p1 ∧ (∀ fuel : Nat, Refines (fun vs (o
      : NanoP4Spec.typingContext) => Outs vs [toValue o]) (Interp_al.Interp.invoke_rel fuel cfg
      internal ctx (Q.i "TableDecl_ok") [v0, v1]) (ExceptT.mk (NanoP4Spec.TableDecl_ok.run p0
      p1))) ∧
      Realizes (fun vs (o : NanoP4Spec.typingContext) => Outs vs [toValue o]) (fun fuel =>
        (Interp_al.Interp.invoke_rel fuel cfg internal ctx (Q.i "TableDecl_ok") [v0, v1]))
        (ExceptT.mk (NanoP4Spec.TableDecl_ok.run p0 p1)) := by
  obtain ⟨p0, admitted0, h0⟩ :=
    (@Representation.Codec.adequate (NanoP4Spec.typingContext)
      ⟨NanoP4Spec.typingContext.toValue⟩ ⟨NanoP4Spec.typingContext.ofValue⟩
      (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t
      (Q.varT "typingContext" [])).it) (NanoP4Spec.typingContext.admitted)
      (NanoP4Spec.typingContext.codec)).coverage v0 hv0
  obtain ⟨p1, admitted1, h1⟩ :=
    (@Representation.Codec.adequate (NanoP4Spec.tableDeclaration)
      ⟨NanoP4Spec.tableDeclaration.toValue⟩ ⟨NanoP4Spec.tableDeclaration.ofValue⟩
      (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t
      (Q.varT "tableDeclaration" [])).it) (NanoP4Spec.tableDeclaration.admitted)
      (NanoP4Spec.tableDeclaration.codec)).coverage v1 hv1
  refine ⟨p0, p1, admitted0, h0, admitted1, h1, ?_, ?_⟩
  · intro fuel
    exact NanoP4Spec.TableDecl_ok.refines fuel cfg ctx internal hguard hhints hfenv hspec ht0
      ht1 v0 v1 p0 p1 h0 h1
  · exact NanoP4Spec.TableDecl_ok.realizes cfg ctx internal hguard hhints hfenv hspec ht0 ht1 v0
      v1 p0 p1 h0 h1

#audit_axioms NanoP4Spec.TableDecl_ok.sourceCorrespondence

end NanoP4Spec
