-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group SourceEntry.Var_init
import P4SpecTec.Refine.Representation.Delay
import P4SpecTec.Refine.Representation.Source
import P4SpecTec.Refine.Representation.SourceAlias
import P4SpecTec.Refine.Representation.SourceAtomic
import P4SpecTec.Refine.Representation.SourceRecord
import P4SpecTec.Refine.Representation.SourceCodec
import P4SpecTec.Refine.Representation.SourceTuple
import P4SpecTec.Refine.Representation.SourceExtern
import P4SpecTec.Refine.Representation.SourceVariant
import P4SpecTec.Tactic.Audit
import P4SpecTec.Tactic.CarrierInduction
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality
import NanoP4Spec.Refinement.Var_init
import NanoP4Spec.Refinement.Representation.evalContext
import NanoP4Spec.Refinement.Representation.typeIR
import NanoP4Spec.Refinement.Representation.nameIR

/-! # NanoP4Spec.Refinement.SourceEntry.Var_init

Generated: refinement theorems, group SourceEntry.Var_init.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

/-- Every declared source input has admitted witnesses with both execution directions. -/
theorem Var_init.sourceCorrespondence
    (cfg : Interp_al.Interp.Config) (ctx : Interp_al.Ctx.t) (internal : Bool)
    (hguard : cfg.guard = false) (hfenv : ctx.local.fenv = [])
    (hspec : HoldsSpec NanoP4Spec.spec ctx.global)
    (ht0 : ctx.global.tdtbl.get? "K" = none)
    (ht1 : ctx.global.tdtbl.get? "V" = none)
    (v0 : Lang.Il.value) (hv0 : (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "evalContext" [])).it) v0)
    (v1 : Lang.Il.value) (hv1 : (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "typeIR" [])).it) v1)
    (v2 : Lang.Il.value) (hv2 : (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "nameIR" [])).it) v2) :
    ∃ p0 : NanoP4Spec.evalContext, ∃ p1 : NanoP4Spec.typeIR, ∃ p2 : NanoP4Spec.nameIR,
      (NanoP4Spec.evalContext.admitted) p0 ∧ Rel v0 p0 ∧ (NanoP4Spec.typeIR.admitted) p1 ∧ Rel
      v1 p1 ∧ (fun _ => True) p2 ∧ Rel v2 p2 ∧ (∀ fuel : Nat, Refines (fun vs (o :
      NanoP4Spec.evalContext) => Outs vs [toValue o]) (Interp_al.Interp.invoke_rel fuel cfg
      internal ctx (Q.i "Var_init") [v0, v1, v2]) (ExceptT.mk (NanoP4Spec.Var_init.run p0 p1
      p2))) ∧
      Realizes (fun vs (o : NanoP4Spec.evalContext) => Outs vs [toValue o]) (fun fuel =>
        (Interp_al.Interp.invoke_rel fuel cfg internal ctx (Q.i "Var_init") [v0, v1, v2]))
        (ExceptT.mk (NanoP4Spec.Var_init.run p0 p1 p2)) := by
  obtain ⟨p0, admitted0, h0⟩ :=
    (@Representation.Codec.adequate (NanoP4Spec.evalContext) ⟨NanoP4Spec.evalContext.toValue⟩
      ⟨NanoP4Spec.evalContext.ofValue⟩ (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "evalContext" [])).it)
      (NanoP4Spec.evalContext.admitted) (NanoP4Spec.evalContext.codec)).coverage v0 hv0
  obtain ⟨p1, admitted1, h1⟩ :=
    (@Representation.Codec.adequate (NanoP4Spec.typeIR) ⟨NanoP4Spec.typeIR.toValue⟩
      ⟨NanoP4Spec.typeIR.ofValue⟩ (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "typeIR" [])).it)
      (NanoP4Spec.typeIR.admitted) (NanoP4Spec.typeIR.codec)).coverage v1 hv1
  obtain ⟨p2, admitted2, h2⟩ :=
    (@Representation.Codec.adequate (NanoP4Spec.nameIR) ⟨NanoP4Spec.nameIR.toValue⟩
      ⟨NanoP4Spec.nameIR.ofValue⟩ (Representation.Source.Valid NanoP4Spec.spec
      Representation.Source.externDomain (Q.t (Q.varT "nameIR" [])).it) (fun _ => True)
      (NanoP4Spec.nameIR.codec)).coverage v2 hv2
  refine ⟨p0, p1, p2, admitted0, h0, admitted1, h1, admitted2, h2, ?_, ?_⟩
  · intro fuel
    exact NanoP4Spec.Var_init.refines fuel cfg ctx internal hguard hfenv hspec ht0 ht1 v0 v1 v2
      p0 p1 p2 h0 h1 h2
  · exact NanoP4Spec.Var_init.realizes cfg ctx internal hguard hfenv hspec ht0 ht1 v0 v1 v2 p0
      p1 p2 h0 h1 h2

#audit_axioms NanoP4Spec.Var_init.sourceCorrespondence

end NanoP4Spec
