-- GENERATED by p4spectec-gen for P4Spec; do not edit, regenerate.
-- source: exports/p4.al.json, state run-soundness, relation TableAction_inst
import P4SpecTec.Prelude
import P4SpecTec.Tactic.StateRunSound
import P4SpecTec.Tactic.Audit
import P4Spec.Refinement.Spec
import P4Spec.Refinement.Relation.TableAction_inst

/-! # P4Spec.Refinement.RunSound.TableAction_inst

Generated: state run-soundness, relation TableAction_inst.
Design section 4.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace P4Spec

theorem TableAction_inst.run_sound
    (p0 : P4Spec.instContext)
    (p1 : P4Spec.store)
    (p2 : P4Spec.tableActionIR)
    (o : P4Spec.store × P4Spec.tableActionIR)
    («@s0» «@sf» : FreshState) :
    P4Spec.TableAction_inst.run p0 p1 p2 «@s0» = some (.ok o, «@sf») →
    P4Spec.TableAction_inst p0 p1 p2 o.1 o.2 «@s0» «@sf» :=
  by state_run_sound

#audit_axioms P4Spec.TableAction_inst.run_sound

end P4Spec
