-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group Reverse.Control_apply
import P4SpecTec.Prelude
import P4SpecTec.Tactic.Audit
import P4SpecTec.Refine.Quote
import P4SpecTec.Refine.Calc
import P4SpecTec.Tactic.Realize
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality
import NanoP4Spec.Refinement.Reverse.inherit_e
import NanoP4Spec.Refinement.Reverse.Copy_in
import NanoP4Spec.Refinement.Reverse.ControlLocalDeclList_eval
import NanoP4Spec.Refinement.Reverse.Call_eval
import NanoP4Spec.Refinement.Reverse.Copy_out

/-! # NanoP4Spec.Refinement.Reverse.Control_apply

Generated: refinement theorems, group Reverse.Control_apply.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

set_option maxHeartbeats 6000000 in
theorem Control_apply.realizes
    [NanoP4Spec.Externs]
    (cfg : Interp_al.Interp.Config) (ctx : Interp_al.Ctx.t) (internal : Bool)
    (hguard : cfg.guard = false) (hhints : cfg.printHints = [])
    (hextern : NanoP4Spec.externsContract cfg) (hfenv : ctx.local.fenv = [])
    (hspec : HoldsSpec NanoP4Spec.spec ctx.global)
    (ht0 : ctx.global.tdtbl.get? "K" = none)
    (ht1 : ctx.global.tdtbl.get? "V" = none)
    (v0 v1 v2 : Lang.Il.value)
    (p0 : NanoP4Spec.evalContext)
    (p1 : List NanoP4Spec.argument)
    (p2 : NanoP4Spec.controlDeclarationIR)
    (h0 : Rel v0 p0)
    (h1 : Rel v1 p1)
    (h2 : Rel v2 p2) :
    Realizes (fun vs (o : NanoP4Spec.evalContext) => Outs vs [toValue o])
      (fun fuel => (Interp_al.Interp.invoke_rel fuel cfg internal ctx
          (Q.i "Control_apply")
          [v0, v1, v2]))
      (ExceptT.mk (NanoP4Spec.Control_apply.run p0 p1 p2)) := by
  realize_al (subtypes)

#audit_axioms NanoP4Spec.Control_apply.realizes

end NanoP4Spec
