-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group Reverse.make_evalContext
import P4SpecTec.Prelude
import P4SpecTec.Tactic.Audit
import P4SpecTec.Refine.Quote
import P4SpecTec.Refine.Calc
import P4SpecTec.Tactic.Realize
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality
import NanoP4Spec.Refinement.Reverse.empty_frame

/-! # NanoP4Spec.Refinement.Reverse.make_evalContext

Generated: refinement theorems, group Reverse.make_evalContext.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

set_option maxHeartbeats 5000000 in
theorem «$make_evalContext».realizes
    (cfg : Interp_al.Interp.Config) (ctx : Interp_al.Ctx.t) (internal : Bool)
    (hguard : cfg.guard = false) (hfenv : ctx.local.fenv = [])
    (hspec : HoldsSpec NanoP4Spec.spec ctx.global)
    (ht0 : ctx.global.tdtbl.get? "K" = none)
    (ht1 : ctx.global.tdtbl.get? "V" = none)
    (v0 v1 : Lang.Il.value)
    (p0 : NanoP4Spec.typingContext)
    (p1 : NanoP4Spec.loadContext)
    (h0 : Rel v0 p0)
    (h1 : Rel v1 p1) :
    Realizes Rel
      (fun fuel => (Interp_al.Interp.invoke_func fuel cfg internal ctx
          (Q.i "make_evalContext")
          []
          [v0, v1]))
      (ExceptT.mk (NanoP4Spec.«$make_evalContext» p0 p1)) := by
  realize_al (subtypes)

#audit_axioms NanoP4Spec.«$make_evalContext».realizes

end NanoP4Spec
