-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group Reverse.typeIR_of_typeDefIR
import P4SpecTec.Prelude
import P4SpecTec.Tactic.Audit
import P4SpecTec.Refine.Quote
import P4SpecTec.Refine.Calc
import P4SpecTec.Tactic.Realize
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality

/-! # NanoP4Spec.Refinement.Reverse.typeIR_of_typeDefIR

Generated: refinement theorems, group Reverse.typeIR_of_typeDefIR.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

set_option maxHeartbeats 6000000 in
theorem «$typeIR_of_typeDefIR».realizes
    (cfg : Interp_al.Interp.Config) (ctx : Interp_al.Ctx.t) (internal : Bool)
    (hguard : cfg.guard = false) (hfenv : ctx.local.fenv = [])
    (hspec : HoldsSpec NanoP4Spec.spec ctx.global)
    (v0 : Lang.Il.value)
    (p0 : NanoP4Spec.typeDefIR)
    (h0 : Rel v0 p0) :
    Realizes Rel
      (fun fuel => (Interp_al.Interp.invoke_func fuel cfg internal ctx
          (Q.i "typeIR_of_typeDefIR")
          []
          [v0]))
      (ExceptT.mk (NanoP4Spec.«$typeIR_of_typeDefIR» p0)) := by
  realize_al (subtypes)

#audit_axioms NanoP4Spec.«$typeIR_of_typeDefIR».realizes

end NanoP4Spec
