-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group Producer.TableAction_ok
import P4SpecTec.Refine.Representation.Delay
import P4SpecTec.Refine.Representation.Source
import P4SpecTec.Refine.Representation.SourceAlias
import P4SpecTec.Refine.Representation.SourceAtomic
import P4SpecTec.Refine.Representation.SourceRecord
import P4SpecTec.Refine.Representation.SourceCodec
import P4SpecTec.Refine.Representation.SourceTuple
import P4SpecTec.Refine.Representation.SourceExtern
import P4SpecTec.Refine.Representation.SourceVariant
import P4SpecTec.Tactic.Audit
import P4SpecTec.Tactic.CarrierInduction
import P4SpecTec.Refine.Producer
import P4SpecTec.Refine.ProducerMap
import P4SpecTec.Tactic.Encoding
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality
import NanoP4Spec.Refinement.Representation.matchAction

/-! # NanoP4Spec.Refinement.Producer.TableAction_ok

Generated: refinement theorems, group Producer.TableAction_ok.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

/-- Every successful result inhabits the independent source domain. -/
theorem TableAction_ok.producesSource :
    ∀ (p0 : NanoP4Spec.typingContext) (p1 : NanoP4Spec.tableAction),
    (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT
      "typingContext" [])).it) ((NanoP4Spec.typingContext.toValue) p0) →
    (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT
      "tableAction" [])).it) ((NanoP4Spec.tableAction.toValue) p1) →
    ∀ result, NanoP4Spec.TableAction_ok.run p0 p1 = some (.ok result) →
    (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT
      "matchAction" [])).it) ((NanoP4Spec.matchAction.toValue) result) := by
  intro p0 p1 _ _ result _
  exact (@Representation.Codec.encodingValid (NanoP4Spec.matchAction)
    ⟨NanoP4Spec.matchAction.toValue⟩ ⟨NanoP4Spec.matchAction.ofValue⟩
    (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT
    "matchAction" [])).it) (NanoP4Spec.matchAction.admitted) (NanoP4Spec.matchAction.codec))
    result (((show ∀ x : (NanoP4Spec.matchAction), (NanoP4Spec.matchAction.admitted) x from
    NanoP4Spec.matchAction.admittedAll)) result)


#audit_axioms TableAction_ok.producesSource

end NanoP4Spec
