-- GENERATED by p4spectec-gen for NanoP4Spec; do not edit, regenerate.
-- source: exports/nano-p4.al.json, refinement theorems, group Producer.Var_init
import P4SpecTec.Refine.Representation.Delay
import P4SpecTec.Refine.Representation.Source
import P4SpecTec.Refine.Representation.SourceAlias
import P4SpecTec.Refine.Representation.SourceAtomic
import P4SpecTec.Refine.Representation.SourceRecord
import P4SpecTec.Refine.Representation.SourceCodec
import P4SpecTec.Refine.Representation.SourceTuple
import P4SpecTec.Refine.Representation.SourceExtern
import P4SpecTec.Refine.Representation.SourceVariant
import P4SpecTec.Tactic.Audit
import P4SpecTec.Tactic.CarrierInduction
import P4SpecTec.Refine.Producer
import P4SpecTec.Refine.ProducerMap
import P4SpecTec.Tactic.Encoding
import NanoP4Spec.Refinement.Spec
import NanoP4Spec.Refinement.Equality
import NanoP4Spec.Refinement.Producer.default
import NanoP4Spec.Refinement.Producer.add_var_e

/-! # NanoP4Spec.Refinement.Producer.Var_init

Generated: refinement theorems, group Producer.Var_init.
Rung 3, design section 5.1.
-/

set_option linter.missingDocs false
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxHeartbeats 4000000
-- the quoted spec is one deep `::` chain
set_option maxRecDepth 8192

open P4SpecTec P4SpecTec.Prelude P4SpecTec.Refine

namespace NanoP4Spec

private theorem Var_init.producerConstant1_0 :
    (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT
      "scope" [])).it) ((NanoP4Spec.scope.toValue) (NanoP4Spec.scope.GLOBAL )) := by
  apply Representation.Source.Valid.variant (Q.i "scope") [] []
    [Q.tc (.Atom (Q.a (.Keyword "GLOBAL"))) "scope" [], Q.tc (.Atom (Q.a (.Keyword "BLOCK")))
      "scope" [], Q.tc (.Atom (Q.a (.Keyword "LOCAL"))) "scope" []]
    (Q.tc (.Atom (Q.a (.Keyword "GLOBAL"))) "scope" [])
    [] _ _ (by rfl)
  · exact List.mem_cons_self
  · rfl
  · rfl
  · simpa [Lang.Il.typcase.nottyp, Domain.Mixfix.args] using
      (show Representation.Source.instantiatedFields [] [] [] [] from ⟨rfl, .nil⟩)
  · simpa [Domain.Mixfix.args] using (Representation.Source.Values.nil
      (spec := NanoP4Spec.spec)
      (externalDomain := Representation.Source.externDomain))

/-- Actual call composition preserves the independently stated source output domain. -/
theorem Var_init.producesSource :
    ∀ (p0 : NanoP4Spec.evalContext) (p1 : NanoP4Spec.typeIR) (p2 : NanoP4Spec.nameIR),
    (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT
      "evalContext" [])).it) ((NanoP4Spec.evalContext.toValue) p0) →
    (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT
      "typeIR" [])).it) ((NanoP4Spec.typeIR.toValue) p1) →
    (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT
      "nameIR" [])).it) ((NanoP4Spec.nameIR.toValue) p2) →
    ∀ result, NanoP4Spec.Var_init.run p0 p1 p2 = some (.ok result) →
    (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT
      "evalContext" [])).it) ((NanoP4Spec.evalContext.toValue) result) := by
  intro p0 p1 p2 h0 h1 h2 result run
  have derivation := NanoP4Spec.Var_init.run_sound p0 p1 p2 result run
  cases derivation with
  | rule0 run0 run1 =>
    rename_i value0
    have accepted0 := NanoP4Spec.«$default».producesSource p1 h1 value0 run0
    have accepted1 := NanoP4Spec.«$add_var_e».producesSource NanoP4Spec.scope.GLOBAL p0 p2
      value0 Var_init.producerConstant1_0 h0 h2 accepted0 result run1
    exact accepted1


/-- Successful earlier calls establish every source input of the next actual call. -/
theorem Var_init.callArgumentsSource : ∀ (p0 : NanoP4Spec.evalContext) (p1 : NanoP4Spec.typeIR)
  (p2 : NanoP4Spec.nameIR), (Representation.Source.Valid NanoP4Spec.spec
  Representation.Source.externDomain (Q.t (Q.varT "evalContext" [])).it)
  ((NanoP4Spec.evalContext.toValue) p0) → (Representation.Source.Valid NanoP4Spec.spec
  Representation.Source.externDomain (Q.t (Q.varT "typeIR" [])).it) ((NanoP4Spec.typeIR.toValue)
  p1) → (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t
  (Q.varT "nameIR" [])).it) ((NanoP4Spec.nameIR.toValue) p2) → ((Representation.Source.Valid
  NanoP4Spec.spec Representation.Source.externDomain (Q.t (Q.varT "typeIR" [])).it)
  ((NanoP4Spec.typeIR.toValue) p1)) ∧ (∀ (value0 : NanoP4Spec.value), NanoP4Spec.«$default» p1 =
  some (.ok value0) → (Representation.Source.Valid NanoP4Spec.spec
  Representation.Source.externDomain (Q.t (Q.varT "scope" [])).it) ((NanoP4Spec.scope.toValue)
  NanoP4Spec.scope.GLOBAL) ∧ (Representation.Source.Valid NanoP4Spec.spec
  Representation.Source.externDomain (Q.t (Q.varT "evalContext" [])).it)
  ((NanoP4Spec.evalContext.toValue) p0) ∧ (Representation.Source.Valid NanoP4Spec.spec
  Representation.Source.externDomain (Q.t (Q.varT "nameIR" [])).it) ((NanoP4Spec.nameIR.toValue)
  p2) ∧ (Representation.Source.Valid NanoP4Spec.spec Representation.Source.externDomain (Q.t
  (Q.varT "value" [])).it) ((NanoP4Spec.value.toValue) value0)) := by
  intro p0 p1 p2 h0 h1 h2
  constructor
  · exact h1
  · intro value0 run0
    have accepted0 := NanoP4Spec.«$default».producesSource p1 h1 value0 run0
    exact ⟨Var_init.producerConstant1_0, h0, h2, accepted0⟩


#audit_axioms Var_init.producerConstant1_0
#audit_axioms Var_init.producesSource
#audit_axioms Var_init.callArgumentsSource

end NanoP4Spec
