#!/usr/bin/env bash
# Per-file elaboration times of a generated library (design section 7):
# rebuild the library from scratch and print a Markdown table of the times
# Lake reports per module, sorted by time, with the machine and toolchain.
# Usage: scripts/time-elab.sh NanoP4Spec > docs/timing-nano-p4.md
set -euo pipefail
root="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
lib="${1:?usage: time-elab.sh <Lib>}"
log="$(mktemp)"
rm -rf "$root/.lake/build/lib/lean/$lib" "$root/.lake/build/lib/lean/$lib.olean" "$root/.lake/build/ir/$lib"
(cd "$root" && lake build "$lib" > "$log" 2>&1) || { cat "$log"; exit 1; }
# module names may carry French-quoted components (NanoP4Spec.«3.2-bits»)
rows="$(grep -oE "Built $lib(\.[^ ]+)? \([0-9.]+(ms|s)\)" "$log" | sed -E 's/Built ([^ ]+) \(([0-9.]+)(ms|s)\)/\1 \2 \3/' \
  | awk '{ t = $2; if ($3 == "ms") t = t / 1000; printf "%s %.2f\n", $1, t }' | sort -k2 -rn)"
echo "# Elaboration times: $lib"
echo ""
echo "Per-module elaboration time of the generated library, from a clean"
echo "build by \`scripts/time-elab.sh $lib\` (design section 7). Regenerated by"
echo "hand at each checkpoint; not checked by CI."
echo ""
echo "- Toolchain: $(cat "$root/lean-toolchain")"
echo "- Machine: $(uname -m), $(uname -s) $(uname -r)"
echo "- Date: $(date +%Y-%m-%d)"
echo ""
echo "| Module | Seconds |"
echo "|---|---|"
echo "$rows" | awk '{ printf "| %s | %s |\n", $1, $2 }'
echo ""
echo "$rows" | awk '{ s += $2; n += 1 } END { printf "Total: %.1fs over %d modules\n", s, n }'
rm -f "$log"
